In [15]:
import pandas as pd
import shutil
from pathlib import Path

lims_path = Path("../avaliacao_llms")

items = []
for item in sorted(lims_path.iterdir()):
    if item.is_dir():
        nome_atual = item.name
        novo_nome = nome_atual
        novo_nome = novo_nome.replace("__anthropic__", "__")
        novo_nome = novo_nome.replace("__openai__", "__")
        novo_nome = novo_nome.replace("__deepseek__deepseek-", "__deepseek-")
        novo_nome = novo_nome.replace("__", "_")

        items.append({"nome_atual": nome_atual, "novo_nome": novo_nome})

df = pd.DataFrame(items)
df

                                 nome_atual                    novo_nome
0        bndes__anthropic__claude-haiku-4-5       bndes_claude-haiku-4-5
1         bndes__anthropic__claude-opus-4-7        bndes_claude-opus-4-7
2       bndes__anthropic__claude-sonnet-4-6      bndes_claude-sonnet-4-6
3        bndes__deepseek__deepseek-v4-flash      bndes_deepseek-v4-flash
4          bndes__deepseek__deepseek-v4-pro        bndes_deepseek-v4-pro
5                bndes__openai__gpt-4o-mini            bndes_gpt-4o-mini
6                    bndes__openai__gpt-5.4                bndes_gpt-5.4
7               bndes__openai__gpt-5.4-mini           bndes_gpt-5.4-mini
8                    bndes__openai__gpt-5.5                bndes_gpt-5.5
9          cvm__anthropic__claude-haiku-4-5         cvm_claude-haiku-4-5
10          cvm__anthropic__claude-opus-4-7          cvm_claude-opus-4-7
11        cvm__anthropic__claude-sonnet-4-6        cvm_claude-sonnet-4-6
12         cvm__deepseek__deepseek-v4-flash        cvm_deepseek-v4-flash
13           cvm__deepseek__deepseek-v4-pro          cvm_deepseek-v4-pro
14                 cvm__openai__gpt-4o-mini              cvm_gpt-4o-mini
15                     cvm__openai__gpt-5.4                  cvm_gpt-5.4
16                cvm__openai__gpt-5.4-mini             cvm_gpt-5.4-mini
17                     cvm__openai__gpt-5.5                  cvm_gpt-5.5
18   petrobras__anthropic__claude-haiku-4-5   petrobras_claude-haiku-4-5
19    petrobras__anthropic__claude-opus-4-7    petrobras_claude-opus-4-7
20  petrobras__anthropic__claude-sonnet-4-6  petrobras_claude-sonnet-4-6
21   petrobras__deepseek__deepseek-v4-flash  petrobras_deepseek-v4-flash
22     petrobras__deepseek__deepseek-v4-pro    petrobras_deepseek-v4-pro
23           petrobras__openai__gpt-4o-mini        petrobras_gpt-4o-mini
24               petrobras__openai__gpt-5.4            petrobras_gpt-5.4
25          petrobras__openai__gpt-5.4-mini       petrobras_gpt-5.4-mini
26               petrobras__openai__gpt-5.5            petrobras_gpt-5.5

In [16]:
for _, row in df.iterrows():
    caminho_atual = lims_path / row["nome_atual"]
    caminho_novo = lims_path / row["novo_nome"]

    if caminho_atual == caminho_novo:
        print(f"➖ Já correto: {row['nome_atual']}")
    elif caminho_atual.exists() and not caminho_novo.exists():
        shutil.move(str(caminho_atual), str(caminho_novo))
        print(f"✓ Renomeado: {row['nome_atual']} → {row['novo_nome']}")
    elif not caminho_atual.exists() and caminho_novo.exists():
        print(f"✓ Já renomeado: {row['novo_nome']}")
    else:
        print(f"⚠️ Conflito: {row['nome_atual']} e {row['novo_nome']} ambos existem!")

✓ Renomeado: bndes__anthropic__claude-haiku-4-5 → bndes_claude-haiku-4-5
✓ Renomeado: bndes__anthropic__claude-opus-4-7 → bndes_claude-opus-4-7
✓ Renomeado: bndes__anthropic__claude-sonnet-4-6 → bndes_claude-sonnet-4-6
✓ Renomeado: bndes__deepseek__deepseek-v4-flash → bndes_deepseek-v4-flash
✓ Renomeado: bndes__deepseek__deepseek-v4-pro → bndes_deepseek-v4-pro
✓ Renomeado: bndes__openai__gpt-4o-mini → bndes_gpt-4o-mini
✓ Renomeado: bndes__openai__gpt-5.4 → bndes_gpt-5.4
✓ Renomeado: bndes__openai__gpt-5.4-mini → bndes_gpt-5.4-mini
✓ Renomeado: bndes__openai__gpt-5.5 → bndes_gpt-5.5
✓ Renomeado: cvm__anthropic__claude-haiku-4-5 → cvm_claude-haiku-4-5
✓ Renomeado: cvm__anthropic__claude-opus-4-7 → cvm_claude-opus-4-7
✓ Renomeado: cvm__anthropic__claude-sonnet-4-6 → cvm_claude-sonnet-4-6
✓ Renomeado: cvm__deepseek__deepseek-v4-flash → cvm_deepseek-v4-flash
✓ Renomeado: cvm__deepseek__deepseek-v4-pro → cvm_deepseek-v4-pro
✓ Renomeado: cvm__openai__gpt-4o-mini → cvm_gpt-4o-mini
✓ Renomeado: cvm__openai__gpt-5.4 → cvm_gpt-5.4
✓ Renomeado: cvm__openai__gpt-5.4-mini → cvm_gpt-5.4-mini
✓ Renomeado: cvm__openai__gpt-5.5 → cvm_gpt-5.5
✓ Renomeado: petrobras__anthropic__claude-haiku-4-5 → petrobras_claude-haiku-4-5
✓ Renomeado: petrobras__anthropic__claude-opus-4-7 → petrobras_claude-opus-4-7
✓ Renomeado: petrobras__anthropic__claude-sonnet-4-6 → petrobras_claude-sonnet-4-6
✓ Renomeado: petrobras__deepseek__deepseek-v4-flash → petrobras_deepseek-v4-flash
✓ Renomeado: petrobras__deepseek__deepseek-v4-pro → petrobras_deepseek-v4-pro
✓ Renomeado: petrobras__openai__gpt-4o-mini → petrobras_gpt-4o-mini
✓ Renomeado: petrobras__openai__gpt-5.4 → petrobras_gpt-5.4
✓ Renomeado: petrobras__openai__gpt-5.4-mini → petrobras_gpt-5.4-mini
✓ Renomeado: petrobras__openai__gpt-5.5 → petrobras_gpt-5.5

In [17]:
items_files = []

for _, row in df.iterrows():
    pasta = lims_path / row["novo_nome"]

    for arquivo in sorted(pasta.iterdir()):
        if arquivo.suffix == ".xlsx":
            nome_atual = arquivo.name
            avaliador = nome_atual.split("_")[-2]
            novo_nome_arquivo = f"{row['novo_nome']}_{avaliador}_eval.xlsx"

            items_files.append({
                "pasta": row["novo_nome"],
                "nome_atual": nome_atual,
                "novo_nome": novo_nome_arquivo
            })

df_files = pd.DataFrame(items_files)
df_files

,pasta,nome_atual,novo_nome
0,bndes_claude-haiku-4-5,bndes_haiku_4-5_gpt_eval.xlsx,bndes_claude-haiku-4-5_gpt_eval.xlsx
1,bndes_claude-haiku-4-5,bndes_haiku_4-5_opus_eval.xlsx,bndes_claude-haiku-4-5_opus_eval.xlsx
2,bndes_claude-opus-4-7,bndes_claude-opus-4-7_gpt_eval.xlsx,bndes_claude-opus-4-7_gpt_eval.xlsx
3,bndes_claude-opus-4-7,bndes_claude-opus-4-7_opus_eval.xlsx,bndes_claude-opus-4-7_opus_eval.xlsx
4,bndes_claude-sonnet-4-6,bndes_claude-sonnet-4-6_gpt_eval.xlsx,bndes_claude-sonnet-4-6_gpt_eval.xlsx
5,bndes_claude-sonnet-4-6,bndes_claude-sonnet-4-6_opus_eval.xlsx,bndes_claude-sonnet-4-6_opus_eval.xlsx
6,bndes_deepseek-v4-flash,bndes_deepseek-v4-flash_gpt_eval.xlsx,bndes_deepseek-v4-flash_gpt_eval.xlsx
7,bndes_deepseek-v4-flash,bndes_deepseek-v4-flash_opus_eval.xlsx,bndes_deepseek-v4-flash_opus_eval.xlsx
8,bndes_deepseek-v4-pro,bndes_deepseek-v4-pro_gpt_eval.xlsx,bndes_deepseek-v4-pro_gpt_eval.xlsx
9,bndes_deepseek-v4-pro,bndes_deepseek-v4-pro_opus_eval.xlsx,bndes_deepseek-v4-pro_opus_eval.xlsx
10,bndes_gpt-4o-mini,bndes_gpt-4o-mini_gpt_eval.xlsx,bndes_gpt-4o-mini_gpt_eval.xlsx
11,bndes_gpt-4o-mini,bndes_gpt-4o-mini_opus_eval.xlsx,bndes_gpt-4o-mini_opus_eval.xlsx
12,bndes_gpt-5.4,bndes_gpt-5.4_gpt_eval.xlsx,bndes_gpt-5.4_gpt_eval.xlsx
13,bndes_gpt-5.4,bndes_gpt-5.4_opus_eval.xlsx,bndes_gpt-5.4_opus_eval.xlsx
14,bndes_gpt-5.4-mini,bndes_gpt-5.4-mini_gpt_eval.xlsx,bndes_gpt-5.4-mini_gpt_eval.xlsx
15,bndes_gpt-5.4-mini,bndes_gpt-5_4-mini_opus_eval.xlsx,bndes_gpt-5.4-mini_opus_eval.xlsx
16,bndes_gpt-5.5,bndes_gpt-5.5_gpt_eval.xlsx,bndes_gpt-5.5_gpt_eval.xlsx
17,bndes_gpt-5.5,bndes_gpt-5_5_opus_eval.xlsx,bndes_gpt-5.5_opus_eval.xlsx
18,cvm_claude-haiku-4-5,cvm_haiku-4-5_gpt_eval.xlsx,cvm_claude-haiku-4-5_gpt_eval.xlsx
19,cvm_claude-haiku-4-5,cvm_haiku_4-5_opus_eval.xlsx,cvm_claude-haiku-4-5_opus_eval.xlsx
20,cvm_claude-opus-4-7,cvm_claude-opus-4-7_gpt_eval.xlsx,cvm_claude-opus-4-7_gpt_eval.xlsx
21,cvm_claude-opus-4-7,cvm_claude-opus-4-7_opus_eval.xlsx,cvm_claude-opus-4-7_opus_eval.xlsx
22,cvm_claude-sonnet-4-6,cvm_claude-sonnet-4-6_gpt_eval.xlsx,cvm_claude-sonnet-4-6_gpt_eval.xlsx
23,cvm_claude-sonnet-4-6,cvm_claude-sonnet-4-6_opus_eval.xlsx,cvm_claude-sonnet-4-6_opus_eval.xlsx
24,cvm_deepseek-v4-flash,cvm_deepseek-v4-flash_gpt_eval.xlsx,cvm_deepseek-v4-flash_gpt_eval.xlsx
25,cvm_deepseek-v4-flash,cvm_deepseek-v4-flash_opus_eval.xlsx,cvm_deepseek-v4-flash_opus_eval.xlsx
26,cvm_deepseek-v4-pro,cvm_deepseek-v4-pro_gpt_eval.xlsx,cvm_deepseek-v4-pro_gpt_eval.xlsx
27,cvm_deepseek-v4-pro,cvm_deepseek-v4-pro_opus_eval.xlsx,cvm_deepseek-v4-pro_opus_eval.xlsx
28,cvm_gpt-4o-mini,cvm_gpt-4o-mini_gpt_eval.xlsx,cvm_gpt-4o-mini_gpt_eval.xlsx
29,cvm_gpt-4o-mini,cvm_gpt-4o-mini_opus_eval.xlsx,cvm_gpt-4o-mini_opus_eval.xlsx
30,cvm_gpt-5.4,cvm_gpt-5-4_opus_eval.xlsx,cvm_gpt-5.4_opus_eval.xlsx
31,cvm_gpt-5.4,cvm_gpt-5.4_gpt_eval.xlsx,cvm_gpt-5.4_gpt_eval.xlsx
32,cvm_gpt-5.4-mini,cvm_gpt-5.4-mini_gpt_eval.xlsx,cvm_gpt-5.4-mini_gpt_eval.xlsx
33,cvm_gpt-5.4-mini,cvm_gpt-5_4-mini_opus_eval.xlsx,cvm_gpt-5.4-mini_opus_eval.xlsx
34,cvm_gpt-5.5,cvm_gpt-5.5_gpt_eval.xlsx,cvm_gpt-5.5_gpt_eval.xlsx
35,cvm_gpt-5.5,cvm_gpt-5_5_opus_eval.xlsx,cvm_gpt-5.5_opus_eval.xlsx
36,petrobras_claude-haiku-4-5,petrobras_haiku-4-5_gpt_eval.xlsx,petrobras_claude-haiku-4-5_gpt_eval.xlsx
37,petrobras_claude-haiku-4-5,petrobras_haiku-4-5_opus_eval.xlsx,petrobras_claude-haiku-4-5_opus_eval.xlsx
38,petrobras_claude-opus-4-7,petrobras_claude-opus-4-7_gpt_eval.xlsx,petrobras_claude-opus-4-7_gpt_eval.xlsx
39,petrobras_claude-opus-4-7,petrobras_claude-opus-4-7_opus_eval.xlsx,petrobras_claude-opus-4-7_opus_eval.xlsx
40,petrobras_claude-sonnet-4-6,petrobras_claude-sonnet-4-6_gpt_eval.xlsx,petrobras_claude-sonnet-4-6_gpt_eval.xlsx
41,petrobras_claude-sonnet-4-6,petrobras_claude-sonnet-4-6_opus_eval.xlsx,petrobras_claude-sonnet-4-6_opus_eval.xlsx
42,petrobras_deepseek-v4-flash,petrobras_deepseek-v4-flash_gpt_eval.xlsx,petrobras_deepseek-v4-flash_gpt_eval.xlsx
43,petrobras_deepseek-v4-flash,petrobras_deepseek-v4-flash_opus_eval.xlsx,petrobras_deepseek-v4-flash_opus_eval.xlsx
44,petrobras_deepseek-v4-pro,petrobras_deepseek-v4-pro_gpt_eval.xlsx,petrobras_deepseek-v4-pro_gpt_eval.xlsx
45,petrobras_deepseek-v4-pro,petrobras_deepseek-v4-pro_opus_eval.xlsx,petrobras_deepseek-v4-pro_opus_eval.xlsx
46,petrobras_gpt-4o-mini,petrobras_gpt-4o-mini_gpt_eval.xlsx,petrobras_gpt-4o-mini_gpt_eval.xlsx
47,petrobras_gpt-4o-mini,petrobras_gpt-4o-mini_opus_eval.xlsx,petrobras_gpt-4o-mini_opus_eval.xlsx
48,petrobras_gpt-5.4,petrobras_gpt-5.4_gpt_eval.xlsx,petrobras_gpt-5.4_gpt_eval.xlsx
49,petrobras_gpt-5.4,petrobras_gpt-5_4_opus_eval.xlsx,petrobras_gpt-5.4_opus_eval.xlsx
50,petrobras_gpt-5.4-mini,petrobras_gpt-5.4-mini_gpt_eval.xlsx,petrobras_gpt-5.4-mini_gpt_eval.xlsx
51,petrobras_gpt-5.4-mini,petrobras_gpt-5_4-mini_opus_eval.xlsx,petrobras_gpt-5.4-mini_opus_eval.xlsx
52,petrobras_gpt-5.5,petrobras_gpt-5.5_gpt_eval.xlsx,petrobras_gpt-5.5_gpt_eval.xlsx
53,petrobras_gpt-5.5,petrobras_gpt-5_5_opus_eval.xlsx,petrobras_gpt-5.5_opus_eval.xlsx

In [18]:
for _, row in df_files.iterrows():
    caminho_atual = lims_path / row["pasta"] / row["nome_atual"]
    caminho_novo = lims_path / row["pasta"] / row["novo_nome"]

    if caminho_atual == caminho_novo:
        print(f"➖ Já correto: {row['nome_atual']}")
    elif caminho_atual.exists() and not caminho_novo.exists():
        shutil.move(str(caminho_atual), str(caminho_novo))
        print(f"✓ Renomeado: {row['nome_atual']} → {row['novo_nome']}")
    elif not caminho_atual.exists() and caminho_novo.exists():
        print(f"✓ Já renomeado: {row['novo_nome']}")
    elif caminho_atual.exists() and caminho_novo.exists():
        print(f"⚠️ Conflito: ambos existem!")
    else:
        print(f"✗ Não encontrado: {row['nome_atual']}")

✓ Renomeado: bndes_haiku_4-5_gpt_eval.xlsx → bndes_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: bndes_haiku_4-5_opus_eval.xlsx → bndes_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: bndes_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: bndes_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: bndes_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: bndes_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: bndes_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: bndes_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: bndes_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: bndes_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: bndes_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: bndes_gpt-4o-mini_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.4_gpt_eval.xlsx
➖ Já correto: bndes_gpt-5.4_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: bndes_gpt-5_4-mini_opus_eval.xlsx → bndes_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: bndes_gpt-5_5_opus_eval.xlsx → bndes_gpt-5.5_opus_eval.xlsx
✓ Renomeado: cvm_haiku-4-5_gpt_eval.xlsx → cvm_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: cvm_haiku_4-5_opus_eval.xlsx → cvm_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: cvm_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: cvm_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: cvm_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: cvm_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: cvm_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: cvm_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: cvm_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: cvm_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: cvm_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: cvm_gpt-4o-mini_opus_eval.xlsx
✓ Renomeado: cvm_gpt-5-4_opus_eval.xlsx → cvm_gpt-5.4_opus_eval.xlsx
➖ Já correto: cvm_gpt-5.4_gpt_eval.xlsx
➖ Já correto: cvm_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: cvm_gpt-5_4-mini_opus_eval.xlsx → cvm_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: cvm_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: cvm_gpt-5_5_opus_eval.xlsx → cvm_gpt-5.5_opus_eval.xlsx
✓ Renomeado: petrobras_haiku-4-5_gpt_eval.xlsx → petrobras_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: petrobras_haiku-4-5_opus_eval.xlsx → petrobras_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: petrobras_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: petrobras_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: petrobras_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: petrobras_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: petrobras_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: petrobras_gpt-4o-mini_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.4_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_4_opus_eval.xlsx → petrobras_gpt-5.4_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_4-mini_opus_eval.xlsx → petrobras_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_5_opus_eval.xlsx → petrobras_gpt-5.5_opus_eval.xlsx

In [21]:
grupos = {}

for _, row in df_files.iterrows():
    arquivo = lims_path / row["pasta"] / row["novo_nome"]
    nome = row["novo_nome"]
    
    if nome.endswith("opus_eval.xlsx"):
        avaliador = "opus"
    elif nome.endswith("gpt_eval.xlsx"):
        avaliador = "gpt"
    else:
        continue
    
    if arquivo.exists():
        df_temp = pd.read_excel(arquivo, nrows=0)
        colunas = tuple(df_temp.columns.tolist())
        
        if avaliador not in grupos:
            grupos[avaliador] = []
        grupos[avaliador].append({"arquivo": nome, "colunas": colunas})

for grupo, items in grupos.items():
    colunas_unicas = set(i["colunas"] for i in items)
    print(f"\n{'='*50}")
    print(f"Grupo: {grupo} ({len(items)} arquivos)")
    if len(colunas_unicas) == 1:
        print(f"✓ Todos compartilham as mesmas colunas:")
        for col in list(colunas_unicas)[0]:
            print(f"   - {col}")
    else:
        print(f"⚠️ Colunas divergentes!")
        for item in items:
            print(f"\n  {item['arquivo']}:\n    {list(item['colunas'])}")

==================================================
Grupo: gpt (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_gpt
   - avaliacao_gpt

==================================================
Grupo: opus (27 arquivos)
⚠️ Colunas divergentes!

  bndes_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'cache_read_tokens__bug', 'custo_real_usd__bug', 'justificativa_opus', 'avaliacao_opus']

  petrobras_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'cache_read_tokens__bug', 'custo_real_usd__bug', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

In [22]:
for arquivo in ["petrobras_deepseek-v4-flash_opus_eval.xlsx", "petrobras_deepseek-v4-pro_opus_eval.xlsx"]:
    pasta = arquivo.split("_opus_eval")[0]
    caminho = lims_path / pasta / arquivo
    
    df_temp = pd.read_excel(caminho)
    df_temp = df_temp.drop(columns=["cache_read_tokens__bug", "custo_real_usd__bug"])
    df_temp.to_excel(caminho, index=False)
    print(f"✓ Colunas removidas: {arquivo}")

✓ Colunas removidas: petrobras_deepseek-v4-flash_opus_eval.xlsx
✓ Colunas removidas: petrobras_deepseek-v4-pro_opus_eval.xlsx

In [23]:
grupos = {}

for _, row in df_files.iterrows():
    arquivo = lims_path / row["pasta"] / row["novo_nome"]
    nome = row["novo_nome"]
    
    if nome.endswith("opus_eval.xlsx"):
        avaliador = "opus"
    elif nome.endswith("gpt_eval.xlsx"):
        avaliador = "gpt"
    else:
        continue
    
    if arquivo.exists():
        df_temp = pd.read_excel(arquivo, nrows=0)
        colunas = tuple(df_temp.columns.tolist())
        
        if avaliador not in grupos:
            grupos[avaliador] = []
        grupos[avaliador].append({"arquivo": nome, "colunas": colunas})

for grupo, items in grupos.items():
    colunas_unicas = set(i["colunas"] for i in items)
    print(f"\n{'='*50}")
    print(f"Grupo: {grupo} ({len(items)} arquivos)")
    if len(colunas_unicas) == 1:
        print(f"✓ Todos compartilham as mesmas colunas:")
        for col in list(colunas_unicas)[0]:
            print(f"   - {col}")
    else:
        print(f"⚠️ Colunas divergentes!")
        for item in items:
            print(f"\n  {item['arquivo']}:\n    {list(item['colunas'])}")

==================================================
Grupo: gpt (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_gpt
   - avaliacao_gpt

==================================================
Grupo: opus (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_opus
   - avaliacao_opus

In [26]:
for _, row in df_files.iterrows():
    caminho = lims_path / row["pasta"] / row["novo_nome"]
    df_temp = pd.read_excel(caminho)
    
    if len(df_temp) != 50:
        print(f"⚠️ {row['novo_nome']}: {len(df_temp)} linhas")
    
    nulos = df_temp.drop(columns=["erro"]).isnull().sum()
    nulos = nulos[nulos > 0]
    if not nulos.empty:
        print(f"⚠️ {row['novo_nome']} tem nulos: {nulos.to_dict()}")

In [27]:
for _, row in df_files.iterrows():
    caminho = lims_path / row["pasta"] / row["novo_nome"]
    df_temp = pd.read_excel(caminho)
    df_temp = df_temp.drop(columns=["erro"])
    df_temp.to_excel(caminho, index=False)
    print(f"✓ Coluna erro removida: {row['novo_nome']}")

✓ Coluna erro removida: bndes_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: bndes_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: bndes_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.5_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.5_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.5_opus_eval.xlsx

In [28]:
editais = ["bndes", "cvm", "petrobras"]

for edital in editais:
    arquivos = df_files[df_files["pasta"].str.startswith(edital)]
    dfs = [pd.read_excel(lims_path / row["pasta"] / row["novo_nome"])[["id", "categoria", "pergunta"]] 
           for _, row in arquivos.iterrows()]
    
    referencia = dfs[0]
    todos_iguais = all(df.equals(referencia) for df in dfs[1:])
    
    print(f"{'✓' if todos_iguais else '⚠️'} {edital}: {'todas iguais' if todos_iguais else 'divergências encontradas'}")

✓ bndes: todas iguais
✓ cvm: todas iguais
✓ petrobras: todas iguais