In [15]:
import pandas as pd
import shutil
from pathlib import Path

lims_path = Path("../avaliacao_llms")

items = []
for item in sorted(lims_path.iterdir()):
    if item.is_dir():
        nome_atual = item.name
        novo_nome = nome_atual
        novo_nome = novo_nome.replace("__anthropic__", "__")
        novo_nome = novo_nome.replace("__openai__", "__")
        novo_nome = novo_nome.replace("__deepseek__deepseek-", "__deepseek-")
        novo_nome = novo_nome.replace("__", "_")

        items.append({"nome_atual": nome_atual, "novo_nome": novo_nome})

df = pd.DataFrame(items)
df

                                 nome_atual                    novo_nome
0        bndes__anthropic__claude-haiku-4-5       bndes_claude-haiku-4-5
1         bndes__anthropic__claude-opus-4-7        bndes_claude-opus-4-7
2       bndes__anthropic__claude-sonnet-4-6      bndes_claude-sonnet-4-6
3        bndes__deepseek__deepseek-v4-flash      bndes_deepseek-v4-flash
4          bndes__deepseek__deepseek-v4-pro        bndes_deepseek-v4-pro
5                bndes__openai__gpt-4o-mini            bndes_gpt-4o-mini
6                    bndes__openai__gpt-5.4                bndes_gpt-5.4
7               bndes__openai__gpt-5.4-mini           bndes_gpt-5.4-mini
8                    bndes__openai__gpt-5.5                bndes_gpt-5.5
9          cvm__anthropic__claude-haiku-4-5         cvm_claude-haiku-4-5
10          cvm__anthropic__claude-opus-4-7          cvm_claude-opus-4-7
11        cvm__anthropic__claude-sonnet-4-6        cvm_claude-sonnet-4-6
12         cvm__deepseek__deepseek-v4-flash        cvm_deepseek-v4-flash
13           cvm__deepseek__deepseek-v4-pro          cvm_deepseek-v4-pro
14                 cvm__openai__gpt-4o-mini              cvm_gpt-4o-mini
15                     cvm__openai__gpt-5.4                  cvm_gpt-5.4
16                cvm__openai__gpt-5.4-mini             cvm_gpt-5.4-mini
17                     cvm__openai__gpt-5.5                  cvm_gpt-5.5
18   petrobras__anthropic__claude-haiku-4-5   petrobras_claude-haiku-4-5
19    petrobras__anthropic__claude-opus-4-7    petrobras_claude-opus-4-7
20  petrobras__anthropic__claude-sonnet-4-6  petrobras_claude-sonnet-4-6
21   petrobras__deepseek__deepseek-v4-flash  petrobras_deepseek-v4-flash
22     petrobras__deepseek__deepseek-v4-pro    petrobras_deepseek-v4-pro
23           petrobras__openai__gpt-4o-mini        petrobras_gpt-4o-mini
24               petrobras__openai__gpt-5.4            petrobras_gpt-5.4
25          petrobras__openai__gpt-5.4-mini       petrobras_gpt-5.4-mini
26               petrobras__openai__gpt-5.5            petrobras_gpt-5.5

In [16]:
for _, row in df.iterrows():
    caminho_atual = lims_path / row["nome_atual"]
    caminho_novo = lims_path / row["novo_nome"]

    if caminho_atual == caminho_novo:
        print(f"➖ Já correto: {row['nome_atual']}")
    elif caminho_atual.exists() and not caminho_novo.exists():
        shutil.move(str(caminho_atual), str(caminho_novo))
        print(f"✓ Renomeado: {row['nome_atual']} → {row['novo_nome']}")
    elif not caminho_atual.exists() and caminho_novo.exists():
        print(f"✓ Já renomeado: {row['novo_nome']}")
    else:
        print(f"⚠️ Conflito: {row['nome_atual']} e {row['novo_nome']} ambos existem!")

✓ Renomeado: bndes__anthropic__claude-haiku-4-5 → bndes_claude-haiku-4-5
✓ Renomeado: bndes__anthropic__claude-opus-4-7 → bndes_claude-opus-4-7
✓ Renomeado: bndes__anthropic__claude-sonnet-4-6 → bndes_claude-sonnet-4-6
✓ Renomeado: bndes__deepseek__deepseek-v4-flash → bndes_deepseek-v4-flash
✓ Renomeado: bndes__deepseek__deepseek-v4-pro → bndes_deepseek-v4-pro
✓ Renomeado: bndes__openai__gpt-4o-mini → bndes_gpt-4o-mini
✓ Renomeado: bndes__openai__gpt-5.4 → bndes_gpt-5.4
✓ Renomeado: bndes__openai__gpt-5.4-mini → bndes_gpt-5.4-mini
✓ Renomeado: bndes__openai__gpt-5.5 → bndes_gpt-5.5
✓ Renomeado: cvm__anthropic__claude-haiku-4-5 → cvm_claude-haiku-4-5
✓ Renomeado: cvm__anthropic__claude-opus-4-7 → cvm_claude-opus-4-7
✓ Renomeado: cvm__anthropic__claude-sonnet-4-6 → cvm_claude-sonnet-4-6
✓ Renomeado: cvm__deepseek__deepseek-v4-flash → cvm_deepseek-v4-flash
✓ Renomeado: cvm__deepseek__deepseek-v4-pro → cvm_deepseek-v4-pro
✓ Renomeado: cvm__openai__gpt-4o-mini → cvm_gpt-4o-mini
✓ Renomeado: cvm__openai__gpt-5.4 → cvm_gpt-5.4
✓ Renomeado: cvm__openai__gpt-5.4-mini → cvm_gpt-5.4-mini
✓ Renomeado: cvm__openai__gpt-5.5 → cvm_gpt-5.5
✓ Renomeado: petrobras__anthropic__claude-haiku-4-5 → petrobras_claude-haiku-4-5
✓ Renomeado: petrobras__anthropic__claude-opus-4-7 → petrobras_claude-opus-4-7
✓ Renomeado: petrobras__anthropic__claude-sonnet-4-6 → petrobras_claude-sonnet-4-6
✓ Renomeado: petrobras__deepseek__deepseek-v4-flash → petrobras_deepseek-v4-flash
✓ Renomeado: petrobras__deepseek__deepseek-v4-pro → petrobras_deepseek-v4-pro
✓ Renomeado: petrobras__openai__gpt-4o-mini → petrobras_gpt-4o-mini
✓ Renomeado: petrobras__openai__gpt-5.4 → petrobras_gpt-5.4
✓ Renomeado: petrobras__openai__gpt-5.4-mini → petrobras_gpt-5.4-mini
✓ Renomeado: petrobras__openai__gpt-5.5 → petrobras_gpt-5.5

In [17]:
items_files = []

for _, row in df.iterrows():
    pasta = lims_path / row["novo_nome"]

    for arquivo in sorted(pasta.iterdir()):
        if arquivo.suffix == ".xlsx":
            nome_atual = arquivo.name
            avaliador = nome_atual.split("_")[-2]
            novo_nome_arquivo = f"{row['novo_nome']}_{avaliador}_eval.xlsx"

            items_files.append({
                "pasta": row["novo_nome"],
                "nome_atual": nome_atual,
                "novo_nome": novo_nome_arquivo
            })

df_files = pd.DataFrame(items_files)
df_files

,pasta,nome_atual,novo_nome
0,bndes_claude-haiku-4-5,bndes_haiku_4-5_gpt_eval.xlsx,bndes_claude-haiku-4-5_gpt_eval.xlsx
1,bndes_claude-haiku-4-5,bndes_haiku_4-5_opus_eval.xlsx,bndes_claude-haiku-4-5_opus_eval.xlsx
2,bndes_claude-opus-4-7,bndes_claude-opus-4-7_gpt_eval.xlsx,bndes_claude-opus-4-7_gpt_eval.xlsx
3,bndes_claude-opus-4-7,bndes_claude-opus-4-7_opus_eval.xlsx,bndes_claude-opus-4-7_opus_eval.xlsx
4,bndes_claude-sonnet-4-6,bndes_claude-sonnet-4-6_gpt_eval.xlsx,bndes_claude-sonnet-4-6_gpt_eval.xlsx
5,bndes_claude-sonnet-4-6,bndes_claude-sonnet-4-6_opus_eval.xlsx,bndes_claude-sonnet-4-6_opus_eval.xlsx
6,bndes_deepseek-v4-flash,bndes_deepseek-v4-flash_gpt_eval.xlsx,bndes_deepseek-v4-flash_gpt_eval.xlsx
7,bndes_deepseek-v4-flash,bndes_deepseek-v4-flash_opus_eval.xlsx,bndes_deepseek-v4-flash_opus_eval.xlsx
8,bndes_deepseek-v4-pro,bndes_deepseek-v4-pro_gpt_eval.xlsx,bndes_deepseek-v4-pro_gpt_eval.xlsx
9,bndes_deepseek-v4-pro,bndes_deepseek-v4-pro_opus_eval.xlsx,bndes_deepseek-v4-pro_opus_eval.xlsx
10,bndes_gpt-4o-mini,bndes_gpt-4o-mini_gpt_eval.xlsx,bndes_gpt-4o-mini_gpt_eval.xlsx
11,bndes_gpt-4o-mini,bndes_gpt-4o-mini_opus_eval.xlsx,bndes_gpt-4o-mini_opus_eval.xlsx
12,bndes_gpt-5.4,bndes_gpt-5.4_gpt_eval.xlsx,bndes_gpt-5.4_gpt_eval.xlsx
13,bndes_gpt-5.4,bndes_gpt-5.4_opus_eval.xlsx,bndes_gpt-5.4_opus_eval.xlsx
14,bndes_gpt-5.4-mini,bndes_gpt-5.4-mini_gpt_eval.xlsx,bndes_gpt-5.4-mini_gpt_eval.xlsx
15,bndes_gpt-5.4-mini,bndes_gpt-5_4-mini_opus_eval.xlsx,bndes_gpt-5.4-mini_opus_eval.xlsx
16,bndes_gpt-5.5,bndes_gpt-5.5_gpt_eval.xlsx,bndes_gpt-5.5_gpt_eval.xlsx
17,bndes_gpt-5.5,bndes_gpt-5_5_opus_eval.xlsx,bndes_gpt-5.5_opus_eval.xlsx
18,cvm_claude-haiku-4-5,cvm_haiku-4-5_gpt_eval.xlsx,cvm_claude-haiku-4-5_gpt_eval.xlsx
19,cvm_claude-haiku-4-5,cvm_haiku_4-5_opus_eval.xlsx,cvm_claude-haiku-4-5_opus_eval.xlsx
20,cvm_claude-opus-4-7,cvm_claude-opus-4-7_gpt_eval.xlsx,cvm_claude-opus-4-7_gpt_eval.xlsx
21,cvm_claude-opus-4-7,cvm_claude-opus-4-7_opus_eval.xlsx,cvm_claude-opus-4-7_opus_eval.xlsx
22,cvm_claude-sonnet-4-6,cvm_claude-sonnet-4-6_gpt_eval.xlsx,cvm_claude-sonnet-4-6_gpt_eval.xlsx
23,cvm_claude-sonnet-4-6,cvm_claude-sonnet-4-6_opus_eval.xlsx,cvm_claude-sonnet-4-6_opus_eval.xlsx
24,cvm_deepseek-v4-flash,cvm_deepseek-v4-flash_gpt_eval.xlsx,cvm_deepseek-v4-flash_gpt_eval.xlsx
25,cvm_deepseek-v4-flash,cvm_deepseek-v4-flash_opus_eval.xlsx,cvm_deepseek-v4-flash_opus_eval.xlsx
26,cvm_deepseek-v4-pro,cvm_deepseek-v4-pro_gpt_eval.xlsx,cvm_deepseek-v4-pro_gpt_eval.xlsx
27,cvm_deepseek-v4-pro,cvm_deepseek-v4-pro_opus_eval.xlsx,cvm_deepseek-v4-pro_opus_eval.xlsx
28,cvm_gpt-4o-mini,cvm_gpt-4o-mini_gpt_eval.xlsx,cvm_gpt-4o-mini_gpt_eval.xlsx
29,cvm_gpt-4o-mini,cvm_gpt-4o-mini_opus_eval.xlsx,cvm_gpt-4o-mini_opus_eval.xlsx
30,cvm_gpt-5.4,cvm_gpt-5-4_opus_eval.xlsx,cvm_gpt-5.4_opus_eval.xlsx
31,cvm_gpt-5.4,cvm_gpt-5.4_gpt_eval.xlsx,cvm_gpt-5.4_gpt_eval.xlsx
32,cvm_gpt-5.4-mini,cvm_gpt-5.4-mini_gpt_eval.xlsx,cvm_gpt-5.4-mini_gpt_eval.xlsx
33,cvm_gpt-5.4-mini,cvm_gpt-5_4-mini_opus_eval.xlsx,cvm_gpt-5.4-mini_opus_eval.xlsx
34,cvm_gpt-5.5,cvm_gpt-5.5_gpt_eval.xlsx,cvm_gpt-5.5_gpt_eval.xlsx
35,cvm_gpt-5.5,cvm_gpt-5_5_opus_eval.xlsx,cvm_gpt-5.5_opus_eval.xlsx
36,petrobras_claude-haiku-4-5,petrobras_haiku-4-5_gpt_eval.xlsx,petrobras_claude-haiku-4-5_gpt_eval.xlsx
37,petrobras_claude-haiku-4-5,petrobras_haiku-4-5_opus_eval.xlsx,petrobras_claude-haiku-4-5_opus_eval.xlsx
38,petrobras_claude-opus-4-7,petrobras_claude-opus-4-7_gpt_eval.xlsx,petrobras_claude-opus-4-7_gpt_eval.xlsx
39,petrobras_claude-opus-4-7,petrobras_claude-opus-4-7_opus_eval.xlsx,petrobras_claude-opus-4-7_opus_eval.xlsx
40,petrobras_claude-sonnet-4-6,petrobras_claude-sonnet-4-6_gpt_eval.xlsx,petrobras_claude-sonnet-4-6_gpt_eval.xlsx
41,petrobras_claude-sonnet-4-6,petrobras_claude-sonnet-4-6_opus_eval.xlsx,petrobras_claude-sonnet-4-6_opus_eval.xlsx
42,petrobras_deepseek-v4-flash,petrobras_deepseek-v4-flash_gpt_eval.xlsx,petrobras_deepseek-v4-flash_gpt_eval.xlsx
43,petrobras_deepseek-v4-flash,petrobras_deepseek-v4-flash_opus_eval.xlsx,petrobras_deepseek-v4-flash_opus_eval.xlsx
44,petrobras_deepseek-v4-pro,petrobras_deepseek-v4-pro_gpt_eval.xlsx,petrobras_deepseek-v4-pro_gpt_eval.xlsx
45,petrobras_deepseek-v4-pro,petrobras_deepseek-v4-pro_opus_eval.xlsx,petrobras_deepseek-v4-pro_opus_eval.xlsx
46,petrobras_gpt-4o-mini,petrobras_gpt-4o-mini_gpt_eval.xlsx,petrobras_gpt-4o-mini_gpt_eval.xlsx
47,petrobras_gpt-4o-mini,petrobras_gpt-4o-mini_opus_eval.xlsx,petrobras_gpt-4o-mini_opus_eval.xlsx
48,petrobras_gpt-5.4,petrobras_gpt-5.4_gpt_eval.xlsx,petrobras_gpt-5.4_gpt_eval.xlsx
49,petrobras_gpt-5.4,petrobras_gpt-5_4_opus_eval.xlsx,petrobras_gpt-5.4_opus_eval.xlsx
50,petrobras_gpt-5.4-mini,petrobras_gpt-5.4-mini_gpt_eval.xlsx,petrobras_gpt-5.4-mini_gpt_eval.xlsx
51,petrobras_gpt-5.4-mini,petrobras_gpt-5_4-mini_opus_eval.xlsx,petrobras_gpt-5.4-mini_opus_eval.xlsx
52,petrobras_gpt-5.5,petrobras_gpt-5.5_gpt_eval.xlsx,petrobras_gpt-5.5_gpt_eval.xlsx
53,petrobras_gpt-5.5,petrobras_gpt-5_5_opus_eval.xlsx,petrobras_gpt-5.5_opus_eval.xlsx

In [18]:
for _, row in df_files.iterrows():
    caminho_atual = lims_path / row["pasta"] / row["nome_atual"]
    caminho_novo = lims_path / row["pasta"] / row["novo_nome"]

    if caminho_atual == caminho_novo:
        print(f"➖ Já correto: {row['nome_atual']}")
    elif caminho_atual.exists() and not caminho_novo.exists():
        shutil.move(str(caminho_atual), str(caminho_novo))
        print(f"✓ Renomeado: {row['nome_atual']} → {row['novo_nome']}")
    elif not caminho_atual.exists() and caminho_novo.exists():
        print(f"✓ Já renomeado: {row['novo_nome']}")
    elif caminho_atual.exists() and caminho_novo.exists():
        print(f"⚠️ Conflito: ambos existem!")
    else:
        print(f"✗ Não encontrado: {row['nome_atual']}")

✓ Renomeado: bndes_haiku_4-5_gpt_eval.xlsx → bndes_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: bndes_haiku_4-5_opus_eval.xlsx → bndes_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: bndes_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: bndes_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: bndes_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: bndes_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: bndes_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: bndes_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: bndes_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: bndes_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: bndes_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: bndes_gpt-4o-mini_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.4_gpt_eval.xlsx
➖ Já correto: bndes_gpt-5.4_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: bndes_gpt-5_4-mini_opus_eval.xlsx → bndes_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: bndes_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: bndes_gpt-5_5_opus_eval.xlsx → bndes_gpt-5.5_opus_eval.xlsx
✓ Renomeado: cvm_haiku-4-5_gpt_eval.xlsx → cvm_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: cvm_haiku_4-5_opus_eval.xlsx → cvm_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: cvm_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: cvm_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: cvm_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: cvm_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: cvm_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: cvm_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: cvm_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: cvm_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: cvm_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: cvm_gpt-4o-mini_opus_eval.xlsx
✓ Renomeado: cvm_gpt-5-4_opus_eval.xlsx → cvm_gpt-5.4_opus_eval.xlsx
➖ Já correto: cvm_gpt-5.4_gpt_eval.xlsx
➖ Já correto: cvm_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: cvm_gpt-5_4-mini_opus_eval.xlsx → cvm_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: cvm_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: cvm_gpt-5_5_opus_eval.xlsx → cvm_gpt-5.5_opus_eval.xlsx
✓ Renomeado: petrobras_haiku-4-5_gpt_eval.xlsx → petrobras_claude-haiku-4-5_gpt_eval.xlsx
✓ Renomeado: petrobras_haiku-4-5_opus_eval.xlsx → petrobras_claude-haiku-4-5_opus_eval.xlsx
➖ Já correto: petrobras_claude-opus-4-7_gpt_eval.xlsx
➖ Já correto: petrobras_claude-opus-4-7_opus_eval.xlsx
➖ Já correto: petrobras_claude-sonnet-4-6_gpt_eval.xlsx
➖ Já correto: petrobras_claude-sonnet-4-6_opus_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-flash_gpt_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-flash_opus_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-pro_gpt_eval.xlsx
➖ Já correto: petrobras_deepseek-v4-pro_opus_eval.xlsx
➖ Já correto: petrobras_gpt-4o-mini_gpt_eval.xlsx
➖ Já correto: petrobras_gpt-4o-mini_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.4_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_4_opus_eval.xlsx → petrobras_gpt-5.4_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.4-mini_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_4-mini_opus_eval.xlsx → petrobras_gpt-5.4-mini_opus_eval.xlsx
➖ Já correto: petrobras_gpt-5.5_gpt_eval.xlsx
✓ Renomeado: petrobras_gpt-5_5_opus_eval.xlsx → petrobras_gpt-5.5_opus_eval.xlsx

In [21]:
grupos = {}

for _, row in df_files.iterrows():
    arquivo = lims_path / row["pasta"] / row["novo_nome"]
    nome = row["novo_nome"]
    
    if nome.endswith("opus_eval.xlsx"):
        avaliador = "opus"
    elif nome.endswith("gpt_eval.xlsx"):
        avaliador = "gpt"
    else:
        continue
    
    if arquivo.exists():
        df_temp = pd.read_excel(arquivo, nrows=0)
        colunas = tuple(df_temp.columns.tolist())
        
        if avaliador not in grupos:
            grupos[avaliador] = []
        grupos[avaliador].append({"arquivo": nome, "colunas": colunas})

for grupo, items in grupos.items():
    colunas_unicas = set(i["colunas"] for i in items)
    print(f"\n{'='*50}")
    print(f"Grupo: {grupo} ({len(items)} arquivos)")
    if len(colunas_unicas) == 1:
        print(f"✓ Todos compartilham as mesmas colunas:")
        for col in list(colunas_unicas)[0]:
            print(f"   - {col}")
    else:
        print(f"⚠️ Colunas divergentes!")
        for item in items:
            print(f"\n  {item['arquivo']}:\n    {list(item['colunas'])}")

==================================================
Grupo: gpt (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_gpt
   - avaliacao_gpt

==================================================
Grupo: opus (27 arquivos)
⚠️ Colunas divergentes!

  bndes_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  bndes_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  cvm_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-haiku-4-5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-opus-4-7_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_claude-sonnet-4-6_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_deepseek-v4-flash_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'cache_read_tokens__bug', 'custo_real_usd__bug', 'justificativa_opus', 'avaliacao_opus']

  petrobras_deepseek-v4-pro_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'cache_read_tokens__bug', 'custo_real_usd__bug', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-4o-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.4_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.4-mini_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

  petrobras_gpt-5.5_opus_eval.xlsx:
    ['id', 'categoria', 'pergunta', 'resposta', 'input_tokens', 'output_tokens', 'total_tokens', 'cache_read_tokens', 'cache_miss_tokens', 'n_invocacoes', 'custo_usd', 'custo_real_usd', 'latencia_s', 'erro', 'justificativa_opus', 'avaliacao_opus']

In [22]:
for arquivo in ["petrobras_deepseek-v4-flash_opus_eval.xlsx", "petrobras_deepseek-v4-pro_opus_eval.xlsx"]:
    pasta = arquivo.split("_opus_eval")[0]
    caminho = lims_path / pasta / arquivo
    
    df_temp = pd.read_excel(caminho)
    df_temp = df_temp.drop(columns=["cache_read_tokens__bug", "custo_real_usd__bug"])
    df_temp.to_excel(caminho, index=False)
    print(f"✓ Colunas removidas: {arquivo}")

✓ Colunas removidas: petrobras_deepseek-v4-flash_opus_eval.xlsx
✓ Colunas removidas: petrobras_deepseek-v4-pro_opus_eval.xlsx

In [23]:
grupos = {}

for _, row in df_files.iterrows():
    arquivo = lims_path / row["pasta"] / row["novo_nome"]
    nome = row["novo_nome"]
    
    if nome.endswith("opus_eval.xlsx"):
        avaliador = "opus"
    elif nome.endswith("gpt_eval.xlsx"):
        avaliador = "gpt"
    else:
        continue
    
    if arquivo.exists():
        df_temp = pd.read_excel(arquivo, nrows=0)
        colunas = tuple(df_temp.columns.tolist())
        
        if avaliador not in grupos:
            grupos[avaliador] = []
        grupos[avaliador].append({"arquivo": nome, "colunas": colunas})

for grupo, items in grupos.items():
    colunas_unicas = set(i["colunas"] for i in items)
    print(f"\n{'='*50}")
    print(f"Grupo: {grupo} ({len(items)} arquivos)")
    if len(colunas_unicas) == 1:
        print(f"✓ Todos compartilham as mesmas colunas:")
        for col in list(colunas_unicas)[0]:
            print(f"   - {col}")
    else:
        print(f"⚠️ Colunas divergentes!")
        for item in items:
            print(f"\n  {item['arquivo']}:\n    {list(item['colunas'])}")

==================================================
Grupo: gpt (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_gpt
   - avaliacao_gpt

==================================================
Grupo: opus (27 arquivos)
✓ Todos compartilham as mesmas colunas:
   - id
   - categoria
   - pergunta
   - resposta
   - input_tokens
   - output_tokens
   - total_tokens
   - cache_read_tokens
   - cache_miss_tokens
   - n_invocacoes
   - custo_usd
   - custo_real_usd
   - latencia_s
   - erro
   - justificativa_opus
   - avaliacao_opus

In [26]:
for _, row in df_files.iterrows():
    caminho = lims_path / row["pasta"] / row["novo_nome"]
    df_temp = pd.read_excel(caminho)
    
    if len(df_temp) != 50:
        print(f"⚠️ {row['novo_nome']}: {len(df_temp)} linhas")
    
    nulos = df_temp.drop(columns=["erro"]).isnull().sum()
    nulos = nulos[nulos > 0]
    if not nulos.empty:
        print(f"⚠️ {row['novo_nome']} tem nulos: {nulos.to_dict()}")

In [27]:
for _, row in df_files.iterrows():
    caminho = lims_path / row["pasta"] / row["novo_nome"]
    df_temp = pd.read_excel(caminho)
    df_temp = df_temp.drop(columns=["erro"])
    df_temp.to_excel(caminho, index=False)
    print(f"✓ Coluna erro removida: {row['novo_nome']}")

✓ Coluna erro removida: bndes_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: bndes_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: bndes_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: bndes_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: bndes_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: bndes_gpt-5.5_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: cvm_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: cvm_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: cvm_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: cvm_gpt-5.5_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-haiku-4-5_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-haiku-4-5_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-opus-4-7_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-opus-4-7_opus_eval.xlsx
✓ Coluna erro removida: petrobras_claude-sonnet-4-6_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_claude-sonnet-4-6_opus_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-flash_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-flash_opus_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-pro_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_deepseek-v4-pro_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-4o-mini_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-4o-mini_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4-mini_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.4-mini_opus_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.5_gpt_eval.xlsx
✓ Coluna erro removida: petrobras_gpt-5.5_opus_eval.xlsx

In [28]:
editais = ["bndes", "cvm", "petrobras"]

for edital in editais:
    arquivos = df_files[df_files["pasta"].str.startswith(edital)]
    dfs = [pd.read_excel(lims_path / row["pasta"] / row["novo_nome"])[["id", "categoria", "pergunta"]] 
           for _, row in arquivos.iterrows()]
    
    referencia = dfs[0]
    todos_iguais = all(df.equals(referencia) for df in dfs[1:])
    
    print(f"{'✓' if todos_iguais else '⚠️'} {edital}: {'todas iguais' if todos_iguais else 'divergências encontradas'}")

✓ bndes: todas iguais
✓ cvm: todas iguais
✓ petrobras: todas iguais

In [29]:
for _, row in df_files[df_files["novo_nome"].str.endswith("gpt_eval.xlsx")].iterrows():
    caminho_gpt = lims_path / row["pasta"] / row["novo_nome"]
    caminho_opus = lims_path / row["pasta"] / row["novo_nome"].replace("gpt_eval", "opus_eval")
    
    df_gpt = pd.read_excel(caminho_gpt)["resposta"]
    df_opus = pd.read_excel(caminho_opus)["resposta"]
    
    if not df_gpt.equals(df_opus):
        print(f"⚠️ {row['pasta']}: resposta divergente")

In [31]:
for pasta in df_files["pasta"].unique():
    arquivos = df_files[df_files["pasta"] == pasta]
    
    caminho_gpt = lims_path / pasta / arquivos[arquivos["novo_nome"].str.endswith("gpt_eval.xlsx")]["novo_nome"].values[0]
    caminho_opus = lims_path / pasta / arquivos[arquivos["novo_nome"].str.endswith("opus_eval.xlsx")]["novo_nome"].values[0]
    
    df_gpt = pd.read_excel(caminho_gpt)[["id", "categoria", "pergunta", "resposta", "justificativa_gpt", "avaliacao_gpt"]]
    df_opus = pd.read_excel(caminho_opus)[["justificativa_opus", "avaliacao_opus"]]
    
    df_consolidado = pd.concat([df_gpt, df_opus], axis=1)
    df_consolidado["convergencia"] = df_consolidado["avaliacao_gpt"] == df_consolidado["avaliacao_opus"]
    
    print(f"\n{'='*50}")
    print(f"{pasta}")
    
    vc = df_consolidado["convergencia"].value_counts()
    vc_norm = df_consolidado["convergencia"].value_counts(normalize=True).round(2)
    print(pd.concat([vc, vc_norm], axis=1, keys=["count", "%"]))
    
    soma_gpt = df_consolidado["avaliacao_gpt"].sum()
    soma_opus = df_consolidado["avaliacao_opus"].sum()
    max_score = len(df_consolidado) * df_consolidado["avaliacao_gpt"].max()
    
    print(f"\n  avaliacao_gpt:  soma={soma_gpt} | {soma_gpt/max_score*100:.1f}%")
    print(f"  avaliacao_opus: soma={soma_opus} | {soma_opus/max_score*100:.1f}%")

==================================================
bndes_claude-haiku-4-5
              count     %
convergencia
True             46  0.92
False             4  0.08

  avaliacao_gpt:  soma=46.5 | 93.0%
  avaliacao_opus: soma=48.5 | 97.0%

==================================================
bndes_claude-opus-4-7
              count    %
convergencia
True             45  0.9
False             5  0.1

  avaliacao_gpt:  soma=47.0 | 94.0%
  avaliacao_opus: soma=49.5 | 99.0%

==================================================
bndes_claude-sonnet-4-6
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=48.0 | 96.0%
  avaliacao_opus: soma=49.5 | 99.0%

==================================================
bndes_deepseek-v4-flash
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=47.5 | 95.0%
  avaliacao_opus: soma=49.0 | 98.0%

==================================================
bndes_deepseek-v4-pro
              count     %
convergencia
True             46  0.92
False             4  0.08

  avaliacao_gpt:  soma=46.5 | 93.0%
  avaliacao_opus: soma=48.5 | 97.0%

==================================================
bndes_gpt-4o-mini
              count    %
convergencia
True             45  0.9
False             5  0.1

  avaliacao_gpt:  soma=45.0 | 90.0%
  avaliacao_opus: soma=47.5 | 95.0%

==================================================
bndes_gpt-5.4
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=47.5 | 95.0%
  avaliacao_opus: soma=47.0 | 94.0%

==================================================
bndes_gpt-5.4-mini
              count     %
convergencia
True             42  0.84
False             8  0.16

  avaliacao_gpt:  soma=44.5 | 89.0%
  avaliacao_opus: soma=45.5 | 91.0%

==================================================
bndes_gpt-5.5
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=49.5 | 99.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
cvm_claude-haiku-4-5
              count    %
convergencia
True             45  0.9
False             5  0.1

  avaliacao_gpt:  soma=47.5 | 95.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
cvm_claude-opus-4-7
              count     %
convergencia
True             48  0.96
False             2  0.04

  avaliacao_gpt:  soma=49.0 | 98.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
cvm_claude-sonnet-4-6
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
cvm_deepseek-v4-flash
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
cvm_deepseek-v4-pro
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=49.0 | 98.0%
  avaliacao_opus: soma=49.5 | 99.0%

==================================================
cvm_gpt-4o-mini
              count     %
convergencia
True             44  0.88
False             6  0.12

  avaliacao_gpt:  soma=46.0 | 92.0%
  avaliacao_opus: soma=49.0 | 98.0%

==================================================
cvm_gpt-5.4
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=48.0 | 96.0%

==================================================
cvm_gpt-5.4-mini
              count    %
convergencia
True             45  0.9
False             5  0.1

  avaliacao_gpt:  soma=45.0 | 90.0%
  avaliacao_opus: soma=47.5 | 95.0%

==================================================
cvm_gpt-5.5
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
petrobras_claude-haiku-4-5
              count     %
convergencia
True             42  0.84
False             8  0.16

  avaliacao_gpt:  soma=45.0 | 90.0%
  avaliacao_opus: soma=49.0 | 98.0%

==================================================
petrobras_claude-opus-4-7
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=49.5 | 99.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
petrobras_claude-sonnet-4-6
              count     %
convergencia
True             48  0.96
False             2  0.04

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=49.5 | 99.0%

==================================================
petrobras_deepseek-v4-flash
              count     %
convergencia
True             48  0.96
False             2  0.04

  avaliacao_gpt:  soma=48.5 | 97.0%
  avaliacao_opus: soma=49.5 | 99.0%

==================================================
petrobras_deepseek-v4-pro
              count     %
convergencia
True             42  0.84
False             8  0.16

  avaliacao_gpt:  soma=46.0 | 92.0%
  avaliacao_opus: soma=50 | 100.0%

==================================================
petrobras_gpt-4o-mini
              count     %
convergencia
True             46  0.92
False             4  0.08

  avaliacao_gpt:  soma=44.5 | 89.0%
  avaliacao_opus: soma=45.5 | 91.0%

==================================================
petrobras_gpt-5.4
              count    %
convergencia
True             50  1.0

  avaliacao_gpt:  soma=49.0 | 98.0%
  avaliacao_opus: soma=49.0 | 98.0%

==================================================
petrobras_gpt-5.4-mini
              count     %
convergencia
True             47  0.94
False             3  0.06

  avaliacao_gpt:  soma=45.0 | 90.0%
  avaliacao_opus: soma=46.5 | 93.0%

==================================================
petrobras_gpt-5.5
              count     %
convergencia
True             49  0.98
False             1  0.02

  avaliacao_gpt:  soma=49.5 | 99.0%
  avaliacao_opus: soma=50 | 100.0%

In [32]:
df_files["modelo"] = df_files["pasta"].str.split("_", n=1).str[1]

for modelo in df_files["modelo"].unique():
    arquivos = df_files[df_files["modelo"] == modelo]
    
    dfs = []
    for _, row in arquivos[arquivos["novo_nome"].str.endswith("gpt_eval.xlsx")].iterrows():
        pasta = row["pasta"]
        caminho_gpt = lims_path / pasta / row["novo_nome"]
        caminho_opus = lims_path / pasta / arquivos[(arquivos["pasta"] == pasta) & (arquivos["novo_nome"].str.endswith("opus_eval.xlsx"))]["novo_nome"].values[0]
        
        df_gpt = pd.read_excel(caminho_gpt)[["id", "categoria", "pergunta", "resposta", "justificativa_gpt", "avaliacao_gpt"]]
        df_opus = pd.read_excel(caminho_opus)[["justificativa_opus", "avaliacao_opus"]]
        df_consolidado = pd.concat([df_gpt, df_opus], axis=1)
        df_consolidado["convergencia"] = df_consolidado["avaliacao_gpt"] == df_consolidado["avaliacao_opus"]
        dfs.append(df_consolidado)
    
    df_modelo = pd.concat(dfs, ignore_index=True)
    
    print(f"\n{'='*50}")
    print(f"{modelo} ({len(dfs)} editais, {len(df_modelo)} linhas)")
    
    vc = df_modelo["convergencia"].value_counts()
    vc_norm = df_modelo["convergencia"].value_counts(normalize=True).round(2)
    print(pd.concat([vc, vc_norm], axis=1, keys=["count", "%"]))
    
    soma_gpt = df_modelo["avaliacao_gpt"].sum()
    soma_opus = df_modelo["avaliacao_opus"].sum()
    max_score = len(df_modelo) * df_modelo["avaliacao_gpt"].max()
    
    print(f"\n  avaliacao_gpt:  soma={soma_gpt} | {soma_gpt/max_score*100:.1f}%")
    print(f"  avaliacao_opus: soma={soma_opus} | {soma_opus/max_score*100:.1f}%")

==================================================
claude-haiku-4-5 (3 editais, 150 linhas)
              count     %
convergencia
True            133  0.89
False            17  0.11

  avaliacao_gpt:  soma=139.0 | 92.7%
  avaliacao_opus: soma=147.5 | 98.3%

==================================================
claude-opus-4-7 (3 editais, 150 linhas)
              count     %
convergencia
True            142  0.95
False             8  0.05

  avaliacao_gpt:  soma=145.5 | 97.0%
  avaliacao_opus: soma=149.5 | 99.7%

==================================================
claude-sonnet-4-6 (3 editais, 150 linhas)
              count     %
convergencia
True            142  0.95
False             8  0.05

  avaliacao_gpt:  soma=145.0 | 96.7%
  avaliacao_opus: soma=149.0 | 99.3%

==================================================
deepseek-v4-flash (3 editais, 150 linhas)
              count     %
convergencia
True            142  0.95
False             8  0.05

  avaliacao_gpt:  soma=144.5 | 96.3%
  avaliacao_opus: soma=148.5 | 99.0%

==================================================
deepseek-v4-pro (3 editais, 150 linhas)
              count     %
convergencia
True            137  0.91
False            13  0.09

  avaliacao_gpt:  soma=141.5 | 94.3%
  avaliacao_opus: soma=148.0 | 98.7%

==================================================
gpt-4o-mini (3 editais, 150 linhas)
              count    %
convergencia
True            135  0.9
False            15  0.1

  avaliacao_gpt:  soma=135.5 | 90.3%
  avaliacao_opus: soma=142.0 | 94.7%

==================================================
gpt-5.4 (3 editais, 150 linhas)
              count     %
convergencia
True            148  0.99
False             2  0.01

  avaliacao_gpt:  soma=145.0 | 96.7%
  avaliacao_opus: soma=144.0 | 96.0%

==================================================
gpt-5.4-mini (3 editais, 150 linhas)
              count     %
convergencia
True            134  0.89
False            16  0.11

  avaliacao_gpt:  soma=134.5 | 89.7%
  avaliacao_opus: soma=139.5 | 93.0%

==================================================
gpt-5.5 (3 editais, 150 linhas)
              count     %
convergencia
True            145  0.97
False             5  0.03

  avaliacao_gpt:  soma=147.5 | 98.3%
  avaliacao_opus: soma=150 | 100.0%

In [33]:
rows = []

df_files["modelo"] = df_files["pasta"].str.split("_", n=1).str[1]

for modelo in df_files["modelo"].unique():
    arquivos = df_files[df_files["modelo"] == modelo]
    
    dfs = []
    for _, row in arquivos[arquivos["novo_nome"].str.endswith("gpt_eval.xlsx")].iterrows():
        pasta = row["pasta"]
        caminho_gpt = lims_path / pasta / row["novo_nome"]
        caminho_opus = lims_path / pasta / arquivos[(arquivos["pasta"] == pasta) & (arquivos["novo_nome"].str.endswith("opus_eval.xlsx"))]["novo_nome"].values[0]
        
        df_gpt = pd.read_excel(caminho_gpt)[["avaliacao_gpt"]]
        df_opus = pd.read_excel(caminho_opus)[["avaliacao_opus"]]
        df_consolidado = pd.concat([df_gpt, df_opus], axis=1)
        df_consolidado["convergencia"] = df_consolidado["avaliacao_gpt"] == df_consolidado["avaliacao_opus"]
        dfs.append(df_consolidado)
    
    df_modelo = pd.concat(dfs, ignore_index=True)
    max_score = len(df_modelo) * df_modelo["avaliacao_gpt"].max()
    
    rows.append({
        "modelo": modelo,
        "n_linhas": len(df_modelo),
        "convergencia_count": df_modelo["convergencia"].sum(),
        "convergencia_%": round(df_modelo["convergencia"].mean() * 100, 1),
        "soma_gpt": df_modelo["avaliacao_gpt"].sum(),
        "score_gpt_%": round(df_modelo["avaliacao_gpt"].sum() / max_score * 100, 1),
        "soma_opus": df_modelo["avaliacao_opus"].sum(),
        "score_opus_%": round(df_modelo["avaliacao_opus"].sum() / max_score * 100, 1),
    })

df_modelos = pd.DataFrame(rows)
df_modelos

,modelo,n_linhas,convergencia_count,convergencia_%,soma_gpt,score_gpt_%,soma_opus,score_opus_%
0,claude-haiku-4-5,150,133,88.7,139.0,92.7,147.5,98.3
1,claude-opus-4-7,150,142,94.7,145.5,97.0,149.5,99.7
2,claude-sonnet-4-6,150,142,94.7,145.0,96.7,149.0,99.3
3,deepseek-v4-flash,150,142,94.7,144.5,96.3,148.5,99.0
4,deepseek-v4-pro,150,137,91.3,141.5,94.3,148.0,98.7
5,gpt-4o-mini,150,135,90.0,135.5,90.3,142.0,94.7
6,gpt-5.4,150,148,98.7,145.0,96.7,144.0,96.0
7,gpt-5.4-mini,150,134,89.3,134.5,89.7,139.5,93.0
8,gpt-5.5,150,145,96.7,147.5,98.3,150.0,100.0

In [34]:
for pasta in df_files["pasta"].unique():
    arquivos = df_files[df_files["pasta"] == pasta]
    
    caminho_gpt = lims_path / pasta / arquivos[arquivos["novo_nome"].str.endswith("gpt_eval.xlsx")]["novo_nome"].values[0]
    caminho_opus = lims_path / pasta / arquivos[arquivos["novo_nome"].str.endswith("opus_eval.xlsx")]["novo_nome"].values[0]
    
    df_gpt = pd.read_excel(caminho_gpt)[["id", "categoria", "pergunta", "resposta", "justificativa_gpt", "avaliacao_gpt"]]
    df_opus = pd.read_excel(caminho_opus)[["justificativa_opus", "avaliacao_opus"]]
    
    df_consolidado = pd.concat([df_gpt, df_opus], axis=1)
    df_consolidado["convergencia"] = df_consolidado["avaliacao_gpt"] == df_consolidado["avaliacao_opus"]
    
    caminho_saida = lims_path / pasta / f"{pasta}_eval_consolidado.xlsx"
    df_consolidado.to_excel(caminho_saida, index=False)
    print(f"✓ {pasta}_eval_consolidado.xlsx")

✓ bndes_claude-haiku-4-5_eval_consolidado.xlsx
✓ bndes_claude-opus-4-7_eval_consolidado.xlsx
✓ bndes_claude-sonnet-4-6_eval_consolidado.xlsx
✓ bndes_deepseek-v4-flash_eval_consolidado.xlsx
✓ bndes_deepseek-v4-pro_eval_consolidado.xlsx
✓ bndes_gpt-4o-mini_eval_consolidado.xlsx
✓ bndes_gpt-5.4_eval_consolidado.xlsx
✓ bndes_gpt-5.4-mini_eval_consolidado.xlsx
✓ bndes_gpt-5.5_eval_consolidado.xlsx
✓ cvm_claude-haiku-4-5_eval_consolidado.xlsx
✓ cvm_claude-opus-4-7_eval_consolidado.xlsx
✓ cvm_claude-sonnet-4-6_eval_consolidado.xlsx
✓ cvm_deepseek-v4-flash_eval_consolidado.xlsx
✓ cvm_deepseek-v4-pro_eval_consolidado.xlsx
✓ cvm_gpt-4o-mini_eval_consolidado.xlsx
✓ cvm_gpt-5.4_eval_consolidado.xlsx
✓ cvm_gpt-5.4-mini_eval_consolidado.xlsx
✓ cvm_gpt-5.5_eval_consolidado.xlsx
✓ petrobras_claude-haiku-4-5_eval_consolidado.xlsx
✓ petrobras_claude-opus-4-7_eval_consolidado.xlsx
✓ petrobras_claude-sonnet-4-6_eval_consolidado.xlsx
✓ petrobras_deepseek-v4-flash_eval_consolidado.xlsx
✓ petrobras_deepseek-v4-pro_eval_consolidado.xlsx
✓ petrobras_gpt-4o-mini_eval_consolidado.xlsx
✓ petrobras_gpt-5.4_eval_consolidado.xlsx
✓ petrobras_gpt-5.4-mini_eval_consolidado.xlsx
✓ petrobras_gpt-5.5_eval_consolidado.xlsx

In [35]:
dfs_divergentes = []

for pasta in df_files["pasta"].unique():
    caminho = lims_path / pasta / f"{pasta}_eval_consolidado.xlsx"
    df_temp = pd.read_excel(caminho)
    df_temp["pasta"] = pasta
    dfs_divergentes.append(df_temp[df_temp["convergencia"] == False])

df_divergentes = pd.concat(dfs_divergentes, ignore_index=True)
df_divergentes.to_excel(lims_path / "divergentes.xlsx", index=False)
print(f"✓ divergentes.xlsx — {len(df_divergentes)} linhas")

✓ divergentes.xlsx — 92 linhas

In [37]:
df_divergentes

,id,categoria,pergunta,resposta,justificativa_gpt,avaliacao_gpt,justificativa_opus,avaliacao_opus,convergencia,pasta
0,10,Dados sobre as inscrições,O candidato precisa guardar o comprovante de i...,"Com base no edital do BNDES, **sim, o candidat...",Parcialmente correta. O edital exige impressão...,0.5,"Os itens 7.1, 7.2 e 9.4 e 9.4.1 confirmam a ob...",1.0,False,bndes_claude-haiku-4-5
1,38,Dados sobre a Prova,Qual é o critério mínimo de aprovação na prova...,"Com base no edital do BNDES, o critério mínimo...",Parcialmente correta. A resposta acerta os mín...,0.5,O item 8.1.3 estabelece o aproveitamento mínim...,1.0,False,bndes_claude-haiku-4-5
2,40,Dados sobre a Prova,O concurso BNDES possui prova discursiva para ...,"Sim, o concurso BNDES para **Analista – Ciênci...",Parcialmente correta. A resposta acerta que há...,0.5,O item 8.1.5 confirma a existência de prova di...,1.0,False,bndes_claude-haiku-4-5
3,44,Dados sobre a Prova,Quantas provas discursivas de Ciência de Dados...,"Com base no edital do BNDES, a resposta é clar...",Parcialmente correta. A resposta cita corretam...,0.5,O item 8.1.6 estabelece exatamente que serão c...,1.0,False,bndes_claude-haiku-4-5
4,22,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas p...,## Reserva de vagas para candidatos negros — B...,"Parcialmente correta. O percentual de 30%, o a...",0.5,Correto. Item 3.2.1 estabelece reserva de 30% ...,1.0,False,bndes_claude-opus-4-7
...,...,...,...,...,...,...,...,...,...,...
87,29,Dados sobre o Cargo,O cargo de Ciência de Dados exige disponibilid...,O edital não menciona explicitamente a exigênc...,"Certo. O Anexo II, item 1.7 (p. 26-27), traz o...",1.0,O edital não exige explicitamente disponibilid...,0.5,False,petrobras_gpt-4o-mini
88,17,Dados sobre o Concurso,Existe possibilidade de impugnar o edital do c...,"Sim, há possibilidade de impugnar/contestar po...",Parcialmente correta. O edital não traz proced...,0.5,Resposta correta e bem fundamentada. O edital ...,1.0,False,petrobras_gpt-5.4-mini
89,25,Dados sobre o Cargo,Qual é a jornada de trabalho do cargo no concu...,O edital que tenho acesso aqui informa a remun...,Não verificável no edital. O Anexo II informa ...,0.5,Não verificável. O edital efetivamente não tra...,1.0,False,petrobras_gpt-5.4-mini
90,29,Dados sobre o Cargo,O cargo de Ciência de Dados exige disponibilid...,Não encontrei no edital uma exigência explícit...,Não verificável como exigência de viagens. O e...,0.5,Resposta correta. O edital não traz exigência ...,1.0,False,petrobras_gpt-5.4-mini
91,36,Dados sobre a Prova,Quantas questões ou itens de conhecimentos esp...,Para o concurso Petrobras — exceto a ênfase 19...,"Parcialmente correta. O número informado, 70 i...",0.5,Resposta correta. O subitem 6.1.1 estabelece 7...,1.0,False,petrobras_gpt-5.5

In [38]:
display(df_divergentes['id'].value_counts())
display(df_divergentes['pergunta'].value_counts())

id
25    8
44    6
17    6
10    5
16    5
50    5
29    5
37    4
42    4
9     3
46    3
12    3
38    2
22    2
33    2
5     2
41    2
26    2
30    2
39    2
18    2
36    2
40    1
45    1
15    1
3     1
48    1
24    1
23    1
8     1
19    1
20    1
4     1
32    1
35    1
47    1
11    1
Name: count, dtype: int64

pergunta
Qual é a jornada de trabalho do cargo no concurso CVM?                                               6
Quantas provas discursivas de Ciência de Dados serão corrigidas no concurso BNDES?                   5
Quais cuidados o candidato deve ter com o cartão ou folha de respostas no concurso CVM?              5
O candidato precisa guardar o comprovante de inscrição ou pagamento do concurso BNDES?               4
Quantos pontos vale a prova discursiva do concurso CVM?                                              4
Existe possibilidade de impugnar o edital do concurso PETROBRAS?                                     4
O cargo de Ciência de Dados exige disponibilidade para viagens no concurso PETROBRAS?                3
Qual é o critério mínimo de aprovação na prova objetiva do concurso BNDES?                           2
Qual o total de pontos das provas objetivas para o concurso BNDES?                                   2
Como é dividida a prova de conhecimentos específicos de Ciência de Dados no concurso BNDES?          2
Qual é o prazo-limite de pagamento da inscrição do concurso BNDES?                                   2
O candidato pode fazer mais de uma inscrição no concurso BNDES?                                      2
Existe possibilidade de impugnar o edital do concurso BNDES?                                         2
Qual escolaridade é exigida para concorrer à área de Ciência de Dados no concurso BNDES?             2
Quais são as atribuições gerais do cargo ligado à Ciência de Dados no concurso BNDES?                2
O cargo de Ciência de Dados exige disponibilidade para viagens no concurso CVM?                      2
Onde o candidato encontra o cronograma oficial do concurso CVM?                                      2
Onde o candidato encontra o cronograma oficial do concurso PETROBRAS?                                2
Quantas fases ou etapas tem o concurso PETROBRAS?                                                    2
Qual é a jornada de trabalho do cargo no concurso PETROBRAS?                                         2
Quantas questões ou itens de conhecimentos específicos existem no concurso PETROBRAS?                2
O concurso BNDES possui prova discursiva para Ciência de Dados?                                      1
Qual percentual ou regra de reserva de vagas para candidatos negros existe no concurso BNDES?        1
Como é calculada a nota final do concurso BNDES para Ciência de Dados?                               1
Qual horário de referência deve ser considerado pelo candidato no concurso BNDES?                    1
Onde o candidato encontra o cronograma oficial do concurso BNDES?                                    1
Como é composta a prova discursiva de Ciência de Dados no concurso BNDES?                            1
Em qual site o candidato deve fazer a inscrição do concurso BNDES?                                   1
Existe penalidade por erro na prova objetiva do concurso BNDES?                                      1
Qual é a data prevista ou oficial da prova do concurso BNDES?                                        1
Existe penalidade por erro na prova objetiva do concurso CVM?                                        1
Qual tipo de caneta pode ser utilizado para realizar o concurso CVM?                                 1
Quantas fases ou etapas tem o concurso CVM?                                                          1
Como é dividida a prova de conhecimentos específicos de Ciência de Dados no concurso CVM?            1
Qual é a data prevista ou oficial da prova do concurso CVM?                                          1
Qual é o regime de contratação ou vínculo do concurso CVM?                                           1
O candidato pode fazer mais de uma inscrição no concurso CVM?                                        1
Qual é o cargo/ênfase/perfil de Ciência de Dados no concurso CVM?                                    1
Qual a remuneração ou salário do cargo do concurso CVM?                                              1
A inscrição do concurso CVM é feita somente pela internet?                                           1
Qual é o cargo/ênfase/perfil de Ciência de Dados no concurso PETROBRAS?                              1
Quantas vagas existem para a área de Ciência de Dados no concurso PETROBRAS?                         1
Quantas vagas imediatas existem para Ciência de Dados no concurso PETROBRAS?                         1
Como é dividida a prova de conhecimentos específicos de Ciência de Dados no concurso PETROBRAS?      1
Como é composta a prova discursiva de Ciência de Dados no concurso PETROBRAS?                        1
Quantas provas discursivas de Ciência de Dados serão corrigidas no concurso PETROBRAS?               1
Quais são as formas de pagamento da taxa de inscrição do concurso PETROBRAS?                         1
O candidato precisa guardar o comprovante de inscrição ou pagamento do concurso PETROBRAS?           1
Quantas questões ou itens objetivos existem no concurso PETROBRAS?                                   1
Quantas questões ou itens de conhecimentos básicos existem no concurso PETROBRAS?                    1
Qual é a data prevista ou oficial da prova do concurso PETROBRAS?                                    1
Qual é a duração ou organização dos turnos de prova do concurso PETROBRAS?                           1
Qual entidade está responsável pela organização e execução do concurso PETROBRAS?                    1
Qual percentual ou regra de reserva de vagas para candidatos negros existe no concurso PETROBRAS?    1
Name: count, dtype: int64