In [1]:
from pathlib import Path
import pandas as pd

NB_DIR = Path('.').resolve()  # avaliacao_chats_comerciais/
DATA_DIR = NB_DIR / 'data'
DF_AVAL_PATH = NB_DIR.parent / 'avaliacao_llms' / 'df_avaliacoes.xlsx'
BATCHES_DIR = NB_DIR / 'batches'
BATCHES_DIR.mkdir(exist_ok=True)

def prepara_batches(concurso: str, chats: dict, n_batches: int = 5):
    """
    concurso: 'bndes' | 'cvm' | 'petrobras'
    chats: {'chatgpt': Path, 'claude_chat': Path} com xlsx contendo colunas id, resposta
    """
    df = pd.read_excel(DF_AVAL_PATH)
    sub = df[df['edital'] == concurso][['id', 'categoria', 'pergunta', 'modelo', 'resposta']]

    wide = (sub.pivot_table(index=['id', 'categoria', 'pergunta'],
                            columns='modelo', values='resposta', aggfunc='first')
              .reset_index())
    wide.columns = list(wide.columns[:3]) + [f'resposta_{c}' for c in wide.columns[3:]]

    for nome, path in chats.items():
        c = pd.read_excel(path)[['id', 'resposta']].rename(columns={'resposta': f'resposta_{nome}'})
        wide = wide.merge(c, on='id', how='left')

    wide = wide.sort_values('id').reset_index(drop=True)
    assert len(wide) == 50, f'esperado 50 perguntas, veio {len(wide)}'

    size = len(wide) // n_batches
    for i in range(n_batches):
        ini, fim = i * size, (i + 1) * size if i < n_batches - 1 else len(wide)
        out = BATCHES_DIR / f'{concurso}_batch_{i+1:02d}.xlsx'
        wide.iloc[ini:fim].to_excel(out, index=False)
        print(f'{out.name}: perguntas {wide.iloc[ini].id}–{wide.iloc[fim-1].id}')
    return wide

prepara_batches('bndes', {
    'chatgpt':     DATA_DIR / 'bndes_std_chatgpt_qa.xlsx',
    'claude_chat': DATA_DIR / 'bndes_std_claude_qa.xlsx',
})

bndes_batch_01.xlsx: perguntas 1–10
bndes_batch_02.xlsx: perguntas 11–20
bndes_batch_03.xlsx: perguntas 21–30
bndes_batch_04.xlsx: perguntas 31–40
bndes_batch_05.xlsx: perguntas 41–50

,id,categoria,pergunta,resposta_claude-haiku-4-5,resposta_claude-opus-4-7,resposta_claude-sonnet-4-6,resposta_deepseek-v4-flash,resposta_deepseek-v4-pro,resposta_gpt-4o-mini,resposta_gpt-5.4,resposta_gpt-5.4-mini,resposta_gpt-5.5,resposta_chatgpt,resposta_claude_chat
0,1,Dados sobre as inscrições,Qual o período de inscrição para o concurso BN...,**Período de inscrição do BNDES (01/2024):**\n...,O período de inscrição para o concurso BNDES (...,Aqui estão as informações sobre o período de i...,O período de inscrição para o concurso BNDES (...,O período de inscrição para o concurso do BNDE...,O período de inscrição para o concurso do BNDE...,O período de inscrição foi de 26/07/2024 a 19/...,O período de inscrição foi de 26/07/2024 a 19/...,Hoje é 30/04/2026. O período de inscrição para...,O período de inscrição para a Seleção Pública ...,O período de inscrições foi de\n26 de julho a ...
1,2,Dados sobre as inscrições,Qual o valor da taxa de inscrição do concurso ...,A **taxa de inscrição do concurso BNDES é de R...,A taxa de inscrição do concurso BNDES (Edital ...,O valor da taxa de inscrição do concurso BNDES...,A taxa de inscrição para o concurso do **BNDES...,O valor da taxa de inscrição do concurso BNDES...,O valor da taxa de inscrição para o concurso d...,"A taxa de inscrição é de R$ 110,00.\n\nref: ed...","A taxa de inscrição é de R$ 110,00.\n\nSe você...",A taxa de inscrição do concurso BNDES é de R$ ...,O valor da taxa de inscrição do concurso do\nB...,O valor da taxa de inscrição do concurso BNDES...
2,3,Dados sobre as inscrições,Em qual site o candidato deve fazer a inscriçã...,O candidato deve fazer a inscrição no **site d...,A inscrição deve ser feita pelo site da **Fund...,A inscrição para o concurso do BNDES deve ser ...,A inscrição para o concurso do BNDES (Edital n...,O edital menciona que a inscrição deve ser fei...,Os candidatos devem realizar a inscrição para ...,A inscrição deve ser feita na página da Fundaç...,O candidato deve fazer a inscrição na página d...,A inscrição deve ser feita somente pela intern...,A inscrição do concurso do\nBanco Nacional de ...,A inscrição do concurso BNDES deveria ser feit...
3,4,Dados sobre as inscrições,Quais são as formas de pagamento da taxa de in...,"Com base no edital do BNDES, as formas de paga...",O edital do BNDES (01/2024) prevê **duas forma...,O edital do BNDES (01/2024) prevê **duas forma...,De acordo com o edital do concurso BNDES (01/2...,"De acordo com o edital, após o envio do requer...",As formas de pagamento da taxa de inscrição do...,As formas de pagamento da taxa de inscrição sã...,As formas de pagamento da taxa de inscrição sã...,As formas de pagamento da taxa de inscrição sã...,De acordo com o edital do concurso do\nBanco N...,"De acordo com o edital, havia\nduas formas de ..."
4,5,Dados sobre as inscrições,Qual é o prazo-limite de pagamento da inscriçã...,"Com base no edital do BNDES, o **prazo-limite ...",O edital não fixa explicitamente uma data únic...,O prazo-limite para pagamento da inscrição no ...,"De acordo com o edital, o prazo-limite de paga...","Com base no edital, o prazo para pagamento da ...",O prazo-limite para o pagamento da inscrição d...,O edital informa que o pagamento da inscrição ...,O edital informa que o pagamento da inscrição ...,"Hoje é 30/04/2026. No edital, as inscrições fo...",O edital informa que o pagamento da inscrição ...,O edital\nnão especifica uma data-limite única...
5,6,Dados sobre as inscrições,Quem pode pedir isenção da taxa de inscrição d...,"Com base no edital do BNDES, **podem pedir ise...",## Quem pode pedir isenção da taxa de inscriçã...,Ótima pergunta! Veja quem tem direito à isençã...,Podem pedir **isenção total** da taxa de inscr...,Com base no edital do concurso BNDES (01/2024)...,Os candidatos que podem solicitar a isenção da...,Pode pedir isenção da taxa de inscrição quem s...,Podem pedir isenção da taxa de inscrição os(as...,Pode pedir isenção total da taxa de inscrição ...,Podiam solicitar isenção da taxa de inscrição ...,"De acordo com o edital, podiam solicitar a\nis..."
6,7,Dados sobre as inscrições,Qual é o período para solicitar isenção da tax...,"Com base no edital do BNDES, o período para so...",O período para solicitar isenção da taxa de in...,Aqui estão as informações sobre a isenção da t...,O período para solicitar a **isenção da taxa d...,O período para solicitar a **isenção da taxa d...,Os candidatos que se enquadram nas condições p...,O período para solicitar isenção da taxa de in...,O período para solicitar isenção da taxa de in...,Hoje é 30/04/2026. O período para solicitar is...,O período para solicitar isenção da taxa de in...,"De acordo com o edital, o período para solicit..."
7,8,Dados sobre as inscrições,A inscrição do concurso BNDES é feita somente ...,"Sim, a inscrição do concurso BNDES é feita **s...",Sim. A inscrição no concurso do BNDES (Edital ...,"Sim! De acordo com o edital do BNDES, a inscri...","Sim, a inscrição para o concurso BNDES é feita...","Sim, a inscrição do concurso BNDES (edital 01/...","Sim, a inscrição para o concurso do BNDES deve...",Sim. A inscrição deve ser feita somente pela i...,Sim. O edital diz que a inscrição deverá ser e...,Sim. A inscrição deveria ser efetuada somente ...,Sim. O edital estabelece que a inscrição para ...,"Sim! De acordo com o edital, a inscrição do co..."
8,9,Dados sobre as inscrições,O candidato pode fazer mais de uma inscrição n...,Com base na leitura completa do capítulo 6 sob...,Tenho o capítulo 6 inteiro. O edital BNDES 01/...,"Com base nas informações do edital, aqui está ...","Analisando o edital, **não há permissão para f...",Com base na leitura completa do Capítulo 6 e n...,O edital não menciona explicitamente se o cand...,"Não. Pelo edital, durante o período de inscriç...",O edital traz a inscrição “somente via interne...,"Não. Pelo edital, o candidato escolhe um único...",O edital não proíbe expressamente mais de uma ...,O edital\nnão menciona explicitamente\na possi...
9,10,Dados sobre as inscrições,O candidato precisa guardar o comprovante de i...,"Com base no edital do BNDES, **sim, o candidat...",Não encontrei nenhum item no edital que obrigu...,"Com base no edital do BNDES, veja o que o cand...","Sim, o candidato precisa guardar o comprovante...","Com base nos trechos do edital, não há uma exi...","Sim, o candidato deve guardar o comprovante de...",O edital não traz uma regra dizendo expressame...,Sim. O edital orienta que o candidato deve aco...,Sim. O edital prevê que:\n\n- a inscrição só é...,Sim. O edital orienta que o candidato deve gua...,O edital\nnão menciona explicitamente\na obrig...
10,11,Dados sobre o Concurso,Qual entidade está responsável pela organizaçã...,A **Fundação Cesgranrio** e o **BNDES** (Banco...,A organização e execução do concurso BNDES (Ed...,A organização e execução do concurso do BNDES ...,A organização e execução do concurso do BNDES ...,A organização e execução do concurso BNDES (Ed...,A responsabilidade pela organização e execução...,A seleção pública está sob a responsabilidade ...,A responsabilidade pela organização e execução...,A Seleção Pública do BNDES está sob responsabi...,A entidade responsável pela organização e exec...,"De acordo com o edital, a responsabilidade pel..."
11,12,Dados sobre o Concurso,Quantas fases ou etapas tem o concurso BNDES?,O concurso BNDES tem **4 etapas principais**:\...,O concurso do BNDES é constituído de **4 etapa...,O concurso do BNDES (Edital 01/2024) para o ca...,O concurso do BNDES (edital 01/2024) é compost...,"Com base no edital, o concurso do BNDES (01/20...",O concurso do BNDES é composto por quatro etap...,O concurso do BNDES para Analista tem 2 fases ...,O concurso do BNDES tem **4 etapas**:\n\n1. **...,O concurso BNDES tem **4 etapas**:\n\n1. **Pro...,O concurso do\nBanco Nacional de Desenvolvimen...,"De acordo com o edital, o concurso BNDES era c..."
12,13,Dados sobre o Concurso,Qual é o prazo de validade do concurso BNDES?,O **prazo de validade do concurso BNDES é de 2...,O prazo de validade da Seleção Pública do BNDE...,Ótima pergunta! Aqui estão as informações sobr...,"De acordo com o item **1.7** do edital, o praz...",O prazo de validade desta Seleção Pública do B...,O prazo de validade do concurso do BNDES é de ...,O prazo de validade da seleção pública do BNDE...,O prazo de validade da Seleção Pública do BNDE...,Hoje é 30/04/2026.\n\nO prazo de validade da S...,O prazo de validade do concurso do\nBanco Naci...,"De acordo com o edital, o prazo de validade do..."
13,14,Dados sobre o Concurso,Em quais cidades ou locais as provas do concur...,"Com base no edital do BNDES, as provas serão r...",As provas do concurso BNDES (Edital 01/2024) s...,Ótima pergunta! Veja o que o edital do BNDES 0...,As provas do concurso BNDES serão realizadas e...,"Com base no edital, as provas do concurso BNDE...",As provas do concurso do BNDES serão realizada...,As provas objetivas e discursiva serão realiza...,As provas objetivas e discursiva serão realiza...,As provas objetivas e discursiva do concurso B...,As provas do concurso do\nBanco Nacional de De...,"De acordo com o edital, as provas do concurso ..."
14,15,Dados sobre o Concurso,Qual horário de referência deve ser considerad...,"Com base no edital do BNDES, o **horário de re...",O horário de referência adotado pelo edital do...,O edital do concurso BNDES 01/2024 estabelece ...,O edital do BNDES estabelece que o **horário d...,"Com base na análise completa do edital, posso ...",O horário de referência que deve ser considera...,O edital fixa como referência o horário oficia...,O edital informa que o horário a ser considera...,O candidato deve considerar o horário oficial ...,O edital estabelece que todos os horários prev...,O edital\nnão menciona explicitamente\num horá...
15,16,Dados sobre o Concurso,Onde o candidato encontra o cronograma oficial...,O cronograma oficial do concurso BNDES está di...,O cronograma oficial do concurso BNDES (Edital...,O cronograma oficial do concurso BNDES 01/2024...,O cronograma oficial do concurso BNDES (Edital...,O cronograma oficial do concurso BNDES está no...,O cronograma oficial do concurso do BNDES está...,O cronograma oficial está no ANEXO III do edit...,O cronograma oficial está no **Anexo III — Cro...,O cronograma oficial do concurso BNDES está no...,O cronograma oficial do concurso do\nBanco Nac...,"De acordo com o edital, o cronograma oficial d..."
16,17,Dados sobre o Concurso,Existe possibilidade de impugnar o edital do c...,"Com base no edital do BNDES, **não há previsão...",Agora tenho a resposta completa.\n\n## Respost...,"Com base nas buscas realizadas, o edital do BN...","Com base no que apurei, aqui está a resposta:\...",Com base na análise do edital do concurso BNDE...,O edital do concurso BNDES não menciona explic...,"Pelo que localizei, o edital do BNDES prevê re...","Sim, mas o edital só prevê **recursos/revisões...",Hoje é 30/04/2026. Pelo edital do BNDES 01/202...,O edital do concurso do\nBanco Nacional de Des...,O edital\nnão menciona explicitamente\num proc...
17,18,Dados sobre o Cargo,Qual é o cargo/ênfase/perfil de Ciência de Dad...,Perfeito! Encontrei as informações sobre o car...,"No concurso BNDES 01/2024, o perfil de Ciência...",Ótimo! Aqui está um resumo completo sobre o ca...,"No concurso BNDES (Edital 01/2024), o cargo é ...","Com base nos dados do edital, aqui está o resu...","No concurso do BNDES para o cargo de Analista,...","No concurso do BNDES, o cargo é **Analista**, ...","No concurso do BNDES, a área de Ciência de Dad...","No concurso do BNDES, o cargo é **Analista**, ...",No concurso do\nBanco Nacional de Desenvolvime...,"De acordo com o edital, seguem todas as inform..."
18,19,Dados sobre o Cargo,Quantas vagas existem para a área de Ciência d...,Perfeito! Encontrei a informação sobre as vaga...,Para a ênfase **Ciência de Dados** do cargo de...,Ótima pergunta! Aqui estão os dados completos ...,Ótimo! Aqui estão as informações completas sob...,Agora tenho a informação completa. Eis a respo...,No concurso do BNDES para a área de Ciência de...,"Para a ênfase de Ciência de Dados, são 20 vaga...","Para a ênfase de Ciência de Dados, o edital pr...","Para a ênfase **Ciência de Dados**, são **20 v...","Para a área/perfil de\nCiência de Dados, o con...","De acordo com o edital, as vagas para a ênfase..."
19,20,Dados sobre o Cargo,Quantas vagas imediatas existem para Ciência d...,Perfeito! Encontrei a informação.\n\n**Para Ci...,Encontrei a informação no Anexo I.\n\nPara a ê...,"Para a ênfase de **Ciência de Dados**, o edita...","De acordo com o **Anexo I** do edital, para a ...","Com base no **Anexo I** do edital, as vagas im...",No concurso do BNDES para o cargo de Analista ...,"Para Ciência de Dados, são 20 vagas imediatas ...","Para a ênfase de **Ciência de Dados**, o edita...","Para **Analista — Ciência de Dados**, há **20 ...",O concurso do\nBanco Nacional de Desenvolvimen...,"De acordo com o edital, as vagas imediatas par..."
20,21,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas P...,## Reserva de Vagas para PcD no BNDES\n\nO con...,## Reserva de vagas para PcD — BNDES (Edital 0...,Aqui está um resumo completo das regras de res...,A reserva de vagas para Pessoas com Deficiênci...,Com base no edital do concurso BNDES (01/2024)...,"No concurso do BNDES, 15% (quinze por cento) d...","No concurso do BNDES, a reserva para PcD é de ...","No BNDES, a reserva para PcD é de **15% das va...","No concurso BNDES, a reserva para PcD é de 15%...",O edital do concurso do\nBanco Nacional de Des...,"De acordo com o edital, as regras de reserva d..."
21,22,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas p...,Perfeito! Encontrei as informações sobre a res...,## Reserva de vagas para candidatos negros — B...,Aqui está um resumo completo das regras de res...,A reserva de vagas para candidatos negros no c...,Agora tenho a informação completa. Eis a respo...,"No concurso do BNDES, 30% (trinta por cento) d...",Existe reserva de 30% das vagas para candidato...,"No BNDES, a reserva para candidatos negros é d...","No concurso do BNDES, há reserva de 30% das va...",O concurso do\nBanco Nacional de Desenvolvimen...,"De acordo com o edital, as regras de reserva d..."
22,23,Dados sobre o Cargo,Qual a remuneração ou salário do cargo do conc...,A remuneração do cargo de **Analista** no conc...,## Remuneração — Cargo de Analista (BNDES 01/2...,Ótima pergunta! Aqui estão as informações sobr...,A remuneração para o cargo de **Analista** do ...,O cargo de **Analista** do concurso BNDES (edi...,A remuneração inicial para o cargo de Analista...,A remuneração inicial do cargo de Analista no ...,"Para o cargo de **Analista**, a **remuneração ...",O cargo é **Analista** e o **salário inicial**...,A remuneração inicial do cargo de\nAnalista\nn...,"De acordo com o edital, as informações sobre r..."
23,24,Dados sobre o Cargo,Qual é o regime de contratação ou vínculo do c...,O regime de contratação do concurso BNDES é **...,O regime de contratação no concurso do BNDES é...,O regime de contratação do concurso BNDES 01/2...,O regime de contratação do concurso do BNDES é...,O regime de contratação do concurso BNDES (edi...,O regime de contratação para o concurso do BND...,O vínculo é celetista.\n\nOs aprovados assinam...,O vínculo é celetista: os aprovados serão conv...,O vínculo é **celetista**: o candidato aprovad...,O regime de contratação do concurso do\nBanco ...,"De acordo com o edital, as informações sobre o..."
24,25,Dados sobre o Cargo,Qual é a jornada de trabalho do cargo no concu...,A **jornada de trabalho é de 35 (trinta e cinc...,A jornada de trabalho do cargo de Analista do ...,A jornada de trabalho para o cargo de **Analis...,A jornada de trabalho para o cargo de **Analis...,A jornada de trabalho para o cargo de **Analis...,A jornada de trabalho para o cargo de Analista...,A jornada de trabalho para o cargo de Analista...,"A jornada de trabalho do cargo de Analista, in...",A jornada de trabalho do cargo de **Analista**...,A jornada de trabalho do cargo de Analista no ...,"De acordo com o edital, a jornada de trabalho ..."
25,26,Dados sobre o Cargo,Qual escolaridade é exigida para concorrer à á...,Perfeito! Encontrei a informação. Para a ênfas...,Para a ênfase de **Ciência de Dados** no concu...,Encontrei a informação! Aqui está a resposta c...,A escolaridade exigida para concorrer à ênfase...,Agora tenho a informação completa. Eis a respo...,Para concorrer à área de Ciência de Dados no c...,"Para a ênfase de Ciência de Dados, o edital ex...","Para a área de **Ciência de Dados**, o edital ...","Para a ênfase **Ciência de Dados**, é exigido ...",Para concorrer ao perfil de\nCiência de Dados\...,"De acordo com o edital, o requisito de escolar..."
26,27,Dados sobre o Cargo,O concurso BNDES exige registro em conselho pr...,Perfeito! Encontrei a resposta. Vou verificar ...,Encontrei a resposta direta no item 2.1.8.1.\n...,Ótima notícia para você! A resposta é **não**....,"**Não, o concurso BNDES para Analista — Ciênci...",Agora tenho a informação completa. O requisito...,O edital do concurso do BNDES para o cargo de ...,"Não. Para a ênfase Ciência de Dados, o edital ...","Não encontrei, no edital do BNDES para Ciência...","Não. Para a ênfase **Ciência de Dados**, o edi...","Não. Para o perfil de\nCiência de Dados, o edi...","De acordo com o edital, a resposta é\nnão! A ê..."
27,28,Dados sobre o Cargo,"Quais requisitos gerais de idade, nacionalidad...","Com base no edital do BNDES, os requisitos ger...",## Requisitos gerais para investidura no cargo...,Aqui estão os **requisitos gerais** que todo c...,"Os requisitos gerais de idade, nacionalidade e...","Com base no Capítulo 4 do edital, os requisito...",Os requisitos gerais que os candidatos devem o...,Os requisitos gerais que o candidato deve obse...,Os requisitos gerais que o candidato deve obse...,"No concurso BNDES, o candidato deve observar e...",Para tomar posse no cargo do concurso do\nBanc...,"De acordo com o edital, os requisitos gerais q..."
28,29,Dados sobre o Cargo,O cargo de Ciência de Dados exige disponibilid...,"Sim, o cargo de Ciência de Dados **exige dispo...","Sim, o cargo de Analista — Ciência de Dados do...",**Sim!** O cargo de Analista com ênfase em **C...,"Sim, o edital é claro quanto a isso.\n\n**Sim,...","Sim, o cargo de **Analista – Ciência de Dados*...","Sim, o cargo de Analista na ênfase de Ciência ...",Sim. Para o cargo de Analista na ênfase de Ciê...,"Sim. Para a ênfase de Ciência de Dados, o edit...",Sim. O edital exige disponibilidade para reali...,Sim. O edital do concurso do\nBanco Nacional d...,"De acordo com o edital, a resposta é\nsim! O c..."
29,30,Dados sobre o Cargo,Quais são as atribuições gerais do cargo ligad...,Perfeito! Encontrei as atribuições gerais do c...,## Atribuições do cargo de Analista — Ênfase C...,Aqui está um resumo completo e preciso sobre a...,Aqui estão as informações completas sobre as a...,"Com base no edital, as atribuições gerais do c...",As atribuições gerais do cargo de Analista na ...,"Para a ênfase de Ciência de Dados, o edital tr...","No edital do BNDES, eu encontrei os **conteúdo...",As atribuições gerais do cargo de **Analista —...,As atribuições gerais do perfil de\nCiência de...,"De acordo com o edital, as atribuições gerais ..."
30,31,Dados sobre a Prova,O concurso BNDES contém provas objetivas?,"Sim, o concurso BNDES contém **provas objetiva...","Sim, o concurso do BNDES (Edital 01/2024) cont...",Sim! O concurso do BNDES (Edital 01/2024) **co...,"Sim, o concurso do BNDES (edital 01/2024) **co...","Sim, o concurso do BNDES (edital 01/2024) **co...","Sim, o concurso do BNDES contém provas objetiv...","Sim. Para o cargo de Analista, incluindo Ciênc...",Sim. O edital do BNDES prevê provas objetivas ...,Sim. O concurso BNDES contém **provas objetiva...,Sim. O concurso do\nBanco Nacional de Desenvol...,"De acordo com o edital, a resposta é\nsim! O c..."

In [3]:
from pathlib import Path
import pandas as pd

NB_DIR = Path('.').resolve()  # avaliacao_chats_comerciais/
DATA_DIR = NB_DIR / 'data'
DF_AVAL_PATH = NB_DIR.parent / 'avaliacao_llms' / 'df_avaliacoes.xlsx'
BATCHES_DIR = NB_DIR / 'batches'
BATCHES_DIR.mkdir(exist_ok=True)

def consolida(concurso: str, n_batches: int = 5) -> pd.DataFrame:
    EVAL_DIR = NB_DIR / 'batches_eval'
    partes = [pd.read_excel(EVAL_DIR / f'{concurso}_batch_{i+1:02d}_eval.xlsx')
              for i in range(n_batches)]
    final = pd.concat(partes, ignore_index=True)

    esperado = {'id', 'pergunta', 'modelo', 'resposta', 'score', 'justificativa'}
    faltando = esperado - set(final.columns)
    assert not faltando, f'colunas faltando: {faltando}'
    assert len(final) == 550, f'esperado 550 linhas, veio {len(final)}'
    assert final['score'].isin([0, 0.5, 1]).all(), 'scores fora do domínio'

    final.to_excel(NB_DIR / f'{concurso}_eval_final.xlsx', index=False)

    # placar rápido por modelo
    placar = (final.groupby('modelo')['score']
                   .agg(['mean', 'sum', 'count'])
                   .sort_values('mean', ascending=False))
    print(placar)
    return final

bndes_final = consolida('bndes')
bndes_final

                   mean   sum  count
modelo
gpt-5.5            0.94  47.0     50
gpt-5.4            0.92  46.0     50
gpt-5.4-mini       0.84  42.0     50
gpt-4o-mini        0.77  38.5     50
deepseek-v4-pro    0.77  38.5     50
claude-opus-4-7    0.77  38.5     50
claude-haiku-4-5   0.72  36.0     50
deepseek-v4-flash  0.69  34.5     50
chatgpt            0.66  33.0     50
claude-sonnet-4-6  0.66  33.0     50
claude_chat        0.49  24.5     50

,id,pergunta,modelo,resposta,score,justificativa
0,1,Qual o período de inscrição para o concurso BN...,claude-haiku-4-5,**Período de inscrição do BNDES (01/2024):**\n...,0.5,item 6.2.1 fixa inscrição de 10h de 26/07/2024...
1,1,Qual o período de inscrição para o concurso BN...,claude-opus-4-7,O período de inscrição para o concurso BNDES (...,0.5,item 6.2.1 fixa inscrição de 10h de 26/07/2024...
2,1,Qual o período de inscrição para o concurso BN...,claude-sonnet-4-6,Aqui estão as informações sobre o período de i...,0.5,item 6.2.1 fixa inscrição de 10h de 26/07/2024...
3,1,Qual o período de inscrição para o concurso BN...,deepseek-v4-flash,O período de inscrição para o concurso BNDES (...,0.5,item 6.2.1 fixa inscrição de 10h de 26/07/2024...
4,1,Qual o período de inscrição para o concurso BN...,deepseek-v4-pro,O período de inscrição para o concurso do BNDE...,0.5,item 6.2.1 fixa inscrição de 10h de 26/07/2024...
...,...,...,...,...,...,...
545,50,Quais cuidados o candidato deve ter com o cart...,gpt-5.4,Os principais cuidados com o Cartão-Resposta s...,1.0,itens 9.16 a 9.18.1 exigem caneta preta transp...
546,50,Quais cuidados o candidato deve ter com o cart...,gpt-5.4-mini,O candidato deve:\n\n- usar caneta esferográfi...,1.0,itens 9.16 a 9.18.1 exigem caneta preta transp...
547,50,Quais cuidados o candidato deve ter com o cart...,gpt-5.5,O candidato deve tomar estes cuidados com o Ca...,1.0,itens 9.16 a 9.18.1 exigem caneta preta transp...
548,50,Quais cuidados o candidato deve ter com o cart...,chatgpt,No concurso do\nBanco Nacional de Desenvolvime...,0.5,itens 9.16 a 9.18.1 tratam dos cuidados com ma...
549,50,Quais cuidados o candidato deve ter com o cart...,claude_chat,"De acordo com o edital, os cuidados que o cand...",0.0,item 9.17 exige assinar o Cartão-Resposta; res...

In [7]:
from pathlib import Path
import pandas as pd

NB_DIR = Path('.').resolve()  # avaliacao_chats_comerciais/
DATA_DIR = NB_DIR / 'data'
DF_AVAL_PATH = NB_DIR.parent / 'avaliacao_llms' / 'df_avaliacoes.xlsx'
BATCHES_DIR = NB_DIR / 'batches'
BATCHES_DIR.mkdir(exist_ok=True)

def prepara_batches(concurso: str, chats: dict, n_batches: int = 5):
    """
    concurso: 'bndes' | 'cvm' | 'petrobras'
    chats: {'chatgpt': Path, 'claude_chat': Path} com xlsx contendo colunas id, resposta
    """
    df = pd.read_excel(DF_AVAL_PATH)
    sub = df[df['edital'] == concurso][['id', 'categoria', 'pergunta', 'modelo', 'resposta']]

    wide = (sub.pivot_table(index=['id', 'categoria', 'pergunta'],
                            columns='modelo', values='resposta', aggfunc='first')
              .reset_index())
    wide.columns = list(wide.columns[:3]) + [f'resposta_{c}' for c in wide.columns[3:]]

    for nome, path in chats.items():
        c = pd.read_excel(path)[['id', 'resposta']].rename(columns={'resposta': f'resposta_{nome}'})
        wide = wide.merge(c, on='id', how='left')

    wide = wide.sort_values('id').reset_index(drop=True)
    assert len(wide) == 50, f'esperado 50 perguntas, veio {len(wide)}'

    size = len(wide) // n_batches
    for i in range(n_batches):
        ini, fim = i * size, (i + 1) * size if i < n_batches - 1 else len(wide)
        out = BATCHES_DIR / f'{concurso}_batch_{i+1:02d}.xlsx'
        wide.iloc[ini:fim].to_excel(out, index=False)
        print(f'{out.name}: perguntas {wide.iloc[ini].id}–{wide.iloc[fim-1].id}')
    return wide

prepara_batches('petrobras', {
    'chatgpt':     DATA_DIR / 'petro_std_chatgpt_qa.xlsx',
    'claude_chat': DATA_DIR / 'petro_std_claude_qa.xlsx',
})

petrobras_batch_01.xlsx: perguntas 1–10
petrobras_batch_02.xlsx: perguntas 11–20
petrobras_batch_03.xlsx: perguntas 21–30
petrobras_batch_04.xlsx: perguntas 31–40
petrobras_batch_05.xlsx: perguntas 41–50

,id,categoria,pergunta,resposta_claude-haiku-4-5,resposta_claude-opus-4-7,resposta_claude-sonnet-4-6,resposta_deepseek-v4-flash,resposta_deepseek-v4-pro,resposta_gpt-4o-mini,resposta_gpt-5.4,resposta_gpt-5.4-mini,resposta_gpt-5.5,resposta_chatgpt,resposta_claude_chat
0,1,Dados sobre as inscrições,Qual o período de inscrição para o concurso PE...,"Com base no edital, o **período de inscrição f...",**Período de inscrição:** de **17/12/2021 a 05...,Aqui estão as informações sobre o período de i...,O período de inscrição para o concurso da **Pe...,O período de inscrição para o concurso da Petr...,O período de inscrição para o concurso da Petr...,O período de inscrição foi de 17/12/2021 a 05/...,Hoje é 29/04/2026. O edital informa que a insc...,Hoje é 30/04/2026. A inscrição para o concurso...,O período de inscrição para o Processo Seletiv...,De acordo com o Anexo IV (Cronograma) do edita...
1,2,Dados sobre as inscrições,Qual o valor da taxa de inscrição do concurso ...,A **taxa de inscrição do concurso Petrobras é ...,A taxa de inscrição do concurso da Petrobras (...,O valor da taxa de inscrição do concurso da Pe...,A taxa de inscrição do concurso **Petrobras — ...,A taxa de inscrição do concurso da Petrobras (...,O valor da taxa de inscrição para o concurso d...,"A taxa de inscrição é de R$ 79,83.\n\nref: edi...","A taxa de inscrição é de **R$ 79,83**.\n\nref:...",A taxa de inscrição do concurso Petrobras é de...,O valor da taxa de inscrição do concurso PETRO...,"De acordo com o item\n5.1\ndo edital, o valor ..."
2,3,Dados sobre as inscrições,Em qual site o candidato deve fazer a inscriçã...,O candidato deve fazer a inscrição no site do ...,A inscrição deve ser feita exclusivamente pela...,O candidato deve realizar a inscrição **exclus...,A inscrição para o concurso da Petrobras deve ...,A inscrição do concurso da Petrobras (Profissi...,O candidato deve realizar a inscrição para o c...,"A inscrição deve ser feita pela internet, no s...",A inscrição deve ser feita exclusivamente pela...,A inscrição deve ser feita somente pela intern...,A inscrição deveria ser realizada no site do C...,"De acordo com o item\n5.2\ndo edital, a inscri..."
3,4,Dados sobre as inscrições,Quais são as formas de pagamento da taxa de in...,"Com base no edital do concurso Petrobras, **a ...",## Forma de pagamento da taxa de inscrição — P...,"Com base no edital, a forma de pagamento da ta...",De acordo com o edital do concurso da Petrobra...,"Com base no edital, as formas de pagamento da ...",As formas de pagamento da taxa de inscrição do...,A taxa de inscrição deve ser paga por meio de ...,A taxa de inscrição deve ser paga por **boleto...,A taxa de inscrição deve ser paga **por meio d...,A taxa de inscrição deveria ser paga por meio ...,"De acordo com o item\n5.2.4\ndo edital, o paga..."
4,5,Dados sobre as inscrições,Qual é o prazo-limite de pagamento da inscriçã...,"Com base no edital da Petrobras, o **prazo-lim...",O prazo-limite de pagamento da taxa de inscriç...,A data-limite para pagamento da taxa de inscri...,De acordo com o **Anexo IV - Cronograma** do e...,O prazo-limite de pagamento da taxa de inscriç...,O prazo-limite para o pagamento da taxa de ins...,O prazo-limite para pagamento da inscrição foi...,O prazo-limite para pagamento da inscrição foi...,Hoje é 30/04/2026. A data limite para pagament...,O prazo-limite para pagamento da taxa de inscr...,De acordo com o\nAnexo IV (Cronograma)\ndo edi...
5,6,Dados sobre as inscrições,Quem pode pedir isenção da taxa de inscrição d...,"Com base no edital da Petrobras, **quem pode p...",## Quem pode pedir isenção da taxa de inscriçã...,Ótima pergunta! Veja abaixo quem pode solicita...,Aqui estão as informações completas sobre quem...,"Com base no edital, aqui está a resposta:\n\n-...",A isenção da taxa de inscrição do concurso da ...,Pode pedir isenção total da taxa apenas o(a) c...,Podem pedir isenção total da taxa de inscrição...,Podem pedir isenção total da taxa de inscrição...,Podiam solicitar isenção da taxa de inscrição ...,"De acordo com o item\n5.4.8.1\ndo edital, teri..."
6,7,Dados sobre as inscrições,Qual é o período para solicitar isenção da tax...,"Com base no edital, o **período para solicitar...",O período para solicitar a **isenção da taxa d...,Aqui estão as informações sobre a isenção da t...,O período para solicitar a **isenção da taxa d...,O período para solicitação de isenção da taxa ...,O período para solicitar a isenção da taxa de ...,O período para solicitar a isenção da taxa de ...,O período para solicitar a isenção da taxa de ...,Hoje é 30/04/2026. O período para solicitar a ...,O período para solicitar a isenção da taxa de ...,De acordo com o\nAnexo IV (Cronograma)\ndo edi...
7,8,Dados sobre as inscrições,A inscrição do concurso PETROBRAS é feita some...,"Sim, a inscrição do concurso Petrobras é feita...",Sim. A inscrição no processo seletivo público ...,Sim! A inscrição no concurso da Petrobras é re...,"Sim, a inscrição para este concurso da Petrobr...","Sim, a inscrição no concurso da Petrobras (edi...","Sim, a inscrição para o concurso da Petrobras ...",Sim. A inscrição é admitida somente via intern...,Sim. O edital informa que a inscrição será adm...,Sim. O edital diz que a inscrição será admitid...,"Sim. De acordo com o edital, a inscrição do co...","Sim! De acordo com o item\n5.2\ndo edital:\n""S..."
8,9,Dados sobre as inscrições,O candidato pode fazer mais de uma inscrição n...,"Sim, o candidato **pode fazer mais de uma insc...","Sim, o candidato pode fazer mais de uma inscri...",Ótima pergunta! Com base no edital da Petrobra...,"Sim, o candidato **pode se inscrever para mais...","Sim, o candidato **pode se inscrever para mais...",O candidato pode se inscrever para mais de uma...,Sim. O edital permite que o(a) candidato(a) se...,Sim. O edital permite que o candidato se inscr...,Sim. O edital permite que o(a) candidato(a) se...,Sim. O edital permite que o candidato faça ins...,"De acordo com o item\n5.4.1.2\ndo edital, sim!..."
9,10,Dados sobre as inscrições,O candidato precisa guardar o comprovante de i...,"Sim, o candidato **deve guardar o comprovante ...","Sim, precisa guardar.\n\nDe acordo com o edita...",**Sim!** O candidato deve guardar o comprovant...,"Sim, o candidato precisa guardar o comprovante...","Sim, o candidato **precisa guardar** tanto o c...","Sim, o candidato deve guardar o comprovante de...",Sim. O edital diz expressamente que o comprova...,Sim. O edital determina que o candidato deve m...,Sim. O edital determina que o candidato deve m...,Sim. O edital determina que o candidato deve m...,"Sim! De acordo com o edital, o candidato dever..."
10,11,Dados sobre o Concurso,Qual entidade está responsável pela organizaçã...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A organização e a execução do concurso são de ...,A entidade responsável pela execução do concur...,A entidade responsável pela organização e exec...,"De acordo com o item\n1.1\ndo edital, a entida..."
11,12,Dados sobre o Concurso,Quantas fases ou etapas tem o concurso PETROBRAS?,"Com base no edital, o concurso Petrobras tem *...",O processo seletivo da Petrobras tem o seguint...,O concurso da Petrobras (Nível Superior Júnior...,O concurso da **Petrobras** (Profissional de N...,Agora tenho uma visão completa. Vou organizar ...,O concurso da Petrobras é composto por duas fa...,"O edital trata o concurso, em regra, com 1 fas...",O concurso PETROBRAS tem 2 fases/etapas princi...,O concurso da Petrobras tem **2 fases principa...,O concurso PETROBRAS possui:\n2 fases\npara a ...,"De acordo com o item\n1.2\ndo edital, o concur..."
12,13,Dados sobre o Concurso,Qual é o prazo de validade do concurso PETROBRAS?,"Com base no edital, o **prazo de validade do c...",O prazo de validade do processo seletivo públi...,Aqui estão as informações sobre o prazo de val...,"De acordo com o item **11.5** do edital, o pra...",O prazo de validade do concurso da Petrobras (...,O prazo de validade do concurso da Petrobras é...,"O prazo de validade do concurso é de 12 meses,...",O prazo de validade deste processo seletivo pú...,"Hoje é 30/04/2026. Pelo edital, o prazo de val...",O prazo de validade do concurso PETROBRAS é de...,"De acordo com o item\n11.5\ndo edital, o prazo..."
13,14,Dados sobre o Concurso,Em quais cidades ou locais as provas do concur...,"Com base no edital, as provas do concurso Petr...",As provas objetivas do concurso Petrobras serã...,"Com base no edital, aqui estão as informações ...","De acordo com o edital, as provas do concurso ...","Com base no edital, as provas objetivas do con...",As provas do concurso da Petrobras serão reali...,As provas serão realizadas nas 26 capitais das...,As provas serão realizadas nas cidades indicad...,"As provas objetivas, a avaliação da equipe mul...",As provas do concurso PETROBRAS seriam realiza...,"De acordo com o item\n1.3\ndo edital, as prova..."
14,15,Dados sobre o Concurso,Qual horário de referência deve ser considerad...,"Com base no edital, o **horário de referência ...",O horário de referência a ser considerado pelo...,Com base nas informações encontradas no edital...,O horário de referência a ser considerado pelo...,"Com base nos trechos encontrados no edital, o ...",O horário de referência que deve ser considera...,O edital remete os prazos e horários ao cronog...,O edital informa que o horário de referência é...,O candidato deve considerar o **horário oficia...,O horário de referência considerado no concurs...,"De acordo com o edital, o horário de referênci..."
15,16,Dados sobre o Concurso,Onde o candidato encontra o cronograma oficial...,O candidato encontra o **cronograma oficial do...,O cronograma oficial do concurso está no **Ane...,Ótima pergunta! Veja onde encontrar o cronogra...,O cronograma oficial do concurso PETROBRAS (Pr...,"Com base nas informações do edital, aqui está ...",O cronograma oficial do concurso da Petrobras ...,O cronograma oficial está no Anexo IV do edita...,O candidato encontra o cronograma oficial no *...,O cronograma oficial está no **Anexo IV – Cron...,O candidato encontra o cronograma oficial do c...,"De acordo com o edital, o cronograma oficial d..."
16,17,Dados sobre o Concurso,Existe possibilidade de impugnar o edital do c...,"Sim, existe possibilidade de impugnar o edital...",## Sobre impugnação do edital Petrobras\n\n**H...,Ótima pergunta! Com base nas informações do ed...,## Impugnação do Edital Petrobras\n\nO edital ...,"Com base na busca realizada, o edital da Petro...","Sim, é possível impugnar o edital do concurso ...","Pelo que consta no edital, eu não encontrei pr...","Sim, há possibilidade de impugnar/contestar po...","No edital consultado, **não encontrei uma regr...",O edital não apresenta uma previsão específica...,O edital do concurso da Petrobras\nnão mencion...
17,18,Dados sobre o Cargo,Qual é o cargo/ênfase/perfil de Ciência de Dad...,Perfeito! Encontrei as informações sobre o car...,## Cargo e Ênfase de Ciência de Dados — Petrob...,Aqui está um resumo completo do cargo/ênfase d...,Aqui estão as informações completas sobre a **...,"Com base no edital, aqui estão as informações ...",No concurso da Petrobras para a ênfase em Ciên...,"No edital, o cargo é **Profissional Petrobras ...","No concurso da Petrobras, o cargo é **Profissi...","No concurso da PETROBRAS, o perfil de Ciência ...","No concurso PETROBRAS/PSP RH 2021, a área de\n...","De acordo com o\nAnexo II\ndo edital, veja aba..."
18,19,Dados sobre o Cargo,Quantas vagas existem para a área de Ciência d...,Perfeito! Encontrei a informação sobre as vaga...,Para a **Ênfase 7 — Ciência de Dados** do conc...,"Com base no **Anexo I** do edital, aqui está o...","De acordo com o **Anexo I** do edital, para a ...","Com base no **Anexo I** do edital, a **Ênfase ...",No concurso da Petrobras para a ênfase em Ciên...,"Para a ênfase de **Ciência de Dados**, o edita...","Para a ênfase de Ciência de Dados, o edital pr...","Para a ênfase **Ciência de Dados**, são **33 v...","Para a área de\nCiência de Dados (Ênfase 7), o...","De acordo com o\nAnexo I\ndo edital, as vagas ..."
19,20,Dados sobre o Cargo,Quantas vagas imediatas existem para Ciência d...,"Com base no edital da Petrobras, para a **Ênfa...",Para a ênfase **Ciência de Dados (Ênfase 7)** ...,Para a ênfase de **Ciência de Dados (Ênfase 7)...,"De acordo com o **Anexo I** do edital, para a ...","Com base no **Anexo I** do edital, as vagas im...",No concurso da Petrobras para a ênfase em Ciên...,"Para a ênfase de **Ciência de Dados**, há **33...","Para a ênfase de **Ciência de Dados**, o edita...","Para a ênfase **Ciência de Dados**, há **33 va...","Para a área de\nCiência de Dados (Ênfase 7), o...","De acordo com o\nAnexo I\ndo edital, as vagas ..."
20,21,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas P...,Perfeito! Encontrei as informações sobre a res...,## Reserva de vagas para PcD — Petrobras (Edit...,Ótima pergunta! Aqui está um resumo completo d...,A reserva de vagas para Pessoas com Deficiênci...,Com base no edital do concurso da Petrobras (P...,"No concurso da Petrobras, 8% das vagas são res...",Há reserva de 8% das vagas para pessoas com de...,"No concurso PETROBRAS, a reserva para PcD é de...","No concurso da Petrobras, a reserva para PcD é...","No concurso PETROBRAS,\n8% das vagas\nde cada ...","De acordo com o item\n3.1.1\ndo edital, a regr..."
21,22,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas p...,Perfeito! Encontrei as informações sobre a res...,## Reserva de vagas para candidatos negros — P...,Aqui está um resumo completo das regras de **r...,A reserva de vagas para candidatos negros no c...,Com base no edital da Petrobras (Profissional ...,"No concurso da Petrobras, 20% das vagas são re...",Há reserva de 20% das vagas para candidatos ne...,O edital prevê reserva de 20% das vagas destin...,"No concurso Petrobras, há reserva de **20% das...","No concurso PETROBRAS,\n20% das vagas\nde cada...","De acordo com o item\n3.2.1\ndo edital, a regr..."
22,23,Dados sobre o Cargo,Qual a remuneração ou salário do cargo do conc...,A remuneração do cargo **Profissional Petrobra...,Para o cargo **Profissional Petrobras de Nível...,Ótima pergunta! Aqui estão os detalhes sobre a...,A remuneração para o cargo de **Profissional P...,"Com base no **Anexo II** do edital, a remunera...",A remuneração para o cargo de Profissional Pet...,Para o cargo de **Profissional Petrobras de Ní...,Para o cargo de **Profissional Petrobras de Ní...,Para o cargo de **Profissional Petrobras de Ní...,A remuneração mínima inicial dos cargos de nív...,"De acordo com o\nAnexo II\ndo edital, a remune..."
23,24,Dados sobre o Cargo,Qual é o regime de contratação ou vínculo do c...,O regime de contratação do concurso Petrobras ...,O regime de contratação do concurso da Petrobr...,O regime de contratação da Petrobras é o segui...,O regime de contratação do concurso da **Petro...,"Com base no edital, o regime de contratação do...",O regime de contratação para os candidatos apr...,O vínculo é celetista.\n\nOs candidatos convoc...,O vínculo é **celetista**: os(as) convocados(a...,O vínculo é **empregatício regido pela CLT**.\...,O regime de contratação do concurso PETROBRAS ...,"De acordo com o edital, o regime de contrataçã..."
24,25,Dados sobre o Cargo,Qual é a jornada de trabalho do cargo no concu...,O edital não especifica a jornada de trabalho ...,"Esgotei as seções relevantes (Anexo II, capítu...",Com base em todas as consultas realizadas ao e...,"Após consultar todo o edital, **não encontrei*...",Após consultar todas as seções relevantes do e...,A jornada de trabalho para o cargo de Profissi...,"O edital consultado não traz, neste trecho, um...",O edital que tenho acesso aqui informa a remun...,O edital **não informa a jornada de trabalho/c...,A jornada de trabalho prevista para os cargos ...,"Após verificar cuidadosamente o edital,\na jor..."
25,26,Dados sobre o Cargo,Qual escolaridade é exigida para concorrer à á...,Perfeito! Encontrei a informação sobre a escol...,Para concorrer à **Ênfase 7: Ciência de Dados*...,A resposta está claramente no edital! Veja aba...,A informação está clara no **Anexo II** do edi...,"Com base no edital, a escolaridade exigida par...",Para concorrer à área de Ciência de Dados no c...,"Para a ênfase de **Ciência de Dados**, a escol...","Para a ênfase em **Ciência de Dados**, o edita...",Para concorrer à **Ênfase 7: Ciência de Dados*...,Para concorrer à área de\nCiência de Dados (Ên...,"De acordo com o\nAnexo II\ndo edital, o requis..."
26,27,Dados sobre o Cargo,O concurso PETROBRAS exige registro em conselh...,Perfeito! Encontrei a informação. De acordo co...,"Encontrei a resposta direta no Anexo II, item ...",Ótima pergunta! A resposta é **não**. O edital...,Agora ficou claro. Vou consolidar a resposta.\...,Agora tenho uma resposta completa e fundamenta...,O edital do concurso da Petrobras não menciona...,"Não. Para a ênfase **Ciência de Dados**, o edi...","Para a ênfase de **Ciência de Dados**, **não h...","Não. Para a Ênfase 7: Ciência de Dados, o edit...",Não. Para a área de\nCiência de Dados (Ênfase ...,"De acordo com o\nAnexo II\ndo edital, para a\n..."
27,28,Dados sobre o Cargo,"Quais requisitos gerais de idade, nacionalidad...","Com base no edital, os requisitos gerais de el...",## Requisitos gerais para admissão na Petrobra...,Aqui estão os **requisitos gerais** que todo c...,"Ótimo, encontrei todos os requisitos no Capítu...","Com base no **Capítulo 4** do edital, os requi...",Os requisitos gerais que os candidatos devem o...,"Os requisitos gerais mencionados no edital, qu...","Os requisitos gerais do concurso Petrobras, ne...",O candidato deve observar estes requisitos ger...,Os requisitos gerais previstos no edital do co...,"De acordo com o\nitem 4\ndo edital, os requisi..."
28,29,Dados sobre o Cargo,O cargo de Ciência de Dados exige disponibilid...,"Baseado na leitura do Anexo II do edital, a sí...",Tenho informação suficiente para responder.\n\...,Tenho a resposta completa. Veja abaixo:\n\n---...,Agora tenho todas as informações necessárias p...,"Com base na análise completa do edital, posso ...",O edital não menciona explicitamente a exigênc...,"O edital, no trecho específico da ênfase **Ciê...",Não encontrei no edital uma exigência explícit...,"Não. Para a ênfase **Ciência de Dados**, o edi...","Não há, no edital da área de\nCiência de Dados...","Após verificar cuidadosamente o edital,\na exi..."
29,30,Dados sobre o Cargo,Quais são as atribuições gerais do cargo ligad...,## Atribuições Gerais do Cargo — Ênfase 7: Ciê...,## Atribuições gerais — Ênfase 7: Ciência de D...,Ótima pergunta! As atribuições do cargo de **C...,Aqui estão as atribuições gerais do cargo de *...,"Com base no edital, as atribuições gerais do c...",As atribuições gerais do cargo de Profissional...,"Para a ênfase de **Ciência de Dados**, as atri...","Para a ênfase em Ciência de Dados, as atribuiç...",Para a ênfase ligada à Ciência de Dados — **Pr...,As atribuições gerais da área de\nCiência de D...,"De acordo com o\nAnexo II, item 1.7\ndo edital..."
30,31,Dados sobre a Prova,O concurso PETROBRAS contém provas objetivas?,"Sim, o concurso Petrobras contém **provas obje...","Sim, o concurso da Petrobras (Profissional Pet...",Sim! O concurso da Petrobras **contém provas o...,"Sim, o concurso **Petrobras** (Profissional Pe...",Sim! O concurso da **Petrobras — Profissional ...,"Sim, o concurso da PETROBRAS contém provas obj...",Sim. O processo seletivo da Petrobras tem prov...,Sim. O edital prevê provas objetivas: P1 (Conh...,Sim. O concurso da Petrobras contém provas obj...,Sim. O concurso PETROBRAS possui provas objeti...,"De acordo com o edital,\nsim! O concurso Petro..."

In [ ]:
from pathlib import Path
import pandas as pd

NB_DIR = Path('.').resolve()  # avaliacao_chats_comerciais/
DATA_DIR = NB_DIR / 'data'
DF_AVAL_PATH = NB_DIR.parent / 'avaliacao_llms' / 'df_avaliacoes.xlsx'
BATCHES_DIR = NB_DIR / 'batches'
BATCHES_DIR.mkdir(exist_ok=True)

In [5]:
from pathlib import Path
import pandas as pd

NB_DIR = Path('.').resolve()  # avaliacao_chats_comerciais/
DATA_DIR = NB_DIR / 'data'
DF_AVAL_PATH = NB_DIR.parent / 'avaliacao_llms' / 'df_avaliacoes.xlsx'
BATCHES_DIR = NB_DIR / 'batches'
BATCHES_DIR.mkdir(exist_ok=True)

def prepara_batches(concurso: str, chats: dict, n_batches: int = 5):
    """
    concurso: 'bndes' | 'cvm' | 'petrobras'
    chats: {'chatgpt': Path, 'claude_chat': Path} com xlsx contendo colunas id, resposta
    """
    df = pd.read_excel(DF_AVAL_PATH)
    sub = df[df['edital'] == concurso][['id', 'categoria', 'pergunta', 'modelo', 'resposta']]

    wide = (sub.pivot_table(index=['id', 'categoria', 'pergunta'],
                            columns='modelo', values='resposta', aggfunc='first')
              .reset_index())
    wide.columns = list(wide.columns[:3]) + [f'resposta_{c}' for c in wide.columns[3:]]

    for nome, path in chats.items():
        c = pd.read_excel(path)[['id', 'resposta']].rename(columns={'resposta': f'resposta_{nome}'})
        wide = wide.merge(c, on='id', how='left')

    wide = wide.sort_values('id').reset_index(drop=True)
    assert len(wide) == 50, f'esperado 50 perguntas, veio {len(wide)}'

    size = len(wide) // n_batches
    for i in range(n_batches):
        ini, fim = i * size, (i + 1) * size if i < n_batches - 1 else len(wide)
        out = BATCHES_DIR / f'{concurso}_batch_{i+1:02d}.xlsx'
        wide.iloc[ini:fim].to_excel(out, index=False)
        print(f'{out.name}: perguntas {wide.iloc[ini].id}–{wide.iloc[fim-1].id}')
    return wide

prepara_batches('cvm', {
    'chatgpt':     DATA_DIR / 'cvm_std_chatgpt_qa.xlsx',
    'claude_chat': DATA_DIR / 'cvm_std_claude_qa.xlsx',
})

cvm_batch_01.xlsx: perguntas 1–10
cvm_batch_02.xlsx: perguntas 11–20
cvm_batch_03.xlsx: perguntas 21–30
cvm_batch_04.xlsx: perguntas 31–40
cvm_batch_05.xlsx: perguntas 41–50

,id,categoria,pergunta,resposta_claude-haiku-4-5,resposta_claude-opus-4-7,resposta_claude-sonnet-4-6,resposta_deepseek-v4-flash,resposta_deepseek-v4-pro,resposta_gpt-4o-mini,resposta_gpt-5.4,resposta_gpt-5.4-mini,resposta_gpt-5.5,resposta_chatgpt,resposta_claude_chat
0,1,Dados sobre as inscrições,Qual o período de inscrição para o concurso CVM?,O período de inscrição para o concurso CVM é:\...,O período de inscrição para o concurso da CVM ...,Aqui estão as informações sobre o período de i...,O período de inscrição para o concurso da CVM ...,**Período de inscrição do concurso CVM (Edital...,As inscrições para o concurso da CVM estarão a...,O período de inscrição foi de 30 de janeiro de...,As inscrições para o concurso CVM estiveram ab...,Hoje é 30/04/2026. A inscrição para o concurso...,O período de inscrição para o concurso da CVM ...,"De acordo com o edital, as inscrições estavam ..."
1,2,Dados sobre as inscrições,Qual o valor da taxa de inscrição do concurso ...,O valor da taxa de inscrição do concurso CVM é...,A taxa de inscrição do concurso da CVM (Edital...,O valor da taxa de inscrição do concurso públi...,O valor da taxa de inscrição para o concurso d...,O valor da taxa de inscrição para o concurso d...,O valor da taxa de inscrição para o concurso d...,"A taxa de inscrição é de R$ 145,00.\n\nref: ed...","A taxa de inscrição é de R$ 145,00.\n\nref: ed...",A taxa de inscrição do concurso da CVM é de R$...,O valor da taxa de inscrição do concurso da CV...,"De acordo com o edital, o valor da taxa de ins..."
2,3,Dados sobre as inscrições,Em qual site o candidato deve fazer a inscriçã...,O candidato deve fazer a inscrição no seguinte...,A inscrição deve ser feita pelo site da FGV (b...,O candidato deve realizar a inscrição pelo seg...,O candidato deve realizar a inscrição por meio...,A inscrição para o concurso da CVM deve ser fe...,O candidato deve realizar a inscrição para o c...,"A inscrição deve ser feita no site da FGV, no ...",O candidato deve fazer a inscrição pela intern...,O candidato deve fazer a inscrição pelo site d...,A inscrição do concurso da CVM deveria ser rea...,"De acordo com o edital, as inscrições deveriam..."
3,4,Dados sobre as inscrições,Quais são as formas de pagamento da taxa de in...,As formas de pagamento da taxa de inscrição do...,## Formas de pagamento da taxa de inscrição — ...,Ótima pergunta! Aqui estão as formas de pagame...,As formas de pagamento da taxa de inscrição do...,"Com base no edital, as formas de pagamento da ...",As formas de pagamento da taxa de inscrição do...,A taxa de inscrição deve ser paga por meio da ...,"A taxa de inscrição deve ser paga por GRU, que...",A taxa de inscrição deve ser paga por **GRU (G...,A taxa de inscrição do concurso CVM poderia se...,"De acordo com o edital, o pagamento da taxa de..."
4,5,Dados sobre as inscrições,Qual é o prazo-limite de pagamento da inscriçã...,"Com base no edital, o **prazo-limite para paga...",O prazo-limite para pagamento da taxa de inscr...,O prazo-limite para pagamento da taxa de inscr...,"De acordo com o edital, o prazo-limite para pa...","Com base no edital, o prazo-limite para pagame...",O prazo-limite para o pagamento da taxa de ins...,O prazo-limite para pagar a taxa de inscrição ...,Hoje é 29/04/2026. O prazo-limite de pagamento...,Hoje é 30/04/2026. O prazo-limite para pagamen...,O prazo-limite para pagamento da taxa de inscr...,"De acordo com o edital, o prazo-limite para pa..."
5,6,Dados sobre as inscrições,Quem pode pedir isenção da taxa de inscrição d...,"Segundo o edital da CVM, **apenas dois grupos ...",Podem solicitar isenção da taxa de inscrição d...,"Com base no edital, **duas categorias de candi...",Podem pedir **isenção da taxa de inscrição** o...,"Com base no edital, aqui está a resposta compl...",A isenção da taxa de inscrição do concurso da ...,"Podem pedir isenção da taxa de inscrição, segu...",Podem pedir isenção da taxa de inscrição:\n\n-...,Pode pedir isenção da taxa de inscrição quem s...,Poderiam solicitar isenção da taxa de inscriçã...,"De acordo com o edital, podiam solicitar isenç..."
6,7,Dados sobre as inscrições,Qual é o período para solicitar isenção da tax...,O período para solicitar isenção da taxa de in...,O período para solicitar isenção da taxa de in...,Aqui estão as informações sobre a isenção da t...,O período para solicitar a **isenção da taxa d...,O período para solicitar isenção da taxa de in...,O período para solicitar a isenção da taxa de ...,O período para solicitar isenção da taxa de in...,A solicitação de isenção da taxa de inscrição ...,O período para solicitar isenção da taxa de in...,O período para solicitar isenção da taxa de in...,"De acordo com o edital, o período para solicit..."
7,8,Dados sobre as inscrições,A inscrição do concurso CVM é feita somente pe...,"Sim, a inscrição é feita **principalmente pela...","Não exatamente. A regra geral é pela internet,...","Sim, a inscrição é feita **pela internet**, ma...","Sim, a inscrição para o concurso da CVM é feit...","Sim, a inscrição para o concurso da CVM é feit...","Sim, a inscrição para o concurso da CVM deve s...","Sim. Pelo edital, a inscrição é feita por meio...","Sim, a inscrição é feita **pela internet** no ...","Sim. Pelo edital, a inscrição deve ser feita p...",Não. Embora a inscrição seja realizada princip...,"De acordo com o edital, a inscrição era realiz..."
8,9,Dados sobre as inscrições,O candidato pode fazer mais de uma inscrição n...,"**Não, o candidato não pode fazer mais de uma ...","Com base no item 4.14 do edital, a resposta é:...","**Sim, é possível realizar mais de uma inscriç...","Sim, o candidato **pode fazer mais de uma insc...",A resposta está clara no item **4.14** do edit...,O candidato não pode fazer mais de uma inscriç...,Não. O edital até admite que o candidato faça ...,Sim. O edital permite identificar mais de uma ...,Sim. O candidato até pode realizar mais de uma...,"Sim, o candidato poderia realizar mais de uma ...","De acordo com o edital, tecnicamente o candida..."
9,10,Dados sobre as inscrições,O candidato precisa guardar o comprovante de i...,"Sim, o candidato **deve guardar o comprovante ...",Sim. O candidato deve guardar o comprovante de...,Sim! O edital é bem claro sobre isso. Veja o q...,"Sim, o candidato precisa guardar o comprovante...",A resposta está clara no item **4.16** do edit...,"Sim, o candidato deve guardar o comprovante de...",Sim. O edital diz expressamente que o comprova...,Sim. O edital determina que o candidato deve m...,Sim. O candidato deve manter em seu poder o co...,Sim. O edital determina que o candidato deve m...,"De acordo com o edital,\nsim, o candidato era ..."
10,11,Dados sobre o Concurso,Qual entidade está responsável pela organizaçã...,A **Fundação Getulio Vargas (FGV)** é a entida...,A organização e execução do concurso CVM 1/202...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A entidade responsável pela organização e exec...,A organização e execução do concurso estão a c...,A organização e execução do concurso ficam a c...,A entidade responsável pela execução do concur...,A entidade responsável pela organização e exec...,"De acordo com o edital, a entidade responsável..."
11,12,Dados sobre o Concurso,Quantas fases ou etapas tem o concurso CVM?,O concurso CVM tem **2 (duas) fases**:\n\n1. *...,"O concurso CVM tem **2 (duas) fases**, ambas d...",O concurso da CVM (Edital 1/2024) é estruturad...,O concurso da CVM (Edital nº 1/2024) possui **...,O concurso da CVM (Analista — Ciência de Dados...,O concurso da Comissão de Valores Mobiliários ...,O concurso da CVM tem 2 fases:\n\n1. Prova Obj...,O concurso da CVM será realizado em 2 fases:\n...,O concurso da CVM tem 2 fases:\n\n1. Prova Obj...,O concurso da CVM possui\n2 fases:\nProva Obje...,"De acordo com o edital, o concurso era realiza..."
12,13,Dados sobre o Concurso,Qual é o prazo de validade do concurso CVM?,O **prazo de validade do concurso CVM é de 24 ...,O prazo de validade do concurso da CVM é de **...,O prazo de validade do concurso CVM 1/2024 é d...,O prazo de validade do concurso da CVM é de **...,O prazo de validade do concurso da CVM está cl...,O prazo de validade do concurso da CVM é de 24...,O prazo de validade do concurso da CVM é de 24...,O prazo de validade do concurso CVM é de 24 me...,Hoje é 30/04/2026. O prazo de validade do conc...,O prazo de validade do concurso da CVM é de\n2...,"De acordo com o edital, o prazo de validade do..."
13,14,Dados sobre o Concurso,Em quais cidades ou locais as provas do concur...,"Com base no edital, as provas do concurso CVM ...",As provas do concurso CVM serão realizadas em ...,As provas do concurso CVM serão realizadas em ...,As provas do concurso CVM (edital 1/2024) serã...,"Com base no edital, as provas do concurso CVM ...",As provas do concurso da CVM (Comissão de Valo...,As provas serão realizadas em todas as capitai...,As provas da CVM serão realizadas em todas as ...,As provas do concurso CVM serão realizadas em ...,As provas do concurso da CVM seriam realizadas...,"De acordo com o edital, as provas seriam reali..."
14,15,Dados sobre o Concurso,Qual horário de referência deve ser considerad...,O horário de referência que deve ser considera...,O horário de referência do concurso da CVM é o...,O horário de referência a ser considerado pelo...,O horário de referência que deve ser considera...,O edital do concurso CVM é claro quanto ao hor...,O horário de referência que deve ser considera...,O edital determina que todos os horários devem...,O horário de referência é o horário oficial da...,O candidato deve considerar o horário oficial ...,Todos os horários previstos no edital do concu...,"De acordo com o edital, o horário de referênci..."
15,16,Dados sobre o Concurso,Onde o candidato encontra o cronograma oficial...,O candidato encontra o **cronograma oficial do...,O cronograma oficial e demais comunicados do c...,"Com base em todas as informações coletadas, po...",O cronograma oficial do concurso CVM está deta...,O edital não possui um anexo ou capítulo espec...,O cronograma oficial do concurso da CVM pode s...,"O candidato deve acompanhar os atos, editais e...",O candidato encontra o cronograma oficial no s...,O candidato deve acompanhar o cronograma e dem...,O cronograma oficial do concurso CVM pode ser ...,"De acordo com o edital, o candidato deveria ac..."
16,17,Dados sobre o Concurso,Existe possibilidade de impugnar o edital do c...,"Sim, existe possibilidade de impugnar o edital...","Sim, o edital prevê expressamente a possibilid...",Sim! O edital do concurso CVM prevê expressame...,"Sim, existe a possibilidade de **impugnar o ed...","Sim, **existe a possibilidade de impugnar o ed...","Sim, é possível impugnar o edital do concurso ...",O edital prevê recursos em situações específic...,Sim. O edital prevê impugnação por qualquer ci...,Sim. O edital prevê que **qualquer cidadão é p...,Sim. O edital prevê que qualquer cidadão poder...,"De acordo com o edital,\nsim, qualquer cidadão..."
17,18,Dados sobre o Cargo,Qual é o cargo/ênfase/perfil de Ciência de Dad...,## Cargo e Perfil de Ciência de Dados na CVM\n...,## Cargo de Ciência de Dados na CVM\n\n- **Car...,Ótima pergunta! Aqui está um resumo completo d...,Aqui estão as informações completas sobre o ca...,"Com base nas informações do edital, aqui está ...",O cargo de Analista CVM com ênfase em Ciência ...,O cargo/ênfase de Ciência de Dados é:\n\n- Car...,"No concurso da CVM, o cargo é **Analista CVM**...","No concurso da CVM, o perfil de Ciência de Dad...",O perfil de\nCiência de Dados\nno concurso CVM...,"De acordo com o edital, o cargo de Ciência de ..."
18,19,Dados sobre o Cargo,Quantas vagas existem para a área de Ciência d...,"Segundo o edital CVM 1/2024, existem **7 vagas...",Para o **Perfil 7 — Analista CVM – Ciência de ...,Para a área de **Ciência de Dados (Perfil 7)**...,Para a **especialidade Perfil 7 - Ciência de D...,Para a área de **Ciência de Dados** no concurs...,No concurso da CVM para o cargo de Analista na...,"Para a área de Ciência de Dados, são 7 vagas i...","Para a área de Ciência de Dados, o edital prev...",Para **Analista CVM — Perfil 7: Ciência de Dad...,Para a área de\nCiência de Dados (Perfil 7 – A...,"De acordo com o edital, as vagas para a área d..."
19,20,Dados sobre o Cargo,Quantas vagas imediatas existem para Ciência d...,"Com base no edital da CVM, existem **7 vagas i...",Para o cargo de **Analista CVM – Perfil 7 (Ciê...,Para a especialidade de **Ciência de Dados (Pe...,"De acordo com o edital, para o **Perfil 7 – Ci...",Para o cargo de **Analista CVM — Perfil 7 (Ciê...,No concurso da CVM para o cargo de Analista CV...,"Para Ciência de Dados, são 7 vagas imediatas n...",Para a especialidade **Analista CVM – Perfil 7...,Para **Analista CVM — Perfil 7: Ciência de Dad...,Existem\n7 vagas imediatas\npara o perfil\nAna...,"De acordo com o edital, as vagas imediatas par..."
20,21,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas P...,## Reserva de Vagas para PcD no Concurso CVM\n...,## Reserva de vagas para PcD no concurso CVM\n...,Aqui está um resumo completo das regras de res...,A reserva de vagas para Pessoas com Deficiênci...,"Com base no edital do concurso CVM (1/2024), a...","No concurso da CVM, 5% (cinco por cento) das v...","No concurso da CVM, a reserva para PcD é de 5%...","No concurso da CVM, a reserva para PcD é de **...","No concurso da CVM, a reserva para Pessoas com...",O edital do concurso CVM prevê a reserva de\n5...,"De acordo com o edital, a reserva de vagas par..."
21,22,Dados sobre o Cargo,Qual percentual ou regra de reserva de vagas p...,## Reserva de Vagas para Candidatos Negros na ...,## Reserva de vagas para candidatos negros — C...,Aqui está um resumo completo das regras de res...,A reserva de vagas para candidatos negros no c...,O concurso da CVM (Edital 1/2024) reserva **20...,"No concurso da CVM, 20% (vinte por cento) do t...","No concurso da CVM, há reserva de 20% das vaga...","No concurso da CVM, a reserva para candidatos ...","No concurso da CVM, há reserva de **20% das va...",O concurso CVM reserva\n20% das vagas\npara ca...,"De acordo com o edital, a reserva de vagas par..."
22,23,Dados sobre o Cargo,Qual a remuneração ou salário do cargo do conc...,A remuneração inicial do cargo de **Analista C...,A remuneração inicial do cargo de **Analista C...,A remuneração do cargo de **Analista CVM** (in...,A remuneração inicial para o cargo de **Analis...,A remuneração inicial para o cargo de **Analis...,A remuneração inicial para o cargo de Analista...,A remuneração inicial do cargo de Analista CVM...,A remuneração inicial para o cargo de Analista...,A remuneração inicial dos cargos de Analista C...,A remuneração inicial dos cargos do concurso C...,"De acordo com o edital, a remuneração dos carg..."
23,24,Dados sobre o Cargo,Qual é o regime de contratação ou vínculo do c...,"Com base no edital, o regime de contratação ou...",O concurso da CVM segue o **regime estatutário...,O regime de contratação do concurso CVM é o **...,O regime de contratação do concurso da CVM é o...,O regime de contratação do concurso da CVM é o...,O regime de contratação para os candidatos apr...,O edital indica que se trata de concurso públi...,O edital informa o concurso para provimento de...,O vínculo é **estatutário**: os candidatos nom...,Os candidatos nomeados no concurso CVM estarão...,"De acordo com o edital, o regime de contrataçã..."
24,25,Dados sobre o Cargo,Qual é a jornada de trabalho do cargo no concu...,"Baseado na minha busca no edital, **a jornada ...",O edital da CVM **não especifica explicitament...,O edital não menciona explicitamente a jornada...,O edital do concurso CVM não especifica direta...,"Após esgotar as buscas no edital, posso conclu...",O edital do concurso da CVM para o cargo de An...,O edital lido não informa expressamente a jorn...,"Não encontrei no edital, nas seções consultada...","Não encontrei, no edital da CVM, uma indicação...",O edital anexado não informa expressamente a j...,O edital\nnão menciona\nexpressamente a jornad...
25,26,Dados sobre o Cargo,Qual escolaridade é exigida para concorrer à á...,Perfeito! Encontrei a informação sobre a escol...,Para concorrer ao cargo de **Analista CVM – Pe...,A exigência de escolaridade para concorrer à á...,"De acordo com o item **3.3, alínea ""r""** do ed...",A informação sobre a escolaridade exigida está...,Para concorrer à área de Ciência de Dados no c...,"Para a área de Ciência de Dados (Perfil 7, car...","Para o perfil de Ciência de Dados, o edital nã...",Para concorrer à área de **Ciência de Dados** ...,Para concorrer ao cargo de\nAnalista CVM – Per...,"De acordo com o edital, a escolaridade exigida..."
26,27,Dados sobre o Cargo,O concurso CVM exige registro em conselho prof...,Baseado na leitura completa da seção de requis...,Não. Para o cargo de **Analista CVM – Ciência ...,**Não.** O edital da CVM (1/2024) **não exige ...,"**Não, o concurso CVM para Analista — Ciência ...","A resposta é clara e direta:\n\n**Não, o concu...",O edital do concurso da CVM para o cargo de An...,"Não. Para Analista CVM – Ciência de Dados, o e...",Não. Para o Perfil 7 — Analista CVM — Ciência ...,Não. Para **Analista CVM – Perfil 7: Ciência d...,Não.\nPara o cargo de\nAnalista CVM – Perfil 7...,"De acordo com o edital,\nnão\nera exigido regi..."
27,28,Dados sobre o Cargo,"Quais requisitos gerais de idade, nacionalidad...","Com base no edital CVM 1/2024, os requisitos g...",## Requisitos gerais para investidura no cargo...,Aqui estão os **requisitos gerais** que todo c...,Os requisitos gerais que o candidato deve aten...,"Com base no edital, os requisitos gerais que o...",Os requisitos gerais que o candidato deve obse...,Os requisitos gerais são os seguintes:\n\n- te...,"O edital exige, para investidura no cargo, que...","O candidato deve observar, entre outros requis...",Os requisitos gerais previstos no edital do co...,"De acordo com o edital, os requisitos gerais q..."
28,29,Dados sobre o Cargo,O cargo de Ciência de Dados exige disponibilid...,"Com base na consulta ao edital, **não há exigê...",Não há menção explícita à exigência de disponi...,"Com base nas informações do edital, **não há n...",Não encontrei no edital nenhuma exigência espe...,"Após realizar buscas exaustivas no edital, pos...",O edital do concurso da CVM para o cargo de An...,"O edital não traz, pelo que encontrei, uma exi...","O edital não traz, para o cargo de Analista CV...",Não há no edital uma exigência expressa de “di...,"Não. O edital do concurso CVM não prevê, para ...",O edital\nnão menciona\nexpressamente exigênci...
29,30,Dados sobre o Cargo,Quais são as atribuições gerais do cargo ligad...,"Com base no edital, as **atribuições gerais do...",## Atribuições do cargo de Analista da CVM (Pe...,Aqui estão as **atribuições gerais do cargo de...,As atribuições do cargo de **Analista CVM** (q...,"Com base no edital, as atribuições gerais do c...",As atribuições gerais do cargo de Analista da ...,Para o cargo de Analista CVM ligado à área de ...,As atribuições gerais do cargo de Analista da ...,As atribuições gerais do cargo de **Analista d...,As atribuições gerais do cargo de\nAnalista da...,"De acordo com o edital, as atribuições do carg..."
30,31,Dados sobre a Prova,O concurso CVM contém provas objetivas?,"Sim, o concurso CVM contém **provas objetivas*...","Sim, o concurso da CVM (Edital nº 1/2024) **co...",Sim! O concurso CVM 1/2024 para Analista – Ciê...,"Sim, o concurso CVM contém **provas objetivas*...","Sim, o concurso da CVM (edital 1/2024) **conté...","Sim, o concurso da CVM contém provas objetivas...","Sim. O concurso da CVM prevê Prova Objetiva, a...",Sim. O concurso da CVM contém prova objetiva: ...,"Sim. O concurso CVM tem **Prova Objetiva**, de...","Sim. O concurso CVM possui\nProva Objetiva, co...","De acordo com o edital,\nsim, o concurso CVM c..."

In [2]:
(NB_DIR / 'batches_eval').mkdir(exist_ok=True)

In [ ]:
def valida_batch(concurso: str, n: int):
    path = NB_DIR / 'batches_eval' / f'{concurso}_batch_{n:02d}_eval.xlsx'
    df = pd.read_excel(path)

    esperado = ['id', 'pergunta', 'modelo', 'resposta', 'score', 'justificativa']
    print(f'arquivo: {path.name}')
    print(f'shape:   {df.shape}  (esperado: 110, 6)')
    print(f'colunas: {list(df.columns)}')

    problemas = []
    if list(df.columns) != esperado:
        problemas.append(f'colunas fora de ordem/nome: {list(df.columns)}')
    if len(df) != 110:
        problemas.append(f'linhas != 110: {len(df)}')

    # score: aceita "1", "1.0", 1, 1.0 — mas normaliza pra float
    df['score'] = pd.to_numeric(df['score'].astype(str).str.replace(',', '.'), errors='coerce')
    fora = df[~df['score'].isin([0, 0.5, 1])]
    if len(fora):
        problemas.append(f'{len(fora)} scores fora de {{0, 0.5, 1}}')

    # cada pergunta deve ter exatamente 11 modelos
    cont = df.groupby('id')['modelo'].nunique()
    if not (cont == 11).all():
        problemas.append(f'perguntas com !=11 modelos: {cont[cont!=11].to_dict()}')

    # 10 perguntas distintas no batch
    if df['id'].nunique() != 10:
        problemas.append(f'ids distintos != 10: {df["id"].nunique()}')

    # justificativa nunca vazia
    vazias = df['justificativa'].isna().sum() + (df['justificativa'].astype(str).str.strip() == '').sum()
    if vazias:
        problemas.append(f'{vazias} justificativas vazias')

    # nomes de modelo consistentes entre batches: confere com o batch de entrada
    entrada = pd.read_excel(NB_DIR / 'batches' / f'{concurso}_batch_{n:02d}.xlsx')
    modelos_esperados = {c.replace('resposta_', '') for c in entrada.columns if c.startswith('resposta_')}
    modelos_vistos = set(df['modelo'].unique())
    if modelos_esperados != modelos_vistos:
        problemas.append(f'faltando: {modelos_esperados - modelos_vistos} | sobrando: {modelos_vistos - modelos_esperados}')

    if problemas:
        print('PROBLEMAS:')
        for p in problemas: print(f'  - {p}')
    else:
        print('OK')
        print('\ndistribuição de scores:')
        print(df['score'].value_counts().sort_index())
        print('\nmédia por modelo neste batch:')
        print(df.groupby('modelo')['score'].mean().sort_values(ascending=False).round(2))

    return df

# uso:
df2 = valida_batch('bndes', 2)

arquivo: bndes_batch_02_eval.xlsx
shape:   (110, 6)  (esperado: 110, 6)
colunas: ['id', 'pergunta', 'modelo', 'resposta', 'score', 'justificativa']
OK

distribuição de scores:
score
0.0     1
0.5    45
1.0    64
Name: count, dtype: int64

média por modelo neste batch:
modelo
gpt-5.4-mini         0.95
gpt-5.5              0.95
gpt-5.4              0.90
claude-opus-4-7      0.85
deepseek-v4-pro      0.80
claude-sonnet-4-6    0.75
chatgpt              0.75
gpt-4o-mini          0.75
deepseek-v4-flash    0.75
claude-haiku-4-5     0.70
claude_chat          0.50
Name: score, dtype: float64

In [6]:
def valida_batch(concurso: str, n: int):
    path = NB_DIR / 'batches_eval' / f'{concurso}_batch_{n:02d}_eval.xlsx'
    df = pd.read_excel(path)

    esperado = ['id', 'pergunta', 'modelo', 'resposta', 'score', 'justificativa']
    print(f'arquivo: {path.name}')
    print(f'shape:   {df.shape}  (esperado: 110, 6)')
    print(f'colunas: {list(df.columns)}')

    problemas = []
    if list(df.columns) != esperado:
        problemas.append(f'colunas fora de ordem/nome: {list(df.columns)}')
    if len(df) != 110:
        problemas.append(f'linhas != 110: {len(df)}')

    # score: aceita "1", "1.0", 1, 1.0 — mas normaliza pra float
    df['score'] = pd.to_numeric(df['score'].astype(str).str.replace(',', '.'), errors='coerce')
    fora = df[~df['score'].isin([0, 0.5, 1])]
    if len(fora):
        problemas.append(f'{len(fora)} scores fora de {{0, 0.5, 1}}')

    # cada pergunta deve ter exatamente 11 modelos
    cont = df.groupby('id')['modelo'].nunique()
    if not (cont == 11).all():
        problemas.append(f'perguntas com !=11 modelos: {cont[cont!=11].to_dict()}')

    # 10 perguntas distintas no batch
    if df['id'].nunique() != 10:
        problemas.append(f'ids distintos != 10: {df["id"].nunique()}')

    # justificativa nunca vazia
    vazias = df['justificativa'].isna().sum() + (df['justificativa'].astype(str).str.strip() == '').sum()
    if vazias:
        problemas.append(f'{vazias} justificativas vazias')

    # nomes de modelo consistentes entre batches: confere com o batch de entrada
    entrada = pd.read_excel(NB_DIR / 'batches' / f'{concurso}_batch_{n:02d}.xlsx')
    modelos_esperados = {c.replace('resposta_', '') for c in entrada.columns if c.startswith('resposta_')}
    modelos_vistos = set(df['modelo'].unique())
    if modelos_esperados != modelos_vistos:
        problemas.append(f'faltando: {modelos_esperados - modelos_vistos} | sobrando: {modelos_vistos - modelos_esperados}')

    if problemas:
        print('PROBLEMAS:')
        for p in problemas: print(f'  - {p}')
    else:
        print('OK')
        print('\ndistribuição de scores:')
        print(df['score'].value_counts().sort_index())
        print('\nmédia por modelo neste batch:')
        print(df.groupby('modelo')['score'].mean().sort_values(ascending=False).round(2))

    return df

# uso:
df2 = valida_batch('bndes', 4)

arquivo: bndes_batch_04_eval.xlsx
shape:   (110, 6)  (esperado: 110, 6)
colunas: ['id', 'pergunta', 'modelo', 'resposta', 'score', 'justificativa']
OK

distribuição de scores:
score
0.0     4
0.5    53
1.0    53
Name: count, dtype: int64

média por modelo neste batch:
modelo
gpt-5.5              1.00
gpt-5.4              0.95
gpt-5.4-mini         0.85
gpt-4o-mini          0.80
deepseek-v4-pro      0.75
claude-haiku-4-5     0.75
claude-opus-4-7      0.70
chatgpt              0.60
deepseek-v4-flash    0.55
claude-sonnet-4-6    0.50
claude_chat          0.50
Name: score, dtype: float64