In [5]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/bndes_std_claude.html")

OUT_XLSX = HTML_PATH.with_name("bndes_std_claude_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("bndes_std_claude_qa.csv")

def clean_text(el):
    txt = el.get_text("\n", strip=True)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for el in soup.find_all(True):
    if el.get("data-testid") == "user-message":
        messages.append({
            "autor": "user",
            "texto": clean_text(el),
            "html": str(el),
        })

    elif el.get("data-is-streaming") == "false":
        resp = el.select_one(".font-claude-response")
        if resp:
            messages.append({
                "autor": "assistant",
                "texto": clean_text(resp),
                "html": str(resp),
            })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
            "pergunta_html": pergunta["html"],
            "resposta_html": resposta["html"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# manter só as colunas desejadas
df = df[["pergunta", "resposta"]]

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 até N
df.insert(0, "id", range(1, len(df) + 1))

# opcional: garantir que ficou de 1 a 50
print(df["id"].min(), df["id"].max(), len(df))

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

1 50 50
50 pares pergunta/resposta extraídos
data/bndes_std_claude_qa.xlsx
data/bndes_std_claude_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso BN...,O período de inscrições foi de\n26 de julho a ...

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,"De acordo com o edital, os cuidados que o cand..."

In [ ]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/bndes_std_claude.html")

OUT_XLSX = HTML_PATH.with_name("bndes_std_claude_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("bndes_std_claude_qa.csv")

def clean_text(el):
    txt = el.get_text("\n", strip=True)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for el in soup.find_all(True):
    if el.get("data-testid") == "user-message":
        messages.append({
            "autor": "user",
            "texto": clean_text(el),
            "html": str(el),
        })

    elif el.get("data-is-streaming") == "false":
        resp = el.select_one(".font-claude-response")
        if resp:
            messages.append({
                "autor": "assistant",
                "texto": clean_text(resp),
                "html": str(resp),
            })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
            "pergunta_html": pergunta["html"],
            "resposta_html": resposta["html"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# manter só as colunas desejadas
df = df[["pergunta", "resposta"]]

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 até N
df.insert(0, "id", range(1, len(df) + 1))

# opcional: garantir que ficou de 1 a 50
print(df["id"].min(), df["id"].max(), len(df))

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

In [8]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/petro_std_claude.html")

OUT_XLSX = HTML_PATH.with_name("petro_std_claude_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("petro_std_claude_qa.csv")

def clean_text(el):
    txt = el.get_text("\n", strip=True)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for el in soup.find_all(True):
    if el.get("data-testid") == "user-message":
        messages.append({
            "autor": "user",
            "texto": clean_text(el),
            "html": str(el),
        })

    elif el.get("data-is-streaming") == "false":
        resp = el.select_one(".font-claude-response")
        if resp:
            messages.append({
                "autor": "assistant",
                "texto": clean_text(resp),
                "html": str(resp),
            })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
            "pergunta_html": pergunta["html"],
            "resposta_html": resposta["html"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# manter só as colunas desejadas
df = df[["pergunta", "resposta"]]

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 até N
df.insert(0, "id", range(1, len(df) + 1))

# opcional: garantir que ficou de 1 a 50
print(df["id"].min(), df["id"].max(), len(df))

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

1 50 50
50 pares pergunta/resposta extraídos
data/petro_std_claude_qa.xlsx
data/petro_std_claude_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso PE...,De acordo com o Anexo IV (Cronograma) do edita...

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,"De acordo com o edital, veja todos os cuidados..."

In [1]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/bndes_std_chatgpt.html")

OUT_XLSX = HTML_PATH.with_name("bndes_std_chatgpt_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("bndes_std_chatgpt_qa.csv")

def clean_text(el):
    ignore = {
        "Você disse:",
        "O ChatGPT disse:",
        "Mostrar mais",
        "Mostrar menos",
        "Copiar",
        "Editar",
        "PDF",
    }

    lines = []
    for line in el.get_text("\n", strip=True).splitlines():
        line = line.strip()
        if line and line not in ignore:
            lines.append(line)

    txt = "\n".join(lines)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for msg in soup.select("[data-message-author-role]"):
    role = msg.get("data-message-author-role")

    if role in {"user", "assistant"}:
        messages.append({
            "autor": role,
            "texto": clean_text(msg),
        })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 a 50
df["id"] = range(1, len(df) + 1)

df = df[["id", "pergunta", "resposta"]]

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

50 pares pergunta/resposta extraídos
data/bndes_std_chatgpt_qa.xlsx
data/bndes_std_chatgpt_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso BN...,O período de inscrição para a Seleção Pública ...

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,No concurso do\nBanco Nacional de Desenvolvime...

In [6]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/petro_std_chatgpt.html")

OUT_XLSX = HTML_PATH.with_name("petro_std_chatgpt_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("petro_std_chatgpt_qa.csv")

def clean_text(el):
    ignore = {
        "Você disse:",
        "O ChatGPT disse:",
        "Mostrar mais",
        "Mostrar menos",
        "Copiar",
        "Editar",
        "PDF",
    }

    lines = []
    for line in el.get_text("\n", strip=True).splitlines():
        line = line.strip()
        if line and line not in ignore:
            lines.append(line)

    txt = "\n".join(lines)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for msg in soup.select("[data-message-author-role]"):
    role = msg.get("data-message-author-role")

    if role in {"user", "assistant"}:
        messages.append({
            "autor": role,
            "texto": clean_text(msg),
        })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 a 50
df["id"] = range(1, len(df) + 1)

df = df[["id", "pergunta", "resposta"]]

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

50 pares pergunta/resposta extraídos
data/petro_std_chatgpt_qa.xlsx
data/petro_std_chatgpt_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso PE...,O período de inscrição para o Processo Seletiv...

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,"No concurso PETROBRAS, o candidato deve tomar ..."

In [7]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/cvm_std_chatgpt.html")

OUT_XLSX = HTML_PATH.with_name("cvm_std_chatgpt_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("cvm_std_chatgpt_qa.csv")

def clean_text(el):
    ignore = {
        "Você disse:",
        "O ChatGPT disse:",
        "Mostrar mais",
        "Mostrar menos",
        "Copiar",
        "Editar",
        "PDF",
    }

    lines = []
    for line in el.get_text("\n", strip=True).splitlines():
        line = line.strip()
        if line and line not in ignore:
            lines.append(line)

    txt = "\n".join(lines)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for msg in soup.select("[data-message-author-role]"):
    role = msg.get("data-message-author-role")

    if role in {"user", "assistant"}:
        messages.append({
            "autor": role,
            "texto": clean_text(msg),
        })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 a 50
df["id"] = range(1, len(df) + 1)

df = df[["id", "pergunta", "resposta"]]

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

50 pares pergunta/resposta extraídos
data/cvm_std_chatgpt_qa.xlsx
data/cvm_std_chatgpt_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso CVM?,O período de inscrição para o concurso da CVM ...

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,O candidato deve tomar diversos cuidados com o...

In [2]:
from pathlib import Path
import re
import pandas as pd
from bs4 import BeautifulSoup

HTML_PATH = Path("data/cvm_std_claude.html")

OUT_XLSX = HTML_PATH.with_name("cvm_std_claude_qa.xlsx")
OUT_CSV = HTML_PATH.with_name("cvm_std_claude_qa.csv")

def clean_text(el):
    txt = el.get_text("\n", strip=True)
    txt = re.sub(r"\n{3,}", "\n\n", txt)
    txt = re.sub(r"\n([,.;:!?])", r"\1", txt)
    return txt.strip()

html = HTML_PATH.read_text(encoding="utf-8", errors="ignore")
soup = BeautifulSoup(html, "html.parser")

messages = []

for el in soup.find_all(True):
    if el.get("data-testid") == "user-message":
        messages.append({
            "autor": "user",
            "texto": clean_text(el),
            "html": str(el),
        })

    elif el.get("data-is-streaming") == "false":
        resp = el.select_one(".font-claude-response")
        if resp:
            messages.append({
                "autor": "assistant",
                "texto": clean_text(resp),
                "html": str(resp),
            })

rows = []
i = 0
qid = 1

while i < len(messages):
    if messages[i]["autor"] == "user":
        pergunta = messages[i]
        resposta = None

        if i + 1 < len(messages) and messages[i + 1]["autor"] == "assistant":
            resposta = messages[i + 1]
            i += 2
        else:
            i += 1

        rows.append({
            "id": qid,
            "pergunta": pergunta["texto"],
            "resposta": resposta["texto"] if resposta else "",
            "pergunta_html": pergunta["html"],
            "resposta_html": resposta["html"] if resposta else "",
        })
        qid += 1
    else:
        i += 1

df = pd.DataFrame(rows)

# manter só as colunas desejadas
df = df[["pergunta", "resposta"]]

# ignorar primeira linha
df = df.iloc[1:].reset_index(drop=True)

# recriar id de 1 até N
df.insert(0, "id", range(1, len(df) + 1))

# opcional: garantir que ficou de 1 a 50
print(df["id"].min(), df["id"].max(), len(df))

df.to_excel(OUT_XLSX, index=False)
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print(f"{len(df)} pares pergunta/resposta extraídos")
print(OUT_XLSX)
print(OUT_CSV)

display(df.head(1))
display(df.tail(1))

1 50 50
50 pares pergunta/resposta extraídos
data/cvm_std_claude_qa.xlsx
data/cvm_std_claude_qa.csv

,id,pergunta,resposta
0,1,Qual o período de inscrição para o concurso CVM?,"De acordo com o edital, as inscrições estavam ..."

,id,pergunta,resposta
49,50,Quais cuidados o candidato deve ter com o cart...,"De acordo com o edital, os cuidados que o cand..."