# Pipeline de avaliação — multi-modelo × multi-edital

Roda o agente em todas as combinações `(modelo, edital)` definidas, salva um xlsx
por combinação em `resultados/` e exibe sumário consolidado.

**Proteções contra desastre:**
1. Validação de preços antes de rodar (pega `PRECOS` faltando).
2. Smoke test: 1 pergunta por combinação antes de soltar as 50.
3. Limite de gasto por combinação — corta no meio se estourar.
4. Salvamento garantido em qualquer erro: o que foi medido até a falha vai pro xlsx.
5. Sumário final lista sucessos, parciais e falhas separadamente.

In [11]:
import os, sys, time, glob
from pathlib import Path
from datetime import datetime

ROOT = Path.cwd().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import warnings
warnings.filterwarnings("ignore")
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import pandas as pd
from dotenv import load_dotenv
load_dotenv(ROOT / ".env")

from agent.agent import build_agent, ask
from langchain_core.callbacks import BaseCallbackHandler

print(f"cwd:  {Path.cwd()}")
print(f"root: {ROOT}")

cwd:  /home/julio/Documentos/tcc_GENAI/v8/edital-assistant/evals
root: /home/julio/Documentos/tcc_GENAI/v8/edital-assistant

## TokenTracker — captura tokens + cache

In [12]:
class TokenTracker(BaseCallbackHandler):
    def __init__(self):
        self.reset()

    def reset(self):
        self.input_tokens = 0
        self.output_tokens = 0
        self.cache_read_tokens = 0
        self.cache_write_tokens = 0
        self.n_calls = 0

    def on_llm_end(self, response, **kwargs):
        self.n_calls += 1

        usage = (getattr(response, "llm_output", None) or {}).get("token_usage") or {}
        if usage:
            self.input_tokens  += usage.get("prompt_tokens", 0) or 0
            self.output_tokens += usage.get("completion_tokens", 0) or 0
            ds_hit = usage.get("prompt_cache_hit_tokens") or 0
            details = usage.get("prompt_tokens_details") or {}
            oai_hit = details.get("cached_tokens") or 0
            self.cache_read_tokens += (ds_hit + oai_hit)
            return

        for gen_list in response.generations:
            for gen in gen_list:
                msg = getattr(gen, "message", None)
                um = getattr(msg, "usage_metadata", None) if msg else None
                if um:
                    self.input_tokens  += um.get("input_tokens", 0) or 0
                    self.output_tokens += um.get("output_tokens", 0) or 0
                    details = um.get("input_token_details") or {}
                    self.cache_read_tokens  += details.get("cache_read", 0) or 0
                    self.cache_write_tokens += details.get("cache_creation", 0) or 0
                    break

## Configuração

Comente os índices que não quer rodar. `LIMITE_USD_POR_COMBO` é teto sobre estimativa
pessimista (sem cache) — real será sempre menor.

In [13]:
MODELOS = [
    # (provider, modelo)
    ("openai",    "gpt-4o-mini"),
    ("deepseek",  "deepseek-v4-flash"),
    ("openai",    "gpt-5.4-mini"),
    ("deepseek",  "deepseek-v4-pro"),
    ("anthropic", "claude-haiku-4-5"),
    # --- modelos caros — descomente quando for rodar ---
    # ("openai",    "gpt-5.4"),
    # ("anthropic", "claude-sonnet-4-6"),
    # ("anthropic", "claude-opus-4-7"),
    # ("openai",    "gpt-5.5"),
]

EDITAIS = [
    ("bndes",     1),
    ("cvm",       2),
    ("petrobras", 3),
]

# USD por 1M tokens. Ordem: (input_miss, input_cached, output).
PRECOS = {
    "openai/gpt-4o-mini":             (0.15,  0.075,  0.60),
    "openai/gpt-5.4-mini":            (0.25,  0.125,  2.00),
    "openai/gpt-5.4":                 (1.25,  0.625, 10.00),
    "openai/gpt-5.5":                 (5.00,  2.500, 30.00),
    "deepseek/deepseek-v4-flash":     (0.14,  0.028,  0.28),
    "deepseek/deepseek-v4-pro":       (1.74,  0.145,  3.48),
    "anthropic/claude-haiku-4-5":     (1.00,  1.000,  5.00),
    "anthropic/claude-sonnet-4-6":    (3.00,  3.000, 15.00),
    "anthropic/claude-opus-4-7":      (5.00,  5.000, 25.00),
}

LIMITE_USD_POR_COMBO = 20.00

PERGUNTAS_DIR  = Path("perguntas")
RESULTADOS_DIR = Path("resultados")
RESULTADOS_DIR.mkdir(exist_ok=True)

print(f"Modelos ativos:        {len(MODELOS)}")
print(f"Editais:               {len(EDITAIS)}")
print(f"Total de combinações:  {len(MODELOS) * len(EDITAIS)}")
print(f"Teto por combinação:   ${LIMITE_USD_POR_COMBO}")

Modelos ativos:        5
Editais:               3
Total de combinações:  15
Teto por combinação:   $20.0

## Validação 1 — preços (gratuita, não chama API)

In [14]:
faltando = [f"{p}/{m}" for p, m in MODELOS if f"{p}/{m}" not in PRECOS]
if faltando:
    raise RuntimeError(f"Modelos sem preço em PRECOS: {faltando}")
print(f"OK — todos os {len(MODELOS)} modelos têm preço configurado.")

OK — todos os 5 modelos têm preço configurado.

## Helpers

In [15]:
def slug(modelo: str) -> str:
    return modelo.replace("/", "_").replace(":", "_")


def custo_estimado(in_tok: int, out_tok: int, p_in: float, p_out: float) -> float:
    """Teto: trata todo input como cache miss."""
    return in_tok / 1_000_000 * p_in + out_tok / 1_000_000 * p_out


def custo_real(in_tok: int, out_tok: int, cache_read: int,
               p_in: float, p_in_cached: float, p_out: float) -> float:
    miss = max(in_tok - cache_read, 0)
    return (
        miss / 1_000_000 * p_in
        + cache_read / 1_000_000 * p_in_cached
        + out_tok / 1_000_000 * p_out
    )


def salvar_xlsx(provider, modelo, edital_nome, resultados, sufixo=""):
    df_r = pd.DataFrame(resultados)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    nome = f"{edital_nome}__{provider}__{slug(modelo)}__{ts}{sufixo}.xlsx"
    arq = RESULTADOS_DIR / nome
    df_r.to_excel(arq, index=False)
    return arq


def apagar_antigos(provider, modelo, edital_nome):
    padrao = str(RESULTADOS_DIR / f"{edital_nome}__{provider}__{slug(modelo)}__*.xlsx")
    n = 0
    for antigo in glob.glob(padrao):
        Path(antigo).unlink()
        n += 1
    return n

In [16]:
def rodar_combo(provider, modelo, edital_nome, edital_id, limite_usd=LIMITE_USD_POR_COMBO):
    """Roda N perguntas. Retorna (xlsx_path, erro_fatal_ou_None).
    
    Erros em perguntas individuais vão pra coluna `erro` e a combinação continua.
    Estouro de orçamento ou erro fora do loop interrompem e salvam parcial."""
    chave = f"{provider}/{modelo}"
    p_in, p_in_cached, p_out = PRECOS[chave]

    arq_perguntas = PERGUNTAS_DIR / f"{edital_nome}.xlsx"
    df_q = pd.read_excel(arq_perguntas)
    df_q = df_q.dropna(subset=["pergunta"])
    df_q = df_q[df_q["pergunta"].str.strip() != ""].reset_index(drop=True)

    agente = build_agent(provider=provider, model=modelo)
    tracker = TokenTracker()
    agente.llm       = agente.llm.with_config(callbacks=[tracker])
    agente.llm_check = agente.llm_check.with_config(callbacks=[tracker])

    resultados = []
    custo_estim_acum = 0.0
    erro_fatal = None

    for i, row in df_q.iterrows():
        pergunta = row["pergunta"]
        t0 = time.time()
        erro, resposta = None, None

        tracker.reset()
        try:
            resposta = ask(agent=agente, question=pergunta, chat_history=[], edital_id_ativo=edital_id)
        except Exception as e:
            erro = str(e)

        in_tok     = tracker.input_tokens
        out_tok    = tracker.output_tokens
        cache_read = tracker.cache_read_tokens
        n_calls    = tracker.n_calls
        latencia   = round(time.time() - t0, 2)

        c_estim = custo_estimado(in_tok, out_tok, p_in, p_out)
        c_real  = custo_real(in_tok, out_tok, cache_read, p_in, p_in_cached, p_out)
        custo_estim_acum += c_estim

        resultados.append({
            "id":                row["id"],
            "categoria":         row.get("categoria", ""),
            "pergunta":          pergunta,
            "resposta":          resposta,
            "input_tokens":      in_tok,
            "output_tokens":     out_tok,
            "total_tokens":      in_tok + out_tok,
            "cache_read_tokens": cache_read,
            "cache_miss_tokens": max(in_tok - cache_read, 0),
            "n_invocacoes":      n_calls,
            "custo_usd":         round(c_estim, 6),
            "custo_real_usd":    round(c_real, 6),
            "latencia_s":        latencia,
            "erro":              erro,
        })

        flag = "ERRO" if erro else "ok"
        cache_pct = (cache_read / in_tok * 100) if in_tok else 0
        print(f"      [{i+1:>2}/{len(df_q)}] {flag:>4}  {latencia:>5}s  "
              f"calls={n_calls}  in={in_tok:>5} (cache {cache_pct:>4.0f}%)  "
              f"out={out_tok:>4}  acum=${custo_estim_acum:.4f}")

        if custo_estim_acum > limite_usd:
            erro_fatal = f"Estouro na pergunta {i+1}: ${custo_estim_acum:.4f} > ${limite_usd}"
            break

    sufixo = "__PARCIAL" if erro_fatal else ""
    arq = salvar_xlsx(provider, modelo, edital_nome, resultados, sufixo) if resultados else None
    return arq, erro_fatal

## Validação 2 — smoke test

Uma pergunta por combinação. Se algum modelo tiver armadilha (thinking mode default,
credencial faltando, formato de tool diferente), explode aqui em vez de em 50
perguntas. Se qualquer combo falhar, **a célula levanta erro** e o loop principal
não roda.

In [17]:
print("=== SMOKE TEST ===\n")

smoke_falhas = []

for provider, modelo in MODELOS:
    for edital_nome, edital_id in EDITAIS:
        print(f"  [test] {provider}/{modelo} × {edital_nome} ... ", end="", flush=True)
        try:
            agente = build_agent(provider=provider, model=modelo)
            tracker = TokenTracker()
            agente.llm       = agente.llm.with_config(callbacks=[tracker])
            agente.llm_check = agente.llm_check.with_config(callbacks=[tracker])

            resp = ask(agent=agente, question="Qual o salário inicial?",
                       chat_history=[], edital_id_ativo=edital_id)

            if not resp or len(resp.strip()) < 20:
                raise ValueError(f"resposta vazia/curta: {resp!r}")
            print(f"ok ({tracker.input_tokens} in / {tracker.output_tokens} out / {tracker.n_calls} calls)")
        except Exception as e:
            smoke_falhas.append(f"{provider}/{modelo} × {edital_nome}: {e}")
            print(f"FALHOU\n           {e}")

if smoke_falhas:
    raise RuntimeError(
        f"\n{len(smoke_falhas)} combinação(ões) falhou(ram). Corrija ou comente:\n  - " +
        "\n  - ".join(smoke_falhas)
    )

print(f"\nTodas as {len(MODELOS) * len(EDITAIS)} combinações passaram.")

=== SMOKE TEST ===

  [test] openai/gpt-4o-mini × bndes ... ok (7590 in / 105 out / 2 calls)
  [test] openai/gpt-4o-mini × cvm ... ok (7146 in / 88 out / 2 calls)
  [test] openai/gpt-4o-mini × petrobras ... ok (7251 in / 78 out / 2 calls)
  [test] deepseek/deepseek-v4-flash × bndes ... ok (9569 in / 205 out / 2 calls)
  [test] deepseek/deepseek-v4-flash × cvm ... ok (8547 in / 160 out / 2 calls)
  [test] deepseek/deepseek-v4-flash × petrobras ... ok (9177 in / 204 out / 2 calls)
  [test] openai/gpt-5.4-mini × bndes ... ok (5150 in / 90 out / 2 calls)
  [test] openai/gpt-5.4-mini × cvm ... ok (4523 in / 104 out / 2 calls)
  [test] openai/gpt-5.4-mini × petrobras ... ok (4564 in / 89 out / 2 calls)
  [test] deepseek/deepseek-v4-pro × bndes ... ok (9128 in / 200 out / 2 calls)
  [test] deepseek/deepseek-v4-pro × cvm ... ok (8539 in / 162 out / 2 calls)
  [test] deepseek/deepseek-v4-pro × petrobras ... ok (9237 in / 184 out / 2 calls)
  [test] anthropic/claude-haiku-4-5 × bndes ... ok (11127 in / 257 out / 2 calls)
  [test] anthropic/claude-haiku-4-5 × cvm ... ok (10436 in / 217 out / 2 calls)
  [test] anthropic/claude-haiku-4-5 × petrobras ... ok (11248 in / 200 out / 2 calls)

Todas as 15 combinações passaram.

## Pipeline principal

Sobrescreve xlsx antigos. Erro numa combinação não para as outras. Sumário
no fim separa sucessos, parciais (estouro) e falhas.

In [ ]:
sucessos, parciais, falhas = [], [], []

for provider, modelo in MODELOS:
    for edital_nome, edital_id in EDITAIS:
        n = apagar_antigos(provider, modelo, edital_nome)
        if n:
            print(f"\n[del]  {n} xlsx antigo(s) de {provider}/{modelo} × {edital_nome}")
        print(f"\n[run]  {provider}/{modelo} × {edital_nome} (id={edital_id})")

        try:
            arq, erro_fatal = rodar_combo(provider, modelo, edital_nome, edital_id)
        except Exception as e:
            falhas.append((provider, modelo, edital_nome, str(e)))
            print(f"       ✗ FALHOU antes do xlsx: {e}")
            continue

        if erro_fatal:
            parciais.append((provider, modelo, edital_nome, arq, erro_fatal))
            print(f"       ⚠ PARCIAL — {erro_fatal}\n         salvo em {arq.name}")
        else:
            sucessos.append((provider, modelo, edital_nome, arq))
            print(f"       ✓ ok — salvo em {arq.name}")

print("\n" + "=" * 60)
print("=== SUMÁRIO ===")
print("=" * 60)
print(f"\n✓ Sucessos: {len(sucessos)}")
for p, m, e, a in sucessos:
    print(f"    {p}/{m} × {e}  →  {a.name}")
print(f"\n⚠ Parciais (estouro de orçamento): {len(parciais)}")
for p, m, e, a, err in parciais:
    print(f"    {p}/{m} × {e}  →  {a.name}\n        {err}")
print(f"\n✗ Falhas: {len(falhas)}")
for p, m, e, err in falhas:
    print(f"    {p}/{m} × {e}\n        {err}")

[run]  openai/gpt-4o-mini × bndes (id=1)
      [ 1/50]   ok   5.24s  calls=3  in= 8490 (cache   35%)  out= 135  acum=$0.0014
      [ 2/50]   ok   3.17s  calls=2  in= 6514 (cache   24%)  out=  67  acum=$0.0024
      [ 3/50]   ok   3.08s  calls=2  in= 7004 (cache   22%)  out=  94  acum=$0.0035
      [ 4/50]   ok    4.7s  calls=2  in= 6323 (cache    0%)  out= 189  acum=$0.0045
      [ 5/50]   ok    4.2s  calls=2  in= 7060 (cache    0%)  out= 179  acum=$0.0057
      [ 6/50]   ok   5.84s  calls=2  in= 7027 (cache    0%)  out= 239  acum=$0.0069
      [ 7/50]   ok   3.06s  calls=2  in= 7033 (cache    0%)  out=  96  acum=$0.0080
      [ 8/50]   ok   4.53s  calls=2  in= 6298 (cache    0%)  out= 104  acum=$0.0090
      [ 9/50]   ok   3.67s  calls=2  in= 6190 (cache    0%)  out= 135  acum=$0.0100
      [10/50]   ok   5.53s  calls=2  in= 6701 (cache   23%)  out= 210  acum=$0.0112
      [11/50]   ok   3.48s  calls=2  in= 6067 (cache   25%)  out= 132  acum=$0.0122
      [12/50]   ok   9.82s  calls=3  in=14811 (cache    0%)  out= 254  acum=$0.0145
      [13/50]   ok   4.72s  calls=2  in=11932 (cache    0%)  out= 139  acum=$0.0164
      [14/50]   ok   3.57s  calls=2  in= 6102 (cache    0%)  out= 106  acum=$0.0174
      [15/50]   ok    8.2s  calls=3  in=17250 (cache   37%)  out= 242  acum=$0.0201
      [16/50]   ok  11.87s  calls=3  in=14804 (cache   10%)  out= 502  acum=$0.0226
      [17/50]   ok   5.18s  calls=2  in= 7627 (cache    0%)  out= 211  acum=$0.0239
      [18/50]   ok   8.44s  calls=2  in= 6951 (cache    0%)  out= 172  acum=$0.0251
      [19/50]   ok   5.84s  calls=3  in=15932 (cache   33%)  out= 166  acum=$0.0275
      [20/50]   ok   4.71s  calls=2  in= 6725 (cache    0%)  out=  98  acum=$0.0286
      [21/50]   ok   5.63s  calls=2  in= 6983 (cache    0%)  out= 230  acum=$0.0298
      [22/50]   ok   4.71s  calls=2  in= 6140 (cache    0%)  out= 196  acum=$0.0308
      [23/50]   ok   3.42s  calls=2  in= 6536 (cache   24%)  out= 102  acum=$0.0319
      [24/50]   ok   4.57s  calls=2  in= 6196 (cache   25%)  out= 176  acum=$0.0329
      [25/50]   ok   2.94s  calls=2  in= 7601 (cache   20%)  out=  82  acum=$0.0341
      [26/50]   ok   6.78s  calls=3  in=16632 (cache   33%)  out= 175  acum=$0.0367
      [27/50]   ok   6.15s  calls=3  in=15426 (cache   10%)  out= 162  acum=$0.0391
      [28/50]   ok   7.68s  calls=2  in= 7688 (cache   20%)  out= 285  acum=$0.0404
      [29/50]   ok   2.97s  calls=2  in= 6681 (cache    0%)  out=  84  acum=$0.0415
      [30/50]   ok  10.84s  calls=2  in= 7490 (cache    0%)  out= 172  acum=$0.0427
      [31/50]   ok   4.93s  calls=2  in= 7165 (cache    0%)  out= 153  acum=$0.0439
      [32/50]   ok   5.51s  calls=2  in= 7195 (cache   21%)  out= 192  acum=$0.0451
      [33/50]   ok   5.55s  calls=2  in= 6870 (cache    0%)  out= 221  acum=$0.0462
      [34/50]   ok   3.58s  calls=2  in= 7448 (cache   21%)  out= 107  acum=$0.0474
      [35/50]   ok   3.99s  calls=2  in= 7428 (cache   21%)  out= 126  acum=$0.0486
      [36/50]   ok   3.28s  calls=2  in= 7721 (cache   20%)  out= 114  acum=$0.0498
      [37/50]   ok  13.84s  calls=3  in=11109 (cache   32%)  out= 544  acum=$0.0518
      [38/50]   ok   5.01s  calls=2  in= 7918 (cache   19%)  out= 188  acum=$0.0531
      [39/50]   ok   6.35s  calls=2  in= 7870 (cache   20%)  out= 254  acum=$0.0545
      [40/50]   ok   5.22s  calls=2  in= 7866 (cache   20%)  out= 170  acum=$0.0557
      [41/50]   ok   6.45s  calls=2  in= 7872 (cache   20%)  out= 280  acum=$0.0571
      [42/50]   ok   4.28s  calls=2  in= 7107 (cache   22%)  out= 166  acum=$0.0583
      [43/50]   ok   4.63s  calls=2  in= 7662 (cache    0%)  out= 119  acum=$0.0595
      [44/50]   ok   4.61s  calls=2  in= 8103 (cache    0%)  out= 160  acum=$0.0608
      [45/50]   ok   6.04s  calls=2  in= 6561 (cache    0%)  out= 327  acum=$0.0620
      [46/50]   ok   2.85s  calls=2  in= 6579 (cache    0%)  out=  70  acum=$0.0630
      [47/50]   ok   6.26s  calls=3  in=16648 (cache   36%)  out= 224  acum=$0.0656
      [48/50]   ok   3.22s  calls=2  in= 6685 (cache    0%)  out=  79  acum=$0.0667
      [49/50]   ok   5.76s  calls=2  in= 7064 (cache    0%)  out= 398  acum=$0.0680
      [50/50]   ok   6.38s  calls=2  in= 6399 (cache   24%)  out= 352  acum=$0.0691
       ✓ ok — salvo em bndes__openai__gpt-4o-mini__20260429_231806.xlsx

[run]  openai/gpt-4o-mini × cvm (id=2)
      [ 1/50]   ok   5.58s  calls=3  in= 7794 (cache   39%)  out= 158  acum=$0.0013
      [ 2/50]   ok   3.33s  calls=2  in= 6123 (cache   25%)  out=  90  acum=$0.0022
      [ 3/50]   ok   3.32s  calls=2  in= 6651 (cache   23%)  out= 118  acum=$0.0033
      [ 4/50]   ok   7.36s  calls=3  in=13984 (cache   49%)  out= 285  acum=$0.0056
      [ 5/50]   ok   4.21s  calls=2  in= 6133 (cache   25%)  out= 162  acum=$0.0066
      [ 6/50]   ok   5.84s  calls=2  in= 6053 (cache   25%)  out= 236  acum=$0.0076
      [ 7/50]   ok   3.23s  calls=2  in= 6059 (cache   25%)  out= 101  acum=$0.0086
      [ 8/50]   ok   4.81s  calls=2  in= 6692 (cache   23%)  out= 173  acum=$0.0097
      [ 9/50]   ok   3.65s  calls=2  in= 6769 (cache   23%)  out= 122  acum=$0.0108
      [10/50]   ok   3.46s  calls=2  in= 5952 (cache   26%)  out= 113  acum=$0.0118
      [11/50]   ok   3.48s  calls=2  in= 6361 (cache   24%)  out= 123  acum=$0.0128
      [12/50]   ok   3.38s  calls=2  in= 6161 (cache   25%)  out= 121  acum=$0.0138
      [13/50]   ok   4.71s  calls=2  in= 9856 (cache   16%)  out= 163  acum=$0.0154
      [14/50]   ok   7.77s  calls=3  in=13796 (cache   46%)  out= 236  acum=$0.0176
      [15/50]   ok   8.44s  calls=3  in=14612 (cache   46%)  out= 274  acum=$0.0199
      [16/50]   ok    5.7s  calls=3  in=15939 (cache   47%)  out= 223  acum=$0.0225
      [17/50]   ok   3.28s  calls=2  in= 6151 (cache   25%)  out= 116  acum=$0.0235
      [18/50]   ok   6.35s  calls=2  in= 7756 (cache   20%)  out= 283  acum=$0.0248
      [19/50]   ok   3.36s  calls=2  in= 7751 (cache   20%)  out= 103  acum=$0.0260
      [20/50]   ok   2.99s  calls=2  in= 7578 (cache   20%)  out=  87  acum=$0.0272
      [21/50]   ok   6.04s  calls=2  in= 6396 (cache   24%)  out= 214  acum=$0.0283
      [22/50]   ok   5.63s  calls=2  in= 6277 (cache   24%)  out= 231  acum=$0.0294
      [23/50]   ok   3.48s  calls=2  in= 6245 (cache   25%)  out=  95  acum=$0.0304
      [24/50]   ok    4.6s  calls=2  in= 6407 (cache   24%)  out=  91  acum=$0.0314
      [25/50]   ok   9.53s  calls=5  in=38613 (cache   62%)  out= 230  acum=$0.0373
      [26/50]   ok    4.3s  calls=2  in= 7505 (cache   20%)  out= 128  acum=$0.0385
      [27/50]   ok   4.81s  calls=3  in=15056 (cache   45%)  out= 117  acum=$0.0408
      [28/50]   ok   6.24s  calls=2  in= 7322 (cache   21%)  out= 239  acum=$0.0421
      [29/50]   ok   6.66s  calls=3  in=16508 (cache   44%)  out= 168  acum=$0.0447
      [30/50]   ok   5.33s  calls=2  in= 6348 (cache   24%)  out= 206  acum=$0.0457
      [31/50]   ok   4.71s  calls=2  in= 6147 (cache   25%)  out= 176  acum=$0.0468
      [32/50]   ok   3.58s  calls=2  in= 6602 (cache   23%)  out= 122  acum=$0.0478
      [33/50]   ok   3.16s  calls=2  in= 6266 (cache   25%)  out=  88  acum=$0.0488
      [34/50]   ok   5.64s  calls=3  in=14814 (cache   47%)  out= 159  acum=$0.0511
      [35/50]   ok   4.91s  calls=2  in= 6592 (cache   23%)  out= 157  acum=$0.0522
      [36/50]   ok   4.81s  calls=2  in= 6703 (cache   23%)  out= 154  acum=$0.0533
      [37/50]   ok   6.44s  calls=3  in= 8416 (cache   44%)  out= 255  acum=$0.0547
      [38/50]   ok   4.82s  calls=2  in= 6917 (cache   22%)  out= 171  acum=$0.0559
      [39/50]   ok   6.35s  calls=2  in= 6288 (cache   24%)  out= 259  acum=$0.0570
      [40/50]   ok   5.73s  calls=2  in= 7310 (cache   21%)  out= 209  acum=$0.0582
      [41/50]   ok   7.37s  calls=2  in= 7316 (cache   21%)  out= 279  acum=$0.0595
      [42/50]   ok    4.0s  calls=2  in= 6267 (cache   25%)  out= 136  acum=$0.0605
      [43/50]   ok    4.3s  calls=2  in= 6194 (cache   25%)  out= 103  acum=$0.0615
      [44/50]   ok   3.79s  calls=2  in= 6592 (cache   23%)  out= 115  acum=$0.0625
      [45/50]   ok   4.87s  calls=2  in= 6829 (cache   22%)  out= 199  acum=$0.0637
      [46/50]   ok   5.06s  calls=3  in= 7148 (cache   43%)  out= 156  acum=$0.0648
      [47/50]   ok  10.24s  calls=3  in=13718 (cache   47%)  out= 270  acum=$0.0671
      [48/50]   ok   5.73s  calls=2  in= 6790 (cache    0%)  out=  97  acum=$0.0681
      [49/50]   ok   6.45s  calls=2  in= 5982 (cache   26%)  out= 282  acum=$0.0692
      [50/50]   ok    8.7s  calls=2  in= 5707 (cache   27%)  out= 372  acum=$0.0703
       ✓ ok — salvo em cvm__openai__gpt-4o-mini__20260429_232228.xlsx

[run]  openai/gpt-4o-mini × petrobras (id=3)
      [ 1/50]   ok   5.18s  calls=3  in= 8740 (cache   35%)  out= 116  acum=$0.0014
      [ 2/50]   ok   2.87s  calls=2  in= 6041 (cache   25%)  out=  56  acum=$0.0023
      [ 3/50]   ok   4.71s  calls=2  in= 6496 (cache   24%)  out= 143  acum=$0.0034
      [ 4/50]   ok    8.6s  calls=3  in=18317 (cache   38%)  out= 247  acum=$0.0063
      [ 5/50]   ok    4.2s  calls=2  in= 7129 (cache   22%)  out=  95  acum=$0.0074
      [ 6/50]   ok   7.47s  calls=2  in= 7081 (cache   22%)  out= 248  acum=$0.0086
      [ 7/50]   ok   5.63s  calls=2  in= 7087 (cache   22%)  out= 112  acum=$0.0097
      [ 8/50]   ok   4.03s  calls=2  in= 6024 (cache   25%)  out= 116  acum=$0.0107
      [ 9/50]   ok   6.11s  calls=2  in= 6814 (cache   23%)  out= 165  acum=$0.0118
      [10/50]   ok   5.07s  calls=2  in= 6460 (cache   24%)  out= 107  acum=$0.0129
      [11/50]   ok   7.21s  calls=3  in=14190 (cache   54%)  out= 169  acum=$0.0151
      [12/50]   ok  10.85s  calls=3  in=13511 (cache   53%)  out= 293  acum=$0.0173
      [13/50]   ok   5.09s  calls=2  in=11388 (cache   13%)  out= 131  acum=$0.0191
      [14/50]   ok   6.69s  calls=3  in=14476 (cache   53%)  out= 175  acum=$0.0214
      [15/50]   ok   7.06s  calls=3  in=17569 (cache   47%)  out= 179  acum=$0.0241
      [16/50]   ok   9.19s  calls=3  in=14779 (cache   50%)  out= 285  acum=$0.0265
      [17/50]   ok   5.87s  calls=2  in= 6016 (cache   26%)  out= 215  acum=$0.0275
      [18/50]   ok   5.63s  calls=2  in= 6925 (cache   22%)  out= 204  acum=$0.0287
      [19/50]   ok   3.95s  calls=2  in= 6845 (cache   22%)  out= 127  acum=$0.0298
      [20/50]   ok   5.06s  calls=2  in= 6910 (cache    0%)  out= 139  acum=$0.0309
      [21/50]   ok   7.37s  calls=2  in= 6106 (cache   25%)  out= 239  acum=$0.0320
      [22/50]   ok   6.29s  calls=2  in= 6102 (cache   25%)  out= 234  acum=$0.0330
      [23/50]   ok   3.03s  calls=2  in= 6296 (cache   24%)  out=  86  acum=$0.0340
      [24/50]   ok   4.89s  calls=2  in= 6638 (cache   23%)  out= 155  acum=$0.0351
      [25/50]   ok   7.71s  calls=3  in=26080 (cache   45%)  out= 248  acum=$0.0392
      [26/50]   ok   6.65s  calls=2  in=12050 (cache   13%)  out= 199  acum=$0.0411
      [27/50]   ok   6.15s  calls=3  in=15264 (cache   44%)  out= 115  acum=$0.0435
      [28/50]   ok  10.26s  calls=2  in= 6311 (cache   24%)  out= 423  acum=$0.0447
      [29/50]   ok   5.02s  calls=3  in=15010 (cache   45%)  out= 135  acum=$0.0470
      [30/50]   ok   5.81s  calls=2  in= 6835 (cache    0%)  out= 162  acum=$0.0481
      [31/50]   ok   5.33s  calls=2  in= 6668 (cache    0%)  out= 160  acum=$0.0492
      [32/50]   ok    4.4s  calls=2  in= 6953 (cache   22%)  out= 133  acum=$0.0503
      [33/50]   ok   3.18s  calls=2  in= 6446 (cache   24%)  out=  81  acum=$0.0513
      [34/50]   ok   4.34s  calls=2  in= 6186 (cache   25%)  out= 122  acum=$0.0523
      [35/50]   ok   4.16s  calls=2  in= 7445 (cache   21%)  out= 126  acum=$0.0535
      [36/50]   ok   5.12s  calls=2  in= 7404 (cache   21%)  out= 119  acum=$0.0547
      [37/50]   ok   6.75s  calls=2  in= 8316 (cache   18%)  out= 284  acum=$0.0561
      [38/50]   ok   4.31s  calls=2  in= 6219 (cache   25%)  out= 158  acum=$0.0572
      [39/50]   ok   6.65s  calls=2  in= 6217 (cache   25%)  out= 206  acum=$0.0582
      [40/50]   ok   6.14s  calls=2  in= 7823 (cache   20%)  out= 140  acum=$0.0595
      [41/50]   ok   9.11s  calls=2  in= 7829 (cache   20%)  out= 356  acum=$0.0609
      [42/50]   ok    4.5s  calls=2  in= 7184 (cache   21%)  out= 159  acum=$0.0620
      [43/50]   ok   5.43s  calls=2  in= 7200 (cache   21%)  out= 192  acum=$0.0632
      [44/50]   ok  11.88s  calls=5  in=43681 (cache   63%)  out= 274  acum=$0.0700
      [45/50]   ok    8.7s  calls=2  in= 6783 (cache   23%)  out= 293  acum=$0.0711
      [46/50]   ok   9.63s  calls=3  in= 9288 (cache   33%)  out= 127  acum=$0.0726
      [47/50]   ok   8.09s  calls=2  in=10732 (cache    0%)  out= 264  acum=$0.0744
      [48/50]   ok   3.79s  calls=2  in= 6902 (cache   22%)  out= 103  acum=$0.0755
      [49/50]   ok   6.96s  calls=2  in= 6560 (cache   23%)  out= 283  acum=$0.0766
      [50/50]   ok   8.83s  calls=2  in= 5974 (cache   26%)  out= 371  acum=$0.0778
       ✓ ok — salvo em petrobras__openai__gpt-4o-mini__20260429_232739.xlsx

[run]  deepseek/deepseek-v4-flash × bndes (id=1)
      [ 1/50]   ok   5.36s  calls=2  in= 8804 (cache  198%)  out= 219  acum=$0.0013
      [ 2/50]   ok   6.25s  calls=2  in= 8441 (cache  197%)  out= 290  acum=$0.0026
      [ 3/50]   ok   7.03s  calls=3  in=21343 (cache  198%)  out= 260  acum=$0.0056
      [ 4/50]   ok   6.83s  calls=2  in= 8221 (cache  196%)  out= 302  acum=$0.0069
      [ 5/50]   ok   6.46s  calls=2  in= 9044 (cache  198%)  out= 281  acum=$0.0082
      [ 6/50]   ok   8.76s  calls=2  in= 9030 (cache  198%)  out= 450  acum=$0.0096
      [ 7/50]   ok   7.78s  calls=2  in= 8991 (cache  196%)  out= 357  acum=$0.0109
      [ 8/50]   ok   7.68s  calls=2  in= 8209 (cache  196%)  out= 364  acum=$0.0122
      [ 9/50]   ok   8.91s  calls=2  in= 8467 (cache  103%)  out= 452  acum=$0.0135
      [10/50]   ok   7.68s  calls=2  in= 8587 (cache  197%)  out= 366  acum=$0.0148
      [11/50]   ok   6.54s  calls=2  in= 8131 (cache  198%)  out= 308  acum=$0.0160
      [12/50]   ok   7.69s  calls=2  in= 8917 (cache  198%)  out= 389  acum=$0.0174
      [13/50]   ok   5.53s  calls=2  in= 9274 (cache  199%)  out= 240  acum=$0.0188
      [14/50]   ok   9.42s  calls=2  in= 8531 (cache  198%)  out= 523  acum=$0.0201
      [15/50]   ok   6.24s  calls=2  in= 9569 (cache  198%)  out= 280  acum=$0.0215
      [16/50]   ok   7.71s  calls=2  in= 9029 (cache  198%)  out= 377  acum=$0.0229
      [17/50]   ok  19.03s  calls=5  in=44822 (cache  199%)  out= 888  acum=$0.0294
      [18/50]   ok   6.96s  calls=2  in= 8861 (cache  196%)  out= 324  acum=$0.0307
      [19/50]   ok  12.08s  calls=4  in=23715 (cache  199%)  out= 530  acum=$0.0342
      [20/50]   ok  10.75s  calls=4  in=24216 (cache  199%)  out= 429  acum=$0.0377
      [21/50]   ok   8.13s  calls=2  in= 8939 (cache  198%)  out= 419  acum=$0.0391
      [22/50]   ok   9.18s  calls=2  in= 8166 (cache  198%)  out= 473  acum=$0.0404
      [23/50]   ok   5.83s  calls=2  in= 8489 (cache  199%)  out= 264  acum=$0.0416
      [24/50]   ok   9.21s  calls=2  in= 7904 (cache  198%)  out= 496  acum=$0.0429
      [25/50]   ok   6.45s  calls=2  in= 9595 (cache  197%)  out= 144  acum=$0.0443
      [26/50]   ok  14.72s  calls=5  in=45632 (cache  172%)  out= 618  acum=$0.0508
      [27/50]   ok  11.62s  calls=4  in=27866 (cache  198%)  out= 473  acum=$0.0549
      [28/50]   ok  10.53s  calls=2  in= 8871 (cache  199%)  out= 568  acum=$0.0563
      [29/50]   ok   4.91s  calls=2  in= 8437 (cache  197%)  out= 186  acum=$0.0575
      [30/50]   ok  17.31s  calls=4  in=34021 (cache  165%)  out= 852  acum=$0.0625
      [31/50]   ok   7.58s  calls=2  in= 9362 (cache  197%)  out= 379  acum=$0.0639
      [32/50]   ok   7.47s  calls=2  in= 9030 (cache  198%)  out= 372  acum=$0.0653
      [33/50]   ok   7.68s  calls=2  in= 8760 (cache  199%)  out= 382  acum=$0.0666
      [34/50]   ok   5.33s  calls=2  in= 9258 (cache  199%)  out= 208  acum=$0.0680
      [35/50]   ok   7.98s  calls=2  in= 9333 (cache  197%)  out= 407  acum=$0.0694
      [36/50]   ok   6.96s  calls=2  in= 9658 (cache  199%)  out= 317  acum=$0.0708
      [37/50]   ok  13.31s  calls=2  in= 9902 (cache  199%)  out= 768  acum=$0.0724
      [38/50]   ok  10.03s  calls=2  in= 9989 (cache  197%)  out= 530  acum=$0.0740
      [39/50]   ok    8.7s  calls=2  in= 9977 (cache  198%)  out= 439  acum=$0.0755
      [40/50]   ok   9.19s  calls=2  in=10791 (cache  199%)  out= 484  acum=$0.0771
      [41/50]   ok  14.56s  calls=2  in= 9871 (cache  197%)  out= 842  acum=$0.0788
      [42/50]   ok   5.63s  calls=2  in= 9915 (cache   88%)  out= 251  acum=$0.0802
      [43/50]   ok   5.95s  calls=2  in= 9696 (cache  198%)  out= 252  acum=$0.0816
      [44/50]   ok  17.92s  calls=4  in=36438 (cache  128%)  out=1001  acum=$0.0870
      [45/50]   ok  16.79s  calls=3  in=23692 (cache  199%)  out= 915  acum=$0.0906
      [46/50]   ok   5.02s  calls=2  in= 8431 (cache  197%)  out= 218  acum=$0.0918
      [47/50]   ok   7.06s  calls=2  in= 8493 (cache  199%)  out= 339  acum=$0.0931
      [48/50]   ok   6.15s  calls=2  in= 9120 (cache  199%)  out= 284  acum=$0.0945
      [49/50]   ok   9.27s  calls=2  in= 9184 (cache  198%)  out= 507  acum=$0.0959
      [50/50]   ok   9.57s  calls=2  in= 8772 (cache  198%)  out= 545  acum=$0.0973
       ✓ ok — salvo em bndes__deepseek__deepseek-v4-flash__20260429_233504.xlsx

[run]  deepseek/deepseek-v4-flash × cvm (id=2)
      [ 1/50]   ok   5.69s  calls=2  in= 8119 (cache  199%)  out= 259  acum=$0.0012
      [ 2/50]   ok   5.84s  calls=2  in= 8067 (cache  197%)  out= 268  acum=$0.0024
      [ 3/50]   ok    5.5s  calls=2  in= 8623 (cache  199%)  out= 224  acum=$0.0037
      [ 4/50]   ok   6.99s  calls=2  in= 7894 (cache  198%)  out= 346  acum=$0.0049
      [ 5/50]   ok   6.45s  calls=2  in= 7929 (cache  197%)  out= 309  acum=$0.0061
      [ 6/50]   ok   7.54s  calls=2  in= 8073 (cache  197%)  out= 425  acum=$0.0073
      [ 7/50]   ok   5.36s  calls=2  in= 8153 (cache  198%)  out= 220  acum=$0.0085
      [ 8/50]   ok   7.58s  calls=2  in= 7954 (cache  109%)  out= 383  acum=$0.0098
      [ 9/50]   ok   5.78s  calls=2  in= 7378 (cache  118%)  out= 262  acum=$0.0109
      [10/50]   ok   6.71s  calls=2  in= 7839 (cache  111%)  out= 330  acum=$0.0121
      [11/50]   ok   6.04s  calls=2  in= 8927 (cache   98%)  out= 253  acum=$0.0134
      [12/50]   ok   6.66s  calls=2  in= 7994 (cache  109%)  out= 296  acum=$0.0146
      [13/50]   ok   5.84s  calls=3  in=10624 (cache  128%)  out= 201  acum=$0.0161
      [14/50]   ok   6.59s  calls=2  in= 7687 (cache  113%)  out= 333  acum=$0.0173
      [15/50]   ok   7.74s  calls=2  in= 7971 (cache  109%)  out= 410  acum=$0.0185
      [16/50]   ok   7.68s  calls=2  in= 8891 (cache   98%)  out= 394  acum=$0.0199
      [17/50]   ok  11.88s  calls=3  in=13694 (cache  146%)  out= 602  acum=$0.0220
      [18/50]   ok  11.31s  calls=2  in= 9650 (cache   90%)  out= 672  acum=$0.0235
      [19/50]   ok   5.58s  calls=2  in= 9173 (cache   95%)  out= 216  acum=$0.0248
      [20/50]   ok   4.94s  calls=2  in= 9592 (cache   91%)  out= 202  acum=$0.0262
      [21/50]   ok   8.06s  calls=2  in= 7867 (cache  111%)  out= 427  acum=$0.0275
      [22/50]   ok    8.2s  calls=2  in= 8227 (cache  106%)  out= 435  acum=$0.0287
      [23/50]   ok    4.2s  calls=2  in= 8177 (cache  106%)  out= 161  acum=$0.0299
      [24/50]   ok   6.25s  calls=2  in= 8422 (cache  103%)  out= 292  acum=$0.0312
      [25/50]   ok  13.93s  calls=4  in=35135 (cache  133%)  out= 637  acum=$0.0363
      [26/50]   ok   5.22s  calls=2  in= 9457 (cache   92%)  out= 234  acum=$0.0377
      [27/50]   ok  14.95s  calls=5  in=42333 (cache  155%)  out= 672  acum=$0.0438
      [28/50]   ok  10.55s  calls=2  in= 8650 (cache  101%)  out= 631  acum=$0.0452
      [29/50]   ok   6.52s  calls=2  in= 8064 (cache  108%)  out= 321  acum=$0.0464
      [30/50]   ok  11.36s  calls=4  in=26771 (cache  151%)  out= 537  acum=$0.0503
      [31/50]   ok   8.13s  calls=2  in= 7968 (cache  109%)  out= 428  acum=$0.0515

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-558e-79d3-b94b-405070846cec,id=019ddc50-558e-79d3-b94b-405070846cec; trace=019ddc50-5b20-7751-8895-63d83d16e0de,id=019ddc50-5b20-7751-8895-63d83d16e0de
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-5b20-7751-8895-63d83d16e0de,id=019ddc50-5b20-7751-8895-63d83d16e0de; trace=019ddc50-5eed-7db1-9fe5-4080b0f40015,id=019ddc50-5eed-7db1-9fe5-4080b0f40015; trace=019ddc50-5eed-7db1-9fe5-4080b0f40015,id=019ddc50-5eed-7db1-9fe5-4080b0f40015; trace=019ddc50-5fde-7bf3-b57c-918bde1767ab,id=019ddc50-5fde-7bf3-b57c-918bde1767ab
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-5fde-7bf3-b57c-918bde1767ab,id=019ddc50-5fde-7bf3-b57c-918bde1767ab; trace=019ddc50-63dc-7e61-aeb6-43706dc13d72,id=019ddc50-63dc-7e61-aeb6-43706dc13d72; trace=019ddc50-63dc-7e61-aeb6-43706dc13d72,id=019ddc50-63dc-7e61-aeb6-43706dc13d72; trace=019ddc50-64ca-70e1-bd93-442aecfa2b19,id=019ddc50-64ca-70e1-bd93-442aecfa2b19
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-64ca-70e1-bd93-442aecfa2b19,id=019ddc50-64ca-70e1-bd93-442aecfa2b19; trace=019ddc50-684a-7fd1-8776-96f6f6bcdb53,id=019ddc50-684a-7fd1-8776-96f6f6bcdb53; trace=019ddc50-684a-7fd1-8776-96f6f6bcdb53,id=019ddc50-684a-7fd1-8776-96f6f6bcdb53; trace=019ddc50-6915-7591-812d-eb79997f9d4f,id=019ddc50-6915-7591-812d-eb79997f9d4f

      [42/50]   ok   5.12s  calls=4  in=23569 (cache   27%)  out= 273  acum=$0.0884

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-6915-7591-812d-eb79997f9d4f,id=019ddc50-6915-7591-812d-eb79997f9d4f; trace=019ddc50-6f20-7e13-8965-9d0cf46cf92b,id=019ddc50-6f20-7e13-8965-9d0cf46cf92b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-6f20-7e13-8965-9d0cf46cf92b,id=019ddc50-6f20-7e13-8965-9d0cf46cf92b; trace=019ddc50-731e-7d81-befa-237d945054e7,id=019ddc50-731e-7d81-befa-237d945054e7; trace=019ddc50-731e-7d81-befa-237d945054e7,id=019ddc50-731e-7d81-befa-237d945054e7; trace=019ddc50-73df-77a3-9e6c-cb3e33a435bf,id=019ddc50-73df-77a3-9e6c-cb3e33a435bf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-73df-77a3-9e6c-cb3e33a435bf,id=019ddc50-73df-77a3-9e6c-cb3e33a435bf; trace=019ddc50-775d-7bc0-8431-dec746d61247,id=019ddc50-775d-7bc0-8431-dec746d61247; trace=019ddc50-775d-7bc0-8431-dec746d61247,id=019ddc50-775d-7bc0-8431-dec746d61247; trace=019ddc50-7830-71e2-9809-995f57c24034,id=019ddc50-7830-71e2-9809-995f57c24034
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-7830-71e2-9809-995f57c24034,id=019ddc50-7830-71e2-9809-995f57c24034; trace=019ddc50-7aae-7053-9ebe-de708247aa54,id=019ddc50-7aae-7053-9ebe-de708247aa54; trace=019ddc50-7aae-7053-9ebe-de708247aa54,id=019ddc50-7aae-7053-9ebe-de708247aa54; trace=019ddc50-7ab1-7763-9b71-975667cbe723,id=019ddc50-7ab1-7763-9b71-975667cbe723
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-7ab1-7763-9b71-975667cbe723,id=019ddc50-7ab1-7763-9b71-975667cbe723; trace=019ddc50-7e11-75e1-abd5-8e3506475eff,id=019ddc50-7e11-75e1-abd5-8e3506475eff; trace=019ddc50-7e11-75e1-abd5-8e3506475eff,id=019ddc50-7e11-75e1-abd5-8e3506475eff; trace=019ddc50-7e14-71b3-bca1-c0b73f91f909,id=019ddc50-7e14-71b3-bca1-c0b73f91f909

      [43/50]   ok   5.15s  calls=5  in=25573 (cache   62%)  out= 263  acum=$0.0953

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-7e14-71b3-bca1-c0b73f91f909,id=019ddc50-7e14-71b3-bca1-c0b73f91f909; trace=019ddc50-8342-7ec1-b4b2-c8f52e982f28,id=019ddc50-8342-7ec1-b4b2-c8f52e982f28
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-8342-7ec1-b4b2-c8f52e982f28,id=019ddc50-8342-7ec1-b4b2-c8f52e982f28; trace=019ddc50-8848-7921-96c9-b295a46d46fb,id=019ddc50-8848-7921-96c9-b295a46d46fb; trace=019ddc50-8848-7921-96c9-b295a46d46fb,id=019ddc50-8848-7921-96c9-b295a46d46fb; trace=019ddc50-8960-7de3-9c85-bfac4b717eea,id=019ddc50-8960-7de3-9c85-bfac4b717eea
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-8960-7de3-9c85-bfac4b717eea,id=019ddc50-8960-7de3-9c85-bfac4b717eea; trace=019ddc50-8ce3-7920-a6a0-f276bbfe1e3c,id=019ddc50-8ce3-7920-a6a0-f276bbfe1e3c; trace=019ddc50-8ce3-7920-a6a0-f276bbfe1e3c,id=019ddc50-8ce3-7920-a6a0-f276bbfe1e3c; trace=019ddc50-8dc4-7593-b0a1-d61fa96ffe85,id=019ddc50-8dc4-7593-b0a1-d61fa96ffe85
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-8dc4-7593-b0a1-d61fa96ffe85,id=019ddc50-8dc4-7593-b0a1-d61fa96ffe85; trace=019ddc50-9184-7392-b6a1-d6613ace02da,id=019ddc50-9184-7392-b6a1-d6613ace02da; trace=019ddc50-9184-7392-b6a1-d6613ace02da,id=019ddc50-9184-7392-b6a1-d6613ace02da; trace=019ddc50-9266-7371-a83d-16311553351b,id=019ddc50-9266-7371-a83d-16311553351b

      [44/50]   ok    5.7s  calls=4  in=22231 (cache   48%)  out= 345  acum=$0.1016

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-9266-7371-a83d-16311553351b,id=019ddc50-9266-7371-a83d-16311553351b; trace=019ddc50-9988-7990-876d-099b7a99e106,id=019ddc50-9988-7990-876d-099b7a99e106
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-9988-7990-876d-099b7a99e106,id=019ddc50-9988-7990-876d-099b7a99e106; trace=019ddc50-9dec-7940-af90-875d3220f309,id=019ddc50-9dec-7940-af90-875d3220f309; trace=019ddc50-9dec-7940-af90-875d3220f309,id=019ddc50-9dec-7940-af90-875d3220f309; trace=019ddc50-9ed7-7440-9955-048afa628ea7,id=019ddc50-9ed7-7440-9955-048afa628ea7

      [45/50]   ok   3.28s  calls=2  in= 6452 (cache   26%)  out= 234  acum=$0.1037

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-9ed7-7440-9955-048afa628ea7,id=019ddc50-9ed7-7440-9955-048afa628ea7; trace=019ddc50-a654-7003-aeed-3f46dc0ddfdd,id=019ddc50-a654-7003-aeed-3f46dc0ddfdd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-a654-7003-aeed-3f46dc0ddfdd,id=019ddc50-a654-7003-aeed-3f46dc0ddfdd; trace=019ddc50-a958-78c2-9d43-67276fdf1abe,id=019ddc50-a958-78c2-9d43-67276fdf1abe; trace=019ddc50-a958-78c2-9d43-67276fdf1abe,id=019ddc50-a958-78c2-9d43-67276fdf1abe; trace=019ddc50-a95a-76e1-8ae4-b98558004523,id=019ddc50-a95a-76e1-8ae4-b98558004523
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-a95a-76e1-8ae4-b98558004523,id=019ddc50-a95a-76e1-8ae4-b98558004523; trace=019ddc50-ac84-7db3-856d-84882ca36be3,id=019ddc50-ac84-7db3-856d-84882ca36be3; trace=019ddc50-ac84-7db3-856d-84882ca36be3,id=019ddc50-ac84-7db3-856d-84882ca36be3; trace=019ddc50-ad54-70d0-9a74-30ef3fb2a616,id=019ddc50-ad54-70d0-9a74-30ef3fb2a616
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-ad54-70d0-9a74-30ef3fb2a616,id=019ddc50-ad54-70d0-9a74-30ef3fb2a616; trace=019ddc50-b184-7123-909e-5c064267b386,id=019ddc50-b184-7123-909e-5c064267b386; trace=019ddc50-b184-7123-909e-5c064267b386,id=019ddc50-b184-7123-909e-5c064267b386; trace=019ddc50-b188-7fd3-90de-2fc1f78f760f,id=019ddc50-b188-7fd3-90de-2fc1f78f760f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-b188-7fd3-90de-2fc1f78f760f,id=019ddc50-b188-7fd3-90de-2fc1f78f760f; trace=019ddc50-b52a-7e42-870a-a0403ed0162c,id=019ddc50-b52a-7e42-870a-a0403ed0162c; trace=019ddc50-b52a-7e42-870a-a0403ed0162c,id=019ddc50-b52a-7e42-870a-a0403ed0162c; trace=019ddc50-b52d-7590-a2b0-a05c52b7c356,id=019ddc50-b52d-7590-a2b0-a05c52b7c356

      [46/50]   ok   5.43s  calls=5  in=15571 (cache   49%)  out= 176  acum=$0.1079

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-b52d-7590-a2b0-a05c52b7c356,id=019ddc50-b52d-7590-a2b0-a05c52b7c356; trace=019ddc50-bb88-7a20-9d28-07540ca47efd,id=019ddc50-bb88-7a20-9d28-07540ca47efd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-bb88-7a20-9d28-07540ca47efd,id=019ddc50-bb88-7a20-9d28-07540ca47efd; trace=019ddc50-bf85-7410-8f69-c8667b74574c,id=019ddc50-bf85-7410-8f69-c8667b74574c; trace=019ddc50-bf85-7410-8f69-c8667b74574c,id=019ddc50-bf85-7410-8f69-c8667b74574c; trace=019ddc50-c03e-7992-a833-aced71ac91be,id=019ddc50-c03e-7992-a833-aced71ac91be

      [47/50]   ok   2.25s  calls=2  in= 4817 (cache   35%)  out= 135  acum=$0.1094

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-c03e-7992-a833-aced71ac91be,id=019ddc50-c03e-7992-a833-aced71ac91be; trace=019ddc50-c458-7a03-ab34-d9739d42d0be,id=019ddc50-c458-7a03-ab34-d9739d42d0be
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-c458-7a03-ab34-d9739d42d0be,id=019ddc50-c458-7a03-ab34-d9739d42d0be; trace=019ddc50-c7e5-7f92-9640-2b01f493aa7d,id=019ddc50-c7e5-7f92-9640-2b01f493aa7d; trace=019ddc50-c7e5-7f92-9640-2b01f493aa7d,id=019ddc50-c7e5-7f92-9640-2b01f493aa7d; trace=019ddc50-c861-7603-a041-d1b879196524,id=019ddc50-c861-7603-a041-d1b879196524

      [48/50]   ok   2.14s  calls=2  in= 5085 (cache    0%)  out= 108  acum=$0.1109

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-c861-7603-a041-d1b879196524,id=019ddc50-c861-7603-a041-d1b879196524; trace=019ddc50-ccb2-7e22-9d23-a347465c6b74,id=019ddc50-ccb2-7e22-9d23-a347465c6b74
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-ccb2-7e22-9d23-a347465c6b74,id=019ddc50-ccb2-7e22-9d23-a347465c6b74; trace=019ddc50-d052-7ce2-aa26-10d0241672ec,id=019ddc50-d052-7ce2-aa26-10d0241672ec; trace=019ddc50-d052-7ce2-aa26-10d0241672ec,id=019ddc50-d052-7ce2-aa26-10d0241672ec; trace=019ddc50-d10c-7fc3-8520-ecfe6e34ebe3,id=019ddc50-d10c-7fc3-8520-ecfe6e34ebe3

      [49/50]   ok   2.73s  calls=2  in= 4673 (cache    0%)  out= 222  acum=$0.1125

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-d10c-7fc3-8520-ecfe6e34ebe3,id=019ddc50-d10c-7fc3-8520-ecfe6e34ebe3; trace=019ddc50-d75b-7bc1-866c-71355c5750bf,id=019ddc50-d75b-7bc1-866c-71355c5750bf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-d75b-7bc1-866c-71355c5750bf,id=019ddc50-d75b-7bc1-866c-71355c5750bf; trace=019ddc50-e5f0-7392-a60b-be6b2f37425b,id=019ddc50-e5f0-7392-a60b-be6b2f37425b; trace=019ddc50-e5f0-7392-a60b-be6b2f37425b,id=019ddc50-e5f0-7392-a60b-be6b2f37425b; trace=019ddc50-e6d7-7bb3-9d63-9c417920904d,id=019ddc50-e6d7-7bb3-9d63-9c417920904d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-e6d7-7bb3-9d63-9c417920904d,id=019ddc50-e6d7-7bb3-9d63-9c417920904d; trace=019ddc50-ea4e-7701-a789-4545e4631317,id=019ddc50-ea4e-7701-a789-4545e4631317; trace=019ddc50-ea4e-7701-a789-4545e4631317,id=019ddc50-ea4e-7701-a789-4545e4631317; trace=019ddc50-eacf-70c2-86eb-3371f2ec1951,id=019ddc50-eacf-70c2-86eb-3371f2ec1951

      [50/50]   ok   7.11s  calls=3  in=13610 (cache   12%)  out= 347  acum=$0.1166
       ✓ ok — salvo em petrobras__openai__gpt-5.4-mini__20260429_235625.xlsx

[run]  deepseek/deepseek-v4-pro × bndes (id=1)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-eacf-70c2-86eb-3371f2ec1951,id=019ddc50-eacf-70c2-86eb-3371f2ec1951; trace=019ddc50-f34d-7c91-bd1b-1ca3a01dd648,id=019ddc50-f34d-7c91-bd1b-1ca3a01dd648
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc50-f34d-7c91-bd1b-1ca3a01dd648,id=019ddc50-f34d-7c91-bd1b-1ca3a01dd648; trace=019ddc51-02d5-76d0-b4fb-bf8962f96600,id=019ddc51-02d5-76d0-b4fb-bf8962f96600; trace=019ddc51-02d5-76d0-b4fb-bf8962f96600,id=019ddc51-02d5-76d0-b4fb-bf8962f96600; trace=019ddc51-02d7-7d93-8cc4-b53763b80bf0,id=019ddc51-02d7-7d93-8cc4-b53763b80bf0; trace=019ddc51-02d7-7d93-8cc4-b53763b80bf0,id=019ddc51-02d7-7d93-8cc4-b53763b80bf0; trace=019ddc51-03a7-7bc0-9db3-b7dcdf74294e,id=019ddc51-03a7-7bc0-9db3-b7dcdf74294e

      [ 1/50]   ok  10.91s  calls=2  in= 8826 (cache   99%)  out= 267  acum=$0.0163

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-03a7-7bc0-9db3-b7dcdf74294e,id=019ddc51-03a7-7bc0-9db3-b7dcdf74294e; trace=019ddc51-1def-7621-aa8b-d9734944b85f,id=019ddc51-1def-7621-aa8b-d9734944b85f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-1def-7621-aa8b-d9734944b85f,id=019ddc51-1def-7621-aa8b-d9734944b85f; trace=019ddc51-2a08-71b3-8c37-84f7263eda28,id=019ddc51-2a08-71b3-8c37-84f7263eda28; trace=019ddc51-2a08-71b3-8c37-84f7263eda28,id=019ddc51-2a08-71b3-8c37-84f7263eda28; trace=019ddc51-2ae1-71b1-ba46-d2581033a412,id=019ddc51-2ae1-71b1-ba46-d2581033a412

      [ 2/50]   ok  11.37s  calls=2  in= 8433 (cache  103%)  out= 271  acum=$0.0319

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-2ae1-71b1-ba46-d2581033a412,id=019ddc51-2ae1-71b1-ba46-d2581033a412; trace=019ddc51-4a55-70c0-9099-6eb8f08f8c3f,id=019ddc51-4a55-70c0-9099-6eb8f08f8c3f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-4a55-70c0-9099-6eb8f08f8c3f,id=019ddc51-4a55-70c0-9099-6eb8f08f8c3f; trace=019ddc51-584b-7161-bbb9-8d4f7b2ec3a7,id=019ddc51-584b-7161-bbb9-8d4f7b2ec3a7; trace=019ddc51-584b-7161-bbb9-8d4f7b2ec3a7,id=019ddc51-584b-7161-bbb9-8d4f7b2ec3a7; trace=019ddc51-58b5-7cc0-aaaa-0f242dbd044e,id=019ddc51-58b5-7cc0-aaaa-0f242dbd044e

      [ 3/50]   ok   9.41s  calls=2  in= 8964 (cache   97%)  out= 217  acum=$0.0483

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-58b5-7cc0-aaaa-0f242dbd044e,id=019ddc51-58b5-7cc0-aaaa-0f242dbd044e; trace=019ddc51-6f19-7513-a694-4880c9c1918b,id=019ddc51-6f19-7513-a694-4880c9c1918b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-6f19-7513-a694-4880c9c1918b,id=019ddc51-6f19-7513-a694-4880c9c1918b; trace=019ddc51-7d20-7a83-8a3e-9c062c9760b8,id=019ddc51-7d20-7a83-8a3e-9c062c9760b8; trace=019ddc51-7d20-7a83-8a3e-9c062c9760b8,id=019ddc51-7d20-7a83-8a3e-9c062c9760b8; trace=019ddc51-7dff-7a13-bf24-0fa0b8e60027,id=019ddc51-7dff-7a13-bf24-0fa0b8e60027

      [ 4/50]   ok   12.8s  calls=2  in= 8213 (cache  106%)  out= 326  acum=$0.0637

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-7dff-7a13-bf24-0fa0b8e60027,id=019ddc51-7dff-7a13-bf24-0fa0b8e60027; trace=019ddc51-a11d-7881-b4fb-eb825845ea30,id=019ddc51-a11d-7881-b4fb-eb825845ea30
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-a11d-7881-b4fb-eb825845ea30,id=019ddc51-a11d-7881-b4fb-eb825845ea30; trace=019ddc51-aef3-7522-a853-6654d4f29a2c,id=019ddc51-aef3-7522-a853-6654d4f29a2c; trace=019ddc51-aef3-7522-a853-6654d4f29a2c,id=019ddc51-aef3-7522-a853-6654d4f29a2c; trace=019ddc51-aef4-70e1-bdb6-36c33df67210,id=019ddc51-aef4-70e1-bdb6-36c33df67210; trace=019ddc51-aef4-70e1-bdb6-36c33df67210,id=019ddc51-aef4-70e1-bdb6-36c33df67210; trace=019ddc51-af4d-7d63-9e88-fd24a570c9b0,id=019ddc51-af4d-7d63-9e88-fd24a570c9b0

      [ 5/50]   ok  16.12s  calls=2  in= 9108 (cache   96%)  out= 445  acum=$0.0811

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-af4d-7d63-9e88-fd24a570c9b0,id=019ddc51-af4d-7d63-9e88-fd24a570c9b0; trace=019ddc51-e014-70e3-9c45-f87f81b45c69,id=019ddc51-e014-70e3-9c45-f87f81b45c69
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-e014-70e3-9c45-f87f81b45c69,id=019ddc51-e014-70e3-9c45-f87f81b45c69; trace=019ddc51-edb3-7282-af18-dea01a654602,id=019ddc51-edb3-7282-af18-dea01a654602; trace=019ddc51-edb3-7282-af18-dea01a654602,id=019ddc51-edb3-7282-af18-dea01a654602; trace=019ddc51-ee7d-7ea0-97ac-c96095d73d6b,id=019ddc51-ee7d-7ea0-97ac-c96095d73d6b

      [ 6/50]   ok  20.65s  calls=2  in= 9010 (cache   97%)  out= 564  acum=$0.0987

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc51-ee7d-7ea0-97ac-c96095d73d6b,id=019ddc51-ee7d-7ea0-97ac-c96095d73d6b; trace=019ddc52-30bc-7d42-985f-6a2cb84c5299,id=019ddc52-30bc-7d42-985f-6a2cb84c5299
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-30bc-7d42-985f-6a2cb84c5299,id=019ddc52-30bc-7d42-985f-6a2cb84c5299; trace=019ddc52-404e-7de0-869b-9d9c582d508a,id=019ddc52-404e-7de0-869b-9d9c582d508a; trace=019ddc52-404e-7de0-869b-9d9c582d508a,id=019ddc52-404e-7de0-869b-9d9c582d508a; trace=019ddc52-40c0-7d62-9a79-201288daa489,id=019ddc52-40c0-7d62-9a79-201288daa489; trace=019ddc52-40c0-7d62-9a79-201288daa489,id=019ddc52-40c0-7d62-9a79-201288daa489; trace=019ddc52-40c1-7e91-9be6-29b5ecfada2b,id=019ddc52-40c1-7e91-9be6-29b5ecfada2b

      [ 7/50]   ok   12.7s  calls=2  in= 9050 (cache   96%)  out= 371  acum=$0.1158

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-40c1-7e91-9be6-29b5ecfada2b,id=019ddc52-40c1-7e91-9be6-29b5ecfada2b; trace=019ddc52-6255-7a12-b36c-f7ad97896905,id=019ddc52-6255-7a12-b36c-f7ad97896905
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-6255-7a12-b36c-f7ad97896905,id=019ddc52-6255-7a12-b36c-f7ad97896905; trace=019ddc52-6f33-7b11-9fbe-36941dc04d34,id=019ddc52-6f33-7b11-9fbe-36941dc04d34; trace=019ddc52-6f33-7b11-9fbe-36941dc04d34,id=019ddc52-6f33-7b11-9fbe-36941dc04d34; trace=019ddc52-700d-79e3-9393-13932359f289,id=019ddc52-700d-79e3-9393-13932359f289

      [ 8/50]   ok  12.51s  calls=2  in= 8301 (cache  105%)  out= 331  acum=$0.1314

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-700d-79e3-9393-13932359f289,id=019ddc52-700d-79e3-9393-13932359f289; trace=019ddc52-9337-7860-8886-921e33fd1ba5,id=019ddc52-9337-7860-8886-921e33fd1ba5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-9337-7860-8886-921e33fd1ba5,id=019ddc52-9337-7860-8886-921e33fd1ba5; trace=019ddc52-a04c-7ec0-94f5-e82cc2b6533f,id=019ddc52-a04c-7ec0-94f5-e82cc2b6533f; trace=019ddc52-a04c-7ec0-94f5-e82cc2b6533f,id=019ddc52-a04c-7ec0-94f5-e82cc2b6533f; trace=019ddc52-a131-7b42-9cff-8fe355e434e7,id=019ddc52-a131-7b42-9cff-8fe355e434e7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-a131-7b42-9cff-8fe355e434e7,id=019ddc52-a131-7b42-9cff-8fe355e434e7; trace=019ddc52-b57f-76a2-9bb0-24c5a873ad54,id=019ddc52-b57f-76a2-9bb0-24c5a873ad54; trace=019ddc52-b57f-76a2-9bb0-24c5a873ad54,id=019ddc52-b57f-76a2-9bb0-24c5a873ad54; trace=019ddc52-b656-7c53-81f1-225abbf15442,id=019ddc52-b656-7c53-81f1-225abbf15442
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-b656-7c53-81f1-225abbf15442,id=019ddc52-b656-7c53-81f1-225abbf15442; trace=019ddc52-c711-7570-b24e-c20db4b695e2,id=019ddc52-c711-7570-b24e-c20db4b695e2; trace=019ddc52-c711-7570-b24e-c20db4b695e2,id=019ddc52-c711-7570-b24e-c20db4b695e2; trace=019ddc52-c715-7b43-9b9e-88bb1c86e4e7,id=019ddc52-c715-7b43-9b9e-88bb1c86e4e7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-c715-7b43-9b9e-88bb1c86e4e7,id=019ddc52-c715-7b43-9b9e-88bb1c86e4e7; trace=019ddc52-e64c-7612-be4d-7b6fd4496985,id=019ddc52-e64c-7612-be4d-7b6fd4496985; trace=019ddc52-e64c-7612-be4d-7b6fd4496985,id=019ddc52-e64c-7612-be4d-7b6fd4496985; trace=019ddc52-e6ca-7352-91f5-1afea127362e,id=019ddc52-e6ca-7352-91f5-1afea127362e

      [ 9/50]   ok   35.3s  calls=5  in=54662 (cache  136%)  out= 938  acum=$0.2297

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc52-e6ca-7352-91f5-1afea127362e,id=019ddc52-e6ca-7352-91f5-1afea127362e; trace=019ddc53-1d1b-7391-b9ca-be323be7e46e,id=019ddc53-1d1b-7391-b9ca-be323be7e46e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-1d1b-7391-b9ca-be323be7e46e,id=019ddc53-1d1b-7391-b9ca-be323be7e46e; trace=019ddc53-2c4b-7c61-a940-8c7dba7f2fe2,id=019ddc53-2c4b-7c61-a940-8c7dba7f2fe2; trace=019ddc53-2c4b-7c61-a940-8c7dba7f2fe2,id=019ddc53-2c4b-7c61-a940-8c7dba7f2fe2; trace=019ddc53-2d34-7283-8f10-b092bce71217,id=019ddc53-2d34-7283-8f10-b092bce71217

      [10/50]   ok  17.71s  calls=2  in= 8500 (cache  102%)  out= 538  acum=$0.2464

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-2d34-7283-8f10-b092bce71217,id=019ddc53-2d34-7283-8f10-b092bce71217; trace=019ddc53-624b-7492-af97-01d0f987ff8d,id=019ddc53-624b-7492-af97-01d0f987ff8d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-624b-7492-af97-01d0f987ff8d,id=019ddc53-624b-7492-af97-01d0f987ff8d; trace=019ddc53-7048-72f2-84ae-b346fec3f03d,id=019ddc53-7048-72f2-84ae-b346fec3f03d; trace=019ddc53-7048-72f2-84ae-b346fec3f03d,id=019ddc53-7048-72f2-84ae-b346fec3f03d; trace=019ddc53-7115-7e50-820b-ed35d0a90bc4,id=019ddc53-7115-7e50-820b-ed35d0a90bc4

      [11/50]   ok  10.34s  calls=2  in= 8526 (cache  102%)  out= 248  acum=$0.2621

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-7115-7e50-820b-ed35d0a90bc4,id=019ddc53-7115-7e50-820b-ed35d0a90bc4; trace=019ddc53-8aae-7062-9ce6-10e31db7ebc4,id=019ddc53-8aae-7062-9ce6-10e31db7ebc4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-8aae-7062-9ce6-10e31db7ebc4,id=019ddc53-8aae-7062-9ce6-10e31db7ebc4; trace=019ddc53-9913-7242-a2a9-f5e98c861e07,id=019ddc53-9913-7242-a2a9-f5e98c861e07; trace=019ddc53-9913-7242-a2a9-f5e98c861e07,id=019ddc53-9913-7242-a2a9-f5e98c861e07; trace=019ddc53-996d-7e83-8be6-e42799e776f6,id=019ddc53-996d-7e83-8be6-e42799e776f6

      [12/50]   ok  20.07s  calls=2  in= 8938 (cache   97%)  out= 580  acum=$0.2797

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-996d-7e83-8be6-e42799e776f6,id=019ddc53-996d-7e83-8be6-e42799e776f6; trace=019ddc53-d914-7d20-9a96-766ade537de1,id=019ddc53-d914-7d20-9a96-766ade537de1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-d914-7d20-9a96-766ade537de1,id=019ddc53-d914-7d20-9a96-766ade537de1; trace=019ddc53-e5d5-7c91-bcf1-21ee52958d21,id=019ddc53-e5d5-7c91-bcf1-21ee52958d21; trace=019ddc53-e5d5-7c91-bcf1-21ee52958d21,id=019ddc53-e5d5-7c91-bcf1-21ee52958d21; trace=019ddc53-e634-7c02-9a59-a842139a8946,id=019ddc53-e634-7c02-9a59-a842139a8946

      [13/50]   ok   7.37s  calls=2  in= 9266 (cache   94%)  out= 159  acum=$0.2963

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-e634-7c02-9a59-a842139a8946,id=019ddc53-e634-7c02-9a59-a842139a8946; trace=019ddc53-f5de-71f0-a59c-8e4fc23ff5c2,id=019ddc53-f5de-71f0-a59c-8e4fc23ff5c2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc53-f5de-71f0-a59c-8e4fc23ff5c2,id=019ddc53-f5de-71f0-a59c-8e4fc23ff5c2; trace=019ddc54-0376-7a13-9fbe-68dff611b992,id=019ddc54-0376-7a13-9fbe-68dff611b992; trace=019ddc54-0376-7a13-9fbe-68dff611b992,id=019ddc54-0376-7a13-9fbe-68dff611b992; trace=019ddc54-044b-7b20-b488-b6a18b052b32,id=019ddc54-044b-7b20-b488-b6a18b052b32

      [14/50]   ok  14.85s  calls=2  in= 8503 (cache  102%)  out= 378  acum=$0.3124

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-044b-7b20-b488-b6a18b052b32,id=019ddc54-044b-7b20-b488-b6a18b052b32; trace=019ddc54-2fe0-74d2-85af-b26fc1fb5371,id=019ddc54-2fe0-74d2-85af-b26fc1fb5371
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-2fe0-74d2-85af-b26fc1fb5371,id=019ddc54-2fe0-74d2-85af-b26fc1fb5371; trace=019ddc54-3d75-7581-a6f7-c35c6c20e9bf,id=019ddc54-3d75-7581-a6f7-c35c6c20e9bf; trace=019ddc54-3d75-7581-a6f7-c35c6c20e9bf,id=019ddc54-3d75-7581-a6f7-c35c6c20e9bf; trace=019ddc54-3e50-7393-9c5b-5c7be62034d3,id=019ddc54-3e50-7393-9c5b-5c7be62034d3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-3e50-7393-9c5b-5c7be62034d3,id=019ddc54-3e50-7393-9c5b-5c7be62034d3; trace=019ddc54-5d10-7012-aca3-85a2aa7d11de,id=019ddc54-5d10-7012-aca3-85a2aa7d11de; trace=019ddc54-5d10-7012-aca3-85a2aa7d11de,id=019ddc54-5d10-7012-aca3-85a2aa7d11de; trace=019ddc54-5d7d-71a3-9cf3-61be35a4d7c1,id=019ddc54-5d7d-71a3-9cf3-61be35a4d7c1; trace=019ddc54-5d7d-71a3-9cf3-61be35a4d7c1,id=019ddc54-5d7d-71a3-9cf3-61be35a4d7c1; trace=019ddc54-5d7f-7193-9bed-eb0246fadfc2,id=019ddc54-5d7f-7193-9bed-eb0246fadfc2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-5d7f-7193-9bed-eb0246fadfc2,id=019ddc54-5d7f-7193-9bed-eb0246fadfc2; trace=019ddc54-7a41-7742-be46-5ccb379e2111,id=019ddc54-7a41-7742-be46-5ccb379e2111; trace=019ddc54-7a41-7742-be46-5ccb379e2111,id=019ddc54-7a41-7742-be46-5ccb379e2111; trace=019ddc54-7a44-75d1-aef7-01849f1758f4,id=019ddc54-7a44-75d1-aef7-01849f1758f4; trace=019ddc54-7a44-75d1-aef7-01849f1758f4,id=019ddc54-7a44-75d1-aef7-01849f1758f4; trace=019ddc54-7a46-7b42-99d7-2fe12641dace,id=019ddc54-7a46-7b42-99d7-2fe12641dace
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-7a46-7b42-99d7-2fe12641dace,id=019ddc54-7a46-7b42-99d7-2fe12641dace; trace=019ddc54-9b05-7793-9cf1-9701a62d1c95,id=019ddc54-9b05-7793-9cf1-9701a62d1c95; trace=019ddc54-9b05-7793-9cf1-9701a62d1c95,id=019ddc54-9b05-7793-9cf1-9701a62d1c95; trace=019ddc54-9b70-7380-9844-0e8f72d846f1,id=019ddc54-9b70-7380-9844-0e8f72d846f1

      [15/50]   ok  40.81s  calls=5  in=60015 (cache  134%)  out= 970  acum=$0.4202

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-9b70-7380-9844-0e8f72d846f1,id=019ddc54-9b70-7380-9844-0e8f72d846f1; trace=019ddc54-cf50-7db2-9d18-cd5b7f65e013,id=019ddc54-cf50-7db2-9d18-cd5b7f65e013
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-cf50-7db2-9d18-cd5b7f65e013,id=019ddc54-cf50-7db2-9d18-cd5b7f65e013; trace=019ddc54-dc37-73e0-87ff-868f6f0468bb,id=019ddc54-dc37-73e0-87ff-868f6f0468bb; trace=019ddc54-dc37-73e0-87ff-868f6f0468bb,id=019ddc54-dc37-73e0-87ff-868f6f0468bb; trace=019ddc54-dc3a-7e22-9fd6-6419106af5c3,id=019ddc54-dc3a-7e22-9fd6-6419106af5c3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-dc3a-7e22-9fd6-6419106af5c3,id=019ddc54-dc3a-7e22-9fd6-6419106af5c3; trace=019ddc54-eca7-70f0-8415-5422d6d48e31,id=019ddc54-eca7-70f0-8415-5422d6d48e31; trace=019ddc54-eca7-70f0-8415-5422d6d48e31,id=019ddc54-eca7-70f0-8415-5422d6d48e31; trace=019ddc54-eca9-78d3-a160-cd676f6957f4,id=019ddc54-eca9-78d3-a160-cd676f6957f4

      [16/50]   ok  14.37s  calls=3  in= 8945 (cache  160%)  out= 318  acum=$0.4369

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc54-eca9-78d3-a160-cd676f6957f4,id=019ddc54-eca9-78d3-a160-cd676f6957f4; trace=019ddc55-0773-77d2-b587-7bc0f65db46c,id=019ddc55-0773-77d2-b587-7bc0f65db46c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-0773-77d2-b587-7bc0f65db46c,id=019ddc55-0773-77d2-b587-7bc0f65db46c; trace=019ddc55-15d3-79b3-8333-14db4a1eee6a,id=019ddc55-15d3-79b3-8333-14db4a1eee6a; trace=019ddc55-15d3-79b3-8333-14db4a1eee6a,id=019ddc55-15d3-79b3-8333-14db4a1eee6a; trace=019ddc55-1692-7c31-9bdd-e11c187e2ce6,id=019ddc55-1692-7c31-9bdd-e11c187e2ce6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-1692-7c31-9bdd-e11c187e2ce6,id=019ddc55-1692-7c31-9bdd-e11c187e2ce6; trace=019ddc55-21ce-77b0-971b-4129ec2474f4,id=019ddc55-21ce-77b0-971b-4129ec2474f4; trace=019ddc55-21ce-77b0-971b-4129ec2474f4,id=019ddc55-21ce-77b0-971b-4129ec2474f4; trace=019ddc55-21cf-79c3-b894-cf1f6394bdf5,id=019ddc55-21cf-79c3-b894-cf1f6394bdf5

      [17/50]   ok  23.45s  calls=3  in=15674 (cache  140%)  out= 673  acum=$0.4665

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-21cf-79c3-b894-cf1f6394bdf5,id=019ddc55-21cf-79c3-b894-cf1f6394bdf5; trace=019ddc55-6308-7552-ab14-b0cbee33c1e7,id=019ddc55-6308-7552-ab14-b0cbee33c1e7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-6308-7552-ab14-b0cbee33c1e7,id=019ddc55-6308-7552-ab14-b0cbee33c1e7; trace=019ddc55-707f-7692-98eb-a84d14bebf63,id=019ddc55-707f-7692-98eb-a84d14bebf63; trace=019ddc55-707f-7692-98eb-a84d14bebf63,id=019ddc55-707f-7692-98eb-a84d14bebf63; trace=019ddc55-70e7-7ba1-881a-0c65749b40ab,id=019ddc55-70e7-7ba1-881a-0c65749b40ab

      [18/50]   ok   21.5s  calls=2  in= 9152 (cache   95%)  out= 605  acum=$0.4846

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-70e7-7ba1-881a-0c65749b40ab,id=019ddc55-70e7-7ba1-881a-0c65749b40ab; trace=019ddc55-b700-7451-8614-9b0470826f13,id=019ddc55-b700-7451-8614-9b0470826f13
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-b700-7451-8614-9b0470826f13,id=019ddc55-b700-7451-8614-9b0470826f13; trace=019ddc55-c4fe-7ee3-a01a-52c3d04687d4,id=019ddc55-c4fe-7ee3-a01a-52c3d04687d4; trace=019ddc55-c4fe-7ee3-a01a-52c3d04687d4,id=019ddc55-c4fe-7ee3-a01a-52c3d04687d4; trace=019ddc55-c567-77b0-955a-fa1caa606d5e,id=019ddc55-c567-77b0-955a-fa1caa606d5e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-c567-77b0-955a-fa1caa606d5e,id=019ddc55-c567-77b0-955a-fa1caa606d5e; trace=019ddc55-dc3a-74e3-b0b5-bf9d9f68b758,id=019ddc55-dc3a-74e3-b0b5-bf9d9f68b758; trace=019ddc55-dc3a-74e3-b0b5-bf9d9f68b758,id=019ddc55-dc3a-74e3-b0b5-bf9d9f68b758; trace=019ddc55-dcb1-7d62-861b-a812018b3294,id=019ddc55-dcb1-7d62-861b-a812018b3294

      [19/50]   ok  19.05s  calls=3  in=19553 (cache  113%)  out= 455  acum=$0.5202

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc55-dcb1-7d62-861b-a812018b3294,id=019ddc55-dcb1-7d62-861b-a812018b3294; trace=019ddc56-016f-7042-a387-0506dca5ce0a,id=019ddc56-016f-7042-a387-0506dca5ce0a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-016f-7042-a387-0506dca5ce0a,id=019ddc56-016f-7042-a387-0506dca5ce0a; trace=019ddc56-0ee2-76e3-9ff0-e99f3270963b,id=019ddc56-0ee2-76e3-9ff0-e99f3270963b; trace=019ddc56-0ee2-76e3-9ff0-e99f3270963b,id=019ddc56-0ee2-76e3-9ff0-e99f3270963b; trace=019ddc56-0fa3-7cd3-8231-0a06dda1ff2b,id=019ddc56-0fa3-7cd3-8231-0a06dda1ff2b

      [20/50]   ok  10.23s  calls=2  in= 8592 (cache  101%)  out= 241  acum=$0.5360

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-0fa3-7cd3-8231-0a06dda1ff2b,id=019ddc56-0fa3-7cd3-8231-0a06dda1ff2b; trace=019ddc56-2965-74c1-b9b5-10fad946cf81,id=019ddc56-2965-74c1-b9b5-10fad946cf81
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-2965-74c1-b9b5-10fad946cf81,id=019ddc56-2965-74c1-b9b5-10fad946cf81; trace=019ddc56-3a2e-7811-8962-a890f360c95b,id=019ddc56-3a2e-7811-8962-a890f360c95b; trace=019ddc56-3a2e-7811-8962-a890f360c95b,id=019ddc56-3a2e-7811-8962-a890f360c95b; trace=019ddc56-3a90-7c10-a24e-129005471818,id=019ddc56-3a90-7c10-a24e-129005471818

      [21/50]   ok   21.0s  calls=2  in= 8931 (cache   97%)  out= 549  acum=$0.5534

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-3a90-7c10-a24e-129005471818,id=019ddc56-3a90-7c10-a24e-129005471818; trace=019ddc56-7b6d-76f3-8398-106fa0c58b0e,id=019ddc56-7b6d-76f3-8398-106fa0c58b0e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-7b6d-76f3-8398-106fa0c58b0e,id=019ddc56-7b6d-76f3-8398-106fa0c58b0e; trace=019ddc56-8bcd-71a0-bd24-9bc4644b3563,id=019ddc56-8bcd-71a0-bd24-9bc4644b3563; trace=019ddc56-8bcd-71a0-bd24-9bc4644b3563,id=019ddc56-8bcd-71a0-bd24-9bc4644b3563; trace=019ddc56-8c48-7652-9573-bf3cfaaab646,id=019ddc56-8c48-7652-9573-bf3cfaaab646
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-8c48-7652-9573-bf3cfaaab646,id=019ddc56-8c48-7652-9573-bf3cfaaab646; trace=019ddc56-a2f9-7653-a168-8bdd627a1d23,id=019ddc56-a2f9-7653-a168-8bdd627a1d23; trace=019ddc56-a2f9-7653-a168-8bdd627a1d23,id=019ddc56-a2f9-7653-a168-8bdd627a1d23; trace=019ddc56-a306-7340-9341-93fd7a4fd21d,id=019ddc56-a306-7340-9341-93fd7a4fd21d

      [22/50]   ok  28.56s  calls=3  in=21070 (cache  100%)  out= 734  acum=$0.5926

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-a306-7340-9341-93fd7a4fd21d,id=019ddc56-a306-7340-9341-93fd7a4fd21d; trace=019ddc56-eafe-74e1-bbb8-4a63e3a00e4b,id=019ddc56-eafe-74e1-bbb8-4a63e3a00e4b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-eafe-74e1-bbb8-4a63e3a00e4b,id=019ddc56-eafe-74e1-bbb8-4a63e3a00e4b; trace=019ddc56-faa7-71c2-a169-739dda0f76fa,id=019ddc56-faa7-71c2-a169-739dda0f76fa; trace=019ddc56-faa7-71c2-a169-739dda0f76fa,id=019ddc56-faa7-71c2-a169-739dda0f76fa; trace=019ddc56-fb03-7091-a19a-88874c7f772b,id=019ddc56-fb03-7091-a19a-88874c7f772b

      [23/50]   ok   12.9s  calls=2  in= 8847 (cache   98%)  out= 271  acum=$0.6090

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc56-fb03-7091-a19a-88874c7f772b,id=019ddc56-fb03-7091-a19a-88874c7f772b; trace=019ddc57-1d61-7532-a4b0-219bde94a8b4,id=019ddc57-1d61-7532-a4b0-219bde94a8b4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-1d61-7532-a4b0-219bde94a8b4,id=019ddc57-1d61-7532-a4b0-219bde94a8b4; trace=019ddc57-2d65-7493-9936-8287e334486e,id=019ddc57-2d65-7493-9936-8287e334486e; trace=019ddc57-2d65-7493-9936-8287e334486e,id=019ddc57-2d65-7493-9936-8287e334486e; trace=019ddc57-2dc0-7c63-8227-509884b81416,id=019ddc57-2dc0-7c63-8227-509884b81416

      [24/50]   ok  14.45s  calls=2  in= 7927 (cache  110%)  out= 391  acum=$0.6241

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-2dc0-7c63-8227-509884b81416,id=019ddc57-2dc0-7c63-8227-509884b81416; trace=019ddc57-55cf-7550-beff-34c56fdae098,id=019ddc57-55cf-7550-beff-34c56fdae098
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-55cf-7550-beff-34c56fdae098,id=019ddc57-55cf-7550-beff-34c56fdae098; trace=019ddc57-6114-7322-8d23-bb5b70a3f05c,id=019ddc57-6114-7322-8d23-bb5b70a3f05c; trace=019ddc57-6114-7322-8d23-bb5b70a3f05c,id=019ddc57-6114-7322-8d23-bb5b70a3f05c; trace=019ddc57-61e5-7e53-9d86-424b9655daf4,id=019ddc57-61e5-7e53-9d86-424b9655daf4

      [25/50]   ok   7.36s  calls=2  in= 8604 (cache  101%)  out= 134  acum=$0.6396

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-61e5-7e53-9d86-424b9655daf4,id=019ddc57-61e5-7e53-9d86-424b9655daf4; trace=019ddc57-7293-72c0-b085-b131ad1b3bfb,id=019ddc57-7293-72c0-b085-b131ad1b3bfb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-7293-72c0-b085-b131ad1b3bfb,id=019ddc57-7293-72c0-b085-b131ad1b3bfb; trace=019ddc57-8168-7d42-9f0d-366154d4c907,id=019ddc57-8168-7d42-9f0d-366154d4c907; trace=019ddc57-8168-7d42-9f0d-366154d4c907,id=019ddc57-8168-7d42-9f0d-366154d4c907; trace=019ddc57-81cc-7ed1-81a0-4e7110274431,id=019ddc57-81cc-7ed1-81a0-4e7110274431
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-81cc-7ed1-81a0-4e7110274431,id=019ddc57-81cc-7ed1-81a0-4e7110274431; trace=019ddc57-9c32-7233-a138-22d2bcecac67,id=019ddc57-9c32-7233-a138-22d2bcecac67; trace=019ddc57-9c32-7233-a138-22d2bcecac67,id=019ddc57-9c32-7233-a138-22d2bcecac67; trace=019ddc57-9caa-7723-982d-02b037be1846,id=019ddc57-9caa-7723-982d-02b037be1846; trace=019ddc57-9caa-7723-982d-02b037be1846,id=019ddc57-9caa-7723-982d-02b037be1846; trace=019ddc57-9cac-7f42-8a54-7d9e96663f5c,id=019ddc57-9cac-7f42-8a54-7d9e96663f5c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-9cac-7f42-8a54-7d9e96663f5c,id=019ddc57-9cac-7f42-8a54-7d9e96663f5c; trace=019ddc57-b299-7dc3-85d8-672ca62181d2,id=019ddc57-b299-7dc3-85d8-672ca62181d2; trace=019ddc57-b299-7dc3-85d8-672ca62181d2,id=019ddc57-b299-7dc3-85d8-672ca62181d2; trace=019ddc57-b29c-7690-9bc8-ee4b94b71122,id=019ddc57-b29c-7690-9bc8-ee4b94b71122

      [26/50]   ok  24.38s  calls=4  in=33353 (cache  139%)  out= 589  acum=$0.6996

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-b29c-7690-9bc8-ee4b94b71122,id=019ddc57-b29c-7690-9bc8-ee4b94b71122; trace=019ddc57-d1cd-7250-b75c-0406f0ceb44b,id=019ddc57-d1cd-7250-b75c-0406f0ceb44b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-d1cd-7250-b75c-0406f0ceb44b,id=019ddc57-d1cd-7250-b75c-0406f0ceb44b; trace=019ddc57-de95-71c1-b4d6-2710934ae15f,id=019ddc57-de95-71c1-b4d6-2710934ae15f; trace=019ddc57-de95-71c1-b4d6-2710934ae15f,id=019ddc57-de95-71c1-b4d6-2710934ae15f; trace=019ddc57-deff-73a3-b120-8b2d9013ae3d,id=019ddc57-deff-73a3-b120-8b2d9013ae3d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-deff-73a3-b120-8b2d9013ae3d,id=019ddc57-deff-73a3-b120-8b2d9013ae3d; trace=019ddc57-f8fd-7500-9e7a-bb937f315022,id=019ddc57-f8fd-7500-9e7a-bb937f315022; trace=019ddc57-f8fd-7500-9e7a-bb937f315022,id=019ddc57-f8fd-7500-9e7a-bb937f315022; trace=019ddc57-f969-7160-98dd-788ec656d80c,id=019ddc57-f969-7160-98dd-788ec656d80c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc57-f969-7160-98dd-788ec656d80c,id=019ddc57-f969-7160-98dd-788ec656d80c; trace=019ddc58-09bb-7c70-99ab-d526856ce800,id=019ddc58-09bb-7c70-99ab-d526856ce800; trace=019ddc58-09bb-7c70-99ab-d526856ce800,id=019ddc58-09bb-7c70-99ab-d526856ce800; trace=019ddc58-09be-7fa2-b846-268744ad4f5a,id=019ddc58-09be-7fa2-b846-268744ad4f5a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-09be-7fa2-b846-268744ad4f5a,id=019ddc58-09be-7fa2-b846-268744ad4f5a; trace=019ddc58-1f59-7211-9dba-ba2bb11942ed,id=019ddc58-1f59-7211-9dba-ba2bb11942ed; trace=019ddc58-1f59-7211-9dba-ba2bb11942ed,id=019ddc58-1f59-7211-9dba-ba2bb11942ed; trace=019ddc58-1f5c-7033-aab5-28b7c93b42ab,id=019ddc58-1f5c-7033-aab5-28b7c93b42ab; trace=019ddc58-1f5c-7033-aab5-28b7c93b42ab,id=019ddc58-1f5c-7033-aab5-28b7c93b42ab; trace=019ddc58-1f5e-78e2-b312-4afcc0370d47,id=019ddc58-1f5e-78e2-b312-4afcc0370d47

      [27/50]   ok   30.1s  calls=5  in=44604 (cache  152%)  out= 712  acum=$0.7797

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-1f5e-78e2-b312-4afcc0370d47,id=019ddc58-1f5e-78e2-b312-4afcc0370d47; trace=019ddc58-4764-7e00-9cf4-ff754e8a5f29,id=019ddc58-4764-7e00-9cf4-ff754e8a5f29
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-4764-7e00-9cf4-ff754e8a5f29,id=019ddc58-4764-7e00-9cf4-ff754e8a5f29; trace=019ddc58-55c6-7420-8157-110f6be3c9b0,id=019ddc58-55c6-7420-8157-110f6be3c9b0; trace=019ddc58-55c6-7420-8157-110f6be3c9b0,id=019ddc58-55c6-7420-8157-110f6be3c9b0; trace=019ddc58-5625-7c91-8a46-c1db3bb4698e,id=019ddc58-5625-7c91-8a46-c1db3bb4698e

      [28/50]   ok  22.57s  calls=2  in= 8846 (cache   98%)  out= 660  acum=$0.7974

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-5625-7c91-8a46-c1db3bb4698e,id=019ddc58-5625-7c91-8a46-c1db3bb4698e; trace=019ddc58-9f93-7fc3-b646-2c4980f6764a,id=019ddc58-9f93-7fc3-b646-2c4980f6764a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-9f93-7fc3-b646-2c4980f6764a,id=019ddc58-9f93-7fc3-b646-2c4980f6764a; trace=019ddc58-adca-7ec2-ba86-d9066075e0b2,id=019ddc58-adca-7ec2-ba86-d9066075e0b2; trace=019ddc58-adca-7ec2-ba86-d9066075e0b2,id=019ddc58-adca-7ec2-ba86-d9066075e0b2; trace=019ddc58-ae2c-7282-b9c8-d525110863d0,id=019ddc58-ae2c-7282-b9c8-d525110863d0

      [29/50]   ok   8.86s  calls=2  in= 8383 (cache  104%)  out= 198  acum=$0.8127

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-ae2c-7282-b9c8-d525110863d0,id=019ddc58-ae2c-7282-b9c8-d525110863d0; trace=019ddc58-c22e-7801-9c8e-ea6d1ac56ccc,id=019ddc58-c22e-7801-9c8e-ea6d1ac56ccc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-c22e-7801-9c8e-ea6d1ac56ccc,id=019ddc58-c22e-7801-9c8e-ea6d1ac56ccc; trace=019ddc58-d08e-7002-8fd8-0de5535cfd64,id=019ddc58-d08e-7002-8fd8-0de5535cfd64; trace=019ddc58-d08e-7002-8fd8-0de5535cfd64,id=019ddc58-d08e-7002-8fd8-0de5535cfd64; trace=019ddc58-d0f1-7653-b210-cd4d754d87c6,id=019ddc58-d0f1-7653-b210-cd4d754d87c6

      [30/50]   ok  19.15s  calls=2  in= 9306 (cache   94%)  out= 517  acum=$0.8307

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc58-d0f1-7653-b210-cd4d754d87c6,id=019ddc58-d0f1-7653-b210-cd4d754d87c6; trace=019ddc59-0cfb-7172-a186-a31bf3a83192,id=019ddc59-0cfb-7172-a186-a31bf3a83192
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-0cfb-7172-a186-a31bf3a83192,id=019ddc59-0cfb-7172-a186-a31bf3a83192; trace=019ddc59-19c5-70d0-a000-9392903aadde,id=019ddc59-19c5-70d0-a000-9392903aadde; trace=019ddc59-19c5-70d0-a000-9392903aadde,id=019ddc59-19c5-70d0-a000-9392903aadde; trace=019ddc59-1aa2-7920-9af4-5b514bf43f75,id=019ddc59-1aa2-7920-9af4-5b514bf43f75

      [31/50]   ok  14.44s  calls=2  in= 9346 (cache   93%)  out= 360  acum=$0.8482

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-1aa2-7920-9af4-5b514bf43f75,id=019ddc59-1aa2-7920-9af4-5b514bf43f75; trace=019ddc59-4561-7b70-8f8a-2b8cac64773f,id=019ddc59-4561-7b70-8f8a-2b8cac64773f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-4561-7b70-8f8a-2b8cac64773f,id=019ddc59-4561-7b70-8f8a-2b8cac64773f; trace=019ddc59-5290-7b11-90c4-5be444cc83f6,id=019ddc59-5290-7b11-90c4-5be444cc83f6; trace=019ddc59-5290-7b11-90c4-5be444cc83f6,id=019ddc59-5290-7b11-90c4-5be444cc83f6; trace=019ddc59-52ee-71d3-a1b2-9ca63943b24e,id=019ddc59-52ee-71d3-a1b2-9ca63943b24e

      [32/50]   ok  12.18s  calls=2  in= 9141 (cache   95%)  out= 309  acum=$0.8652

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-52ee-71d3-a1b2-9ca63943b24e,id=019ddc59-52ee-71d3-a1b2-9ca63943b24e; trace=019ddc59-74f8-7150-8aea-93b72132510d,id=019ddc59-74f8-7150-8aea-93b72132510d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-74f8-7150-8aea-93b72132510d,id=019ddc59-74f8-7150-8aea-93b72132510d; trace=019ddc59-814b-7730-a0f8-766e461b658e,id=019ddc59-814b-7730-a0f8-766e461b658e; trace=019ddc59-814b-7730-a0f8-766e461b658e,id=019ddc59-814b-7730-a0f8-766e461b658e; trace=019ddc59-821c-7d63-91f6-c4721766d1c1,id=019ddc59-821c-7d63-91f6-c4721766d1c1

      [33/50]   ok  13.21s  calls=2  in= 8752 (cache   99%)  out= 335  acum=$0.8816

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-821c-7d63-91f6-c4721766d1c1,id=019ddc59-821c-7d63-91f6-c4721766d1c1; trace=019ddc59-a891-71f3-a4d7-4ff82abfdf67,id=019ddc59-a891-71f3-a4d7-4ff82abfdf67
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-a891-71f3-a4d7-4ff82abfdf67,id=019ddc59-a891-71f3-a4d7-4ff82abfdf67; trace=019ddc59-b666-7f43-8d06-efd382a516b8,id=019ddc59-b666-7f43-8d06-efd382a516b8; trace=019ddc59-b666-7f43-8d06-efd382a516b8,id=019ddc59-b666-7f43-8d06-efd382a516b8; trace=019ddc59-b745-7233-8f2b-8e69eaea58cb,id=019ddc59-b745-7233-8f2b-8e69eaea58cb

      [34/50]   ok   8.18s  calls=2  in= 9210 (cache   95%)  out= 130  acum=$0.8980

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-b745-7233-8f2b-8e69eaea58cb,id=019ddc59-b745-7233-8f2b-8e69eaea58cb; trace=019ddc59-c889-7220-83dd-4c4d6cc0c3b4,id=019ddc59-c889-7220-83dd-4c4d6cc0c3b4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-c889-7220-83dd-4c4d6cc0c3b4,id=019ddc59-c889-7220-83dd-4c4d6cc0c3b4; trace=019ddc59-d6f4-7263-afc4-3cd49e3abec4,id=019ddc59-d6f4-7263-afc4-3cd49e3abec4; trace=019ddc59-d6f4-7263-afc4-3cd49e3abec4,id=019ddc59-d6f4-7263-afc4-3cd49e3abec4; trace=019ddc59-d7c6-7710-9640-f4194f5e465c,id=019ddc59-d7c6-7710-9640-f4194f5e465c

      [35/50]   ok  13.42s  calls=2  in= 9761 (cache   89%)  out= 306  acum=$0.9161

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-d7c6-7710-9640-f4194f5e465c,id=019ddc59-d7c6-7710-9640-f4194f5e465c; trace=019ddc59-fcf6-7a93-8c05-9196349f9c8f,id=019ddc59-fcf6-7a93-8c05-9196349f9c8f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc59-fcf6-7a93-8c05-9196349f9c8f,id=019ddc59-fcf6-7a93-8c05-9196349f9c8f; trace=019ddc5a-0af1-7c83-88d9-80cc7a327f58,id=019ddc5a-0af1-7c83-88d9-80cc7a327f58; trace=019ddc5a-0af1-7c83-88d9-80cc7a327f58,id=019ddc5a-0af1-7c83-88d9-80cc7a327f58; trace=019ddc5a-0b87-7f83-9f4d-4d1ed2072f27,id=019ddc5a-0b87-7f83-9f4d-4d1ed2072f27

      [36/50]   ok  13.44s  calls=2  in= 8717 (cache  100%)  out= 344  acum=$0.9325

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-0b87-7f83-9f4d-4d1ed2072f27,id=019ddc5a-0b87-7f83-9f4d-4d1ed2072f27; trace=019ddc5a-3173-7dd3-acf7-398c1a910e55,id=019ddc5a-3173-7dd3-acf7-398c1a910e55
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-3173-7dd3-acf7-398c1a910e55,id=019ddc5a-3173-7dd3-acf7-398c1a910e55; trace=019ddc5a-4090-7ba3-b742-93d219d96ee0,id=019ddc5a-4090-7ba3-b742-93d219d96ee0; trace=019ddc5a-4090-7ba3-b742-93d219d96ee0,id=019ddc5a-4090-7ba3-b742-93d219d96ee0; trace=019ddc5a-40f9-7f12-bfc6-81a370a88a5e,id=019ddc5a-40f9-7f12-bfc6-81a370a88a5e

      [37/50]   ok   22.2s  calls=2  in= 9860 (cache   88%)  out= 619  acum=$0.9518

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-40f9-7f12-bfc6-81a370a88a5e,id=019ddc5a-40f9-7f12-bfc6-81a370a88a5e; trace=019ddc5a-8828-7ec2-95c9-002e0ed204a2,id=019ddc5a-8828-7ec2-95c9-002e0ed204a2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-8828-7ec2-95c9-002e0ed204a2,id=019ddc5a-8828-7ec2-95c9-002e0ed204a2; trace=019ddc5a-9686-7932-bc5a-b17407901578,id=019ddc5a-9686-7932-bc5a-b17407901578; trace=019ddc5a-9686-7932-bc5a-b17407901578,id=019ddc5a-9686-7932-bc5a-b17407901578; trace=019ddc5a-96eb-75d2-87b2-2a1f0351d03b,id=019ddc5a-96eb-75d2-87b2-2a1f0351d03b

      [38/50]   ok  19.25s  calls=2  in= 9981 (cache   87%)  out= 521  acum=$0.9710

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-96eb-75d2-87b2-2a1f0351d03b,id=019ddc5a-96eb-75d2-87b2-2a1f0351d03b; trace=019ddc5a-d35d-7260-96cb-508e7a4f0358,id=019ddc5a-d35d-7260-96cb-508e7a4f0358
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-d35d-7260-96cb-508e7a4f0358,id=019ddc5a-d35d-7260-96cb-508e7a4f0358; trace=019ddc5a-e0f2-7d31-bc9b-5b2e8e916410,id=019ddc5a-e0f2-7d31-bc9b-5b2e8e916410; trace=019ddc5a-e0f2-7d31-bc9b-5b2e8e916410,id=019ddc5a-e0f2-7d31-bc9b-5b2e8e916410; trace=019ddc5a-e151-7561-9c06-29325412b3a9,id=019ddc5a-e151-7561-9c06-29325412b3a9

      [39/50]   ok  15.05s  calls=2  in= 9952 (cache   87%)  out= 398  acum=$0.9897

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5a-e151-7561-9c06-29325412b3a9,id=019ddc5a-e151-7561-9c06-29325412b3a9; trace=019ddc5b-0e26-7b72-9f32-888f543c9232,id=019ddc5b-0e26-7b72-9f32-888f543c9232
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-0e26-7b72-9f32-888f543c9232,id=019ddc5b-0e26-7b72-9f32-888f543c9232; trace=019ddc5b-1c1c-7b92-be33-f06d6f895820,id=019ddc5b-1c1c-7b92-be33-f06d6f895820; trace=019ddc5b-1c1c-7b92-be33-f06d6f895820,id=019ddc5b-1c1c-7b92-be33-f06d6f895820; trace=019ddc5b-1c7f-76a0-a1d7-ebf0d888d158,id=019ddc5b-1c7f-76a0-a1d7-ebf0d888d158

      [40/50]   ok   15.9s  calls=2  in=10773 (cache   81%)  out= 505  acum=$1.0102

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-1c7f-76a0-a1d7-ebf0d888d158,id=019ddc5b-1c7f-76a0-a1d7-ebf0d888d158; trace=019ddc5b-4c3f-7150-b6a2-fd75f94e66d4,id=019ddc5b-4c3f-7150-b6a2-fd75f94e66d4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-4c3f-7150-b6a2-fd75f94e66d4,id=019ddc5b-4c3f-7150-b6a2-fd75f94e66d4; trace=019ddc5b-5a24-7522-a3e6-5fc25487a573,id=019ddc5b-5a24-7522-a3e6-5fc25487a573; trace=019ddc5b-5a24-7522-a3e6-5fc25487a573,id=019ddc5b-5a24-7522-a3e6-5fc25487a573; trace=019ddc5b-5af4-7900-aefd-a38ff917241c,id=019ddc5b-5af4-7900-aefd-a38ff917241c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-5af4-7900-aefd-a38ff917241c,id=019ddc5b-5af4-7900-aefd-a38ff917241c; trace=019ddc5b-6bc0-7532-903c-39b40de4025e,id=019ddc5b-6bc0-7532-903c-39b40de4025e; trace=019ddc5b-6bc0-7532-903c-39b40de4025e,id=019ddc5b-6bc0-7532-903c-39b40de4025e; trace=019ddc5b-6bc2-70d0-aec0-5c2353f6f576,id=019ddc5b-6bc2-70d0-aec0-5c2353f6f576

      [41/50]   ok  31.41s  calls=3  in=21101 (cache  118%)  out= 996  acum=$1.0503

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-6bc2-70d0-aec0-5c2353f6f576,id=019ddc5b-6bc2-70d0-aec0-5c2353f6f576; trace=019ddc5b-c6f3-79e1-ad93-d3e1359941c3,id=019ddc5b-c6f3-79e1-ad93-d3e1359941c3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-c6f3-79e1-ad93-d3e1359941c3,id=019ddc5b-c6f3-79e1-ad93-d3e1359941c3; trace=019ddc5b-d53a-7f02-8703-fc00f9962844,id=019ddc5b-d53a-7f02-8703-fc00f9962844; trace=019ddc5b-d53a-7f02-8703-fc00f9962844,id=019ddc5b-d53a-7f02-8703-fc00f9962844; trace=019ddc5b-d600-76c3-8b45-1d876a4c3290,id=019ddc5b-d600-76c3-8b45-1d876a4c3290

      [42/50]   ok  10.12s  calls=2  in= 9117 (cache   95%)  out= 241  acum=$1.0670

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-d600-76c3-8b45-1d876a4c3290,id=019ddc5b-d600-76c3-8b45-1d876a4c3290; trace=019ddc5b-ee7a-7c41-a361-86cde92d0e8d,id=019ddc5b-ee7a-7c41-a361-86cde92d0e8d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-ee7a-7c41-a361-86cde92d0e8d,id=019ddc5b-ee7a-7c41-a361-86cde92d0e8d; trace=019ddc5b-fb57-72a1-88b0-b67c205d656d,id=019ddc5b-fb57-72a1-88b0-b67c205d656d; trace=019ddc5b-fb57-72a1-88b0-b67c205d656d,id=019ddc5b-fb57-72a1-88b0-b67c205d656d; trace=019ddc5b-fbb4-7a81-823d-4dc8f5b60f31,id=019ddc5b-fbb4-7a81-823d-4dc8f5b60f31

      [43/50]   ok   9.44s  calls=2  in= 9690 (cache   90%)  out= 247  acum=$1.0848

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5b-fbb4-7a81-823d-4dc8f5b60f31,id=019ddc5b-fbb4-7a81-823d-4dc8f5b60f31; trace=019ddc5c-1358-7d52-884a-60151baa2747,id=019ddc5c-1358-7d52-884a-60151baa2747
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-1358-7d52-884a-60151baa2747,id=019ddc5c-1358-7d52-884a-60151baa2747; trace=019ddc5c-22f0-7982-b3d7-7f01642cd466,id=019ddc5c-22f0-7982-b3d7-7f01642cd466; trace=019ddc5c-22f0-7982-b3d7-7f01642cd466,id=019ddc5c-22f0-7982-b3d7-7f01642cd466; trace=019ddc5c-2357-7e13-9183-2bfb92231565,id=019ddc5c-2357-7e13-9183-2bfb92231565
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-2357-7e13-9183-2bfb92231565,id=019ddc5c-2357-7e13-9183-2bfb92231565; trace=019ddc5c-3c4d-7932-9a0e-a55167e488f8,id=019ddc5c-3c4d-7932-9a0e-a55167e488f8; trace=019ddc5c-3c4d-7932-9a0e-a55167e488f8,id=019ddc5c-3c4d-7932-9a0e-a55167e488f8; trace=019ddc5c-3d2b-7360-b7cd-b9b1b0f47584,id=019ddc5c-3d2b-7360-b7cd-b9b1b0f47584

      [44/50]   ok  26.69s  calls=3  in=21977 (cache  111%)  out= 675  acum=$1.1253

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-3d2b-7360-b7cd-b9b1b0f47584,id=019ddc5c-3d2b-7360-b7cd-b9b1b0f47584; trace=019ddc5c-7b9e-7aa2-b8cb-ae1417aad7b5,id=019ddc5c-7b9e-7aa2-b8cb-ae1417aad7b5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-7b9e-7aa2-b8cb-ae1417aad7b5,id=019ddc5c-7b9e-7aa2-b8cb-ae1417aad7b5; trace=019ddc5c-8b7d-7723-965e-ce37578f65bb,id=019ddc5c-8b7d-7723-965e-ce37578f65bb; trace=019ddc5c-8b7d-7723-965e-ce37578f65bb,id=019ddc5c-8b7d-7723-965e-ce37578f65bb; trace=019ddc5c-8c50-7d31-a32e-cdf549eb2c7b,id=019ddc5c-8c50-7d31-a32e-cdf549eb2c7b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-8c50-7d31-a32e-cdf549eb2c7b,id=019ddc5c-8c50-7d31-a32e-cdf549eb2c7b; trace=019ddc5c-a223-7522-81a3-c56e12e902b4,id=019ddc5c-a223-7522-81a3-c56e12e902b4; trace=019ddc5c-a223-7522-81a3-c56e12e902b4,id=019ddc5c-a223-7522-81a3-c56e12e902b4; trace=019ddc5c-a226-7440-9e85-efdd7f61800e,id=019ddc5c-a226-7440-9e85-efdd7f61800e

      [45/50]   ok  35.66s  calls=3  in=19968 (cache  119%)  out= 977  acum=$1.1635

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5c-a226-7440-9e85-efdd7f61800e,id=019ddc5c-a226-7440-9e85-efdd7f61800e; trace=019ddc5d-06ea-7ba0-92ed-1e308810c40a,id=019ddc5d-06ea-7ba0-92ed-1e308810c40a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-06ea-7ba0-92ed-1e308810c40a,id=019ddc5d-06ea-7ba0-92ed-1e308810c40a; trace=019ddc5d-161a-7ee0-a0f0-f4a891791544,id=019ddc5d-161a-7ee0-a0f0-f4a891791544; trace=019ddc5d-161a-7ee0-a0f0-f4a891791544,id=019ddc5d-161a-7ee0-a0f0-f4a891791544; trace=019ddc5d-161c-7c41-9576-a92c49d638db,id=019ddc5d-161c-7c41-9576-a92c49d638db; trace=019ddc5d-161c-7c41-9576-a92c49d638db,id=019ddc5d-161c-7c41-9576-a92c49d638db; trace=019ddc5d-16f2-7012-a0be-19f4735df1d8,id=019ddc5d-16f2-7012-a0be-19f4735df1d8

      [46/50]   ok  10.35s  calls=2  in= 9657 (cache   90%)  out= 222  acum=$1.1811

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-16f2-7012-a0be-19f4735df1d8,id=019ddc5d-16f2-7012-a0be-19f4735df1d8; trace=019ddc5d-2f56-75e3-8af4-9f6dd26a5ecf,id=019ddc5d-2f56-75e3-8af4-9f6dd26a5ecf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-2f56-75e3-8af4-9f6dd26a5ecf,id=019ddc5d-2f56-75e3-8af4-9f6dd26a5ecf; trace=019ddc5d-4100-70d3-b707-9aa6ea27fcf7,id=019ddc5d-4100-70d3-b707-9aa6ea27fcf7; trace=019ddc5d-4100-70d3-b707-9aa6ea27fcf7,id=019ddc5d-4100-70d3-b707-9aa6ea27fcf7; trace=019ddc5d-41d8-74a3-8720-a03587823247,id=019ddc5d-41d8-74a3-8720-a03587823247

      [47/50]   ok  16.79s  calls=2  in= 8558 (cache  102%)  out= 499  acum=$1.1977

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-41d8-74a3-8720-a03587823247,id=019ddc5d-41d8-74a3-8720-a03587823247; trace=019ddc5d-70ef-74f1-ac4b-39ecb5efe7cb,id=019ddc5d-70ef-74f1-ac4b-39ecb5efe7cb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-70ef-74f1-ac4b-39ecb5efe7cb,id=019ddc5d-70ef-74f1-ac4b-39ecb5efe7cb; trace=019ddc5d-7eed-7ac1-a570-a44c81175517,id=019ddc5d-7eed-7ac1-a570-a44c81175517; trace=019ddc5d-7eed-7ac1-a570-a44c81175517,id=019ddc5d-7eed-7ac1-a570-a44c81175517; trace=019ddc5d-7f4b-7b70-907c-4751f5e53e40,id=019ddc5d-7f4b-7b70-907c-4751f5e53e40

      [48/50]   ok  14.23s  calls=2  in= 9540 (cache   91%)  out= 336  acum=$1.2155

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-7f4b-7b70-907c-4751f5e53e40,id=019ddc5d-7f4b-7b70-907c-4751f5e53e40; trace=019ddc5d-a88a-7d41-b5cf-742ea6af8e2c,id=019ddc5d-a88a-7d41-b5cf-742ea6af8e2c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-a88a-7d41-b5cf-742ea6af8e2c,id=019ddc5d-a88a-7d41-b5cf-742ea6af8e2c; trace=019ddc5d-b755-7263-9d5d-789a2d214d65,id=019ddc5d-b755-7263-9d5d-789a2d214d65; trace=019ddc5d-b755-7263-9d5d-789a2d214d65,id=019ddc5d-b755-7263-9d5d-789a2d214d65; trace=019ddc5d-b824-77d1-bb93-1601e33cd86a,id=019ddc5d-b824-77d1-bb93-1601e33cd86a

      [49/50]   ok  22.26s  calls=2  in= 9022 (cache   96%)  out= 651  acum=$1.2334

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-b824-77d1-bb93-1601e33cd86a,id=019ddc5d-b824-77d1-bb93-1601e33cd86a; trace=019ddc5d-ff7e-7d31-9940-ff06569bf542,id=019ddc5d-ff7e-7d31-9940-ff06569bf542
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5d-ff7e-7d31-9940-ff06569bf542,id=019ddc5d-ff7e-7d31-9940-ff06569bf542; trace=019ddc5e-0e21-7842-87df-5f6f19bd94ec,id=019ddc5e-0e21-7842-87df-5f6f19bd94ec; trace=019ddc5e-0e21-7842-87df-5f6f19bd94ec,id=019ddc5e-0e21-7842-87df-5f6f19bd94ec; trace=019ddc5e-0e87-7741-bfef-c30eeaf4cd17,id=019ddc5e-0e87-7741-bfef-c30eeaf4cd17
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-0e87-7741-bfef-c30eeaf4cd17,id=019ddc5e-0e87-7741-bfef-c30eeaf4cd17; trace=019ddc5e-2019-7383-b234-fb36d529dcc3,id=019ddc5e-2019-7383-b234-fb36d529dcc3; trace=019ddc5e-2019-7383-b234-fb36d529dcc3,id=019ddc5e-2019-7383-b234-fb36d529dcc3; trace=019ddc5e-201c-7440-bc9e-2347374b465a,id=019ddc5e-201c-7440-bc9e-2347374b465a

      [50/50]   ok  29.35s  calls=3  in=17293 (cache  118%)  out= 848  acum=$1.2665
       ✓ ok — salvo em bndes__deepseek__deepseek-v4-pro__20260430_001110.xlsx

[run]  deepseek/deepseek-v4-pro × cvm (id=2)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-201c-7440-bc9e-2347374b465a,id=019ddc5e-201c-7440-bc9e-2347374b465a; trace=019ddc5e-724d-7cd3-a352-3daa4d75f0f7,id=019ddc5e-724d-7cd3-a352-3daa4d75f0f7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-724d-7cd3-a352-3daa4d75f0f7,id=019ddc5e-724d-7cd3-a352-3daa4d75f0f7; trace=019ddc5e-8311-7570-903b-dec8c3045f1a,id=019ddc5e-8311-7570-903b-dec8c3045f1a; trace=019ddc5e-8311-7570-903b-dec8c3045f1a,id=019ddc5e-8311-7570-903b-dec8c3045f1a; trace=019ddc5e-8313-7170-826b-48e2a9e069af,id=019ddc5e-8313-7170-826b-48e2a9e069af; trace=019ddc5e-8313-7170-826b-48e2a9e069af,id=019ddc5e-8313-7170-826b-48e2a9e069af; trace=019ddc5e-83da-7ea3-99f6-658e68718575,id=019ddc5e-83da-7ea3-99f6-658e68718575

      [ 1/50]   ok  15.69s  calls=2  in= 8141 (cache  107%)  out= 389  acum=$0.0155

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-83da-7ea3-99f6-658e68718575,id=019ddc5e-83da-7ea3-99f6-658e68718575; trace=019ddc5e-af95-7833-a579-2755559a1357,id=019ddc5e-af95-7833-a579-2755559a1357
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-af95-7833-a579-2755559a1357,id=019ddc5e-af95-7833-a579-2755559a1357; trace=019ddc5e-bc85-76e1-a9a0-3ba8721289eb,id=019ddc5e-bc85-76e1-a9a0-3ba8721289eb; trace=019ddc5e-bc85-76e1-a9a0-3ba8721289eb,id=019ddc5e-bc85-76e1-a9a0-3ba8721289eb; trace=019ddc5e-bd53-7d40-88cc-57cf342916eb,id=019ddc5e-bd53-7d40-88cc-57cf342916eb

      [ 2/50]   ok   8.23s  calls=2  in= 8059 (cache  108%)  out= 182  acum=$0.0302

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-bd53-7d40-88cc-57cf342916eb,id=019ddc5e-bd53-7d40-88cc-57cf342916eb; trace=019ddc5e-cfb9-73e1-8df5-bc6dd60d42f9,id=019ddc5e-cfb9-73e1-8df5-bc6dd60d42f9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-cfb9-73e1-8df5-bc6dd60d42f9,id=019ddc5e-cfb9-73e1-8df5-bc6dd60d42f9; trace=019ddc5e-dced-7060-acc0-03f405d3f69f,id=019ddc5e-dced-7060-acc0-03f405d3f69f; trace=019ddc5e-dced-7060-acc0-03f405d3f69f,id=019ddc5e-dced-7060-acc0-03f405d3f69f; trace=019ddc5e-ddc1-73f3-9326-2915133cb144,id=019ddc5e-ddc1-73f3-9326-2915133cb144

      [ 3/50]   ok   8.59s  calls=2  in= 8859 (cache   98%)  out= 173  acum=$0.0462

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-ddc1-73f3-9326-2915133cb144,id=019ddc5e-ddc1-73f3-9326-2915133cb144; trace=019ddc5e-f14c-7721-a779-e6130d0a98b7,id=019ddc5e-f14c-7721-a779-e6130d0a98b7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-f14c-7721-a779-e6130d0a98b7,id=019ddc5e-f14c-7721-a779-e6130d0a98b7; trace=019ddc5e-fef1-72b3-a714-0a28a2210913,id=019ddc5e-fef1-72b3-a714-0a28a2210913; trace=019ddc5e-fef1-72b3-a714-0a28a2210913,id=019ddc5e-fef1-72b3-a714-0a28a2210913; trace=019ddc5e-ffc2-75f1-a220-a807da49a4b6,id=019ddc5e-ffc2-75f1-a220-a807da49a4b6

      [ 4/50]   ok  13.75s  calls=2  in= 7905 (cache  110%)  out= 401  acum=$0.0613

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5e-ffc2-75f1-a220-a807da49a4b6,id=019ddc5e-ffc2-75f1-a220-a807da49a4b6; trace=019ddc5f-2705-7430-b9e6-9c69684b5250,id=019ddc5f-2705-7430-b9e6-9c69684b5250
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-2705-7430-b9e6-9c69684b5250,id=019ddc5f-2705-7430-b9e6-9c69684b5250; trace=019ddc5f-34ed-76d1-b9a7-9d57e9404720,id=019ddc5f-34ed-76d1-b9a7-9d57e9404720; trace=019ddc5f-34ed-76d1-b9a7-9d57e9404720,id=019ddc5f-34ed-76d1-b9a7-9d57e9404720; trace=019ddc5f-34ef-7373-a44d-dfac9150ba80,id=019ddc5f-34ef-7373-a44d-dfac9150ba80; trace=019ddc5f-34ef-7373-a44d-dfac9150ba80,id=019ddc5f-34ef-7373-a44d-dfac9150ba80; trace=019ddc5f-35bd-7091-8635-6210153886ae,id=019ddc5f-35bd-7091-8635-6210153886ae

      [ 5/50]   ok  12.88s  calls=2  in= 7877 (cache  110%)  out= 351  acum=$0.0763

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-35bd-7091-8635-6210153886ae,id=019ddc5f-35bd-7091-8635-6210153886ae; trace=019ddc5f-5952-7a93-a4ed-23addb52fb75,id=019ddc5f-5952-7a93-a4ed-23addb52fb75
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-5952-7a93-a4ed-23addb52fb75,id=019ddc5f-5952-7a93-a4ed-23addb52fb75; trace=019ddc5f-6751-7812-9bd2-914b7a67f82c,id=019ddc5f-6751-7812-9bd2-914b7a67f82c; trace=019ddc5f-6751-7812-9bd2-914b7a67f82c,id=019ddc5f-6751-7812-9bd2-914b7a67f82c; trace=019ddc5f-67ba-7101-abbf-0d3dca7bba92,id=019ddc5f-67ba-7101-abbf-0d3dca7bba92

      [ 6/50]   ok  19.75s  calls=2  in= 8087 (cache  108%)  out= 577  acum=$0.0923

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-67ba-7101-abbf-0d3dca7bba92,id=019ddc5f-67ba-7101-abbf-0d3dca7bba92; trace=019ddc5f-a678-7a80-8dcf-b2a65b117c88,id=019ddc5f-a678-7a80-8dcf-b2a65b117c88
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-a678-7a80-8dcf-b2a65b117c88,id=019ddc5f-a678-7a80-8dcf-b2a65b117c88; trace=019ddc5f-b5b7-7a02-b1b4-0c725dd25f44,id=019ddc5f-b5b7-7a02-b1b4-0c725dd25f44; trace=019ddc5f-b5b7-7a02-b1b4-0c725dd25f44,id=019ddc5f-b5b7-7a02-b1b4-0c725dd25f44; trace=019ddc5f-b69e-7d12-99b8-44a2a8da0bec,id=019ddc5f-b69e-7d12-99b8-44a2a8da0bec; trace=019ddc5f-b69e-7d12-99b8-44a2a8da0bec,id=019ddc5f-b69e-7d12-99b8-44a2a8da0bec; trace=019ddc5f-b69f-7993-a7ef-221ace2c5673,id=019ddc5f-b69f-7993-a7ef-221ace2c5673

      [ 7/50]   ok  10.26s  calls=2  in= 8097 (cache  107%)  out= 243  acum=$0.1073

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-b69f-7993-a7ef-221ace2c5673,id=019ddc5f-b69f-7993-a7ef-221ace2c5673; trace=019ddc5f-ce88-7dd1-ad17-846b16e7a98e,id=019ddc5f-ce88-7dd1-ad17-846b16e7a98e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-ce88-7dd1-ad17-846b16e7a98e,id=019ddc5f-ce88-7dd1-ad17-846b16e7a98e; trace=019ddc5f-daea-76d3-bec2-cb1b8c1e86fa,id=019ddc5f-daea-76d3-bec2-cb1b8c1e86fa; trace=019ddc5f-daea-76d3-bec2-cb1b8c1e86fa,id=019ddc5f-daea-76d3-bec2-cb1b8c1e86fa; trace=019ddc5f-dbbf-7c81-97ce-f34d75366eb0,id=019ddc5f-dbbf-7c81-97ce-f34d75366eb0

      [ 8/50]   ok  10.65s  calls=2  in= 7825 (cache  111%)  out= 302  acum=$0.1219

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-dbbf-7c81-97ce-f34d75366eb0,id=019ddc5f-dbbf-7c81-97ce-f34d75366eb0; trace=019ddc5f-f823-7a92-aac8-203e9da01d7a,id=019ddc5f-f823-7a92-aac8-203e9da01d7a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc5f-f823-7a92-aac8-203e9da01d7a,id=019ddc5f-f823-7a92-aac8-203e9da01d7a; trace=019ddc60-0a1e-7de2-851e-6b7f9733f39f,id=019ddc60-0a1e-7de2-851e-6b7f9733f39f; trace=019ddc60-0a1e-7de2-851e-6b7f9733f39f,id=019ddc60-0a1e-7de2-851e-6b7f9733f39f; trace=019ddc60-0ae4-7210-964b-e968e88ea647,id=019ddc60-0ae4-7210-964b-e968e88ea647

      [ 9/50]   ok  12.07s  calls=2  in= 8068 (cache  108%)  out= 313  acum=$0.1371

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-0ae4-7210-964b-e968e88ea647,id=019ddc60-0ae4-7210-964b-e968e88ea647; trace=019ddc60-274a-7341-9c6a-e51fb97d5bb5,id=019ddc60-274a-7341-9c6a-e51fb97d5bb5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-274a-7341-9c6a-e51fb97d5bb5,id=019ddc60-274a-7341-9c6a-e51fb97d5bb5; trace=019ddc60-3ae9-7293-8e33-69a6172b24a5,id=019ddc60-3ae9-7293-8e33-69a6172b24a5; trace=019ddc60-3ae9-7293-8e33-69a6172b24a5,id=019ddc60-3ae9-7293-8e33-69a6172b24a5; trace=019ddc60-3aeb-7fb0-9128-fe5395f330fd,id=019ddc60-3aeb-7fb0-9128-fe5395f330fd; trace=019ddc60-3aeb-7fb0-9128-fe5395f330fd,id=019ddc60-3aeb-7fb0-9128-fe5395f330fd; trace=019ddc60-3b4c-74d1-8e57-154fcc89ca6d,id=019ddc60-3b4c-74d1-8e57-154fcc89ca6d

      [10/50]   ok  14.08s  calls=2  in= 7637 (cache  114%)  out= 358  acum=$0.1516

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-3b4c-74d1-8e57-154fcc89ca6d,id=019ddc60-3b4c-74d1-8e57-154fcc89ca6d; trace=019ddc60-5e4c-7ec3-aa11-aa7e4aa7c7bd,id=019ddc60-5e4c-7ec3-aa11-aa7e4aa7c7bd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-5e4c-7ec3-aa11-aa7e4aa7c7bd,id=019ddc60-5e4c-7ec3-aa11-aa7e4aa7c7bd; trace=019ddc60-6c1e-7661-8aca-2ef7d42ce358,id=019ddc60-6c1e-7661-8aca-2ef7d42ce358; trace=019ddc60-6c1e-7661-8aca-2ef7d42ce358,id=019ddc60-6c1e-7661-8aca-2ef7d42ce358; trace=019ddc60-6ce9-73d2-9550-3863e0d1f320,id=019ddc60-6ce9-73d2-9550-3863e0d1f320

      [11/50]   ok   9.44s  calls=2  in= 8235 (cache  106%)  out= 257  acum=$0.1668

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-6ce9-73d2-9550-3863e0d1f320,id=019ddc60-6ce9-73d2-9550-3863e0d1f320; trace=019ddc60-832c-7a62-8e60-914b035d28c9,id=019ddc60-832c-7a62-8e60-914b035d28c9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-832c-7a62-8e60-914b035d28c9,id=019ddc60-832c-7a62-8e60-914b035d28c9; trace=019ddc60-8ea8-7872-b545-5350e1c829a9,id=019ddc60-8ea8-7872-b545-5350e1c829a9; trace=019ddc60-8ea8-7872-b545-5350e1c829a9,id=019ddc60-8ea8-7872-b545-5350e1c829a9; trace=019ddc60-8eac-78c0-a690-e024047c1190,id=019ddc60-8eac-78c0-a690-e024047c1190
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-8eac-78c0-a690-e024047c1190,id=019ddc60-8eac-78c0-a690-e024047c1190; trace=019ddc60-9fb5-78a1-86c1-ca21a5ffc095,id=019ddc60-9fb5-78a1-86c1-ca21a5ffc095; trace=019ddc60-9fb5-78a1-86c1-ca21a5ffc095,id=019ddc60-9fb5-78a1-86c1-ca21a5ffc095; trace=019ddc60-9fb6-78c1-a5fc-780542e8e53c,id=019ddc60-9fb6-78c1-a5fc-780542e8e53c

      [12/50]   ok  16.83s  calls=3  in=10937 (cache  133%)  out= 406  acum=$0.1873

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-9fb6-78c1-a5fc-780542e8e53c,id=019ddc60-9fb6-78c1-a5fc-780542e8e53c; trace=019ddc60-c4eb-7622-b2c0-98258146dadb,id=019ddc60-c4eb-7622-b2c0-98258146dadb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-c4eb-7622-b2c0-98258146dadb,id=019ddc60-c4eb-7622-b2c0-98258146dadb; trace=019ddc60-d21d-75f2-a270-28d007926d0b,id=019ddc60-d21d-75f2-a270-28d007926d0b; trace=019ddc60-d21d-75f2-a270-28d007926d0b,id=019ddc60-d21d-75f2-a270-28d007926d0b; trace=019ddc60-d2ee-79f0-ab7a-27a5628e32b5,id=019ddc60-d2ee-79f0-ab7a-27a5628e32b5

      [13/50]   ok  10.24s  calls=2  in= 8028 (cache  108%)  out= 240  acum=$0.2021

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-d2ee-79f0-ab7a-27a5628e32b5,id=019ddc60-d2ee-79f0-ab7a-27a5628e32b5; trace=019ddc60-eceb-71e0-807d-23958246c9ed,id=019ddc60-eceb-71e0-807d-23958246c9ed
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-eceb-71e0-807d-23958246c9ed,id=019ddc60-eceb-71e0-807d-23958246c9ed; trace=019ddc60-fc14-70e0-98bc-88090addf15c,id=019ddc60-fc14-70e0-98bc-88090addf15c; trace=019ddc60-fc14-70e0-98bc-88090addf15c,id=019ddc60-fc14-70e0-98bc-88090addf15c; trace=019ddc60-fcd4-7ca1-bd4d-85bd184c3888,id=019ddc60-fcd4-7ca1-bd4d-85bd184c3888

      [14/50]   ok   13.1s  calls=2  in= 7537 (cache  115%)  out= 352  acum=$0.2164

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc60-fcd4-7ca1-bd4d-85bd184c3888,id=019ddc60-fcd4-7ca1-bd4d-85bd184c3888; trace=019ddc61-2016-7bf2-b2c8-d4d728a221c9,id=019ddc61-2016-7bf2-b2c8-d4d728a221c9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-2016-7bf2-b2c8-d4d728a221c9,id=019ddc61-2016-7bf2-b2c8-d4d728a221c9; trace=019ddc61-2e24-7ee1-969b-24aa7ed6811a,id=019ddc61-2e24-7ee1-969b-24aa7ed6811a; trace=019ddc61-2e24-7ee1-969b-24aa7ed6811a,id=019ddc61-2e24-7ee1-969b-24aa7ed6811a; trace=019ddc61-2ef2-7640-b364-78c1ad3e1f9d,id=019ddc61-2ef2-7640-b364-78c1ad3e1f9d

      [15/50]   ok  16.29s  calls=2  in= 7840 (cache  111%)  out= 449  acum=$0.2316

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-2ef2-7640-b364-78c1ad3e1f9d,id=019ddc61-2ef2-7640-b364-78c1ad3e1f9d; trace=019ddc61-5fb9-7c02-81a6-e0e128bf6c68,id=019ddc61-5fb9-7c02-81a6-e0e128bf6c68
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-5fb9-7c02-81a6-e0e128bf6c68,id=019ddc61-5fb9-7c02-81a6-e0e128bf6c68; trace=019ddc61-6c68-7d71-a974-36edd5ca4632,id=019ddc61-6c68-7d71-a974-36edd5ca4632; trace=019ddc61-6c68-7d71-a974-36edd5ca4632,id=019ddc61-6c68-7d71-a974-36edd5ca4632; trace=019ddc61-6c6b-7b82-a2d7-414c9b23eb5d,id=019ddc61-6c6b-7b82-a2d7-414c9b23eb5d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-6c6b-7b82-a2d7-414c9b23eb5d,id=019ddc61-6c6b-7b82-a2d7-414c9b23eb5d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-8a82-7790-be44-e880eb719efd,id=019ddc61-8a82-7790-be44-e880eb719efd; trace=019ddc61-8a82-7790-be44-e880eb719efd,id=019ddc61-8a82-7790-be44-e880eb719efd; trace=019ddc61-8a91-7e30-a238-fea04985f4e7,id=019ddc61-8a91-7e30-a238-fea04985f4e7; trace=019ddc61-8a91-7e30-a238-fea04985f4e7,id=019ddc61-8a91-7e30-a238-fea04985f4e7; trace=019ddc61-8af3-7ae0-a19b-79456b49c2b6,id=019ddc61-8af3-7ae0-a19b-79456b49c2b6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-8af3-7ae0-a19b-79456b49c2b6,id=019ddc61-8af3-7ae0-a19b-79456b49c2b6; trace=019ddc61-a794-7410-ba40-3755fec9fb0c,id=019ddc61-a794-7410-ba40-3755fec9fb0c; trace=019ddc61-a794-7410-ba40-3755fec9fb0c,id=019ddc61-a794-7410-ba40-3755fec9fb0c; trace=019ddc61-a7a0-76d2-893d-376a27c7d12f,id=019ddc61-a7a0-76d2-893d-376a27c7d12f; trace=019ddc61-a7a0-76d2-893d-376a27c7d12f,id=019ddc61-a7a0-76d2-893d-376a27c7d12f; trace=019ddc61-a7a3-74b3-b1d8-fab27316d95a,id=019ddc61-a7a3-74b3-b1d8-fab27316d95a

      [16/50]   ok  32.05s  calls=4  in=22130 (cache  139%)  out= 913  acum=$0.2733

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-a7a3-74b3-b1d8-fab27316d95a,id=019ddc61-a7a3-74b3-b1d8-fab27316d95a; trace=019ddc61-dceb-7c50-95db-9ba23df6b792,id=019ddc61-dceb-7c50-95db-9ba23df6b792
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-dceb-7c50-95db-9ba23df6b792,id=019ddc61-dceb-7c50-95db-9ba23df6b792; trace=019ddc61-ee88-7ff3-9eb7-5b5c0d741ac3,id=019ddc61-ee88-7ff3-9eb7-5b5c0d741ac3; trace=019ddc61-ee88-7ff3-9eb7-5b5c0d741ac3,id=019ddc61-ee88-7ff3-9eb7-5b5c0d741ac3; trace=019ddc61-ef4f-7b71-aa96-9792b2f3dee8,id=019ddc61-ef4f-7b71-aa96-9792b2f3dee8

      [17/50]   ok  16.58s  calls=2  in= 8136 (cache  107%)  out= 460  acum=$0.2891

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc61-ef4f-7b71-aa96-9792b2f3dee8,id=019ddc61-ef4f-7b71-aa96-9792b2f3dee8; trace=019ddc62-1db2-7a00-a2e1-8ca4411030fe,id=019ddc62-1db2-7a00-a2e1-8ca4411030fe
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-1db2-7a00-a2e1-8ca4411030fe,id=019ddc62-1db2-7a00-a2e1-8ca4411030fe; trace=019ddc62-2c84-7650-a0cf-1391f8e9c4d0,id=019ddc62-2c84-7650-a0cf-1391f8e9c4d0; trace=019ddc62-2c84-7650-a0cf-1391f8e9c4d0,id=019ddc62-2c84-7650-a0cf-1391f8e9c4d0; trace=019ddc62-2ce9-7ed3-9159-7c656ec4634e,id=019ddc62-2ce9-7ed3-9159-7c656ec4634e

      [18/50]   ok  22.23s  calls=2  in= 9641 (cache   90%)  out= 655  acum=$0.3081

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-2ce9-7ed3-9159-7c656ec4634e,id=019ddc62-2ce9-7ed3-9159-7c656ec4634e; trace=019ddc62-7486-74f2-b36e-835a7d629686,id=019ddc62-7486-74f2-b36e-835a7d629686
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-7486-74f2-b36e-835a7d629686,id=019ddc62-7486-74f2-b36e-835a7d629686; trace=019ddc62-807f-7731-b524-d0c4b1b5f39f,id=019ddc62-807f-7731-b524-d0c4b1b5f39f; trace=019ddc62-807f-7731-b524-d0c4b1b5f39f,id=019ddc62-807f-7731-b524-d0c4b1b5f39f; trace=019ddc62-8147-74b3-ab51-6d8a2785cf72,id=019ddc62-8147-74b3-ab51-6d8a2785cf72

      [19/50]   ok  11.77s  calls=2  in= 9165 (cache   95%)  out= 290  acum=$0.3251

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-8147-74b3-ab51-6d8a2785cf72,id=019ddc62-8147-74b3-ab51-6d8a2785cf72; trace=019ddc62-a284-7af3-a5e1-f9b01917ae2c,id=019ddc62-a284-7af3-a5e1-f9b01917ae2c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-a284-7af3-a5e1-f9b01917ae2c,id=019ddc62-a284-7af3-a5e1-f9b01917ae2c; trace=019ddc62-b0ec-7810-9c41-80aeec2dd6f8,id=019ddc62-b0ec-7810-9c41-80aeec2dd6f8; trace=019ddc62-b0ec-7810-9c41-80aeec2dd6f8,id=019ddc62-b0ec-7810-9c41-80aeec2dd6f8; trace=019ddc62-b1bd-7ee3-9901-b71cacc28ec1,id=019ddc62-b1bd-7ee3-9901-b71cacc28ec1

      [20/50]   ok   8.91s  calls=2  in= 9457 (cache   92%)  out= 195  acum=$0.3422

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-b1bd-7ee3-9901-b71cacc28ec1,id=019ddc62-b1bd-7ee3-9901-b71cacc28ec1; trace=019ddc62-c551-7971-b769-05e4c5d6b0f4,id=019ddc62-c551-7971-b769-05e4c5d6b0f4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-c551-7971-b769-05e4c5d6b0f4,id=019ddc62-c551-7971-b769-05e4c5d6b0f4; trace=019ddc62-d483-73b3-a9ba-1736ef195451,id=019ddc62-d483-73b3-a9ba-1736ef195451; trace=019ddc62-d483-73b3-a9ba-1736ef195451,id=019ddc62-d483-73b3-a9ba-1736ef195451; trace=019ddc62-d556-7163-9fdd-f31fb1392345,id=019ddc62-d556-7163-9fdd-f31fb1392345

      [21/50]   ok  25.09s  calls=2  in= 8112 (cache  107%)  out= 717  acum=$0.3588

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc62-d556-7163-9fdd-f31fb1392345,id=019ddc62-d556-7163-9fdd-f31fb1392345; trace=019ddc63-2751-7550-a964-07dfa653a3bd,id=019ddc63-2751-7550-a964-07dfa653a3bd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-2751-7550-a964-07dfa653a3bd,id=019ddc63-2751-7550-a964-07dfa653a3bd; trace=019ddc63-3684-7131-8f26-cfa5176b086e,id=019ddc63-3684-7131-8f26-cfa5176b086e; trace=019ddc63-3684-7131-8f26-cfa5176b086e,id=019ddc63-3684-7131-8f26-cfa5176b086e; trace=019ddc63-3741-7570-968e-973eef07d64f,id=019ddc63-3741-7570-968e-973eef07d64f

      [22/50]   ok  17.91s  calls=2  in= 8329 (cache  105%)  out= 489  acum=$0.3750

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-3741-7570-968e-973eef07d64f,id=019ddc63-3741-7570-968e-973eef07d64f; trace=019ddc63-6d49-7b91-b1b2-8c76db5f19b9,id=019ddc63-6d49-7b91-b1b2-8c76db5f19b9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-6d49-7b91-b1b2-8c76db5f19b9,id=019ddc63-6d49-7b91-b1b2-8c76db5f19b9; trace=019ddc63-7ae9-7a72-a300-751e18a225f5,id=019ddc63-7ae9-7a72-a300-751e18a225f5; trace=019ddc63-7ae9-7a72-a300-751e18a225f5,id=019ddc63-7ae9-7a72-a300-751e18a225f5; trace=019ddc63-7bb5-7793-86a5-4550f4534347,id=019ddc63-7bb5-7793-86a5-4550f4534347

      [23/50]   ok   8.81s  calls=2  in= 8314 (cache  105%)  out= 180  acum=$0.3901

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-7bb5-7793-86a5-4550f4534347,id=019ddc63-7bb5-7793-86a5-4550f4534347; trace=019ddc63-8fb7-7831-9037-bd57f7ac0702,id=019ddc63-8fb7-7831-9037-bd57f7ac0702
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-8fb7-7831-9037-bd57f7ac0702,id=019ddc63-8fb7-7831-9037-bd57f7ac0702; trace=019ddc63-9eb2-7400-ba4b-fe95636d6479,id=019ddc63-9eb2-7400-ba4b-fe95636d6479; trace=019ddc63-9eb2-7400-ba4b-fe95636d6479,id=019ddc63-9eb2-7400-ba4b-fe95636d6479; trace=019ddc63-9f23-7402-a602-daf42b9a9fec,id=019ddc63-9f23-7402-a602-daf42b9a9fec

      [24/50]   ok  10.55s  calls=2  in= 8973 (cache   97%)  out= 255  acum=$0.4066

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-9f23-7402-a602-daf42b9a9fec,id=019ddc63-9f23-7402-a602-daf42b9a9fec; trace=019ddc63-b8ec-7cd2-ab00-ef261076d4a1,id=019ddc63-b8ec-7cd2-ab00-ef261076d4a1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-b8ec-7cd2-ab00-ef261076d4a1,id=019ddc63-b8ec-7cd2-ab00-ef261076d4a1; trace=019ddc63-c683-7430-974d-75e0b006aa54,id=019ddc63-c683-7430-974d-75e0b006aa54; trace=019ddc63-c683-7430-974d-75e0b006aa54,id=019ddc63-c683-7430-974d-75e0b006aa54; trace=019ddc63-c75b-7c00-8d72-4fb82a5f921f,id=019ddc63-c75b-7c00-8d72-4fb82a5f921f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-c75b-7c00-8d72-4fb82a5f921f,id=019ddc63-c75b-7c00-8d72-4fb82a5f921f; trace=019ddc63-e21a-77e0-a7e8-355b12756a83,id=019ddc63-e21a-77e0-a7e8-355b12756a83; trace=019ddc63-e21a-77e0-a7e8-355b12756a83,id=019ddc63-e21a-77e0-a7e8-355b12756a83; trace=019ddc63-e21d-79c1-ad86-01131805ea06,id=019ddc63-e21d-79c1-ad86-01131805ea06; trace=019ddc63-e21d-79c1-ad86-01131805ea06,id=019ddc63-e21d-79c1-ad86-01131805ea06; trace=019ddc63-e2e0-7fb2-b845-4fe0ddbb272b,id=019ddc63-e2e0-7fb2-b845-4fe0ddbb272b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-e2e0-7fb2-b845-4fe0ddbb272b,id=019ddc63-e2e0-7fb2-b845-4fe0ddbb272b; trace=019ddc63-f79e-7802-8c40-9b4f38d532ce,id=019ddc63-f79e-7802-8c40-9b4f38d532ce; trace=019ddc63-f79e-7802-8c40-9b4f38d532ce,id=019ddc63-f79e-7802-8c40-9b4f38d532ce; trace=019ddc63-f7a1-7e43-92ca-202c19951c92,id=019ddc63-f7a1-7e43-92ca-202c19951c92
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc63-f7a1-7e43-92ca-202c19951c92,id=019ddc63-f7a1-7e43-92ca-202c19951c92; trace=019ddc64-061b-7ab1-a4c5-151558f66740,id=019ddc64-061b-7ab1-a4c5-151558f66740; trace=019ddc64-061b-7ab1-a4c5-151558f66740,id=019ddc64-061b-7ab1-a4c5-151558f66740; trace=019ddc64-061e-7fa0-9b27-c4e932507839,id=019ddc64-061e-7fa0-9b27-c4e932507839
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-061e-7fa0-9b27-c4e932507839,id=019ddc64-061e-7fa0-9b27-c4e932507839; trace=019ddc64-2082-7830-90cc-bc5301f652fb,id=019ddc64-2082-7830-90cc-bc5301f652fb; trace=019ddc64-2082-7830-90cc-bc5301f652fb,id=019ddc64-2082-7830-90cc-bc5301f652fb; trace=019ddc64-20ec-7793-8b98-f52987fa6d69,id=019ddc64-20ec-7793-8b98-f52987fa6d69

      [25/50]   ok   42.7s  calls=6  in=71404 (cache  149%)  out=1047  acum=$0.5345

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-20ec-7793-8b98-f52987fa6d69,id=019ddc64-20ec-7793-8b98-f52987fa6d69; trace=019ddc64-5fb5-71b3-8af8-0191e6fa599f,id=019ddc64-5fb5-71b3-8af8-0191e6fa599f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-5fb5-71b3-8af8-0191e6fa599f,id=019ddc64-5fb5-71b3-8af8-0191e6fa599f; trace=019ddc64-6e1c-7d82-9d8f-ea00fad3ebb3,id=019ddc64-6e1c-7d82-9d8f-ea00fad3ebb3; trace=019ddc64-6e1c-7d82-9d8f-ea00fad3ebb3,id=019ddc64-6e1c-7d82-9d8f-ea00fad3ebb3; trace=019ddc64-6eee-7a43-9e27-3b0ad73311ae,id=019ddc64-6eee-7a43-9e27-3b0ad73311ae

      [26/50]   ok   9.83s  calls=2  in= 9456 (cache   92%)  out= 238  acum=$0.5518

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-6eee-7a43-9e27-3b0ad73311ae,id=019ddc64-6eee-7a43-9e27-3b0ad73311ae; trace=019ddc64-861e-7c62-97e4-b337e429820f,id=019ddc64-861e-7c62-97e4-b337e429820f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-861e-7c62-97e4-b337e429820f,id=019ddc64-861e-7c62-97e4-b337e429820f; trace=019ddc64-95b6-7183-a0af-f0b5b72fa70d,id=019ddc64-95b6-7183-a0af-f0b5b72fa70d; trace=019ddc64-95b6-7183-a0af-f0b5b72fa70d,id=019ddc64-95b6-7183-a0af-f0b5b72fa70d; trace=019ddc64-9685-78a0-a3ee-236b964f7087,id=019ddc64-9685-78a0-a3ee-236b964f7087
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-9685-78a0-a3ee-236b964f7087,id=019ddc64-9685-78a0-a3ee-236b964f7087; trace=019ddc64-b14f-7723-98b2-19d969a4e006,id=019ddc64-b14f-7723-98b2-19d969a4e006; trace=019ddc64-b14f-7723-98b2-19d969a4e006,id=019ddc64-b14f-7723-98b2-19d969a4e006; trace=019ddc64-b21d-7682-8e37-7249a75d2a2d,id=019ddc64-b21d-7682-8e37-7249a75d2a2d; trace=019ddc64-b21d-7682-8e37-7249a75d2a2d,id=019ddc64-b21d-7682-8e37-7249a75d2a2d; trace=019ddc64-b21f-71b0-8ebd-ffc9c7c04c3a,id=019ddc64-b21f-71b0-8ebd-ffc9c7c04c3a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-b21f-71b0-8ebd-ffc9c7c04c3a,id=019ddc64-b21f-71b0-8ebd-ffc9c7c04c3a; trace=019ddc64-c5b0-7293-93db-6fa61c220445,id=019ddc64-c5b0-7293-93db-6fa61c220445; trace=019ddc64-c5b0-7293-93db-6fa61c220445,id=019ddc64-c5b0-7293-93db-6fa61c220445; trace=019ddc64-c5b3-7753-84e4-6bf4d1bff184,id=019ddc64-c5b3-7753-84e4-6bf4d1bff184

      [27/50]   ok  24.88s  calls=4  in=30650 (cache  136%)  out= 636  acum=$0.6073

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-c5b3-7753-84e4-6bf4d1bff184,id=019ddc64-c5b3-7753-84e4-6bf4d1bff184; trace=019ddc64-e752-7c62-ab3c-3b0b27c90667,id=019ddc64-e752-7c62-ab3c-3b0b27c90667
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-e752-7c62-ab3c-3b0b27c90667,id=019ddc64-e752-7c62-ab3c-3b0b27c90667; trace=019ddc64-f4ea-7e00-80e3-ec2a0f694c8c,id=019ddc64-f4ea-7e00-80e3-ec2a0f694c8c; trace=019ddc64-f4ea-7e00-80e3-ec2a0f694c8c,id=019ddc64-f4ea-7e00-80e3-ec2a0f694c8c; trace=019ddc64-f54d-7400-81b6-bffb1079e586,id=019ddc64-f54d-7400-81b6-bffb1079e586

      [28/50]   ok  24.54s  calls=2  in= 8642 (cache  101%)  out= 702  acum=$0.6248

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc64-f54d-7400-81b6-bffb1079e586,id=019ddc64-f54d-7400-81b6-bffb1079e586; trace=019ddc65-4733-7392-8896-ca777eaa088e,id=019ddc65-4733-7392-8896-ca777eaa088e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-4733-7392-8896-ca777eaa088e,id=019ddc65-4733-7392-8896-ca777eaa088e; trace=019ddc65-54e5-7b92-92f8-fc8f3156264b,id=019ddc65-54e5-7b92-92f8-fc8f3156264b; trace=019ddc65-54e5-7b92-92f8-fc8f3156264b,id=019ddc65-54e5-7b92-92f8-fc8f3156264b; trace=019ddc65-5563-7812-98e7-355f44759dd8,id=019ddc65-5563-7812-98e7-355f44759dd8
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-5563-7812-98e7-355f44759dd8,id=019ddc65-5563-7812-98e7-355f44759dd8; trace=019ddc65-661c-79e0-af5b-ad1a0916f3cc,id=019ddc65-661c-79e0-af5b-ad1a0916f3cc; trace=019ddc65-661c-79e0-af5b-ad1a0916f3cc,id=019ddc65-661c-79e0-af5b-ad1a0916f3cc; trace=019ddc65-661f-7f93-a2e0-9738fbd0d0d3,id=019ddc65-661f-7f93-a2e0-9738fbd0d0d3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-661f-7f93-a2e0-9738fbd0d0d3,id=019ddc65-661f-7f93-a2e0-9738fbd0d0d3; trace=019ddc65-770c-7d82-8b80-7fdfd28fd57c,id=019ddc65-770c-7d82-8b80-7fdfd28fd57c; trace=019ddc65-770c-7d82-8b80-7fdfd28fd57c,id=019ddc65-770c-7d82-8b80-7fdfd28fd57c; trace=019ddc65-770e-7b82-9997-74f660e54468,id=019ddc65-770e-7b82-9997-74f660e54468
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-770e-7b82-9997-74f660e54468,id=019ddc65-770e-7b82-9997-74f660e54468; trace=019ddc65-89d9-7672-b748-1a7d9e0c05c9,id=019ddc65-89d9-7672-b748-1a7d9e0c05c9; trace=019ddc65-89d9-7672-b748-1a7d9e0c05c9,id=019ddc65-89d9-7672-b748-1a7d9e0c05c9; trace=019ddc65-8acd-7b30-a139-3098c8a68434,id=019ddc65-8acd-7b30-a139-3098c8a68434

      [29/50]   ok   28.5s  calls=5  in=40962 (cache  137%)  out= 707  acum=$0.6985

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-8acd-7b30-a139-3098c8a68434,id=019ddc65-8acd-7b30-a139-3098c8a68434; trace=019ddc65-b684-73b1-bfe0-7cb0d8adff05,id=019ddc65-b684-73b1-bfe0-7cb0d8adff05
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-b684-73b1-bfe0-7cb0d8adff05,id=019ddc65-b684-73b1-bfe0-7cb0d8adff05; trace=019ddc65-c54e-79c0-b666-7b0a16d13a45,id=019ddc65-c54e-79c0-b666-7b0a16d13a45; trace=019ddc65-c54e-79c0-b666-7b0a16d13a45,id=019ddc65-c54e-79c0-b666-7b0a16d13a45; trace=019ddc65-c61f-7812-ab75-f543b0311646,id=019ddc65-c61f-7812-ab75-f543b0311646

      [30/50]   ok  16.79s  calls=2  in= 8336 (cache  104%)  out= 452  acum=$0.7146

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-c61f-7812-ab75-f543b0311646,id=019ddc65-c61f-7812-ab75-f543b0311646; trace=019ddc65-f81d-7bc2-a42c-51b21aaca8b5,id=019ddc65-f81d-7bc2-a42c-51b21aaca8b5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc65-f81d-7bc2-a42c-51b21aaca8b5,id=019ddc65-f81d-7bc2-a42c-51b21aaca8b5; trace=019ddc66-061b-76d2-8bc3-31f5f78a80e2,id=019ddc66-061b-76d2-8bc3-31f5f78a80e2; trace=019ddc66-061b-76d2-8bc3-31f5f78a80e2,id=019ddc66-061b-76d2-8bc3-31f5f78a80e2; trace=019ddc66-06f2-7e20-9d6c-17cae5cf1a15,id=019ddc66-06f2-7e20-9d6c-17cae5cf1a15

      [31/50]   ok  21.22s  calls=2  in= 7956 (cache  109%)  out= 586  acum=$0.7305

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-06f2-7e20-9d6c-17cae5cf1a15,id=019ddc66-06f2-7e20-9d6c-17cae5cf1a15; trace=019ddc66-4b00-71c2-b03c-20b32792e849,id=019ddc66-4b00-71c2-b03c-20b32792e849
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-4b00-71c2-b03c-20b32792e849,id=019ddc66-4b00-71c2-b03c-20b32792e849; trace=019ddc66-591b-7783-87bb-6aba33d5b9d8,id=019ddc66-591b-7783-87bb-6aba33d5b9d8; trace=019ddc66-591b-7783-87bb-6aba33d5b9d8,id=019ddc66-591b-7783-87bb-6aba33d5b9d8; trace=019ddc66-5987-7631-9362-8f11fdeff1d9,id=019ddc66-5987-7631-9362-8f11fdeff1d9

      [32/50]   ok  11.37s  calls=2  in= 8437 (cache  103%)  out= 294  acum=$0.7462

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-5987-7631-9362-8f11fdeff1d9,id=019ddc66-5987-7631-9362-8f11fdeff1d9; trace=019ddc66-776f-7882-8265-6b6db2f520d0,id=019ddc66-776f-7882-8265-6b6db2f520d0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-776f-7882-8265-6b6db2f520d0,id=019ddc66-776f-7882-8265-6b6db2f520d0; trace=019ddc66-8336-72c0-a361-bc0f53030f5f,id=019ddc66-8336-72c0-a361-bc0f53030f5f; trace=019ddc66-8336-72c0-a361-bc0f53030f5f,id=019ddc66-8336-72c0-a361-bc0f53030f5f; trace=019ddc66-8398-7a60-b425-529c49e15faa,id=019ddc66-8398-7a60-b425-529c49e15faa

      [33/50]   ok  11.03s  calls=2  in= 8035 (cache  108%)  out= 265  acum=$0.7611

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-8398-7a60-b425-529c49e15faa,id=019ddc66-8398-7a60-b425-529c49e15faa; trace=019ddc66-a286-7350-a3a1-90ef8d99d8f6,id=019ddc66-a286-7350-a3a1-90ef8d99d8f6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-a286-7350-a3a1-90ef8d99d8f6,id=019ddc66-a286-7350-a3a1-90ef8d99d8f6; trace=019ddc66-b01a-72b1-b5fe-a39983e64045,id=019ddc66-b01a-72b1-b5fe-a39983e64045; trace=019ddc66-b01a-72b1-b5fe-a39983e64045,id=019ddc66-b01a-72b1-b5fe-a39983e64045; trace=019ddc66-b0ee-7d03-abb6-54907bed785b,id=019ddc66-b0ee-7d03-abb6-54907bed785b

      [34/50]   ok   6.28s  calls=2  in= 7846 (cache  111%)  out= 120  acum=$0.7752

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-b0ee-7d03-abb6-54907bed785b,id=019ddc66-b0ee-7d03-abb6-54907bed785b; trace=019ddc66-bb10-7582-9ab8-ccf88740dc91,id=019ddc66-bb10-7582-9ab8-ccf88740dc91
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-bb10-7582-9ab8-ccf88740dc91,id=019ddc66-bb10-7582-9ab8-ccf88740dc91; trace=019ddc66-cc84-7422-8f80-5f105dafce8b,id=019ddc66-cc84-7422-8f80-5f105dafce8b; trace=019ddc66-cc84-7422-8f80-5f105dafce8b,id=019ddc66-cc84-7422-8f80-5f105dafce8b; trace=019ddc66-cced-72b1-9883-8c8d680ce70f,id=019ddc66-cced-72b1-9883-8c8d680ce70f

      [35/50]   ok   15.8s  calls=2  in= 8237 (cache  106%)  out= 395  acum=$0.7909

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-cced-72b1-9883-8c8d680ce70f,id=019ddc66-cced-72b1-9883-8c8d680ce70f; trace=019ddc66-f8c5-78b2-b783-c7e05d212a46,id=019ddc66-f8c5-78b2-b783-c7e05d212a46
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc66-f8c5-78b2-b783-c7e05d212a46,id=019ddc66-f8c5-78b2-b783-c7e05d212a46; trace=019ddc67-0990-7ce0-98ab-1e36f0e73bf2,id=019ddc67-0990-7ce0-98ab-1e36f0e73bf2; trace=019ddc67-0990-7ce0-98ab-1e36f0e73bf2,id=019ddc67-0990-7ce0-98ab-1e36f0e73bf2; trace=019ddc67-0993-70c2-898c-e9b028d27596,id=019ddc67-0993-70c2-898c-e9b028d27596
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-0993-70c2-898c-e9b028d27596,id=019ddc67-0993-70c2-898c-e9b028d27596; trace=019ddc67-1f4f-7b63-888a-f4da1c376c42,id=019ddc67-1f4f-7b63-888a-f4da1c376c42; trace=019ddc67-1f4f-7b63-888a-f4da1c376c42,id=019ddc67-1f4f-7b63-888a-f4da1c376c42; trace=019ddc67-1f52-70f1-a790-a3b18859bf34,id=019ddc67-1f52-70f1-a790-a3b18859bf34; trace=019ddc67-1f52-70f1-a790-a3b18859bf34,id=019ddc67-1f52-70f1-a790-a3b18859bf34; trace=019ddc67-1f5d-7e62-95b6-43347a841867,id=019ddc67-1f5d-7e62-95b6-43347a841867

      [36/50]   ok   19.6s  calls=3  in=15931 (cache   93%)  out= 493  acum=$0.8203

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-1f5d-7e62-95b6-43347a841867,id=019ddc67-1f5d-7e62-95b6-43347a841867; trace=019ddc67-4554-72f2-a1e9-9613989c6f2b,id=019ddc67-4554-72f2-a1e9-9613989c6f2b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-4554-72f2-a1e9-9613989c6f2b,id=019ddc67-4554-72f2-a1e9-9613989c6f2b; trace=019ddc67-569d-76b1-87aa-850768918083,id=019ddc67-569d-76b1-87aa-850768918083; trace=019ddc67-569d-76b1-87aa-850768918083,id=019ddc67-569d-76b1-87aa-850768918083; trace=019ddc67-5789-7483-af9c-f0a3505bef04,id=019ddc67-5789-7483-af9c-f0a3505bef04

      [37/50]   ok  23.03s  calls=2  in= 9759 (cache   89%)  out= 664  acum=$0.8396

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-5789-7483-af9c-f0a3505bef04,id=019ddc67-5789-7483-af9c-f0a3505bef04; trace=019ddc67-9f4a-7331-8b15-e5847af92379,id=019ddc67-9f4a-7331-8b15-e5847af92379
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-9f4a-7331-8b15-e5847af92379,id=019ddc67-9f4a-7331-8b15-e5847af92379; trace=019ddc67-aee9-7c53-86d3-ac72a1c30743,id=019ddc67-aee9-7c53-86d3-ac72a1c30743; trace=019ddc67-aee9-7c53-86d3-ac72a1c30743,id=019ddc67-aee9-7c53-86d3-ac72a1c30743; trace=019ddc67-afba-7d21-9026-84187ee7e0be,id=019ddc67-afba-7d21-9026-84187ee7e0be
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-afba-7d21-9026-84187ee7e0be,id=019ddc67-afba-7d21-9026-84187ee7e0be; trace=019ddc67-c41b-7bd0-8b6f-416716fa2086,id=019ddc67-c41b-7bd0-8b6f-416716fa2086; trace=019ddc67-c41b-7bd0-8b6f-416716fa2086,id=019ddc67-c41b-7bd0-8b6f-416716fa2086; trace=019ddc67-c4f5-75b2-ac47-04d402de4302,id=019ddc67-c4f5-75b2-ac47-04d402de4302

      [38/50]   ok  18.12s  calls=3  in=18973 (cache  116%)  out= 415  acum=$0.8741

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-c4f5-75b2-ac47-04d402de4302,id=019ddc67-c4f5-75b2-ac47-04d402de4302; trace=019ddc67-e616-7c62-9851-fc74e2ed4927,id=019ddc67-e616-7c62-9851-fc74e2ed4927
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-e616-7c62-9851-fc74e2ed4927,id=019ddc67-e616-7c62-9851-fc74e2ed4927; trace=019ddc67-f38e-76c3-8698-095851c82689,id=019ddc67-f38e-76c3-8698-095851c82689; trace=019ddc67-f38e-76c3-8698-095851c82689,id=019ddc67-f38e-76c3-8698-095851c82689; trace=019ddc67-f45b-7cb2-b544-6ae59a8ac2d0,id=019ddc67-f45b-7cb2-b544-6ae59a8ac2d0

      [39/50]   ok  13.17s  calls=2  in= 8090 (cache  108%)  out= 340  acum=$0.8893

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc67-f45b-7cb2-b544-6ae59a8ac2d0,id=019ddc67-f45b-7cb2-b544-6ae59a8ac2d0; trace=019ddc68-198a-77f3-98cc-747103717e40,id=019ddc68-198a-77f3-98cc-747103717e40
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-198a-77f3-98cc-747103717e40,id=019ddc68-198a-77f3-98cc-747103717e40; trace=019ddc68-27b7-73a0-a978-d52c6bfe93eb,id=019ddc68-27b7-73a0-a978-d52c6bfe93eb; trace=019ddc68-27b7-73a0-a978-d52c6bfe93eb,id=019ddc68-27b7-73a0-a978-d52c6bfe93eb; trace=019ddc68-288a-7000-a5a1-de5628c7cabc,id=019ddc68-288a-7000-a5a1-de5628c7cabc

      [40/50]   ok  22.57s  calls=2  in= 9062 (cache   96%)  out= 625  acum=$0.9073

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-288a-7000-a5a1-de5628c7cabc,id=019ddc68-288a-7000-a5a1-de5628c7cabc; trace=019ddc68-71b1-7eb0-a2fc-ea41c898805a,id=019ddc68-71b1-7eb0-a2fc-ea41c898805a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-71b1-7eb0-a2fc-ea41c898805a,id=019ddc68-71b1-7eb0-a2fc-ea41c898805a; trace=019ddc68-8283-76e3-98b6-2c1235b2566c,id=019ddc68-8283-76e3-98b6-2c1235b2566c; trace=019ddc68-8283-76e3-98b6-2c1235b2566c,id=019ddc68-8283-76e3-98b6-2c1235b2566c; trace=019ddc68-8349-75a3-b764-2f63d2d6e7c6,id=019ddc68-8349-75a3-b764-2f63d2d6e7c6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-8349-75a3-b764-2f63d2d6e7c6,id=019ddc68-8349-75a3-b764-2f63d2d6e7c6; trace=019ddc68-9481-7412-a1a1-a2763f99c13a,id=019ddc68-9481-7412-a1a1-a2763f99c13a; trace=019ddc68-9481-7412-a1a1-a2763f99c13a,id=019ddc68-9481-7412-a1a1-a2763f99c13a; trace=019ddc68-9484-7be0-a3f5-4ce4ae4c59d2,id=019ddc68-9484-7be0-a3f5-4ce4ae4c59d2

      [41/50]   ok  32.14s  calls=3  in=19857 (cache  119%)  out= 909  acum=$0.9450

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-9484-7be0-a3f5-4ce4ae4c59d2,id=019ddc68-9484-7be0-a3f5-4ce4ae4c59d2; trace=019ddc68-ef3d-7562-885c-1efd95792b8d,id=019ddc68-ef3d-7562-885c-1efd95792b8d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-ef3d-7562-885c-1efd95792b8d,id=019ddc68-ef3d-7562-885c-1efd95792b8d; trace=019ddc68-fb62-7f60-94ad-c1babde42650,id=019ddc68-fb62-7f60-94ad-c1babde42650; trace=019ddc68-fb62-7f60-94ad-c1babde42650,id=019ddc68-fb62-7f60-94ad-c1babde42650; trace=019ddc68-fbbf-71e3-bc13-d1b11b28d410,id=019ddc68-fbbf-71e3-bc13-d1b11b28d410

      [42/50]   ok   9.23s  calls=2  in= 7914 (cache  110%)  out= 232  acum=$0.9596

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc68-fbbf-71e3-bc13-d1b11b28d410,id=019ddc68-fbbf-71e3-bc13-d1b11b28d410; trace=019ddc69-1351-7e11-afb3-569a6f6a11fd,id=019ddc69-1351-7e11-afb3-569a6f6a11fd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-1351-7e11-afb3-569a6f6a11fd,id=019ddc69-1351-7e11-afb3-569a6f6a11fd; trace=019ddc69-21b5-7fb3-8ad6-dd0c1a4636c1,id=019ddc69-21b5-7fb3-8ad6-dd0c1a4636c1; trace=019ddc69-21b5-7fb3-8ad6-dd0c1a4636c1,id=019ddc69-21b5-7fb3-8ad6-dd0c1a4636c1; trace=019ddc69-2286-73d0-9981-4a496836cd65,id=019ddc69-2286-73d0-9981-4a496836cd65

      [43/50]   ok   9.39s  calls=2  in= 7940 (cache  110%)  out= 218  acum=$0.9741

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-2286-73d0-9981-4a496836cd65,id=019ddc69-2286-73d0-9981-4a496836cd65; trace=019ddc69-3801-7752-a0ab-f07c9eee0539,id=019ddc69-3801-7752-a0ab-f07c9eee0539
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-3801-7752-a0ab-f07c9eee0539,id=019ddc69-3801-7752-a0ab-f07c9eee0539; trace=019ddc69-4edf-7170-9fec-913f50349387,id=019ddc69-4edf-7170-9fec-913f50349387; trace=019ddc69-4edf-7170-9fec-913f50349387,id=019ddc69-4edf-7170-9fec-913f50349387; trace=019ddc69-4fb4-78e3-ad81-06c6dbd1bfd8,id=019ddc69-4fb4-78e3-ad81-06c6dbd1bfd8; trace=019ddc69-4fb4-78e3-ad81-06c6dbd1bfd8,id=019ddc69-4fb4-78e3-ad81-06c6dbd1bfd8; trace=019ddc69-4fb6-7b01-87b5-7dcf917dfd8f,id=019ddc69-4fb6-7b01-87b5-7dcf917dfd8f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-4fb6-7b01-87b5-7dcf917dfd8f,id=019ddc69-4fb6-7b01-87b5-7dcf917dfd8f; trace=019ddc69-634c-76f2-8d0f-44bc72eda36b,id=019ddc69-634c-76f2-8d0f-44bc72eda36b; trace=019ddc69-634c-76f2-8d0f-44bc72eda36b,id=019ddc69-634c-76f2-8d0f-44bc72eda36b; trace=019ddc69-634e-7ce2-9614-87d4fc0ac8de,id=019ddc69-634e-7ce2-9614-87d4fc0ac8de

      [44/50]   ok  21.63s  calls=3  in=21236 (cache  117%)  out= 567  acum=$1.0131

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-634e-7ce2-9614-87d4fc0ac8de,id=019ddc69-634e-7ce2-9614-87d4fc0ac8de; trace=019ddc69-8c83-7611-9198-769e0e969a40,id=019ddc69-8c83-7611-9198-769e0e969a40
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-8c83-7611-9198-769e0e969a40,id=019ddc69-8c83-7611-9198-769e0e969a40; trace=019ddc69-a419-70e0-b210-380bd52abf86,id=019ddc69-a419-70e0-b210-380bd52abf86; trace=019ddc69-a419-70e0-b210-380bd52abf86,id=019ddc69-a419-70e0-b210-380bd52abf86; trace=019ddc69-a4e2-78e1-932a-aae7d8750a78,id=019ddc69-a4e2-78e1-932a-aae7d8750a78
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-a4e2-78e1-932a-aae7d8750a78,id=019ddc69-a4e2-78e1-932a-aae7d8750a78; trace=019ddc69-b7e8-78b0-99d1-588514ac6499,id=019ddc69-b7e8-78b0-99d1-588514ac6499; trace=019ddc69-b7e8-78b0-99d1-588514ac6499,id=019ddc69-b7e8-78b0-99d1-588514ac6499; trace=019ddc69-b7f2-7e62-b76a-849d19206ed5,id=019ddc69-b7f2-7e62-b76a-849d19206ed5

      [45/50]   ok  26.04s  calls=3  in=18425 (cache  133%)  out= 740  acum=$1.0477

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-b7f2-7e62-b76a-849d19206ed5,id=019ddc69-b7f2-7e62-b76a-849d19206ed5; trace=019ddc69-f23a-7cf0-89d6-c1f527032095,id=019ddc69-f23a-7cf0-89d6-c1f527032095
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc69-f23a-7cf0-89d6-c1f527032095,id=019ddc69-f23a-7cf0-89d6-c1f527032095; trace=019ddc6a-03b7-7471-8081-b1c5758a6103,id=019ddc6a-03b7-7471-8081-b1c5758a6103; trace=019ddc6a-03b7-7471-8081-b1c5758a6103,id=019ddc6a-03b7-7471-8081-b1c5758a6103; trace=019ddc6a-03b9-7943-a549-899ff676d137,id=019ddc6a-03b9-7943-a549-899ff676d137; trace=019ddc6a-03b9-7943-a549-899ff676d137,id=019ddc6a-03b9-7943-a549-899ff676d137; trace=019ddc6a-048f-72e3-aa94-996deb8ebe27,id=019ddc6a-048f-72e3-aa94-996deb8ebe27

      [46/50]   ok  15.13s  calls=2  in= 7735 (cache  113%)  out= 371  acum=$1.0624

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-048f-72e3-aa94-996deb8ebe27,id=019ddc6a-048f-72e3-aa94-996deb8ebe27; trace=019ddc6a-2d55-7672-bb83-5366a1314070,id=019ddc6a-2d55-7672-bb83-5366a1314070
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-2d55-7672-bb83-5366a1314070,id=019ddc6a-2d55-7672-bb83-5366a1314070; trace=019ddc6a-3daa-7eb1-b6bc-dadf694f960f,id=019ddc6a-3daa-7eb1-b6bc-dadf694f960f; trace=019ddc6a-3daa-7eb1-b6bc-dadf694f960f,id=019ddc6a-3daa-7eb1-b6bc-dadf694f960f; trace=019ddc6a-3e14-7ff0-bf7c-6669934145cf,id=019ddc6a-3e14-7ff0-bf7c-6669934145cf

      [47/50]   ok  16.79s  calls=2  in= 7401 (cache  118%)  out= 519  acum=$1.0771

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-3e14-7ff0-bf7c-6669934145cf,id=019ddc6a-3e14-7ff0-bf7c-6669934145cf; trace=019ddc6a-6eeb-7ee1-81a0-0b6a3fc84682,id=019ddc6a-6eeb-7ee1-81a0-0b6a3fc84682
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-6eeb-7ee1-81a0-0b6a3fc84682,id=019ddc6a-6eeb-7ee1-81a0-0b6a3fc84682; trace=019ddc6a-7bb8-74e1-882c-a1e96facfe36,id=019ddc6a-7bb8-74e1-882c-a1e96facfe36; trace=019ddc6a-7bb8-74e1-882c-a1e96facfe36,id=019ddc6a-7bb8-74e1-882c-a1e96facfe36; trace=019ddc6a-7c86-73b0-9cc4-3e0d3655cc4b,id=019ddc6a-7c86-73b0-9cc4-3e0d3655cc4b

      [48/50]   ok  11.06s  calls=2  in= 7595 (cache  115%)  out= 280  acum=$1.0913

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-7c86-73b0-9cc4-3e0d3655cc4b,id=019ddc6a-7c86-73b0-9cc4-3e0d3655cc4b; trace=019ddc6a-9a1d-7012-b2e7-44883a7e58a6,id=019ddc6a-9a1d-7012-b2e7-44883a7e58a6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-9a1d-7012-b2e7-44883a7e58a6,id=019ddc6a-9a1d-7012-b2e7-44883a7e58a6; trace=019ddc6a-a81e-7912-9d19-145d20a8ce53,id=019ddc6a-a81e-7912-9d19-145d20a8ce53; trace=019ddc6a-a81e-7912-9d19-145d20a8ce53,id=019ddc6a-a81e-7912-9d19-145d20a8ce53; trace=019ddc6a-a8af-71a2-96ab-aa4db07ce829,id=019ddc6a-a8af-71a2-96ab-aa4db07ce829

      [49/50]   ok  19.48s  calls=2  in= 8019 (cache  109%)  out= 627  acum=$1.1074

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-a8af-71a2-96ab-aa4db07ce829,id=019ddc6a-a8af-71a2-96ab-aa4db07ce829; trace=019ddc6a-e636-7642-926e-46f38ccda4d0,id=019ddc6a-e636-7642-926e-46f38ccda4d0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-e636-7642-926e-46f38ccda4d0,id=019ddc6a-e636-7642-926e-46f38ccda4d0; trace=019ddc6a-f716-7f11-acb8-04a3bb745bc4,id=019ddc6a-f716-7f11-acb8-04a3bb745bc4; trace=019ddc6a-f716-7f11-acb8-04a3bb745bc4,id=019ddc6a-f716-7f11-acb8-04a3bb745bc4; trace=019ddc6a-f7e5-7da1-8d51-652d220123c4,id=019ddc6a-f7e5-7da1-8d51-652d220123c4

      [50/50]   ok  21.19s  calls=2  in= 8459 (cache  106%)  out= 599  acum=$1.1243
       ✓ ok — salvo em cvm__deepseek__deepseek-v4-pro__20260430_002507.xlsx

[run]  deepseek/deepseek-v4-pro × petrobras (id=3)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6a-f7e5-7da1-8d51-652d220123c4,id=019ddc6a-f7e5-7da1-8d51-652d220123c4; trace=019ddc6b-3924-78d3-b45d-48cd96dbb811,id=019ddc6b-3924-78d3-b45d-48cd96dbb811
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-3924-78d3-b45d-48cd96dbb811,id=019ddc6b-3924-78d3-b45d-48cd96dbb811; trace=019ddc6b-47b7-7451-a774-d6a5ec8aa5fe,id=019ddc6b-47b7-7451-a774-d6a5ec8aa5fe; trace=019ddc6b-47b7-7451-a774-d6a5ec8aa5fe,id=019ddc6b-47b7-7451-a774-d6a5ec8aa5fe; trace=019ddc6b-47b9-7a80-b986-98c455bd8013,id=019ddc6b-47b9-7a80-b986-98c455bd8013; trace=019ddc6b-47b9-7a80-b986-98c455bd8013,id=019ddc6b-47b9-7a80-b986-98c455bd8013; trace=019ddc6b-487a-71c0-a32c-b7820721f11f,id=019ddc6b-487a-71c0-a32c-b7820721f11f

      [ 1/50]   ok  10.28s  calls=2  in= 9177 (cache   95%)  out= 255  acum=$0.0169

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-487a-71c0-a32c-b7820721f11f,id=019ddc6b-487a-71c0-a32c-b7820721f11f; trace=019ddc6b-6152-7502-86db-2f0611334464,id=019ddc6b-6152-7502-86db-2f0611334464
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-6152-7502-86db-2f0611334464,id=019ddc6b-6152-7502-86db-2f0611334464; trace=019ddc6b-6f50-7e40-8f03-3841d930ce01,id=019ddc6b-6f50-7e40-8f03-3841d930ce01; trace=019ddc6b-6f50-7e40-8f03-3841d930ce01,id=019ddc6b-6f50-7e40-8f03-3841d930ce01; trace=019ddc6b-7006-7730-9cf2-00008fe8bbff,id=019ddc6b-7006-7730-9cf2-00008fe8bbff

      [ 2/50]   ok  10.85s  calls=2  in= 7891 (cache  110%)  out= 262  acum=$0.0315

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-7006-7730-9cf2-00008fe8bbff,id=019ddc6b-7006-7730-9cf2-00008fe8bbff; trace=019ddc6b-8bb9-7613-9464-2b15c81d5599,id=019ddc6b-8bb9-7613-9464-2b15c81d5599
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-8bb9-7613-9464-2b15c81d5599,id=019ddc6b-8bb9-7613-9464-2b15c81d5599; trace=019ddc6b-9950-7b83-b8c6-71fbdefd075c,id=019ddc6b-9950-7b83-b8c6-71fbdefd075c; trace=019ddc6b-9950-7b83-b8c6-71fbdefd075c,id=019ddc6b-9950-7b83-b8c6-71fbdefd075c; trace=019ddc6b-9a17-7100-93e5-fd5dbe9c2831,id=019ddc6b-9a17-7100-93e5-fd5dbe9c2831

      [ 3/50]   ok    8.7s  calls=2  in= 9514 (cache   91%)  out= 194  acum=$0.0487

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-9a17-7100-93e5-fd5dbe9c2831,id=019ddc6b-9a17-7100-93e5-fd5dbe9c2831; trace=019ddc6b-adb8-75e1-bd61-5c66e10020fe,id=019ddc6b-adb8-75e1-bd61-5c66e10020fe
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-adb8-75e1-bd61-5c66e10020fe,id=019ddc6b-adb8-75e1-bd61-5c66e10020fe; trace=019ddc6b-bbb6-7461-88f2-a164a8ad94a0,id=019ddc6b-bbb6-7461-88f2-a164a8ad94a0; trace=019ddc6b-bbb6-7461-88f2-a164a8ad94a0,id=019ddc6b-bbb6-7461-88f2-a164a8ad94a0; trace=019ddc6b-bc7b-73a0-8317-9c81732881de,id=019ddc6b-bc7b-73a0-8317-9c81732881de

      [ 4/50]   ok  19.25s  calls=2  in= 8133 (cache  107%)  out= 520  acum=$0.0647

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-bc7b-73a0-8317-9c81732881de,id=019ddc6b-bc7b-73a0-8317-9c81732881de; trace=019ddc6b-f8ed-78d2-beb6-67151297b54d,id=019ddc6b-f8ed-78d2-beb6-67151297b54d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6b-f8ed-78d2-beb6-67151297b54d,id=019ddc6b-f8ed-78d2-beb6-67151297b54d; trace=019ddc6c-08ec-7d01-82ca-0b1ff36eb2bd,id=019ddc6c-08ec-7d01-82ca-0b1ff36eb2bd; trace=019ddc6c-08ec-7d01-82ca-0b1ff36eb2bd,id=019ddc6c-08ec-7d01-82ca-0b1ff36eb2bd; trace=019ddc6c-08ee-77d3-ad79-1d48d4e22851,id=019ddc6c-08ee-77d3-ad79-1d48d4e22851; trace=019ddc6c-08ee-77d3-ad79-1d48d4e22851,id=019ddc6c-08ee-77d3-ad79-1d48d4e22851; trace=019ddc6c-09bd-7a51-9e4f-1c47b20addcb,id=019ddc6c-09bd-7a51-9e4f-1c47b20addcb

      [ 5/50]   ok   9.55s  calls=2  in= 9197 (cache   95%)  out= 241  acum=$0.0815

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-09bd-7a51-9e4f-1c47b20addcb,id=019ddc6c-09bd-7a51-9e4f-1c47b20addcb; trace=019ddc6c-1e3f-7cd3-8c5f-dfe225d69586,id=019ddc6c-1e3f-7cd3-8c5f-dfe225d69586
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-1e3f-7cd3-8c5f-dfe225d69586,id=019ddc6c-1e3f-7cd3-8c5f-dfe225d69586; trace=019ddc6c-2cd3-79f1-bbd2-18a02a7fa90f,id=019ddc6c-2cd3-79f1-bbd2-18a02a7fa90f; trace=019ddc6c-2cd3-79f1-bbd2-18a02a7fa90f,id=019ddc6c-2cd3-79f1-bbd2-18a02a7fa90f; trace=019ddc6c-2da3-7d50-a76e-337521a31606,id=019ddc6c-2da3-7d50-a76e-337521a31606

      [ 6/50]   ok  22.19s  calls=2  in= 9097 (cache   96%)  out= 632  acum=$0.0996

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-2da3-7d50-a76e-337521a31606,id=019ddc6c-2da3-7d50-a76e-337521a31606; trace=019ddc6c-74ef-7293-81c7-c59a51aa5209,id=019ddc6c-74ef-7293-81c7-c59a51aa5209
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-74ef-7293-81c7-c59a51aa5209,id=019ddc6c-74ef-7293-81c7-c59a51aa5209; trace=019ddc6c-84a8-7421-80b4-4cd077ab963c,id=019ddc6c-84a8-7421-80b4-4cd077ab963c; trace=019ddc6c-84a8-7421-80b4-4cd077ab963c,id=019ddc6c-84a8-7421-80b4-4cd077ab963c; trace=019ddc6c-84aa-7323-8b53-1f871741bab6,id=019ddc6c-84aa-7323-8b53-1f871741bab6; trace=019ddc6c-84aa-7323-8b53-1f871741bab6,id=019ddc6c-84aa-7323-8b53-1f871741bab6; trace=019ddc6c-8584-7381-bf58-b18d3d0349c9,id=019ddc6c-8584-7381-bf58-b18d3d0349c9

      [ 7/50]   ok  14.64s  calls=2  in= 9107 (cache   96%)  out= 382  acum=$0.1167

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-8584-7381-bf58-b18d3d0349c9,id=019ddc6c-8584-7381-bf58-b18d3d0349c9; trace=019ddc6c-ae1f-7920-8242-d0bbf6192343,id=019ddc6c-ae1f-7920-8242-d0bbf6192343
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-ae1f-7920-8242-d0bbf6192343,id=019ddc6c-ae1f-7920-8242-d0bbf6192343; trace=019ddc6c-bc0c-7db2-84ad-52fd201515ca,id=019ddc6c-bc0c-7db2-84ad-52fd201515ca; trace=019ddc6c-bc0c-7db2-84ad-52fd201515ca,id=019ddc6c-bc0c-7db2-84ad-52fd201515ca; trace=019ddc6c-bcd7-7432-b0b2-30a8ffad9c9b,id=019ddc6c-bcd7-7432-b0b2-30a8ffad9c9b

      [ 8/50]   ok  11.26s  calls=2  in= 8017 (cache  109%)  out= 285  acum=$0.1317

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-bcd7-7432-b0b2-30a8ffad9c9b,id=019ddc6c-bcd7-7432-b0b2-30a8ffad9c9b; trace=019ddc6c-da1e-7142-8ee7-e0edca2dff3a,id=019ddc6c-da1e-7142-8ee7-e0edca2dff3a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-da1e-7142-8ee7-e0edca2dff3a,id=019ddc6c-da1e-7142-8ee7-e0edca2dff3a; trace=019ddc6c-e751-7ab0-a59f-4636d4a7911c,id=019ddc6c-e751-7ab0-a59f-4636d4a7911c; trace=019ddc6c-e751-7ab0-a59f-4636d4a7911c,id=019ddc6c-e751-7ab0-a59f-4636d4a7911c; trace=019ddc6c-e80d-7622-b7a5-7864eca89b2e,id=019ddc6c-e80d-7622-b7a5-7864eca89b2e

      [ 9/50]   ok  16.38s  calls=2  in= 7899 (cache  110%)  out= 502  acum=$0.1472

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6c-e80d-7622-b7a5-7864eca89b2e,id=019ddc6c-e80d-7622-b7a5-7864eca89b2e; trace=019ddc6d-1a17-7e93-b800-2377808d085c,id=019ddc6d-1a17-7e93-b800-2377808d085c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-1a17-7e93-b800-2377808d085c,id=019ddc6d-1a17-7e93-b800-2377808d085c; trace=019ddc6d-2951-7fe1-9287-ef32aae5990c,id=019ddc6d-2951-7fe1-9287-ef32aae5990c; trace=019ddc6d-2951-7fe1-9287-ef32aae5990c,id=019ddc6d-2951-7fe1-9287-ef32aae5990c; trace=019ddc6d-2a1c-7253-a15b-7f4d7c94c7b6,id=019ddc6d-2a1c-7253-a15b-7f4d7c94c7b6

      [10/50]   ok  11.99s  calls=2  in= 8030 (cache  108%)  out= 333  acum=$0.1623

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-2a1c-7253-a15b-7f4d7c94c7b6,id=019ddc6d-2a1c-7253-a15b-7f4d7c94c7b6; trace=019ddc6d-48ed-79f1-ae88-59dc2e259ec4,id=019ddc6d-48ed-79f1-ae88-59dc2e259ec4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-48ed-79f1-ae88-59dc2e259ec4,id=019ddc6d-48ed-79f1-ae88-59dc2e259ec4; trace=019ddc6d-5798-72d2-a43d-3d3d2229b3cc,id=019ddc6d-5798-72d2-a43d-3d3d2229b3cc; trace=019ddc6d-5798-72d2-a43d-3d3d2229b3cc,id=019ddc6d-5798-72d2-a43d-3d3d2229b3cc; trace=019ddc6d-5869-76a2-9c90-061681ad7a64,id=019ddc6d-5869-76a2-9c90-061681ad7a64

      [11/50]   ok   7.29s  calls=2  in= 8164 (cache  107%)  out= 148  acum=$0.1770

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-5869-76a2-9c90-061681ad7a64,id=019ddc6d-5869-76a2-9c90-061681ad7a64; trace=019ddc6d-6568-70b3-bafd-344e9aa55791,id=019ddc6d-6568-70b3-bafd-344e9aa55791
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-6568-70b3-bafd-344e9aa55791,id=019ddc6d-6568-70b3-bafd-344e9aa55791; trace=019ddc6d-7552-7600-9918-d21656476b2d,id=019ddc6d-7552-7600-9918-d21656476b2d; trace=019ddc6d-7552-7600-9918-d21656476b2d,id=019ddc6d-7552-7600-9918-d21656476b2d; trace=019ddc6d-760c-7ac1-93b6-b60bb2e7f99b,id=019ddc6d-760c-7ac1-93b6-b60bb2e7f99b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-760c-7ac1-93b6-b60bb2e7f99b,id=019ddc6d-760c-7ac1-93b6-b60bb2e7f99b; trace=019ddc6d-86e6-7490-a846-73a4885b5ee0,id=019ddc6d-86e6-7490-a846-73a4885b5ee0; trace=019ddc6d-86e6-7490-a846-73a4885b5ee0,id=019ddc6d-86e6-7490-a846-73a4885b5ee0; trace=019ddc6d-86ea-7c83-af0c-30f0a825a950,id=019ddc6d-86ea-7c83-af0c-30f0a825a950
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-86ea-7c83-af0c-30f0a825a950,id=019ddc6d-86ea-7c83-af0c-30f0a825a950; trace=019ddc6d-a0f9-7131-851b-4627f94956c1,id=019ddc6d-a0f9-7131-851b-4627f94956c1; trace=019ddc6d-a0f9-7131-851b-4627f94956c1,id=019ddc6d-a0f9-7131-851b-4627f94956c1; trace=019ddc6d-a0fc-7e32-b428-67df15dffa53,id=019ddc6d-a0fc-7e32-b428-67df15dffa53; trace=019ddc6d-a0fc-7e32-b428-67df15dffa53,id=019ddc6d-a0fc-7e32-b428-67df15dffa53; trace=019ddc6d-a182-7e41-a015-cd0274cb8a37,id=019ddc6d-a182-7e41-a015-cd0274cb8a37

      [12/50]   ok  32.54s  calls=4  in=29578 (cache  132%)  out= 951  acum=$0.2318

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-a182-7e41-a015-cd0274cb8a37,id=019ddc6d-a182-7e41-a015-cd0274cb8a37; trace=019ddc6d-e486-74c1-951e-b7751cb0318d,id=019ddc6d-e486-74c1-951e-b7751cb0318d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-e486-74c1-951e-b7751cb0318d,id=019ddc6d-e486-74c1-951e-b7751cb0318d; trace=019ddc6d-f41e-7c30-82e3-e774d00dd69b,id=019ddc6d-f41e-7c30-82e3-e774d00dd69b; trace=019ddc6d-f41e-7c30-82e3-e774d00dd69b,id=019ddc6d-f41e-7c30-82e3-e774d00dd69b; trace=019ddc6d-f420-7980-b093-8dc1fd04ae68,id=019ddc6d-f420-7980-b093-8dc1fd04ae68; trace=019ddc6d-f420-7980-b093-8dc1fd04ae68,id=019ddc6d-f420-7980-b093-8dc1fd04ae68; trace=019ddc6d-f4df-7e90-9bb5-f4df1047aa54,id=019ddc6d-f4df-7e90-9bb5-f4df1047aa54

      [13/50]   ok   11.7s  calls=2  in= 9797 (cache   89%)  out= 319  acum=$0.2499

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6d-f4df-7e90-9bb5-f4df1047aa54,id=019ddc6d-f4df-7e90-9bb5-f4df1047aa54; trace=019ddc6e-1237-7482-8057-3e45c65b8ea8,id=019ddc6e-1237-7482-8057-3e45c65b8ea8
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-1237-7482-8057-3e45c65b8ea8,id=019ddc6e-1237-7482-8057-3e45c65b8ea8; trace=019ddc6e-1f6a-76a1-acd1-123106bab005,id=019ddc6e-1f6a-76a1-acd1-123106bab005; trace=019ddc6e-1f6a-76a1-acd1-123106bab005,id=019ddc6e-1f6a-76a1-acd1-123106bab005; trace=019ddc6e-2039-7940-8374-67f16c387c9c,id=019ddc6e-2039-7940-8374-67f16c387c9c

      [14/50]   ok  12.46s  calls=2  in= 8311 (cache  105%)  out= 323  acum=$0.2655

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-2039-7940-8374-67f16c387c9c,id=019ddc6e-2039-7940-8374-67f16c387c9c; trace=019ddc6e-42e1-7292-bed4-481e9f00e2b5,id=019ddc6e-42e1-7292-bed4-481e9f00e2b5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-42e1-7292-bed4-481e9f00e2b5,id=019ddc6e-42e1-7292-bed4-481e9f00e2b5; trace=019ddc6e-51c0-7e30-b6d8-14c871226030,id=019ddc6e-51c0-7e30-b6d8-14c871226030; trace=019ddc6e-51c0-7e30-b6d8-14c871226030,id=019ddc6e-51c0-7e30-b6d8-14c871226030; trace=019ddc6e-529d-7b33-b378-b3353204f42e,id=019ddc6e-529d-7b33-b378-b3353204f42e

      [15/50]   ok  17.26s  calls=2  in= 9199 (cache   95%)  out= 457  acum=$0.2831

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-529d-7b33-b378-b3353204f42e,id=019ddc6e-529d-7b33-b378-b3353204f42e; trace=019ddc6e-864b-74e2-9f72-b4ffec68e424,id=019ddc6e-864b-74e2-9f72-b4ffec68e424
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-864b-74e2-9f72-b4ffec68e424,id=019ddc6e-864b-74e2-9f72-b4ffec68e424; trace=019ddc6e-961d-75f2-8058-3f373ef44ba6,id=019ddc6e-961d-75f2-8058-3f373ef44ba6; trace=019ddc6e-961d-75f2-8058-3f373ef44ba6,id=019ddc6e-961d-75f2-8058-3f373ef44ba6; trace=019ddc6e-9620-70a1-907b-d3785f8658f0,id=019ddc6e-9620-70a1-907b-d3785f8658f0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-9620-70a1-907b-d3785f8658f0,id=019ddc6e-9620-70a1-907b-d3785f8658f0; trace=019ddc6e-aeef-7630-b406-9b7b00fe5014,id=019ddc6e-aeef-7630-b406-9b7b00fe5014; trace=019ddc6e-aeef-7630-b406-9b7b00fe5014,id=019ddc6e-aeef-7630-b406-9b7b00fe5014; trace=019ddc6e-aef6-7f12-83bf-e6780bda8ecf,id=019ddc6e-aef6-7f12-83bf-e6780bda8ecf; trace=019ddc6e-aef6-7f12-83bf-e6780bda8ecf,id=019ddc6e-aef6-7f12-83bf-e6780bda8ecf; trace=019ddc6e-aefb-7070-8add-53463a89aac4,id=019ddc6e-aefb-7070-8add-53463a89aac4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-aefb-7070-8add-53463a89aac4,id=019ddc6e-aefb-7070-8add-53463a89aac4; trace=019ddc6e-c3b8-77d3-b4ab-c9554d5f5b09,id=019ddc6e-c3b8-77d3-b4ab-c9554d5f5b09; trace=019ddc6e-c3b8-77d3-b4ab-c9554d5f5b09,id=019ddc6e-c3b8-77d3-b4ab-c9554d5f5b09; trace=019ddc6e-c42b-7480-8099-1d1fc56eaa0b,id=019ddc6e-c42b-7480-8099-1d1fc56eaa0b

      [16/50]   ok  28.63s  calls=4  in=21100 (cache  121%)  out= 711  acum=$0.3223

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-c42b-7480-8099-1d1fc56eaa0b,id=019ddc6e-c42b-7480-8099-1d1fc56eaa0b; trace=019ddc6e-f622-7150-9486-d39cba15e598,id=019ddc6e-f622-7150-9486-d39cba15e598
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6e-f622-7150-9486-d39cba15e598,id=019ddc6e-f622-7150-9486-d39cba15e598; trace=019ddc6f-04fe-7e92-b5f6-a063ba0e2364,id=019ddc6f-04fe-7e92-b5f6-a063ba0e2364; trace=019ddc6f-04fe-7e92-b5f6-a063ba0e2364,id=019ddc6f-04fe-7e92-b5f6-a063ba0e2364; trace=019ddc6f-05c8-7e00-889b-4d5e5f054776,id=019ddc6f-05c8-7e00-889b-4d5e5f054776

      [17/50]   ok  22.27s  calls=2  in= 9353 (cache   93%)  out= 722  acum=$0.3411

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-05c8-7e00-889b-4d5e5f054776,id=019ddc6f-05c8-7e00-889b-4d5e5f054776; trace=019ddc6f-4d24-7c03-bcd4-c903bb438282,id=019ddc6f-4d24-7c03-bcd4-c903bb438282
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-4d24-7c03-bcd4-c903bb438282,id=019ddc6f-4d24-7c03-bcd4-c903bb438282; trace=019ddc6f-5ae8-7bf3-97eb-30e567961aa0,id=019ddc6f-5ae8-7bf3-97eb-30e567961aa0; trace=019ddc6f-5ae8-7bf3-97eb-30e567961aa0,id=019ddc6f-5ae8-7bf3-97eb-30e567961aa0; trace=019ddc6f-5b54-7512-85f2-bc06a6ad6cbc,id=019ddc6f-5b54-7512-85f2-bc06a6ad6cbc

      [18/50]   ok  16.43s  calls=2  in= 8198 (cache  106%)  out= 484  acum=$0.3571

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-5b54-7512-85f2-bc06a6ad6cbc,id=019ddc6f-5b54-7512-85f2-bc06a6ad6cbc; trace=019ddc6f-8d53-7f71-80c9-807ae39b90cc,id=019ddc6f-8d53-7f71-80c9-807ae39b90cc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-8d53-7f71-80c9-807ae39b90cc,id=019ddc6f-8d53-7f71-80c9-807ae39b90cc; trace=019ddc6f-9b25-7740-8989-80c1e24c78c0,id=019ddc6f-9b25-7740-8989-80c1e24c78c0; trace=019ddc6f-9b25-7740-8989-80c1e24c78c0,id=019ddc6f-9b25-7740-8989-80c1e24c78c0; trace=019ddc6f-9bf2-7c32-b823-c126d3080450,id=019ddc6f-9bf2-7c32-b823-c126d3080450

      [19/50]   ok  12.89s  calls=2  in= 8658 (cache  101%)  out= 325  acum=$0.3733

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-9bf2-7c32-b823-c126d3080450,id=019ddc6f-9bf2-7c32-b823-c126d3080450; trace=019ddc6f-bfa9-7362-aa82-ed485fedfe55,id=019ddc6f-bfa9-7362-aa82-ed485fedfe55
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-bfa9-7362-aa82-ed485fedfe55,id=019ddc6f-bfa9-7362-aa82-ed485fedfe55; trace=019ddc6f-cdb7-7840-84c1-958bb615fbf1,id=019ddc6f-cdb7-7840-84c1-958bb615fbf1; trace=019ddc6f-cdb7-7840-84c1-958bb615fbf1,id=019ddc6f-cdb7-7840-84c1-958bb615fbf1; trace=019ddc6f-ce92-7d70-897a-cbf1d7f125dd,id=019ddc6f-ce92-7d70-897a-cbf1d7f125dd

      [20/50]   ok  12.08s  calls=2  in= 8739 (cache  100%)  out= 284  acum=$0.3894

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-ce92-7d70-897a-cbf1d7f125dd,id=019ddc6f-ce92-7d70-897a-cbf1d7f125dd; trace=019ddc6f-eedb-7670-984a-cabb603a7c89,id=019ddc6f-eedb-7670-984a-cabb603a7c89
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-eedb-7670-984a-cabb603a7c89,id=019ddc6f-eedb-7670-984a-cabb603a7c89; trace=019ddc6f-fd38-72b0-a257-b6bb8fed278b,id=019ddc6f-fd38-72b0-a257-b6bb8fed278b; trace=019ddc6f-fd38-72b0-a257-b6bb8fed278b,id=019ddc6f-fd38-72b0-a257-b6bb8fed278b; trace=019ddc6f-fe13-7641-977b-6ac15f39c212,id=019ddc6f-fe13-7641-977b-6ac15f39c212

      [21/50]   ok  23.99s  calls=2  in= 8036 (cache  108%)  out= 786  acum=$0.4062

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc6f-fe13-7641-977b-6ac15f39c212,id=019ddc6f-fe13-7641-977b-6ac15f39c212; trace=019ddc70-4c90-75d1-b3b4-5b641510689f,id=019ddc70-4c90-75d1-b3b4-5b641510689f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-4c90-75d1-b3b4-5b641510689f,id=019ddc70-4c90-75d1-b3b4-5b641510689f; trace=019ddc70-5b52-76c1-9bbb-3e8542091c9e,id=019ddc70-5b52-76c1-9bbb-3e8542091c9e; trace=019ddc70-5b52-76c1-9bbb-3e8542091c9e,id=019ddc70-5b52-76c1-9bbb-3e8542091c9e; trace=019ddc70-5c25-7da2-a598-1a2db328636d,id=019ddc70-5c25-7da2-a598-1a2db328636d

      [22/50]   ok  21.94s  calls=2  in= 7762 (cache  112%)  out= 624  acum=$0.4218

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-5c25-7da2-a598-1a2db328636d,id=019ddc70-5c25-7da2-a598-1a2db328636d; trace=019ddc70-a244-7483-b2ba-16664a04dddd,id=019ddc70-a244-7483-b2ba-16664a04dddd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-a244-7483-b2ba-16664a04dddd,id=019ddc70-a244-7483-b2ba-16664a04dddd; trace=019ddc70-ae3e-7c13-97ba-0010118a84eb,id=019ddc70-ae3e-7c13-97ba-0010118a84eb; trace=019ddc70-ae3e-7c13-97ba-0010118a84eb,id=019ddc70-ae3e-7c13-97ba-0010118a84eb; trace=019ddc70-af08-70d3-b255-acb9070b77b0,id=019ddc70-af08-70d3-b255-acb9070b77b0

      [23/50]   ok  10.44s  calls=2  in= 8245 (cache  106%)  out= 246  acum=$0.4370

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-af08-70d3-b255-acb9070b77b0,id=019ddc70-af08-70d3-b255-acb9070b77b0; trace=019ddc70-cb0b-7230-808b-a347128241a3,id=019ddc70-cb0b-7230-808b-a347128241a3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-cb0b-7230-808b-a347128241a3,id=019ddc70-cb0b-7230-808b-a347128241a3; trace=019ddc70-d9b9-7391-b41b-08c0e8f4f35a,id=019ddc70-d9b9-7391-b41b-08c0e8f4f35a; trace=019ddc70-d9b9-7391-b41b-08c0e8f4f35a,id=019ddc70-d9b9-7391-b41b-08c0e8f4f35a; trace=019ddc70-da80-7502-83f2-c509718b30ad,id=019ddc70-da80-7502-83f2-c509718b30ad

      [24/50]   ok  16.24s  calls=2  in= 8511 (cache  102%)  out= 405  acum=$0.4533

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc70-da80-7502-83f2-c509718b30ad,id=019ddc70-da80-7502-83f2-c509718b30ad; trace=019ddc71-0a7f-7cf0-87d5-f344196a95c2,id=019ddc71-0a7f-7cf0-87d5-f344196a95c2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-0a7f-7cf0-87d5-f344196a95c2,id=019ddc71-0a7f-7cf0-87d5-f344196a95c2; trace=019ddc71-18ed-7ac2-8aeb-bee3f24a5eb9,id=019ddc71-18ed-7ac2-8aeb-bee3f24a5eb9; trace=019ddc71-18ed-7ac2-8aeb-bee3f24a5eb9,id=019ddc71-18ed-7ac2-8aeb-bee3f24a5eb9; trace=019ddc71-19b8-7812-a2b5-946eba8bb100,id=019ddc71-19b8-7812-a2b5-946eba8bb100
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-19b8-7812-a2b5-946eba8bb100,id=019ddc71-19b8-7812-a2b5-946eba8bb100; trace=019ddc71-341c-76b2-8454-9a64a8240e0e,id=019ddc71-341c-76b2-8454-9a64a8240e0e; trace=019ddc71-341c-76b2-8454-9a64a8240e0e,id=019ddc71-341c-76b2-8454-9a64a8240e0e; trace=019ddc71-341d-76b1-a9f7-015df58007cb,id=019ddc71-341d-76b1-a9f7-015df58007cb; trace=019ddc71-341d-76b1-a9f7-015df58007cb,id=019ddc71-341d-76b1-a9f7-015df58007cb; trace=019ddc71-349f-73c0-b618-5c3faa57c0c2,id=019ddc71-349f-73c0-b618-5c3faa57c0c2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-349f-73c0-b618-5c3faa57c0c2,id=019ddc71-349f-73c0-b618-5c3faa57c0c2; trace=019ddc71-45bb-72c2-829b-d8a5a5432d2b,id=019ddc71-45bb-72c2-829b-d8a5a5432d2b; trace=019ddc71-45bb-72c2-829b-d8a5a5432d2b,id=019ddc71-45bb-72c2-829b-d8a5a5432d2b; trace=019ddc71-45bf-7020-a8a8-ed4aaaa70047,id=019ddc71-45bf-7020-a8a8-ed4aaaa70047
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-45bf-7020-a8a8-ed4aaaa70047,id=019ddc71-45bf-7020-a8a8-ed4aaaa70047; trace=019ddc71-5f79-7730-b853-aa34800f2303,id=019ddc71-5f79-7730-b853-aa34800f2303; trace=019ddc71-5f79-7730-b853-aa34800f2303,id=019ddc71-5f79-7730-b853-aa34800f2303; trace=019ddc71-5f7c-77f0-8651-2e401bd6b2b3,id=019ddc71-5f7c-77f0-8651-2e401bd6b2b3; trace=019ddc71-5f7c-77f0-8651-2e401bd6b2b3,id=019ddc71-5f7c-77f0-8651-2e401bd6b2b3; trace=019ddc71-5f7e-7043-b488-7a2ea158cedf,id=019ddc71-5f7e-7043-b488-7a2ea158cedf; trace=019ddc71-5f7e-7043-b488-7a2ea158cedf,id=019ddc71-5f7e-7043-b488-7a2ea158cedf; trace=019ddc71-5f80-7ca1-b4fb-16b9bc7c3bb3,id=019ddc71-5f80-7ca1-b4fb-16b9bc7c3bb3

      [25/50]   ok  31.09s  calls=5  in=48521 (cache  151%)  out= 812  acum=$0.5405

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-5f80-7ca1-b4fb-16b9bc7c3bb3,id=019ddc71-5f80-7ca1-b4fb-16b9bc7c3bb3; trace=019ddc71-83f2-70c2-8145-b1c936c6fae4,id=019ddc71-83f2-70c2-8145-b1c936c6fae4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-83f2-70c2-8145-b1c936c6fae4,id=019ddc71-83f2-70c2-8145-b1c936c6fae4; trace=019ddc71-9157-7611-aced-567e5a065a15,id=019ddc71-9157-7611-aced-567e5a065a15; trace=019ddc71-9157-7611-aced-567e5a065a15,id=019ddc71-9157-7611-aced-567e5a065a15; trace=019ddc71-91bb-7273-928e-fb641741a0b4,id=019ddc71-91bb-7273-928e-fb641741a0b4

      [26/50]   ok   9.87s  calls=2  in=10073 (cache   86%)  out= 250  acum=$0.5589

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-91bb-7273-928e-fb641741a0b4,id=019ddc71-91bb-7273-928e-fb641741a0b4; trace=019ddc71-aa82-7f43-b4af-c9c13d7f85be,id=019ddc71-aa82-7f43-b4af-c9c13d7f85be
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-aa82-7f43-b4af-c9c13d7f85be,id=019ddc71-aa82-7f43-b4af-c9c13d7f85be; trace=019ddc71-b957-7072-bc0d-e53af5bc851c,id=019ddc71-b957-7072-bc0d-e53af5bc851c; trace=019ddc71-b957-7072-bc0d-e53af5bc851c,id=019ddc71-b957-7072-bc0d-e53af5bc851c; trace=019ddc71-ba25-7641-aa5f-56f0d8a67314,id=019ddc71-ba25-7641-aa5f-56f0d8a67314
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-ba25-7641-aa5f-56f0d8a67314,id=019ddc71-ba25-7641-aa5f-56f0d8a67314; trace=019ddc71-d692-7cb3-bdba-fb0faa880dcc,id=019ddc71-d692-7cb3-bdba-fb0faa880dcc; trace=019ddc71-d692-7cb3-bdba-fb0faa880dcc,id=019ddc71-d692-7cb3-bdba-fb0faa880dcc; trace=019ddc71-d761-7d43-a79b-c3d2807ac6e2,id=019ddc71-d761-7d43-a79b-c3d2807ac6e2; trace=019ddc71-d761-7d43-a79b-c3d2807ac6e2,id=019ddc71-d761-7d43-a79b-c3d2807ac6e2; trace=019ddc71-d763-7b21-bfcd-586dcce68d15,id=019ddc71-d763-7b21-bfcd-586dcce68d15
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-d763-7b21-bfcd-586dcce68d15,id=019ddc71-d763-7b21-bfcd-586dcce68d15; trace=019ddc71-efbc-7e03-9449-8c3de39b691b,id=019ddc71-efbc-7e03-9449-8c3de39b691b; trace=019ddc71-efbc-7e03-9449-8c3de39b691b,id=019ddc71-efbc-7e03-9449-8c3de39b691b; trace=019ddc71-efc8-7b03-a4d0-f5fa2adb1e2b,id=019ddc71-efc8-7b03-a4d0-f5fa2adb1e2b; trace=019ddc71-efc8-7b03-a4d0-f5fa2adb1e2b,id=019ddc71-efc8-7b03-a4d0-f5fa2adb1e2b; trace=019ddc71-efcc-7ff0-80d6-2f0515831c55,id=019ddc71-efcc-7ff0-80d6-2f0515831c55

      [27/50]   ok  29.85s  calls=4  in=33134 (cache  137%)  out= 753  acum=$0.6192

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc71-efcc-7ff0-80d6-2f0515831c55,id=019ddc71-efcc-7ff0-80d6-2f0515831c55; trace=019ddc72-1f21-7c12-8210-2923643f962c,id=019ddc72-1f21-7c12-8210-2923643f962c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-1f21-7c12-8210-2923643f962c,id=019ddc72-1f21-7c12-8210-2923643f962c; trace=019ddc72-2d58-7233-ae77-a86a1a876ff5,id=019ddc72-2d58-7233-ae77-a86a1a876ff5; trace=019ddc72-2d58-7233-ae77-a86a1a876ff5,id=019ddc72-2d58-7233-ae77-a86a1a876ff5; trace=019ddc72-2e2e-76f3-b614-a7a7ac3fd8d9,id=019ddc72-2e2e-76f3-b614-a7a7ac3fd8d9

      [28/50]   ok  21.86s  calls=2  in= 8461 (cache  103%)  out= 697  acum=$0.6363

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-2e2e-76f3-b614-a7a7ac3fd8d9,id=019ddc72-2e2e-76f3-b614-a7a7ac3fd8d9; trace=019ddc72-7486-71a0-b21e-ab9ab117ae09,id=019ddc72-7486-71a0-b21e-ab9ab117ae09
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-7486-71a0-b21e-ab9ab117ae09,id=019ddc72-7486-71a0-b21e-ab9ab117ae09; trace=019ddc72-81e9-72f2-8c3c-0d98d7510d90,id=019ddc72-81e9-72f2-8c3c-0d98d7510d90; trace=019ddc72-81e9-72f2-8c3c-0d98d7510d90,id=019ddc72-81e9-72f2-8c3c-0d98d7510d90; trace=019ddc72-82c7-7110-ba5e-41c2973c1f77,id=019ddc72-82c7-7110-ba5e-41c2973c1f77
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-82c7-7110-ba5e-41c2973c1f77,id=019ddc72-82c7-7110-ba5e-41c2973c1f77; trace=019ddc72-9e0b-7062-a705-9b05b3d9132f,id=019ddc72-9e0b-7062-a705-9b05b3d9132f; trace=019ddc72-9e0b-7062-a705-9b05b3d9132f,id=019ddc72-9e0b-7062-a705-9b05b3d9132f; trace=019ddc72-9ee0-7ef3-8b94-6a651ed33bed,id=019ddc72-9ee0-7ef3-8b94-6a651ed33bed; trace=019ddc72-9ee0-7ef3-8b94-6a651ed33bed,id=019ddc72-9ee0-7ef3-8b94-6a651ed33bed; trace=019ddc72-9ee2-79b3-9763-d44abe8fc569,id=019ddc72-9ee2-79b3-9763-d44abe8fc569
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-9ee2-79b3-9763-d44abe8fc569,id=019ddc72-9ee2-79b3-9763-d44abe8fc569; trace=019ddc72-bc8f-7c12-88c5-bded428fb49c,id=019ddc72-bc8f-7c12-88c5-bded428fb49c; trace=019ddc72-bc8f-7c12-88c5-bded428fb49c,id=019ddc72-bc8f-7c12-88c5-bded428fb49c; trace=019ddc72-bc92-7a20-b555-c2f89c11e005,id=019ddc72-bc92-7a20-b555-c2f89c11e005; trace=019ddc72-bc92-7a20-b555-c2f89c11e005,id=019ddc72-bc92-7a20-b555-c2f89c11e005; trace=019ddc72-bc94-7633-bb8b-16a5dce9bf19,id=019ddc72-bc94-7633-bb8b-16a5dce9bf19; trace=019ddc72-bc94-7633-bb8b-16a5dce9bf19,id=019ddc72-bc94-7633-bb8b-16a5dce9bf19; trace=019ddc72-bc96-7bd2-814e-f04ade863012,id=019ddc72-bc96-7bd2-814e-f04ade863012
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-bc96-7bd2-814e-f04ade863012,id=019ddc72-bc96-7bd2-814e-f04ade863012; trace=019ddc72-d828-7820-b08b-751ec5e1828f,id=019ddc72-d828-7820-b08b-751ec5e1828f; trace=019ddc72-d828-7820-b08b-751ec5e1828f,id=019ddc72-d828-7820-b08b-751ec5e1828f; trace=019ddc72-d82a-7d62-b1bb-a50c35d7558c,id=019ddc72-d82a-7d62-b1bb-a50c35d7558c; trace=019ddc72-d82a-7d62-b1bb-a50c35d7558c,id=019ddc72-d82a-7d62-b1bb-a50c35d7558c; trace=019ddc72-d898-7a52-9b27-1b8d4b8ab5db,id=019ddc72-d898-7a52-9b27-1b8d4b8ab5db

      [29/50]   ok  36.93s  calls=5  in=51911 (cache  139%)  out=1031  acum=$0.7302

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc72-d898-7a52-9b27-1b8d4b8ab5db,id=019ddc72-d898-7a52-9b27-1b8d4b8ab5db; trace=019ddc73-04cc-7641-a45a-d3dc42d45137,id=019ddc73-04cc-7641-a45a-d3dc42d45137
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-04cc-7641-a45a-d3dc42d45137,id=019ddc73-04cc-7641-a45a-d3dc42d45137; trace=019ddc73-134f-7b22-8aa4-a8fd097cddbf,id=019ddc73-134f-7b22-8aa4-a8fd097cddbf; trace=019ddc73-134f-7b22-8aa4-a8fd097cddbf,id=019ddc73-134f-7b22-8aa4-a8fd097cddbf; trace=019ddc73-13b3-78e2-8efb-790e5dcf4698,id=019ddc73-13b3-78e2-8efb-790e5dcf4698

      [30/50]   ok  14.99s  calls=2  in= 8355 (cache  104%)  out= 452  acum=$0.7464

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-13b3-78e2-8efb-790e5dcf4698,id=019ddc73-13b3-78e2-8efb-790e5dcf4698; trace=019ddc73-3f5e-7c90-b0f9-167edc50b41f,id=019ddc73-3f5e-7c90-b0f9-167edc50b41f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-3f5e-7c90-b0f9-167edc50b41f,id=019ddc73-3f5e-7c90-b0f9-167edc50b41f; trace=019ddc73-5095-77c3-a446-425cc262c658,id=019ddc73-5095-77c3-a446-425cc262c658; trace=019ddc73-5095-77c3-a446-425cc262c658,id=019ddc73-5095-77c3-a446-425cc262c658; trace=019ddc73-5125-7550-a32c-a6dfd2e80051,id=019ddc73-5125-7550-a32c-a6dfd2e80051

      [31/50]   ok  20.38s  calls=2  in= 8058 (cache  108%)  out= 570  acum=$0.7624

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-5125-7550-a32c-a6dfd2e80051,id=019ddc73-5125-7550-a32c-a6dfd2e80051; trace=019ddc73-8efa-7083-b088-0b2b184de9fa,id=019ddc73-8efa-7083-b088-0b2b184de9fa
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-8efa-7083-b088-0b2b184de9fa,id=019ddc73-8efa-7083-b088-0b2b184de9fa; trace=019ddc73-9eaa-7831-ad7a-8d2adc8abe35,id=019ddc73-9eaa-7831-ad7a-8d2adc8abe35; trace=019ddc73-9eaa-7831-ad7a-8d2adc8abe35,id=019ddc73-9eaa-7831-ad7a-8d2adc8abe35; trace=019ddc73-9f88-7ef2-81eb-4892f4776d58,id=019ddc73-9f88-7ef2-81eb-4892f4776d58

      [32/50]   ok  14.54s  calls=2  in= 9537 (cache   91%)  out= 353  acum=$0.7802

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-9f88-7ef2-81eb-4892f4776d58,id=019ddc73-9f88-7ef2-81eb-4892f4776d58; trace=019ddc73-c7c9-7113-8239-f047e84dd115,id=019ddc73-c7c9-7113-8239-f047e84dd115
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-c7c9-7113-8239-f047e84dd115,id=019ddc73-c7c9-7113-8239-f047e84dd115; trace=019ddc73-d5be-7b70-8bd2-95aa10aaf0fb,id=019ddc73-d5be-7b70-8bd2-95aa10aaf0fb; trace=019ddc73-d5be-7b70-8bd2-95aa10aaf0fb,id=019ddc73-d5be-7b70-8bd2-95aa10aaf0fb; trace=019ddc73-d672-7c91-8a58-076b49b4a050,id=019ddc73-d672-7c91-8a58-076b49b4a050

      [33/50]   ok  14.13s  calls=2  in= 8323 (cache  105%)  out= 368  acum=$0.7959

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-d672-7c91-8a58-076b49b4a050,id=019ddc73-d672-7c91-8a58-076b49b4a050; trace=019ddc73-fefb-7843-8724-dce50fb59f1d,id=019ddc73-fefb-7843-8724-dce50fb59f1d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc73-fefb-7843-8724-dce50fb59f1d,id=019ddc73-fefb-7843-8724-dce50fb59f1d; trace=019ddc74-0d61-7270-af77-5fbcfbeedccc,id=019ddc74-0d61-7270-af77-5fbcfbeedccc; trace=019ddc74-0d61-7270-af77-5fbcfbeedccc,id=019ddc74-0d61-7270-af77-5fbcfbeedccc; trace=019ddc74-0e4b-7183-881a-08ba1e0c56fa,id=019ddc74-0e4b-7183-881a-08ba1e0c56fa

      [34/50]   ok  12.05s  calls=2  in= 8032 (cache  108%)  out= 297  acum=$0.8110

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-0e4b-7183-881a-08ba1e0c56fa,id=019ddc74-0e4b-7183-881a-08ba1e0c56fa; trace=019ddc74-2e0c-7701-a0d2-3962b4de56d1,id=019ddc74-2e0c-7701-a0d2-3962b4de56d1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-2e0c-7701-a0d2-3962b4de56d1,id=019ddc74-2e0c-7701-a0d2-3962b4de56d1; trace=019ddc74-3c2f-7a91-995e-b81ac6e1cd22,id=019ddc74-3c2f-7a91-995e-b81ac6e1cd22; trace=019ddc74-3c2f-7a91-995e-b81ac6e1cd22,id=019ddc74-3c2f-7a91-995e-b81ac6e1cd22; trace=019ddc74-3ceb-7903-a4ef-ea0d837a9c0a,id=019ddc74-3ceb-7903-a4ef-ea0d837a9c0a

      [35/50]   ok  12.94s  calls=2  in= 8818 (cache   99%)  out= 295  acum=$0.8273

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-3ceb-7903-a4ef-ea0d837a9c0a,id=019ddc74-3ceb-7903-a4ef-ea0d837a9c0a; trace=019ddc74-6097-7923-9884-eb5bee4fbfbe,id=019ddc74-6097-7923-9884-eb5bee4fbfbe
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-6097-7923-9884-eb5bee4fbfbe,id=019ddc74-6097-7923-9884-eb5bee4fbfbe; trace=019ddc74-70cc-7483-b0f8-fdebb81b2656,id=019ddc74-70cc-7483-b0f8-fdebb81b2656; trace=019ddc74-70cc-7483-b0f8-fdebb81b2656,id=019ddc74-70cc-7483-b0f8-fdebb81b2656; trace=019ddc74-71a5-7e03-a82c-4f87e24d55f1,id=019ddc74-71a5-7e03-a82c-4f87e24d55f1

      [36/50]   ok   12.8s  calls=2  in= 9700 (cache   90%)  out= 320  acum=$0.8453

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-71a5-7e03-a82c-4f87e24d55f1,id=019ddc74-71a5-7e03-a82c-4f87e24d55f1; trace=019ddc74-929b-77f2-ab76-b54723db6666,id=019ddc74-929b-77f2-ab76-b54723db6666
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-929b-77f2-ab76-b54723db6666,id=019ddc74-929b-77f2-ab76-b54723db6666; trace=019ddc74-a22f-7eb3-8688-fa5c4303c4bc,id=019ddc74-a22f-7eb3-8688-fa5c4303c4bc; trace=019ddc74-a22f-7eb3-8688-fa5c4303c4bc,id=019ddc74-a22f-7eb3-8688-fa5c4303c4bc; trace=019ddc74-a30e-7cd2-9b1d-d2011582e679,id=019ddc74-a30e-7cd2-9b1d-d2011582e679
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-a30e-7cd2-9b1d-d2011582e679,id=019ddc74-a30e-7cd2-9b1d-d2011582e679; trace=019ddc74-ba34-7890-b10a-88c6c9abda59,id=019ddc74-ba34-7890-b10a-88c6c9abda59; trace=019ddc74-ba34-7890-b10a-88c6c9abda59,id=019ddc74-ba34-7890-b10a-88c6c9abda59; trace=019ddc74-ba41-75c3-b666-0e0ff790f501,id=019ddc74-ba41-75c3-b666-0e0ff790f501
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-ba41-75c3-b666-0e0ff790f501,id=019ddc74-ba41-75c3-b666-0e0ff790f501; trace=019ddc74-ce49-71d1-a228-305a2116366c,id=019ddc74-ce49-71d1-a228-305a2116366c; trace=019ddc74-ce49-71d1-a228-305a2116366c,id=019ddc74-ce49-71d1-a228-305a2116366c; trace=019ddc74-cf12-7603-82f3-aa024a1088cb,id=019ddc74-cf12-7603-82f3-aa024a1088cb

      [37/50]   ok  47.69s  calls=4  in=31423 (cache  128%)  out=1326  acum=$0.9046

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc74-cf12-7603-82f3-aa024a1088cb,id=019ddc74-cf12-7603-82f3-aa024a1088cb; trace=019ddc75-4ce5-7ec2-a32b-92d33cfb7ff5,id=019ddc75-4ce5-7ec2-a32b-92d33cfb7ff5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-4ce5-7ec2-a32b-92d33cfb7ff5,id=019ddc75-4ce5-7ec2-a32b-92d33cfb7ff5; trace=019ddc75-5ae8-7d10-9539-84a73c4a18bd,id=019ddc75-5ae8-7d10-9539-84a73c4a18bd; trace=019ddc75-5ae8-7d10-9539-84a73c4a18bd,id=019ddc75-5ae8-7d10-9539-84a73c4a18bd; trace=019ddc75-5bc3-7ff3-b1a0-5f7f2f80edf6,id=019ddc75-5bc3-7ff3-b1a0-5f7f2f80edf6

      [38/50]   ok  16.05s  calls=2  in= 8054 (cache  108%)  out= 403  acum=$0.9200

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-5bc3-7ff3-b1a0-5f7f2f80edf6,id=019ddc75-5bc3-7ff3-b1a0-5f7f2f80edf6; trace=019ddc75-8b9b-7693-beda-c3fa2eda80ea,id=019ddc75-8b9b-7693-beda-c3fa2eda80ea
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-8b9b-7693-beda-c3fa2eda80ea,id=019ddc75-8b9b-7693-beda-c3fa2eda80ea; trace=019ddc75-99ce-7f32-831e-7410c642f491,id=019ddc75-99ce-7f32-831e-7410c642f491; trace=019ddc75-99ce-7f32-831e-7410c642f491,id=019ddc75-99ce-7f32-831e-7410c642f491; trace=019ddc75-9aa1-7903-9605-1a6f1511d2c3,id=019ddc75-9aa1-7903-9605-1a6f1511d2c3

      [39/50]   ok  17.57s  calls=2  in= 8106 (cache  107%)  out= 446  acum=$0.9357

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-9aa1-7903-9605-1a6f1511d2c3,id=019ddc75-9aa1-7903-9605-1a6f1511d2c3; trace=019ddc75-d03e-7c93-bafe-dea3a59fa0b6,id=019ddc75-d03e-7c93-bafe-dea3a59fa0b6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-d03e-7c93-bafe-dea3a59fa0b6,id=019ddc75-d03e-7c93-bafe-dea3a59fa0b6; trace=019ddc75-dfcc-7683-8ee2-ac81b996d6ff,id=019ddc75-dfcc-7683-8ee2-ac81b996d6ff; trace=019ddc75-dfcc-7683-8ee2-ac81b996d6ff,id=019ddc75-dfcc-7683-8ee2-ac81b996d6ff; trace=019ddc75-e02a-7692-9f91-d0ebb103d8aa,id=019ddc75-e02a-7692-9f91-d0ebb103d8aa

      [40/50]   ok  14.53s  calls=2  in=10660 (cache   82%)  out= 372  acum=$0.9555

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc75-e02a-7692-9f91-d0ebb103d8aa,id=019ddc75-e02a-7692-9f91-d0ebb103d8aa; trace=019ddc76-0901-7e10-b6f2-8aff1d9f9db2,id=019ddc76-0901-7e10-b6f2-8aff1d9f9db2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-0901-7e10-b6f2-8aff1d9f9db2,id=019ddc76-0901-7e10-b6f2-8aff1d9f9db2; trace=019ddc76-1969-7102-ad4e-6fc5cbed01d5,id=019ddc76-1969-7102-ad4e-6fc5cbed01d5; trace=019ddc76-1969-7102-ad4e-6fc5cbed01d5,id=019ddc76-1969-7102-ad4e-6fc5cbed01d5; trace=019ddc76-1a47-7961-af4d-190f9511471a,id=019ddc76-1a47-7961-af4d-190f9511471a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-1a47-7961-af4d-190f9511471a,id=019ddc76-1a47-7961-af4d-190f9511471a; trace=019ddc76-31ce-74e1-8e20-f03d05a5b0b3,id=019ddc76-31ce-74e1-8e20-f03d05a5b0b3; trace=019ddc76-31ce-74e1-8e20-f03d05a5b0b3,id=019ddc76-31ce-74e1-8e20-f03d05a5b0b3; trace=019ddc76-3241-7cb1-ba33-45546cd2b9c7,id=019ddc76-3241-7cb1-ba33-45546cd2b9c7; trace=019ddc76-3241-7cb1-ba33-45546cd2b9c7,id=019ddc76-3241-7cb1-ba33-45546cd2b9c7; trace=019ddc76-3243-7a43-a72e-12601398a266,id=019ddc76-3243-7a43-a72e-12601398a266
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-3243-7a43-a72e-12601398a266,id=019ddc76-3243-7a43-a72e-12601398a266; trace=019ddc76-4e35-7510-ac4f-46dd511a474f,id=019ddc76-4e35-7510-ac4f-46dd511a474f; trace=019ddc76-4e35-7510-ac4f-46dd511a474f,id=019ddc76-4e35-7510-ac4f-46dd511a474f; trace=019ddc76-4e36-7062-b7b5-ffbbea0ee618,id=019ddc76-4e36-7062-b7b5-ffbbea0ee618; trace=019ddc76-4e36-7062-b7b5-ffbbea0ee618,id=019ddc76-4e36-7062-b7b5-ffbbea0ee618; trace=019ddc76-4e40-7851-a497-506b4c899a58,id=019ddc76-4e40-7851-a497-506b4c899a58
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-4e40-7851-a497-506b4c899a58,id=019ddc76-4e40-7851-a497-506b4c899a58; trace=019ddc76-622a-7e41-a3a1-0139bbb4b729,id=019ddc76-622a-7e41-a3a1-0139bbb4b729; trace=019ddc76-622a-7e41-a3a1-0139bbb4b729,id=019ddc76-622a-7e41-a3a1-0139bbb4b729; trace=019ddc76-6306-7693-b5b2-bb1f9ae7b766,id=019ddc76-6306-7693-b5b2-bb1f9ae7b766

      [41/50]   ok   42.0s  calls=5  in=52390 (cache  143%)  out=1105  acum=$1.0505

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-6306-7693-b5b2-bb1f9ae7b766,id=019ddc76-6306-7693-b5b2-bb1f9ae7b766; trace=019ddc76-ad0f-7430-993a-d2cf93feeae1,id=019ddc76-ad0f-7430-993a-d2cf93feeae1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-ad0f-7430-993a-d2cf93feeae1,id=019ddc76-ad0f-7430-993a-d2cf93feeae1; trace=019ddc76-b8ee-7fe2-a22e-e3f95691c363,id=019ddc76-b8ee-7fe2-a22e-e3f95691c363; trace=019ddc76-b8ee-7fe2-a22e-e3f95691c363,id=019ddc76-b8ee-7fe2-a22e-e3f95691c363; trace=019ddc76-b9bf-7620-a3ed-db174ea5b3d5,id=019ddc76-b9bf-7620-a3ed-db174ea5b3d5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-b9bf-7620-a3ed-db174ea5b3d5,id=019ddc76-b9bf-7620-a3ed-db174ea5b3d5; trace=019ddc76-ca38-7be2-a5bc-5f64179efd6d,id=019ddc76-ca38-7be2-a5bc-5f64179efd6d; trace=019ddc76-ca38-7be2-a5bc-5f64179efd6d,id=019ddc76-ca38-7be2-a5bc-5f64179efd6d; trace=019ddc76-ca3b-78f3-a0aa-5ebeee53d5b4,id=019ddc76-ca3b-78f3-a0aa-5ebeee53d5b4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-ca3b-78f3-a0aa-5ebeee53d5b4,id=019ddc76-ca3b-78f3-a0aa-5ebeee53d5b4; trace=019ddc76-e217-7153-85a5-b0d5e1218a70,id=019ddc76-e217-7153-85a5-b0d5e1218a70; trace=019ddc76-e217-7153-85a5-b0d5e1218a70,id=019ddc76-e217-7153-85a5-b0d5e1218a70; trace=019ddc76-e21a-7272-b94c-ece528fd8c65,id=019ddc76-e21a-7272-b94c-ece528fd8c65; trace=019ddc76-e21a-7272-b94c-ece528fd8c65,id=019ddc76-e21a-7272-b94c-ece528fd8c65; trace=019ddc76-e2b8-7023-be76-4a99337d4d8d,id=019ddc76-e2b8-7023-be76-4a99337d4d8d

      [42/50]   ok  22.76s  calls=4  in=28527 (cache  133%)  out= 605  acum=$1.1023

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc76-e2b8-7023-be76-4a99337d4d8d,id=019ddc76-e2b8-7023-be76-4a99337d4d8d; trace=019ddc77-05f6-7391-851b-1b67c502d3b0,id=019ddc77-05f6-7391-851b-1b67c502d3b0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-05f6-7391-851b-1b67c502d3b0,id=019ddc77-05f6-7391-851b-1b67c502d3b0; trace=019ddc77-1370-74a3-b118-643fd0b79eb7,id=019ddc77-1370-74a3-b118-643fd0b79eb7; trace=019ddc77-1370-74a3-b118-643fd0b79eb7,id=019ddc77-1370-74a3-b118-643fd0b79eb7; trace=019ddc77-143c-7032-bb2d-e687724f121f,id=019ddc77-143c-7032-bb2d-e687724f121f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-143c-7032-bb2d-e687724f121f,id=019ddc77-143c-7032-bb2d-e687724f121f; trace=019ddc77-2907-7c31-b11e-b306993b0d01,id=019ddc77-2907-7c31-b11e-b306993b0d01; trace=019ddc77-2907-7c31-b11e-b306993b0d01,id=019ddc77-2907-7c31-b11e-b306993b0d01; trace=019ddc77-290a-7640-830c-331dbeb2327b,id=019ddc77-290a-7640-830c-331dbeb2327b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-290a-7640-830c-331dbeb2327b,id=019ddc77-290a-7640-830c-331dbeb2327b; trace=019ddc77-3aa0-76f0-9329-ad4c24749903,id=019ddc77-3aa0-76f0-9329-ad4c24749903; trace=019ddc77-3aa0-76f0-9329-ad4c24749903,id=019ddc77-3aa0-76f0-9329-ad4c24749903; trace=019ddc77-3aa3-7b02-a28e-aec00f7ce3e1,id=019ddc77-3aa3-7b02-a28e-aec00f7ce3e1

      [43/50]   ok   22.6s  calls=4  in=25646 (cache  151%)  out= 585  acum=$1.1489

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-3aa3-7b02-a28e-aec00f7ce3e1,id=019ddc77-3aa3-7b02-a28e-aec00f7ce3e1; trace=019ddc77-5e3f-7c33-b355-4f35394bb3cf,id=019ddc77-5e3f-7c33-b355-4f35394bb3cf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-5e3f-7c33-b355-4f35394bb3cf,id=019ddc77-5e3f-7c33-b355-4f35394bb3cf; trace=019ddc77-6d6b-76e3-88c1-be340ae41cc2,id=019ddc77-6d6b-76e3-88c1-be340ae41cc2; trace=019ddc77-6d6b-76e3-88c1-be340ae41cc2,id=019ddc77-6d6b-76e3-88c1-be340ae41cc2; trace=019ddc77-6dc6-7ad2-924d-10b9a9dd9578,id=019ddc77-6dc6-7ad2-924d-10b9a9dd9578
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-6dc6-7ad2-924d-10b9a9dd9578,id=019ddc77-6dc6-7ad2-924d-10b9a9dd9578; trace=019ddc77-88a0-76f2-8628-cdb203a6e319,id=019ddc77-88a0-76f2-8628-cdb203a6e319; trace=019ddc77-88a0-76f2-8628-cdb203a6e319,id=019ddc77-88a0-76f2-8628-cdb203a6e319; trace=019ddc77-8961-72a3-942c-8090cd3b6f60,id=019ddc77-8961-72a3-942c-8090cd3b6f60; trace=019ddc77-8961-72a3-942c-8090cd3b6f60,id=019ddc77-8961-72a3-942c-8090cd3b6f60; trace=019ddc77-8962-7eb0-be62-d58886f29941,id=019ddc77-8962-7eb0-be62-d58886f29941
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-8962-7eb0-be62-d58886f29941,id=019ddc77-8962-7eb0-be62-d58886f29941; trace=019ddc77-a96f-7693-ba99-9d4c725c45fc,id=019ddc77-a96f-7693-ba99-9d4c725c45fc; trace=019ddc77-a96f-7693-ba99-9d4c725c45fc,id=019ddc77-a96f-7693-ba99-9d4c725c45fc; trace=019ddc77-a971-7e62-95a8-e91a1cf5b510,id=019ddc77-a971-7e62-95a8-e91a1cf5b510; trace=019ddc77-a971-7e62-95a8-e91a1cf5b510,id=019ddc77-a971-7e62-95a8-e91a1cf5b510; trace=019ddc77-a974-7070-b270-2196926ae4e6,id=019ddc77-a974-7070-b270-2196926ae4e6

      [44/50]   ok  29.39s  calls=4  in=37414 (cache  131%)  out= 770  acum=$1.2167

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-a974-7070-b270-2196926ae4e6,id=019ddc77-a974-7070-b270-2196926ae4e6; trace=019ddc77-d10c-7a42-ab26-5eb9cb599829,id=019ddc77-d10c-7a42-ab26-5eb9cb599829
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-d10c-7a42-ab26-5eb9cb599829,id=019ddc77-d10c-7a42-ab26-5eb9cb599829; trace=019ddc77-e7d8-7533-b344-4cb8d83ab67d,id=019ddc77-e7d8-7533-b344-4cb8d83ab67d; trace=019ddc77-e7d8-7533-b344-4cb8d83ab67d,id=019ddc77-e7d8-7533-b344-4cb8d83ab67d; trace=019ddc77-e8a9-7713-a61f-9432a2cb13ed,id=019ddc77-e8a9-7713-a61f-9432a2cb13ed; trace=019ddc77-e8a9-7713-a61f-9432a2cb13ed,id=019ddc77-e8a9-7713-a61f-9432a2cb13ed; trace=019ddc77-e8ab-7843-bfc9-df4297308908,id=019ddc77-e8ab-7843-bfc9-df4297308908
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc77-e8ab-7843-bfc9-df4297308908,id=019ddc77-e8ab-7843-bfc9-df4297308908; trace=019ddc78-01d8-7101-b832-f2bfa191381e,id=019ddc78-01d8-7101-b832-f2bfa191381e; trace=019ddc78-01d8-7101-b832-f2bfa191381e,id=019ddc78-01d8-7101-b832-f2bfa191381e; trace=019ddc78-01dc-77f2-ad3b-fa0234783898,id=019ddc78-01dc-77f2-ad3b-fa0234783898; trace=019ddc78-01dc-77f2-ad3b-fa0234783898,id=019ddc78-01dc-77f2-ad3b-fa0234783898; trace=019ddc78-01df-7593-8d57-bf540fca4c64,id=019ddc78-01df-7593-8d57-bf540fca4c64

      [45/50]   ok  38.89s  calls=3  in=23826 (cache  113%)  out=1148  acum=$1.2622

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-01df-7593-8d57-bf540fca4c64,id=019ddc78-01df-7593-8d57-bf540fca4c64; trace=019ddc78-68fa-7e42-a0fe-5008cddae00a,id=019ddc78-68fa-7e42-a0fe-5008cddae00a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-68fa-7e42-a0fe-5008cddae00a,id=019ddc78-68fa-7e42-a0fe-5008cddae00a; trace=019ddc78-7970-7102-8feb-c6fd572343d4,id=019ddc78-7970-7102-8feb-c6fd572343d4; trace=019ddc78-7970-7102-8feb-c6fd572343d4,id=019ddc78-7970-7102-8feb-c6fd572343d4; trace=019ddc78-7972-7212-9c4c-d043782024df,id=019ddc78-7972-7212-9c4c-d043782024df; trace=019ddc78-7972-7212-9c4c-d043782024df,id=019ddc78-7972-7212-9c4c-d043782024df; trace=019ddc78-7a3f-7eb1-a136-72e83df1621a,id=019ddc78-7a3f-7eb1-a136-72e83df1621a

      [46/50]   ok  12.61s  calls=2  in= 9315 (cache   93%)  out= 316  acum=$1.2795

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-7a3f-7eb1-a136-72e83df1621a,id=019ddc78-7a3f-7eb1-a136-72e83df1621a; trace=019ddc78-9a3e-7aa2-a0dd-2991382d9abc,id=019ddc78-9a3e-7aa2-a0dd-2991382d9abc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-9a3e-7aa2-a0dd-2991382d9abc,id=019ddc78-9a3e-7aa2-a0dd-2991382d9abc; trace=019ddc78-ac07-7580-9e58-4c4cb40fc566,id=019ddc78-ac07-7580-9e58-4c4cb40fc566; trace=019ddc78-ac07-7580-9e58-4c4cb40fc566,id=019ddc78-ac07-7580-9e58-4c4cb40fc566; trace=019ddc78-acdc-73b0-886d-a129b12eeeb3,id=019ddc78-acdc-73b0-886d-a129b12eeeb3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-acdc-73b0-886d-a129b12eeeb3,id=019ddc78-acdc-73b0-886d-a129b12eeeb3; trace=019ddc78-bdda-7b12-9848-dd875eb4e1a5,id=019ddc78-bdda-7b12-9848-dd875eb4e1a5; trace=019ddc78-bdda-7b12-9848-dd875eb4e1a5,id=019ddc78-bdda-7b12-9848-dd875eb4e1a5; trace=019ddc78-bddd-7b20-a31e-0abf1a2d08a4,id=019ddc78-bddd-7b20-a31e-0abf1a2d08a4

      [47/50]   ok  24.79s  calls=3  in=16832 (cache  134%)  out= 670  acum=$1.3111

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-bddd-7b20-a31e-0abf1a2d08a4,id=019ddc78-bddd-7b20-a31e-0abf1a2d08a4; trace=019ddc78-fb0f-7782-80e3-c2fea916443a,id=019ddc78-fb0f-7782-80e3-c2fea916443a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc78-fb0f-7782-80e3-c2fea916443a,id=019ddc78-fb0f-7782-80e3-c2fea916443a; trace=019ddc79-0961-7d51-9d71-ee467dfd09ff,id=019ddc79-0961-7d51-9d71-ee467dfd09ff; trace=019ddc79-0961-7d51-9d71-ee467dfd09ff,id=019ddc79-0961-7d51-9d71-ee467dfd09ff; trace=019ddc79-0a2e-7011-9320-103d60a72d8b,id=019ddc79-0a2e-7011-9320-103d60a72d8b

      [48/50]   ok  11.77s  calls=2  in= 8433 (cache  103%)  out= 270  acum=$1.3267

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-0a2e-7011-9320-103d60a72d8b,id=019ddc79-0a2e-7011-9320-103d60a72d8b; trace=019ddc79-290d-7f61-a88a-de3a9e5b962a,id=019ddc79-290d-7f61-a88a-de3a9e5b962a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-290d-7f61-a88a-de3a9e5b962a,id=019ddc79-290d-7f61-a88a-de3a9e5b962a; trace=019ddc79-34ec-74c1-97a4-e470071079f8,id=019ddc79-34ec-74c1-97a4-e470071079f8; trace=019ddc79-34ec-74c1-97a4-e470071079f8,id=019ddc79-34ec-74c1-97a4-e470071079f8; trace=019ddc79-35aa-7db3-8b23-d70c4853205b,id=019ddc79-35aa-7db3-8b23-d70c4853205b

      [49/50]   ok  22.63s  calls=2  in= 8500 (cache  102%)  out= 652  acum=$1.3438

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-35aa-7db3-8b23-d70c4853205b,id=019ddc79-35aa-7db3-8b23-d70c4853205b; trace=019ddc79-8176-7b51-8d9b-0f4bbaee9c65,id=019ddc79-8176-7b51-8d9b-0f4bbaee9c65
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-8176-7b51-8d9b-0f4bbaee9c65,id=019ddc79-8176-7b51-8d9b-0f4bbaee9c65; trace=019ddc79-9242-7bc1-9411-2f245027977e,id=019ddc79-9242-7bc1-9411-2f245027977e; trace=019ddc79-9242-7bc1-9411-2f245027977e,id=019ddc79-9242-7bc1-9411-2f245027977e; trace=019ddc79-932b-7da0-9d76-e63e2cada10d,id=019ddc79-932b-7da0-9d76-e63e2cada10d

      [50/50]   ok  25.15s  calls=2  in= 8284 (cache  108%)  out= 748  acum=$1.3608
       ✓ ok — salvo em petrobras__deepseek__deepseek-v4-pro__20260430_004108.xlsx

[run]  anthropic/claude-haiku-4-5 × bndes (id=1)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-932b-7da0-9d76-e63e2cada10d,id=019ddc79-932b-7da0-9d76-e63e2cada10d; trace=019ddc79-e3e0-7621-871a-f5de2b5e2146,id=019ddc79-e3e0-7621-871a-f5de2b5e2146
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-e3e0-7621-871a-f5de2b5e2146,id=019ddc79-e3e0-7621-871a-f5de2b5e2146; trace=019ddc79-ea2c-72e0-9257-4d1d8a6bf40a,id=019ddc79-ea2c-72e0-9257-4d1d8a6bf40a; trace=019ddc79-ea2c-72e0-9257-4d1d8a6bf40a,id=019ddc79-ea2c-72e0-9257-4d1d8a6bf40a; trace=019ddc79-eb05-7b41-99d2-a649a24e6070,id=019ddc79-eb05-7b41-99d2-a649a24e6070; trace=019ddc79-eb05-7b41-99d2-a649a24e6070,id=019ddc79-eb05-7b41-99d2-a649a24e6070; trace=019ddc79-eb07-7100-88cf-2ea07163f9fb,id=019ddc79-eb07-7100-88cf-2ea07163f9fb

      [ 1/50]   ok   4.91s  calls=2  in=10951 (cache    0%)  out= 307  acum=$0.0125

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-eb07-7100-88cf-2ea07163f9fb,id=019ddc79-eb07-7100-88cf-2ea07163f9fb; trace=019ddc79-f712-77e2-8aff-72d968adfd74,id=019ddc79-f712-77e2-8aff-72d968adfd74
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-f712-77e2-8aff-72d968adfd74,id=019ddc79-f712-77e2-8aff-72d968adfd74; trace=019ddc79-fc52-76d0-aa2f-d51564f9fce0,id=019ddc79-fc52-76d0-aa2f-d51564f9fce0; trace=019ddc79-fc52-76d0-aa2f-d51564f9fce0,id=019ddc79-fc52-76d0-aa2f-d51564f9fce0; trace=019ddc79-fd1d-7283-b26e-b08655644012,id=019ddc79-fd1d-7283-b26e-b08655644012

      [ 2/50]   ok   5.25s  calls=2  in=10440 (cache    0%)  out= 362  acum=$0.0247

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc79-fd1d-7283-b26e-b08655644012,id=019ddc79-fd1d-7283-b26e-b08655644012; trace=019ddc7a-0b8f-7583-8fd7-498f1a7388e4,id=019ddc7a-0b8f-7583-8fd7-498f1a7388e4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-0b8f-7583-8fd7-498f1a7388e4,id=019ddc7a-0b8f-7583-8fd7-498f1a7388e4; trace=019ddc7a-1112-7530-9419-777bf76d533e,id=019ddc7a-1112-7530-9419-777bf76d533e; trace=019ddc7a-1112-7530-9419-777bf76d533e,id=019ddc7a-1112-7530-9419-777bf76d533e; trace=019ddc7a-11db-7f82-95e6-3457233a2df9,id=019ddc7a-11db-7f82-95e6-3457233a2df9

      [ 3/50]   ok   4.38s  calls=2  in=10079 (cache    0%)  out= 257  acum=$0.0361

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-11db-7f82-95e6-3457233a2df9,id=019ddc7a-11db-7f82-95e6-3457233a2df9; trace=019ddc7a-1cab-7071-aaf5-6548d43ae7dd,id=019ddc7a-1cab-7071-aaf5-6548d43ae7dd
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-1cab-7071-aaf5-6548d43ae7dd,id=019ddc7a-1cab-7071-aaf5-6548d43ae7dd; trace=019ddc7a-21c3-7573-869c-40838cd20e73,id=019ddc7a-21c3-7573-869c-40838cd20e73; trace=019ddc7a-21c3-7573-869c-40838cd20e73,id=019ddc7a-21c3-7573-869c-40838cd20e73; trace=019ddc7a-2292-7030-80d3-34aaf64f9b2e,id=019ddc7a-2292-7030-80d3-34aaf64f9b2e

      [ 4/50]   ok   5.66s  calls=2  in=10304 (cache    0%)  out= 381  acum=$0.0483

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-2292-7030-80d3-34aaf64f9b2e,id=019ddc7a-2292-7030-80d3-34aaf64f9b2e; trace=019ddc7a-32cb-7b90-acb6-6963f8cd67bf,id=019ddc7a-32cb-7b90-acb6-6963f8cd67bf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-32cb-7b90-acb6-6963f8cd67bf,id=019ddc7a-32cb-7b90-acb6-6963f8cd67bf; trace=019ddc7a-3911-77e3-a959-eb364ed9ae4a,id=019ddc7a-3911-77e3-a959-eb364ed9ae4a; trace=019ddc7a-3911-77e3-a959-eb364ed9ae4a,id=019ddc7a-3911-77e3-a959-eb364ed9ae4a; trace=019ddc7a-39e6-7a71-9484-c5e20ce9316a,id=019ddc7a-39e6-7a71-9484-c5e20ce9316a; trace=019ddc7a-39e6-7a71-9484-c5e20ce9316a,id=019ddc7a-39e6-7a71-9484-c5e20ce9316a; trace=019ddc7a-39e7-7422-9ba9-bb433007f014,id=019ddc7a-39e7-7422-9ba9-bb433007f014

      [ 5/50]   ok   7.11s  calls=2  in=11284 (cache    0%)  out= 568  acum=$0.0624

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-39e7-7422-9ba9-bb433007f014,id=019ddc7a-39e7-7422-9ba9-bb433007f014; trace=019ddc7a-4e93-7061-863a-363f35cc074b,id=019ddc7a-4e93-7061-863a-363f35cc074b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-4e93-7061-863a-363f35cc074b,id=019ddc7a-4e93-7061-863a-363f35cc074b; trace=019ddc7a-53db-7cf3-aa4f-e3432a5ccaaf,id=019ddc7a-53db-7cf3-aa4f-e3432a5ccaaf; trace=019ddc7a-53db-7cf3-aa4f-e3432a5ccaaf,id=019ddc7a-53db-7cf3-aa4f-e3432a5ccaaf; trace=019ddc7a-5437-73c3-939b-3b6ca0eefb79,id=019ddc7a-5437-73c3-939b-3b6ca0eefb79

      [ 6/50]   ok   6.58s  calls=2  in=11076 (cache    0%)  out= 566  acum=$0.0763

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-5437-73c3-939b-3b6ca0eefb79,id=019ddc7a-5437-73c3-939b-3b6ca0eefb79; trace=019ddc7a-6847-7a02-9a08-8b794533c950,id=019ddc7a-6847-7a02-9a08-8b794533c950
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-6847-7a02-9a08-8b794533c950,id=019ddc7a-6847-7a02-9a08-8b794533c950; trace=019ddc7a-6e44-7ce2-b2ec-17ee5a968828,id=019ddc7a-6e44-7ce2-b2ec-17ee5a968828; trace=019ddc7a-6e44-7ce2-b2ec-17ee5a968828,id=019ddc7a-6e44-7ce2-b2ec-17ee5a968828; trace=019ddc7a-6ea9-7382-99d4-acd842ee4e16,id=019ddc7a-6ea9-7382-99d4-acd842ee4e16

      [ 7/50]   ok   5.12s  calls=2  in=11078 (cache    0%)  out= 362  acum=$0.0892

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-6ea9-7382-99d4-acd842ee4e16,id=019ddc7a-6ea9-7382-99d4-acd842ee4e16; trace=019ddc7a-7c46-7e51-a48f-568cef710847,id=019ddc7a-7c46-7e51-a48f-568cef710847
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-7c46-7e51-a48f-568cef710847,id=019ddc7a-7c46-7e51-a48f-568cef710847; trace=019ddc7a-8177-7ba1-91dc-da162467d26c,id=019ddc7a-8177-7ba1-91dc-da162467d26c; trace=019ddc7a-8177-7ba1-91dc-da162467d26c,id=019ddc7a-8177-7ba1-91dc-da162467d26c; trace=019ddc7a-8242-77c2-bf89-97bc2fb1ab21,id=019ddc7a-8242-77c2-bf89-97bc2fb1ab21

      [ 8/50]   ok   6.04s  calls=2  in=10318 (cache    0%)  out= 422  acum=$0.1017

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-8242-77c2-bf89-97bc2fb1ab21,id=019ddc7a-8242-77c2-bf89-97bc2fb1ab21; trace=019ddc7a-93e2-7b03-8ca1-aecda4166bfe,id=019ddc7a-93e2-7b03-8ca1-aecda4166bfe
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-93e2-7b03-8ca1-aecda4166bfe,id=019ddc7a-93e2-7b03-8ca1-aecda4166bfe; trace=019ddc7a-9990-7502-8b7a-ef21f7a8fd2c,id=019ddc7a-9990-7502-8b7a-ef21f7a8fd2c; trace=019ddc7a-9990-7502-8b7a-ef21f7a8fd2c,id=019ddc7a-9990-7502-8b7a-ef21f7a8fd2c; trace=019ddc7a-9a53-7a02-a0e1-52de2591b6ce,id=019ddc7a-9a53-7a02-a0e1-52de2591b6ce
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-9a53-7a02-a0e1-52de2591b6ce,id=019ddc7a-9a53-7a02-a0e1-52de2591b6ce; trace=019ddc7a-a311-77c2-bc66-b561cd60ebe5,id=019ddc7a-a311-77c2-bc66-b561cd60ebe5; trace=019ddc7a-a311-77c2-bc66-b561cd60ebe5,id=019ddc7a-a311-77c2-bc66-b561cd60ebe5; trace=019ddc7a-a3f1-78a3-bd5a-648136aaa71d,id=019ddc7a-a3f1-78a3-bd5a-648136aaa71d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-a3f1-78a3-bd5a-648136aaa71d,id=019ddc7a-a3f1-78a3-bd5a-648136aaa71d; trace=019ddc7a-d179-7fc3-840e-b46ff145bb79,id=019ddc7a-d179-7fc3-840e-b46ff145bb79; trace=019ddc7a-d179-7fc3-840e-b46ff145bb79,id=019ddc7a-d179-7fc3-840e-b46ff145bb79; trace=019ddc7a-d17c-73c1-87f7-6e9e47fdc85b,id=019ddc7a-d17c-73c1-87f7-6e9e47fdc85b

      [ 9/50]   ok  33.49s  calls=4  in=41080 (cache    0%)  out= 747  acum=$0.1465

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7a-d17c-73c1-87f7-6e9e47fdc85b,id=019ddc7a-d17c-73c1-87f7-6e9e47fdc85b; trace=019ddc7b-16b0-7fe0-9c74-3d59048ecb89,id=019ddc7b-16b0-7fe0-9c74-3d59048ecb89
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-16b0-7fe0-9c74-3d59048ecb89,id=019ddc7b-16b0-7fe0-9c74-3d59048ecb89; trace=019ddc7b-6178-7f50-b401-2c5ba2bbd8b8,id=019ddc7b-6178-7f50-b401-2c5ba2bbd8b8; trace=019ddc7b-6178-7f50-b401-2c5ba2bbd8b8,id=019ddc7b-6178-7f50-b401-2c5ba2bbd8b8; trace=019ddc7b-61d3-7b53-8659-04a5d15319e0,id=019ddc7b-61d3-7b53-8659-04a5d15319e0

      [10/50]   ok  23.65s  calls=2  in=10635 (cache    0%)  out= 447  acum=$0.1593

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-61d3-7b53-8659-04a5d15319e0,id=019ddc7b-61d3-7b53-8659-04a5d15319e0; trace=019ddc7b-7311-7800-8871-6416fb1394e0,id=019ddc7b-7311-7800-8871-6416fb1394e0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-7311-7800-8871-6416fb1394e0,id=019ddc7b-7311-7800-8871-6416fb1394e0; trace=019ddc7b-8df0-7872-b2af-9024d164c60d,id=019ddc7b-8df0-7872-b2af-9024d164c60d; trace=019ddc7b-8df0-7872-b2af-9024d164c60d,id=019ddc7b-8df0-7872-b2af-9024d164c60d; trace=019ddc7b-8e85-7b21-afa6-220a84ff0e9b,id=019ddc7b-8e85-7b21-afa6-220a84ff0e9b

      [11/50]   ok   9.93s  calls=2  in=10511 (cache    0%)  out= 276  acum=$0.1712

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-8e85-7b21-afa6-220a84ff0e9b,id=019ddc7b-8e85-7b21-afa6-220a84ff0e9b; trace=019ddc7b-99dc-76d2-942a-35756e24a956,id=019ddc7b-99dc-76d2-942a-35756e24a956
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-99dc-76d2-942a-35756e24a956,id=019ddc7b-99dc-76d2-942a-35756e24a956; trace=019ddc7b-c181-7083-a9f8-fc598c0ff51e,id=019ddc7b-c181-7083-a9f8-fc598c0ff51e; trace=019ddc7b-c181-7083-a9f8-fc598c0ff51e,id=019ddc7b-c181-7083-a9f8-fc598c0ff51e; trace=019ddc7b-c218-7af2-a4b9-52fcb26fa85b,id=019ddc7b-c218-7af2-a4b9-52fcb26fa85b

      [12/50]   ok  13.78s  calls=2  in=10972 (cache    0%)  out= 489  acum=$0.1846

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-c218-7af2-a4b9-52fcb26fa85b,id=019ddc7b-c218-7af2-a4b9-52fcb26fa85b; trace=019ddc7b-cfaf-7142-b2e0-64835b078f71,id=019ddc7b-cfaf-7142-b2e0-64835b078f71
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-cfaf-7142-b2e0-64835b078f71,id=019ddc7b-cfaf-7142-b2e0-64835b078f71; trace=019ddc7b-f37d-7e82-a86c-75490bda4e3d,id=019ddc7b-f37d-7e82-a86c-75490bda4e3d; trace=019ddc7b-f37d-7e82-a86c-75490bda4e3d,id=019ddc7b-f37d-7e82-a86c-75490bda4e3d; trace=019ddc7b-f448-7983-b4ff-2cfd6e868429,id=019ddc7b-f448-7983-b4ff-2cfd6e868429

      [13/50]   ok  12.55s  calls=2  in=11420 (cache    0%)  out= 338  acum=$0.1978

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7b-f448-7983-b4ff-2cfd6e868429,id=019ddc7b-f448-7983-b4ff-2cfd6e868429; trace=019ddc7c-00b2-7533-96b0-fb595b47a88d,id=019ddc7c-00b2-7533-96b0-fb595b47a88d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-00b2-7533-96b0-fb595b47a88d,id=019ddc7c-00b2-7533-96b0-fb595b47a88d; trace=019ddc7c-284b-7b20-97de-b51260f3ccf0,id=019ddc7c-284b-7b20-97de-b51260f3ccf0; trace=019ddc7c-284b-7b20-97de-b51260f3ccf0,id=019ddc7c-284b-7b20-97de-b51260f3ccf0; trace=019ddc7c-2924-73b3-97b2-520cef9dc990,id=019ddc7c-2924-73b3-97b2-520cef9dc990

      [14/50]   ok  14.74s  calls=2  in=10785 (cache    0%)  out= 511  acum=$0.2111

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-2924-73b3-97b2-520cef9dc990,id=019ddc7c-2924-73b3-97b2-520cef9dc990; trace=019ddc7c-3a47-7c33-8f90-bf755b5beeeb,id=019ddc7c-3a47-7c33-8f90-bf755b5beeeb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-3a47-7c33-8f90-bf755b5beeeb,id=019ddc7c-3a47-7c33-8f90-bf755b5beeeb; trace=019ddc7c-597c-7fd1-8335-1b85828b33c3,id=019ddc7c-597c-7fd1-8335-1b85828b33c3; trace=019ddc7c-597c-7fd1-8335-1b85828b33c3,id=019ddc7c-597c-7fd1-8335-1b85828b33c3; trace=019ddc7c-5a4b-7183-89fc-148c6e45dcc6,id=019ddc7c-5a4b-7183-89fc-148c6e45dcc6

      [15/50]   ok  12.81s  calls=2  in=11580 (cache    0%)  out= 457  acum=$0.2250

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-5a4b-7183-89fc-148c6e45dcc6,id=019ddc7c-5a4b-7183-89fc-148c6e45dcc6; trace=019ddc7c-6c4c-7970-9047-2d80b0e317d7,id=019ddc7c-6c4c-7970-9047-2d80b0e317d7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-6c4c-7970-9047-2d80b0e317d7,id=019ddc7c-6c4c-7970-9047-2d80b0e317d7; trace=019ddc7c-904b-7472-9f0d-24d80f46abbd,id=019ddc7c-904b-7472-9f0d-24d80f46abbd; trace=019ddc7c-904b-7472-9f0d-24d80f46abbd,id=019ddc7c-904b-7472-9f0d-24d80f46abbd; trace=019ddc7c-911a-7360-8dda-1cbea308f01a,id=019ddc7c-911a-7360-8dda-1cbea308f01a

      [16/50]   ok  12.83s  calls=2  in=10684 (cache    0%)  out= 395  acum=$0.2376

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-911a-7360-8dda-1cbea308f01a,id=019ddc7c-911a-7360-8dda-1cbea308f01a; trace=019ddc7c-9e6f-7ca3-a198-8da7db44eb53,id=019ddc7c-9e6f-7ca3-a198-8da7db44eb53
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-9e6f-7ca3-a198-8da7db44eb53,id=019ddc7c-9e6f-7ca3-a198-8da7db44eb53; trace=019ddc7c-bf80-7221-a732-b671c5d7aace,id=019ddc7c-bf80-7221-a732-b671c5d7aace; trace=019ddc7c-bf80-7221-a732-b671c5d7aace,id=019ddc7c-bf80-7221-a732-b671c5d7aace; trace=019ddc7c-c054-7520-ab9a-1d74fa459aa3,id=019ddc7c-c054-7520-ab9a-1d74fa459aa3

      [17/50]   ok  15.94s  calls=2  in=10746 (cache    0%)  out= 558  acum=$0.2512

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-c054-7520-ab9a-1d74fa459aa3,id=019ddc7c-c054-7520-ab9a-1d74fa459aa3; trace=019ddc7c-dcae-7473-a6aa-f5cee035ff28,id=019ddc7c-dcae-7473-a6aa-f5cee035ff28
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-dcae-7473-a6aa-f5cee035ff28,id=019ddc7c-dcae-7473-a6aa-f5cee035ff28; trace=019ddc7c-f220-7703-b9d8-b5c93bc49d17,id=019ddc7c-f220-7703-b9d8-b5c93bc49d17; trace=019ddc7c-f220-7703-b9d8-b5c93bc49d17,id=019ddc7c-f220-7703-b9d8-b5c93bc49d17; trace=019ddc7c-f2ee-76f0-ad6f-e17b76241035,id=019ddc7c-f2ee-76f0-ad6f-e17b76241035

      [18/50]   ok  12.19s  calls=2  in=10938 (cache    0%)  out= 587  acum=$0.2650

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7c-f2ee-76f0-ad6f-e17b76241035,id=019ddc7c-f2ee-76f0-ad6f-e17b76241035; trace=019ddc7d-0c4d-7823-8689-ee516ae18c0f,id=019ddc7d-0c4d-7823-8689-ee516ae18c0f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-0c4d-7823-8689-ee516ae18c0f,id=019ddc7d-0c4d-7823-8689-ee516ae18c0f; trace=019ddc7d-277f-75e0-8748-f3b1f1904986,id=019ddc7d-277f-75e0-8748-f3b1f1904986; trace=019ddc7d-277f-75e0-8748-f3b1f1904986,id=019ddc7d-277f-75e0-8748-f3b1f1904986; trace=019ddc7d-27da-78b3-8d5c-e015b26b8764,id=019ddc7d-27da-78b3-8d5c-e015b26b8764

      [19/50]   ok  10.04s  calls=2  in=11579 (cache    0%)  out= 387  acum=$0.2785

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-27da-78b3-8d5c-e015b26b8764,id=019ddc7d-27da-78b3-8d5c-e015b26b8764; trace=019ddc7d-3382-72a0-9133-1abec16744fb,id=019ddc7d-3382-72a0-9133-1abec16744fb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-3382-72a0-9133-1abec16744fb,id=019ddc7d-3382-72a0-9133-1abec16744fb; trace=019ddc7d-5ee8-7711-8ba1-0a76fc06c968,id=019ddc7d-5ee8-7711-8ba1-0a76fc06c968; trace=019ddc7d-5ee8-7711-8ba1-0a76fc06c968,id=019ddc7d-5ee8-7711-8ba1-0a76fc06c968; trace=019ddc7d-5fb8-7643-9101-489700c522fc,id=019ddc7d-5fb8-7643-9101-489700c522fc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-5fb8-7643-9101-489700c522fc,id=019ddc7d-5fb8-7643-9101-489700c522fc; trace=019ddc7d-677e-7e21-9278-d4c5d326c6ef,id=019ddc7d-677e-7e21-9278-d4c5d326c6ef; trace=019ddc7d-677e-7e21-9278-d4c5d326c6ef,id=019ddc7d-677e-7e21-9278-d4c5d326c6ef; trace=019ddc7d-6781-7fe2-a3e7-3b7b7c86487b,id=019ddc7d-6781-7fe2-a3e7-3b7b7c86487b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-6781-7fe2-a3e7-3b7b7c86487b,id=019ddc7d-6781-7fe2-a3e7-3b7b7c86487b; trace=019ddc7d-944d-7241-9c62-3c31d20e7e21,id=019ddc7d-944d-7241-9c62-3c31d20e7e21; trace=019ddc7d-944d-7241-9c62-3c31d20e7e21,id=019ddc7d-944d-7241-9c62-3c31d20e7e21; trace=019ddc7d-944f-7070-bb00-6a5855c5f915,id=019ddc7d-944f-7070-bb00-6a5855c5f915

      [20/50]   ok  37.07s  calls=4  in=29454 (cache    0%)  out= 523  acum=$0.3106

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-944f-7070-bb00-6a5855c5f915,id=019ddc7d-944f-7070-bb00-6a5855c5f915; trace=019ddc7d-c453-7161-9d3b-027ed1b7f33d,id=019ddc7d-c453-7161-9d3b-027ed1b7f33d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-c453-7161-9d3b-027ed1b7f33d,id=019ddc7d-c453-7161-9d3b-027ed1b7f33d; trace=019ddc7d-e84a-7c31-b03a-67983236a635,id=019ddc7d-e84a-7c31-b03a-67983236a635; trace=019ddc7d-e84a-7c31-b03a-67983236a635,id=019ddc7d-e84a-7c31-b03a-67983236a635; trace=019ddc7d-e8a7-79b2-b570-c917b7d09a54,id=019ddc7d-e8a7-79b2-b570-c917b7d09a54

      [21/50]   ok  13.82s  calls=2  in=10933 (cache    0%)  out= 538  acum=$0.3242

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-e8a7-79b2-b570-c917b7d09a54,id=019ddc7d-e8a7-79b2-b570-c917b7d09a54; trace=019ddc7d-fa4a-7980-956e-63c543c5a0b1,id=019ddc7d-fa4a-7980-956e-63c543c5a0b1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7d-fa4a-7980-956e-63c543c5a0b1,id=019ddc7d-fa4a-7980-956e-63c543c5a0b1; trace=019ddc7e-1d83-7492-bb93-8b0b195548af,id=019ddc7e-1d83-7492-bb93-8b0b195548af; trace=019ddc7e-1d83-7492-bb93-8b0b195548af,id=019ddc7e-1d83-7492-bb93-8b0b195548af; trace=019ddc7e-1e52-7812-9205-acda483d482f,id=019ddc7e-1e52-7812-9205-acda483d482f

      [22/50]   ok  14.53s  calls=2  in=10045 (cache    0%)  out= 640  acum=$0.3375

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-1e52-7812-9205-acda483d482f,id=019ddc7e-1e52-7812-9205-acda483d482f; trace=019ddc7e-3311-7023-a83a-3ae0e33946c0,id=019ddc7e-3311-7023-a83a-3ae0e33946c0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-3311-7023-a83a-3ae0e33946c0,id=019ddc7e-3311-7023-a83a-3ae0e33946c0; trace=019ddc7e-49ea-7683-b92a-eb8086591c8b,id=019ddc7e-49ea-7683-b92a-eb8086591c8b; trace=019ddc7e-49ea-7683-b92a-eb8086591c8b,id=019ddc7e-49ea-7683-b92a-eb8086591c8b; trace=019ddc7e-4ab9-7f02-b611-0ad611a4176e,id=019ddc7e-4ab9-7f02-b611-0ad611a4176e

      [23/50]   ok   10.0s  calls=2  in=10229 (cache    0%)  out= 375  acum=$0.3496

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-4ab9-7f02-b611-0ad611a4176e,id=019ddc7e-4ab9-7f02-b611-0ad611a4176e; trace=019ddc7e-5a23-7182-82b6-8d863fc0fc65,id=019ddc7e-5a23-7182-82b6-8d863fc0fc65
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-5a23-7182-82b6-8d863fc0fc65,id=019ddc7e-5a23-7182-82b6-8d863fc0fc65; trace=019ddc7e-7c4e-7e00-8db1-da3b007f5fbb,id=019ddc7e-7c4e-7e00-8db1-da3b007f5fbb; trace=019ddc7e-7c4e-7e00-8db1-da3b007f5fbb,id=019ddc7e-7c4e-7e00-8db1-da3b007f5fbb; trace=019ddc7e-7ca6-7b73-a0db-bc91e7cc4428,id=019ddc7e-7ca6-7b73-a0db-bc91e7cc4428

      [24/50]   ok  13.41s  calls=2  in= 9782 (cache    0%)  out= 466  acum=$0.3617

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-7ca6-7b73-a0db-bc91e7cc4428,id=019ddc7e-7ca6-7b73-a0db-bc91e7cc4428; trace=019ddc7e-8e82-7603-9dbd-2bf67d39aeb6,id=019ddc7e-8e82-7603-9dbd-2bf67d39aeb6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-8e82-7603-9dbd-2bf67d39aeb6,id=019ddc7e-8e82-7603-9dbd-2bf67d39aeb6; trace=019ddc7e-ab1d-7613-b744-30c098278b44,id=019ddc7e-ab1d-7613-b744-30c098278b44; trace=019ddc7e-ab1d-7613-b744-30c098278b44,id=019ddc7e-ab1d-7613-b744-30c098278b44; trace=019ddc7e-abe8-7620-b11b-f3f4d90b9d64,id=019ddc7e-abe8-7620-b11b-f3f4d90b9d64

      [25/50]   ok   9.98s  calls=2  in=11865 (cache    0%)  out= 181  acum=$0.3745

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-abe8-7620-b11b-f3f4d90b9d64,id=019ddc7e-abe8-7620-b11b-f3f4d90b9d64; trace=019ddc7e-b57b-7170-a886-1f517ed897e6,id=019ddc7e-b57b-7170-a886-1f517ed897e6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-b57b-7170-a886-1f517ed897e6,id=019ddc7e-b57b-7170-a886-1f517ed897e6; trace=019ddc7e-e11d-7f43-b51e-81e0705c87c8,id=019ddc7e-e11d-7f43-b51e-81e0705c87c8; trace=019ddc7e-e11d-7f43-b51e-81e0705c87c8,id=019ddc7e-e11d-7f43-b51e-81e0705c87c8; trace=019ddc7e-e184-72b1-a6e1-7b54304c9cdc,id=019ddc7e-e184-72b1-a6e1-7b54304c9cdc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-e184-72b1-a6e1-7b54304c9cdc,id=019ddc7e-e184-72b1-a6e1-7b54304c9cdc; trace=019ddc7e-e94e-7ca1-ad18-032f3c1565ab,id=019ddc7e-e94e-7ca1-ad18-032f3c1565ab; trace=019ddc7e-e94e-7ca1-ad18-032f3c1565ab,id=019ddc7e-e94e-7ca1-ad18-032f3c1565ab; trace=019ddc7e-ea07-7b10-af35-c9703484c7fe,id=019ddc7e-ea07-7b10-af35-c9703484c7fe
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7e-ea07-7b10-af35-c9703484c7fe,id=019ddc7e-ea07-7b10-af35-c9703484c7fe; trace=019ddc7f-1d1f-75c2-8c32-f21ff50b13d6,id=019ddc7f-1d1f-75c2-8c32-f21ff50b13d6; trace=019ddc7f-1d1f-75c2-8c32-f21ff50b13d6,id=019ddc7f-1d1f-75c2-8c32-f21ff50b13d6; trace=019ddc7f-1d22-7a83-8b29-f4fd8d711b29,id=019ddc7f-1d22-7a83-8b29-f4fd8d711b29
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7f-1d22-7a83-8b29-f4fd8d711b29,id=019ddc7f-1d22-7a83-8b29-f4fd8d711b29; trace=019ddc7f-5beb-7eb3-954c-50d6a611e32a,id=019ddc7f-5beb-7eb3-954c-50d6a611e32a; trace=019ddc7f-5beb-7eb3-954c-50d6a611e32a,id=019ddc7f-5beb-7eb3-954c-50d6a611e32a; trace=019ddc7f-5bee-7080-b939-c0e659249fd4,id=019ddc7f-5bee-7080-b939-c0e659249fd4

      [26/50]   ok  61.36s  calls=5  in=54406 (cache    0%)  out= 797  acum=$0.4329

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7f-5bee-7080-b939-c0e659249fd4,id=019ddc7f-5bee-7080-b939-c0e659249fd4; trace=019ddc7f-a52c-7b43-9cf3-b3fcc545b4be,id=019ddc7f-a52c-7b43-9cf3-b3fcc545b4be
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7f-a52c-7b43-9cf3-b3fcc545b4be,id=019ddc7f-a52c-7b43-9cf3-b3fcc545b4be; trace=019ddc7f-e107-7c82-bd95-70f3c2e6857f,id=019ddc7f-e107-7c82-bd95-70f3c2e6857f; trace=019ddc7f-e107-7c82-bd95-70f3c2e6857f,id=019ddc7f-e107-7c82-bd95-70f3c2e6857f; trace=019ddc7f-e18d-7d03-b418-16b985737430,id=019ddc7f-e18d-7d03-b418-16b985737430
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7f-e18d-7d03-b418-16b985737430,id=019ddc7f-e18d-7d03-b418-16b985737430; trace=019ddc7f-eb22-7d02-a71d-af5a7e3a0e6c,id=019ddc7f-eb22-7d02-a71d-af5a7e3a0e6c; trace=019ddc7f-eb22-7d02-a71d-af5a7e3a0e6c,id=019ddc7f-eb22-7d02-a71d-af5a7e3a0e6c; trace=019ddc7f-ebbe-7bd2-ac80-0a98d76d7a3a,id=019ddc7f-ebbe-7bd2-ac80-0a98d76d7a3a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc7f-ebbe-7bd2-ac80-0a98d76d7a3a,id=019ddc7f-ebbe-7bd2-ac80-0a98d76d7a3a; trace=019ddc80-12b8-7a82-b072-262221a297ef,id=019ddc80-12b8-7a82-b072-262221a297ef; trace=019ddc80-12b8-7a82-b072-262221a297ef,id=019ddc80-12b8-7a82-b072-262221a297ef; trace=019ddc80-12bc-7f73-b1a3-7f514c988b3f,id=019ddc80-12bc-7f73-b1a3-7f514c988b3f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-12bc-7f73-b1a3-7f514c988b3f,id=019ddc80-12bc-7f73-b1a3-7f514c988b3f; trace=019ddc80-4c02-7543-865c-512549cfec2e,id=019ddc80-4c02-7543-865c-512549cfec2e; trace=019ddc80-4c02-7543-865c-512549cfec2e,id=019ddc80-4c02-7543-865c-512549cfec2e; trace=019ddc80-4c04-75c0-8b3e-070f78a1f2a7,id=019ddc80-4c04-75c0-8b3e-070f78a1f2a7; trace=019ddc80-4c04-75c0-8b3e-070f78a1f2a7,id=019ddc80-4c04-75c0-8b3e-070f78a1f2a7; trace=019ddc80-4c07-7510-9a81-b4afb07926b9,id=019ddc80-4c07-7510-9a81-b4afb07926b9

      [27/50]   ok  59.67s  calls=5  in=50405 (cache    0%)  out= 769  acum=$0.4871

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-4c07-7510-9a81-b4afb07926b9,id=019ddc80-4c07-7510-9a81-b4afb07926b9; trace=019ddc80-8e42-7ee1-aeca-15aa31de2cf2,id=019ddc80-8e42-7ee1-aeca-15aa31de2cf2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-8e42-7ee1-aeca-15aa31de2cf2,id=019ddc80-8e42-7ee1-aeca-15aa31de2cf2; trace=019ddc80-cdef-7b21-847b-e49e4942366e,id=019ddc80-cdef-7b21-847b-e49e4942366e; trace=019ddc80-cdef-7b21-847b-e49e4942366e,id=019ddc80-cdef-7b21-847b-e49e4942366e; trace=019ddc80-ce58-73f0-9be9-11edf9dc3af5,id=019ddc80-ce58-73f0-9be9-11edf9dc3af5

      [28/50]   ok  22.03s  calls=2  in=10879 (cache    0%)  out= 623  acum=$0.5011

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-ce58-73f0-9be9-11edf9dc3af5,id=019ddc80-ce58-73f0-9be9-11edf9dc3af5; trace=019ddc80-e456-7d83-9fd9-57c3ef706a72,id=019ddc80-e456-7d83-9fd9-57c3ef706a72
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-e456-7d83-9fd9-57c3ef706a72,id=019ddc80-e456-7d83-9fd9-57c3ef706a72; trace=019ddc80-fc49-7243-b658-edaa19596d3a,id=019ddc80-fc49-7243-b658-edaa19596d3a; trace=019ddc80-fc49-7243-b658-edaa19596d3a,id=019ddc80-fc49-7243-b658-edaa19596d3a; trace=019ddc80-fd20-7882-bbc8-b32bc36f00a5,id=019ddc80-fd20-7882-bbc8-b32bc36f00a5

      [29/50]   ok   9.36s  calls=2  in=10417 (cache    0%)  out= 282  acum=$0.5129

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc80-fd20-7882-bbc8-b32bc36f00a5,id=019ddc80-fd20-7882-bbc8-b32bc36f00a5; trace=019ddc81-08eb-7e33-adf6-bf88386312f6,id=019ddc81-08eb-7e33-adf6-bf88386312f6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-08eb-7e33-adf6-bf88386312f6,id=019ddc81-08eb-7e33-adf6-bf88386312f6; trace=019ddc81-2fd4-73d0-920c-8a5df6ef30c2,id=019ddc81-2fd4-73d0-920c-8a5df6ef30c2; trace=019ddc81-2fd4-73d0-920c-8a5df6ef30c2,id=019ddc81-2fd4-73d0-920c-8a5df6ef30c2; trace=019ddc81-30a8-7582-8860-b8398b8e6a3b,id=019ddc81-30a8-7582-8860-b8398b8e6a3b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-30a8-7582-8860-b8398b8e6a3b,id=019ddc81-30a8-7582-8860-b8398b8e6a3b; trace=019ddc81-391e-7332-a2d3-fda94a8ea798,id=019ddc81-391e-7332-a2d3-fda94a8ea798; trace=019ddc81-391e-7332-a2d3-fda94a8ea798,id=019ddc81-391e-7332-a2d3-fda94a8ea798; trace=019ddc81-398c-7b43-8f2e-fa4b584c11d8,id=019ddc81-398c-7b43-8f2e-fa4b584c11d8

      [30/50]   ok  27.75s  calls=3  in=23591 (cache    0%)  out= 687  acum=$0.5400

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-398c-7b43-8f2e-fa4b584c11d8,id=019ddc81-398c-7b43-8f2e-fa4b584c11d8; trace=019ddc81-7555-7a63-bd12-f700ca824f19,id=019ddc81-7555-7a63-bd12-f700ca824f19
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-7555-7a63-bd12-f700ca824f19,id=019ddc81-7555-7a63-bd12-f700ca824f19; trace=019ddc81-9ffc-7c42-ba23-aee07ddd5d0f,id=019ddc81-9ffc-7c42-ba23-aee07ddd5d0f; trace=019ddc81-9ffc-7c42-ba23-aee07ddd5d0f,id=019ddc81-9ffc-7c42-ba23-aee07ddd5d0f; trace=019ddc81-a0c5-7352-888b-115684e665bd,id=019ddc81-a0c5-7352-888b-115684e665bd

      [31/50]   ok  14.49s  calls=2  in=11461 (cache    0%)  out= 361  acum=$0.5532

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-a0c5-7352-888b-115684e665bd,id=019ddc81-a0c5-7352-888b-115684e665bd; trace=019ddc81-adea-7770-b7e1-712af766c5de,id=019ddc81-adea-7770-b7e1-712af766c5de
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-adea-7770-b7e1-712af766c5de,id=019ddc81-adea-7770-b7e1-712af766c5de; trace=019ddc81-d588-70c2-a9dc-da7b9d4fc626,id=019ddc81-d588-70c2-a9dc-da7b9d4fc626; trace=019ddc81-d588-70c2-a9dc-da7b9d4fc626,id=019ddc81-d588-70c2-a9dc-da7b9d4fc626; trace=019ddc81-d65a-71d0-9e15-d9a113f5e9ea,id=019ddc81-d65a-71d0-9e15-d9a113f5e9ea

      [32/50]   ok  14.13s  calls=2  in=12334 (cache    0%)  out= 416  acum=$0.5676

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-d65a-71d0-9e15-d9a113f5e9ea,id=019ddc81-d65a-71d0-9e15-d9a113f5e9ea; trace=019ddc81-e520-7132-af4c-341a47f89209,id=019ddc81-e520-7132-af4c-341a47f89209
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc81-e520-7132-af4c-341a47f89209,id=019ddc81-e520-7132-af4c-341a47f89209; trace=019ddc82-0e71-7b62-a149-93837ffa0a63,id=019ddc82-0e71-7b62-a149-93837ffa0a63; trace=019ddc82-0e71-7b62-a149-93837ffa0a63,id=019ddc82-0e71-7b62-a149-93837ffa0a63; trace=019ddc82-0f4a-7d50-aedd-4d7b5c3790e6,id=019ddc82-0f4a-7d50-aedd-4d7b5c3790e6

      [33/50]   ok  15.88s  calls=2  in=10864 (cache    0%)  out= 327  acum=$0.5801

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-0f4a-7d50-aedd-4d7b5c3790e6,id=019ddc82-0f4a-7d50-aedd-4d7b5c3790e6; trace=019ddc82-2325-7bf3-9eda-57cfdb95660d,id=019ddc82-2325-7bf3-9eda-57cfdb95660d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-2325-7bf3-9eda-57cfdb95660d,id=019ddc82-2325-7bf3-9eda-57cfdb95660d; trace=019ddc82-4258-7541-895d-d787a841ad4d,id=019ddc82-4258-7541-895d-d787a841ad4d; trace=019ddc82-4258-7541-895d-d787a841ad4d,id=019ddc82-4258-7541-895d-d787a841ad4d; trace=019ddc82-42bd-7fe3-911f-21abe08e1a36,id=019ddc82-42bd-7fe3-911f-21abe08e1a36

      [34/50]   ok  10.55s  calls=2  in=11576 (cache    0%)  out= 220  acum=$0.5928

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-42bd-7fe3-911f-21abe08e1a36,id=019ddc82-42bd-7fe3-911f-21abe08e1a36; trace=019ddc82-4c57-7880-b2be-18fa2b82ea8e,id=019ddc82-4c57-7880-b2be-18fa2b82ea8e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-4c57-7880-b2be-18fa2b82ea8e,id=019ddc82-4c57-7880-b2be-18fa2b82ea8e; trace=019ddc82-77ee-7921-a2f1-f0f0cba57575,id=019ddc82-77ee-7921-a2f1-f0f0cba57575; trace=019ddc82-77ee-7921-a2f1-f0f0cba57575,id=019ddc82-77ee-7921-a2f1-f0f0cba57575; trace=019ddc82-7850-7803-990a-43d8f16f2c13,id=019ddc82-7850-7803-990a-43d8f16f2c13

      [35/50]   ok  15.16s  calls=2  in=12013 (cache    0%)  out= 438  acum=$0.6070

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-7850-7803-990a-43d8f16f2c13,id=019ddc82-7850-7803-990a-43d8f16f2c13; trace=019ddc82-878b-70e3-86cd-b0c07a6c4f53,id=019ddc82-878b-70e3-86cd-b0c07a6c4f53
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-878b-70e3-86cd-b0c07a6c4f53,id=019ddc82-878b-70e3-86cd-b0c07a6c4f53; trace=019ddc82-ae44-7962-981f-60c63d8ea315,id=019ddc82-ae44-7962-981f-60c63d8ea315; trace=019ddc82-ae44-7962-981f-60c63d8ea315,id=019ddc82-ae44-7962-981f-60c63d8ea315; trace=019ddc82-aea6-7242-8691-e3fbd8466f19,id=019ddc82-aea6-7242-8691-e3fbd8466f19

      [36/50]   ok  14.24s  calls=2  in=11951 (cache    0%)  out= 496  acum=$0.6214

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-aea6-7242-8691-e3fbd8466f19,id=019ddc82-aea6-7242-8691-e3fbd8466f19; trace=019ddc82-bf28-7231-8281-064c312d9947,id=019ddc82-bf28-7231-8281-064c312d9947
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-bf28-7231-8281-064c312d9947,id=019ddc82-bf28-7231-8281-064c312d9947; trace=019ddc82-e656-76d0-aec5-72e423b555bd,id=019ddc82-e656-76d0-aec5-72e423b555bd; trace=019ddc82-e656-76d0-aec5-72e423b555bd,id=019ddc82-e656-76d0-aec5-72e423b555bd; trace=019ddc82-e720-7f62-8b5b-b38fcc2ae271,id=019ddc82-e720-7f62-8b5b-b38fcc2ae271

      [37/50]   ok  15.36s  calls=2  in=12051 (cache    0%)  out= 617  acum=$0.6366

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-e720-7f62-8b5b-b38fcc2ae271,id=019ddc82-e720-7f62-8b5b-b38fcc2ae271; trace=019ddc82-fb26-72f2-af1a-91d83d0da225,id=019ddc82-fb26-72f2-af1a-91d83d0da225
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc82-fb26-72f2-af1a-91d83d0da225,id=019ddc82-fb26-72f2-af1a-91d83d0da225; trace=019ddc83-1e47-7852-925f-05bdd22177af,id=019ddc83-1e47-7852-925f-05bdd22177af; trace=019ddc83-1e47-7852-925f-05bdd22177af,id=019ddc83-1e47-7852-925f-05bdd22177af; trace=019ddc83-1efe-7a33-a29b-591e747cf02e,id=019ddc83-1efe-7a33-a29b-591e747cf02e

      [38/50]   ok  12.25s  calls=2  in=12465 (cache    0%)  out= 337  acum=$0.6507

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-1efe-7a33-a29b-591e747cf02e,id=019ddc83-1efe-7a33-a29b-591e747cf02e; trace=019ddc83-2afd-71d1-b3c9-3b4297714aae,id=019ddc83-2afd-71d1-b3c9-3b4297714aae
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-2afd-71d1-b3c9-3b4297714aae,id=019ddc83-2afd-71d1-b3c9-3b4297714aae; trace=019ddc83-5a09-78e2-84ce-c97830c41ee1,id=019ddc83-5a09-78e2-84ce-c97830c41ee1; trace=019ddc83-5a09-78e2-84ce-c97830c41ee1,id=019ddc83-5a09-78e2-84ce-c97830c41ee1; trace=019ddc83-5aad-7851-8332-26b708db6cb1,id=019ddc83-5aad-7851-8332-26b708db6cb1

      [39/50]   ok  16.32s  calls=2  in=11572 (cache    0%)  out= 413  acum=$0.6644

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-5aad-7851-8332-26b708db6cb1,id=019ddc83-5aad-7851-8332-26b708db6cb1; trace=019ddc83-6ac2-7701-84f7-ca32ebd3b3af,id=019ddc83-6ac2-7701-84f7-ca32ebd3b3af
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-6ac2-7701-84f7-ca32ebd3b3af,id=019ddc83-6ac2-7701-84f7-ca32ebd3b3af; trace=019ddc83-90c0-7513-8277-4ea99ea8ef22,id=019ddc83-90c0-7513-8277-4ea99ea8ef22; trace=019ddc83-90c0-7513-8277-4ea99ea8ef22,id=019ddc83-90c0-7513-8277-4ea99ea8ef22; trace=019ddc83-9187-7890-bbf1-ae13b80364d1,id=019ddc83-9187-7890-bbf1-ae13b80364d1

      [40/50]   ok  15.56s  calls=2  in=12024 (cache    0%)  out= 590  acum=$0.6793

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-9187-7890-bbf1-ae13b80364d1,id=019ddc83-9187-7890-bbf1-ae13b80364d1; trace=019ddc83-a78c-7cf3-82ed-ff7ddf886299,id=019ddc83-a78c-7cf3-82ed-ff7ddf886299
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-a78c-7cf3-82ed-ff7ddf886299,id=019ddc83-a78c-7cf3-82ed-ff7ddf886299; trace=019ddc83-cb8b-7122-9e4f-c020257300f7,id=019ddc83-cb8b-7122-9e4f-c020257300f7; trace=019ddc83-cb8b-7122-9e4f-c020257300f7,id=019ddc83-cb8b-7122-9e4f-c020257300f7; trace=019ddc83-cbf4-7f03-9609-95cadfd7fa43,id=019ddc83-cbf4-7f03-9609-95cadfd7fa43

      [41/50]   ok  15.77s  calls=2  in=13339 (cache    0%)  out= 674  acum=$0.6961

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-cbf4-7f03-9609-95cadfd7fa43,id=019ddc83-cbf4-7f03-9609-95cadfd7fa43; trace=019ddc83-e528-7c41-b480-05293d3a6fec,id=019ddc83-e528-7c41-b480-05293d3a6fec
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc83-e528-7c41-b480-05293d3a6fec,id=019ddc83-e528-7c41-b480-05293d3a6fec; trace=019ddc84-07ef-71f0-9204-fb7063e1ba2e,id=019ddc84-07ef-71f0-9204-fb7063e1ba2e; trace=019ddc84-07ef-71f0-9204-fb7063e1ba2e,id=019ddc84-07ef-71f0-9204-fb7063e1ba2e; trace=019ddc84-083d-7f83-ad5d-e0d22742503e,id=019ddc84-083d-7f83-ad5d-e0d22742503e

      [42/50]   ok  11.87s  calls=2  in=11727 (cache    0%)  out= 305  acum=$0.7093

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-083d-7f83-ad5d-e0d22742503e,id=019ddc84-083d-7f83-ad5d-e0d22742503e; trace=019ddc84-1389-7242-b496-c686f43baa42,id=019ddc84-1389-7242-b496-c686f43baa42
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-1389-7242-b496-c686f43baa42,id=019ddc84-1389-7242-b496-c686f43baa42; trace=019ddc84-3ec0-7ee0-b45e-a29721219f5d,id=019ddc84-3ec0-7ee0-b45e-a29721219f5d; trace=019ddc84-3ec0-7ee0-b45e-a29721219f5d,id=019ddc84-3ec0-7ee0-b45e-a29721219f5d; trace=019ddc84-3f8f-7812-966e-f500de8c0b63,id=019ddc84-3f8f-7812-966e-f500de8c0b63

      [43/50]   ok  14.13s  calls=2  in=11899 (cache    0%)  out= 303  acum=$0.7227

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-3f8f-7812-966e-f500de8c0b63,id=019ddc84-3f8f-7812-966e-f500de8c0b63; trace=019ddc84-4ac1-7120-8c25-932b0daf2f58,id=019ddc84-4ac1-7120-8c25-932b0daf2f58
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-4ac1-7120-8c25-932b0daf2f58,id=019ddc84-4ac1-7120-8c25-932b0daf2f58; trace=019ddc84-7649-7bc3-a20e-eb002c8d5fd9,id=019ddc84-7649-7bc3-a20e-eb002c8d5fd9; trace=019ddc84-7649-7bc3-a20e-eb002c8d5fd9,id=019ddc84-7649-7bc3-a20e-eb002c8d5fd9; trace=019ddc84-76f3-72c1-917e-0bdb47c066dd,id=019ddc84-76f3-72c1-917e-0bdb47c066dd

      [44/50]   ok  15.46s  calls=2  in=12239 (cache    0%)  out= 395  acum=$0.7369

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-76f3-72c1-917e-0bdb47c066dd,id=019ddc84-76f3-72c1-917e-0bdb47c066dd; trace=019ddc84-872a-74d2-aee6-50dc289ed6b0,id=019ddc84-872a-74d2-aee6-50dc289ed6b0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-872a-74d2-aee6-50dc289ed6b0,id=019ddc84-872a-74d2-aee6-50dc289ed6b0; trace=019ddc84-aff3-7613-9484-6a1af5e23962,id=019ddc84-aff3-7613-9484-6a1af5e23962; trace=019ddc84-aff3-7613-9484-6a1af5e23962,id=019ddc84-aff3-7613-9484-6a1af5e23962; trace=019ddc84-b0dd-7bf3-98f8-d5ae1dbc3656,id=019ddc84-b0dd-7bf3-98f8-d5ae1dbc3656

      [45/50]   ok  17.71s  calls=2  in=11331 (cache    0%)  out= 749  acum=$0.7520

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-b0dd-7bf3-98f8-d5ae1dbc3656,id=019ddc84-b0dd-7bf3-98f8-d5ae1dbc3656; trace=019ddc84-cc5b-73b1-b082-5173f6032891,id=019ddc84-cc5b-73b1-b082-5173f6032891
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-cc5b-73b1-b082-5173f6032891,id=019ddc84-cc5b-73b1-b082-5173f6032891; trace=019ddc84-e2bf-7b53-a7e0-b5dac2db7558,id=019ddc84-e2bf-7b53-a7e0-b5dac2db7558; trace=019ddc84-e2bf-7b53-a7e0-b5dac2db7558,id=019ddc84-e2bf-7b53-a7e0-b5dac2db7558; trace=019ddc84-e312-7901-848e-0d5a10428c0a,id=019ddc84-e312-7901-848e-0d5a10428c0a

      [46/50]   ok    8.8s  calls=2  in=10453 (cache    0%)  out= 300  acum=$0.7640

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-e312-7901-848e-0d5a10428c0a,id=019ddc84-e312-7901-848e-0d5a10428c0a; trace=019ddc84-eeba-76c1-ac30-91a9c420aed3,id=019ddc84-eeba-76c1-ac30-91a9c420aed3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc84-eeba-76c1-ac30-91a9c420aed3,id=019ddc84-eeba-76c1-ac30-91a9c420aed3; trace=019ddc85-15f6-7e00-a45a-af06ce56e914,id=019ddc85-15f6-7e00-a45a-af06ce56e914; trace=019ddc85-15f6-7e00-a45a-af06ce56e914,id=019ddc85-15f6-7e00-a45a-af06ce56e914; trace=019ddc85-16d5-77d2-873e-f14a97d1b792,id=019ddc85-16d5-77d2-873e-f14a97d1b792

      [47/50]   ok  14.96s  calls=2  in=10548 (cache    0%)  out= 515  acum=$0.7771

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-16d5-77d2-873e-f14a97d1b792,id=019ddc85-16d5-77d2-873e-f14a97d1b792; trace=019ddc85-292a-7423-aacf-c838efcef6fa,id=019ddc85-292a-7423-aacf-c838efcef6fa
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-292a-7423-aacf-c838efcef6fa,id=019ddc85-292a-7423-aacf-c838efcef6fa; trace=019ddc85-485f-7dd3-adc4-5c1097ad9b83,id=019ddc85-485f-7dd3-adc4-5c1097ad9b83; trace=019ddc85-485f-7dd3-adc4-5c1097ad9b83,id=019ddc85-485f-7dd3-adc4-5c1097ad9b83; trace=019ddc85-4900-7382-8656-f593200b6865,id=019ddc85-4900-7382-8656-f593200b6865

      [48/50]   ok  11.47s  calls=2  in=11489 (cache    0%)  out= 308  acum=$0.7901

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-4900-7382-8656-f593200b6865,id=019ddc85-4900-7382-8656-f593200b6865; trace=019ddc85-55f8-7a92-8dc0-e2abf510a437,id=019ddc85-55f8-7a92-8dc0-e2abf510a437
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-55f8-7a92-8dc0-e2abf510a437,id=019ddc85-55f8-7a92-8dc0-e2abf510a437; trace=019ddc85-7d4c-77d2-83a7-4830ab0c0052,id=019ddc85-7d4c-77d2-83a7-4830ab0c0052; trace=019ddc85-7d4c-77d2-83a7-4830ab0c0052,id=019ddc85-7d4c-77d2-83a7-4830ab0c0052; trace=019ddc85-7da9-7632-99fa-4f8e0720b83a,id=019ddc85-7da9-7632-99fa-4f8e0720b83a

      [49/50]   ok  17.35s  calls=2  in=11388 (cache    0%)  out= 656  acum=$0.8048

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-7da9-7632-99fa-4f8e0720b83a,id=019ddc85-7da9-7632-99fa-4f8e0720b83a; trace=019ddc85-99c0-7a72-810b-f52fdf04e522,id=019ddc85-99c0-7a72-810b-f52fdf04e522
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-99c0-7a72-810b-f52fdf04e522,id=019ddc85-99c0-7a72-810b-f52fdf04e522; trace=019ddc85-b125-72b0-891a-958abdcd52cc,id=019ddc85-b125-72b0-891a-958abdcd52cc; trace=019ddc85-b125-72b0-891a-958abdcd52cc,id=019ddc85-b125-72b0-891a-958abdcd52cc; trace=019ddc85-b17d-7f20-bd3b-c92d52f0f0f3,id=019ddc85-b17d-7f20-bd3b-c92d52f0f0f3

      [50/50]   ok  11.11s  calls=2  in= 9676 (cache    0%)  out= 529  acum=$0.8171
       ✓ ok — salvo em bndes__anthropic__claude-haiku-4-5__20260430_005407.xlsx

[run]  anthropic/claude-haiku-4-5 × cvm (id=2)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-b17d-7f20-bd3b-c92d52f0f0f3,id=019ddc85-b17d-7f20-bd3b-c92d52f0f0f3; trace=019ddc85-c550-7392-9658-d89d29428481,id=019ddc85-c550-7392-9658-d89d29428481
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-c550-7392-9658-d89d29428481,id=019ddc85-c550-7392-9658-d89d29428481; trace=019ddc85-e190-71b1-ba80-67a5327e7699,id=019ddc85-e190-71b1-ba80-67a5327e7699; trace=019ddc85-e190-71b1-ba80-67a5327e7699,id=019ddc85-e190-71b1-ba80-67a5327e7699; trace=019ddc85-e25a-7203-8568-dafa8d6bbc59,id=019ddc85-e25a-7203-8568-dafa8d6bbc59

      [ 1/50]   ok  11.11s  calls=2  in=10264 (cache    0%)  out= 420  acum=$0.0124

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-e25a-7203-8568-dafa8d6bbc59,id=019ddc85-e25a-7203-8568-dafa8d6bbc59; trace=019ddc85-f0b8-74d3-afd4-ef497ba77960,id=019ddc85-f0b8-74d3-afd4-ef497ba77960
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc85-f0b8-74d3-afd4-ef497ba77960,id=019ddc85-f0b8-74d3-afd4-ef497ba77960; trace=019ddc86-0f90-7ce3-aa8e-33aa1eff93c6,id=019ddc86-0f90-7ce3-aa8e-33aa1eff93c6; trace=019ddc86-0f90-7ce3-aa8e-33aa1eff93c6,id=019ddc86-0f90-7ce3-aa8e-33aa1eff93c6; trace=019ddc86-105b-7a12-83e2-6a3a7426d6af,id=019ddc86-105b-7a12-83e2-6a3a7426d6af

      [ 2/50]   ok  11.28s  calls=2  in= 9956 (cache    0%)  out= 275  acum=$0.0237

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-105b-7a12-83e2-6a3a7426d6af,id=019ddc86-105b-7a12-83e2-6a3a7426d6af; trace=019ddc86-1cc4-7372-be17-2f2474588162,id=019ddc86-1cc4-7372-be17-2f2474588162
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-1cc4-7372-be17-2f2474588162,id=019ddc86-1cc4-7372-be17-2f2474588162; trace=019ddc86-42c2-7353-a0d7-39449d3c7ee5,id=019ddc86-42c2-7353-a0d7-39449d3c7ee5; trace=019ddc86-42c2-7353-a0d7-39449d3c7ee5,id=019ddc86-42c2-7353-a0d7-39449d3c7ee5; trace=019ddc86-4392-7e43-bcc6-e19e5c83e36f,id=019ddc86-4392-7e43-bcc6-e19e5c83e36f

      [ 3/50]   ok  13.01s  calls=2  in= 9511 (cache    0%)  out= 309  acum=$0.0348

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-4392-7e43-bcc6-e19e5c83e36f,id=019ddc86-4392-7e43-bcc6-e19e5c83e36f; trace=019ddc86-4f95-7e12-baa5-4ba3c85726b1,id=019ddc86-4f95-7e12-baa5-4ba3c85726b1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-4f95-7e12-baa5-4ba3c85726b1,id=019ddc86-4f95-7e12-baa5-4ba3c85726b1; trace=019ddc86-6a06-7ca2-a8fa-d6fe499e347c,id=019ddc86-6a06-7ca2-a8fa-d6fe499e347c; trace=019ddc86-6a06-7ca2-a8fa-d6fe499e347c,id=019ddc86-6a06-7ca2-a8fa-d6fe499e347c; trace=019ddc86-6ad9-7c01-a616-a8f513e7d7ec,id=019ddc86-6ad9-7c01-a616-a8f513e7d7ec

      [ 4/50]   ok  10.75s  calls=2  in= 9920 (cache    0%)  out= 394  acum=$0.0466

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-6ad9-7c01-a616-a8f513e7d7ec,id=019ddc86-6ad9-7c01-a616-a8f513e7d7ec; trace=019ddc86-7993-77d1-9f6b-7370d7dc2c34,id=019ddc86-7993-77d1-9f6b-7370d7dc2c34
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-7993-77d1-9f6b-7370d7dc2c34,id=019ddc86-7993-77d1-9f6b-7370d7dc2c34; trace=019ddc86-985c-7923-99c8-bfd41cdae5d7,id=019ddc86-985c-7923-99c8-bfd41cdae5d7; trace=019ddc86-985c-7923-99c8-bfd41cdae5d7,id=019ddc86-985c-7923-99c8-bfd41cdae5d7; trace=019ddc86-9934-7350-9f32-f44a676c7526,id=019ddc86-9934-7350-9f32-f44a676c7526

      [ 5/50]   ok  11.78s  calls=2  in= 9735 (cache    0%)  out= 393  acum=$0.0583

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-9934-7350-9f32-f44a676c7526,id=019ddc86-9934-7350-9f32-f44a676c7526; trace=019ddc86-a794-7020-bd35-f2ff841ba783,id=019ddc86-a794-7020-bd35-f2ff841ba783
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-a794-7020-bd35-f2ff841ba783,id=019ddc86-a794-7020-bd35-f2ff841ba783; trace=019ddc86-c790-76f2-a107-e87f3f998285,id=019ddc86-c790-76f2-a107-e87f3f998285; trace=019ddc86-c790-76f2-a107-e87f3f998285,id=019ddc86-c790-76f2-a107-e87f3f998285; trace=019ddc86-c7f6-7860-abbc-5b2cc128b55c,id=019ddc86-c7f6-7860-abbc-5b2cc128b55c

      [ 6/50]   ok   12.9s  calls=2  in= 9575 (cache    0%)  out= 493  acum=$0.0704

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-c7f6-7860-abbc-5b2cc128b55c,id=019ddc86-c7f6-7860-abbc-5b2cc128b55c; trace=019ddc86-d9fb-7421-971e-a0077d25e2f7,id=019ddc86-d9fb-7421-971e-a0077d25e2f7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-d9fb-7421-971e-a0077d25e2f7,id=019ddc86-d9fb-7421-971e-a0077d25e2f7; trace=019ddc86-f592-79a0-b25f-3f189dc8746d,id=019ddc86-f592-79a0-b25f-3f189dc8746d; trace=019ddc86-f592-79a0-b25f-3f189dc8746d,id=019ddc86-f592-79a0-b25f-3f189dc8746d; trace=019ddc86-f65a-70c0-93b1-9aa96cc29862,id=019ddc86-f65a-70c0-93b1-9aa96cc29862

      [ 7/50]   ok  11.26s  calls=2  in= 9969 (cache    0%)  out= 414  acum=$0.0824

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc86-f65a-70c0-93b1-9aa96cc29862,id=019ddc86-f65a-70c0-93b1-9aa96cc29862; trace=019ddc87-05fb-74b2-83ce-ba8b9092e759,id=019ddc87-05fb-74b2-83ce-ba8b9092e759
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-05fb-74b2-83ce-ba8b9092e759,id=019ddc87-05fb-74b2-83ce-ba8b9092e759; trace=019ddc87-218f-76f0-b91e-a5560ca0eafb,id=019ddc87-218f-76f0-b91e-a5560ca0eafb; trace=019ddc87-218f-76f0-b91e-a5560ca0eafb,id=019ddc87-218f-76f0-b91e-a5560ca0eafb; trace=019ddc87-21ee-7662-a18a-75477d7277bb,id=019ddc87-21ee-7662-a18a-75477d7277bb

      [ 8/50]   ok  11.86s  calls=2  in= 9826 (cache    0%)  out= 477  acum=$0.0946

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-21ee-7662-a18a-75477d7277bb,id=019ddc87-21ee-7662-a18a-75477d7277bb; trace=019ddc87-344d-7983-b13c-88837ac33971,id=019ddc87-344d-7983-b13c-88837ac33971
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-344d-7983-b13c-88837ac33971,id=019ddc87-344d-7983-b13c-88837ac33971; trace=019ddc87-4e5f-7092-8174-57187a097a06,id=019ddc87-4e5f-7092-8174-57187a097a06; trace=019ddc87-4e5f-7092-8174-57187a097a06,id=019ddc87-4e5f-7092-8174-57187a097a06; trace=019ddc87-4eca-7751-9364-9f9be5a24711,id=019ddc87-4eca-7751-9364-9f9be5a24711

      [ 9/50]   ok   12.2s  calls=2  in= 9063 (cache    0%)  out= 305  acum=$0.1052

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-4eca-7751-9364-9f9be5a24711,id=019ddc87-4eca-7751-9364-9f9be5a24711; trace=019ddc87-63fa-7e11-8ef1-d3333a7167cc,id=019ddc87-63fa-7e11-8ef1-d3333a7167cc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-63fa-7e11-8ef1-d3333a7167cc,id=019ddc87-63fa-7e11-8ef1-d3333a7167cc; trace=019ddc87-79f8-79d1-905f-5bd217038931,id=019ddc87-79f8-79d1-905f-5bd217038931; trace=019ddc87-79f8-79d1-905f-5bd217038931,id=019ddc87-79f8-79d1-905f-5bd217038931; trace=019ddc87-7abf-78d3-86c3-2aa111c3b25f,id=019ddc87-7abf-78d3-86c3-2aa111c3b25f

      [10/50]   ok    8.6s  calls=2  in= 9624 (cache    0%)  out= 350  acum=$0.1166

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-7abf-78d3-86c3-2aa111c3b25f,id=019ddc87-7abf-78d3-86c3-2aa111c3b25f; trace=019ddc87-8593-7591-9162-7b82bb15d48b,id=019ddc87-8593-7591-9162-7b82bb15d48b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-8593-7591-9162-7b82bb15d48b,id=019ddc87-8593-7591-9162-7b82bb15d48b; trace=019ddc87-a72b-72e3-9b19-e95da29923a8,id=019ddc87-a72b-72e3-9b19-e95da29923a8; trace=019ddc87-a72b-72e3-9b19-e95da29923a8,id=019ddc87-a72b-72e3-9b19-e95da29923a8; trace=019ddc87-a789-7393-b1c0-d58bcab15d49,id=019ddc87-a789-7393-b1c0-d58bcab15d49

      [11/50]   ok  11.06s  calls=2  in=10161 (cache    0%)  out= 248  acum=$0.1280

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-a789-7393-b1c0-d58bcab15d49,id=019ddc87-a789-7393-b1c0-d58bcab15d49; trace=019ddc87-b0c8-7440-bb30-9e04b559fd6b,id=019ddc87-b0c8-7440-bb30-9e04b559fd6b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-b0c8-7440-bb30-9e04b559fd6b,id=019ddc87-b0c8-7440-bb30-9e04b559fd6b; trace=019ddc87-d594-7463-8573-53540ea721f9,id=019ddc87-d594-7463-8573-53540ea721f9; trace=019ddc87-d594-7463-8573-53540ea721f9,id=019ddc87-d594-7463-8573-53540ea721f9; trace=019ddc87-d664-7133-b673-a4a128ef79b2,id=019ddc87-d664-7133-b673-a4a128ef79b2

      [12/50]   ok   12.7s  calls=2  in=10188 (cache    0%)  out= 347  acum=$0.1399

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-d664-7133-b673-a4a128ef79b2,id=019ddc87-d664-7133-b673-a4a128ef79b2; trace=019ddc87-e262-7340-b8f7-69b03eace393,id=019ddc87-e262-7340-b8f7-69b03eace393
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc87-e262-7340-b8f7-69b03eace393,id=019ddc87-e262-7340-b8f7-69b03eace393; trace=019ddc88-072d-7143-ad73-927abaa3d9f0,id=019ddc88-072d-7143-ad73-927abaa3d9f0; trace=019ddc88-072d-7143-ad73-927abaa3d9f0,id=019ddc88-072d-7143-ad73-927abaa3d9f0; trace=019ddc88-07f9-7c70-bb28-4bae1291dbf5,id=019ddc88-07f9-7c70-bb28-4bae1291dbf5

      [13/50]   ok  11.69s  calls=2  in= 9845 (cache    0%)  out= 237  acum=$0.1509

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-07f9-7c70-bb28-4bae1291dbf5,id=019ddc88-07f9-7c70-bb28-4bae1291dbf5; trace=019ddc88-100a-7913-b00f-850a414cced6,id=019ddc88-100a-7913-b00f-850a414cced6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-100a-7913-b00f-850a414cced6,id=019ddc88-100a-7913-b00f-850a414cced6; trace=019ddc88-3594-7232-8d7f-32f943612601,id=019ddc88-3594-7232-8d7f-32f943612601; trace=019ddc88-3594-7232-8d7f-32f943612601,id=019ddc88-3594-7232-8d7f-32f943612601; trace=019ddc88-35f1-7993-a3d0-495a0504f1dc,id=019ddc88-35f1-7993-a3d0-495a0504f1dc

      [14/50]   ok   13.3s  calls=2  in= 9466 (cache    0%)  out= 415  acum=$0.1625

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-35f1-7993-a3d0-495a0504f1dc,id=019ddc88-35f1-7993-a3d0-495a0504f1dc; trace=019ddc88-43fb-7023-afec-bfdc41a6fab6,id=019ddc88-43fb-7023-afec-bfdc41a6fab6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-43fb-7023-afec-bfdc41a6fab6,id=019ddc88-43fb-7023-afec-bfdc41a6fab6; trace=019ddc88-6396-7e30-939d-ffe12806c961,id=019ddc88-6396-7e30-939d-ffe12806c961; trace=019ddc88-6396-7e30-939d-ffe12806c961,id=019ddc88-6396-7e30-939d-ffe12806c961; trace=019ddc88-646f-7b33-b038-fa83967d8b8a,id=019ddc88-646f-7b33-b038-fa83967d8b8a

      [15/50]   ok  12.08s  calls=2  in=10343 (cache    0%)  out= 402  acum=$0.1748

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-646f-7b33-b038-fa83967d8b8a,id=019ddc88-646f-7b33-b038-fa83967d8b8a; trace=019ddc88-732e-7312-8ed3-074021f8e53c,id=019ddc88-732e-7312-8ed3-074021f8e53c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-732e-7312-8ed3-074021f8e53c,id=019ddc88-732e-7312-8ed3-074021f8e53c; trace=019ddc88-9261-7020-9277-1cf0d3185e49,id=019ddc88-9261-7020-9277-1cf0d3185e49; trace=019ddc88-9261-7020-9277-1cf0d3185e49,id=019ddc88-9261-7020-9277-1cf0d3185e49; trace=019ddc88-9330-7d53-a77d-351db55ac2a4,id=019ddc88-9330-7d53-a77d-351db55ac2a4

      [16/50]   ok  12.39s  calls=2  in=10579 (cache    0%)  out= 446  acum=$0.1876

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-9330-7d53-a77d-351db55ac2a4,id=019ddc88-9330-7d53-a77d-351db55ac2a4; trace=019ddc88-a395-7430-8cab-175edd307458,id=019ddc88-a395-7430-8cab-175edd307458
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-a395-7430-8cab-175edd307458,id=019ddc88-a395-7430-8cab-175edd307458; trace=019ddc88-c2fb-7350-9f36-3e9e202455b7,id=019ddc88-c2fb-7350-9f36-3e9e202455b7; trace=019ddc88-c2fb-7350-9f36-3e9e202455b7,id=019ddc88-c2fb-7350-9f36-3e9e202455b7; trace=019ddc88-c3cf-76c0-b896-5eb080aa67ec,id=019ddc88-c3cf-76c0-b896-5eb080aa67ec

      [17/50]   ok  11.68s  calls=2  in= 9744 (cache    0%)  out= 389  acum=$0.1993

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-c3cf-76c0-b896-5eb080aa67ec,id=019ddc88-c3cf-76c0-b896-5eb080aa67ec; trace=019ddc88-d131-7673-9bc9-c1c3b10d8f24,id=019ddc88-d131-7673-9bc9-c1c3b10d8f24
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-d131-7673-9bc9-c1c3b10d8f24,id=019ddc88-d131-7673-9bc9-c1c3b10d8f24; trace=019ddc88-f461-7091-9a34-6b3f0e7ec923,id=019ddc88-f461-7091-9a34-6b3f0e7ec923; trace=019ddc88-f461-7091-9a34-6b3f0e7ec923,id=019ddc88-f461-7091-9a34-6b3f0e7ec923; trace=019ddc88-f52a-7371-9c45-db5d171f980a,id=019ddc88-f52a-7371-9c45-db5d171f980a

      [18/50]   ok  16.79s  calls=2  in=11812 (cache    0%)  out= 809  acum=$0.2152

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc88-f52a-7371-9c45-db5d171f980a,id=019ddc88-f52a-7371-9c45-db5d171f980a; trace=019ddc89-12ca-7633-8e8a-1541c5fdca24,id=019ddc89-12ca-7633-8e8a-1541c5fdca24
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-12ca-7633-8e8a-1541c5fdca24,id=019ddc89-12ca-7633-8e8a-1541c5fdca24; trace=019ddc89-2bb8-7262-8a94-43a0c4a1632b,id=019ddc89-2bb8-7262-8a94-43a0c4a1632b; trace=019ddc89-2bb8-7262-8a94-43a0c4a1632b,id=019ddc89-2bb8-7262-8a94-43a0c4a1632b; trace=019ddc89-2c8b-7fe3-b7af-2533bdef0678,id=019ddc89-2c8b-7fe3-b7af-2533bdef0678
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-2c8b-7fe3-b7af-2533bdef0678,id=019ddc89-2c8b-7fe3-b7af-2533bdef0678

      [19/50]   ok    8.8s  calls=2  in=10739 (cache    0%)  out= 236  acum=$0.2271

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-3531-7f21-8f57-b43610349732,id=019ddc89-3531-7f21-8f57-b43610349732
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-3531-7f21-8f57-b43610349732,id=019ddc89-3531-7f21-8f57-b43610349732; trace=019ddc89-5b94-7361-a356-2b5469794143,id=019ddc89-5b94-7361-a356-2b5469794143; trace=019ddc89-5b94-7361-a356-2b5469794143,id=019ddc89-5b94-7361-a356-2b5469794143; trace=019ddc89-5c53-73c1-a7bb-57d628155c8a,id=019ddc89-5c53-73c1-a7bb-57d628155c8a

      [20/50]   ok  12.29s  calls=2  in=10740 (cache    0%)  out= 238  acum=$0.2390

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-5c53-73c1-a7bb-57d628155c8a,id=019ddc89-5c53-73c1-a7bb-57d628155c8a; trace=019ddc89-6532-7d93-84d5-6945a07ccf54,id=019ddc89-6532-7d93-84d5-6945a07ccf54
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-6532-7d93-84d5-6945a07ccf54,id=019ddc89-6532-7d93-84d5-6945a07ccf54; trace=019ddc89-8dfd-7370-8ab5-012f7babe5ee,id=019ddc89-8dfd-7370-8ab5-012f7babe5ee; trace=019ddc89-8dfd-7370-8ab5-012f7babe5ee,id=019ddc89-8dfd-7370-8ab5-012f7babe5ee; trace=019ddc89-8ec6-7942-9789-edae3eedf63a,id=019ddc89-8ec6-7942-9789-edae3eedf63a

      [21/50]   ok  15.66s  calls=2  in= 9614 (cache    0%)  out= 534  acum=$0.2513

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-8ec6-7942-9789-edae3eedf63a,id=019ddc89-8ec6-7942-9789-edae3eedf63a; trace=019ddc89-a263-7b13-bbe9-696ef16b2a27,id=019ddc89-a263-7b13-bbe9-696ef16b2a27
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-a263-7b13-bbe9-696ef16b2a27,id=019ddc89-a263-7b13-bbe9-696ef16b2a27; trace=019ddc89-b862-71d2-a7ed-e10182d9dff1,id=019ddc89-b862-71d2-a7ed-e10182d9dff1; trace=019ddc89-b862-71d2-a7ed-e10182d9dff1,id=019ddc89-b862-71d2-a7ed-e10182d9dff1; trace=019ddc89-b926-7f33-829b-eb39a4268351,id=019ddc89-b926-7f33-829b-eb39a4268351

      [22/50]   ok  11.38s  calls=2  in=10009 (cache    0%)  out= 579  acum=$0.2642

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-b926-7f33-829b-eb39a4268351,id=019ddc89-b926-7f33-829b-eb39a4268351; trace=019ddc89-ced3-78f0-9d47-39ff84a85c41,id=019ddc89-ced3-78f0-9d47-39ff84a85c41
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-ced3-78f0-9d47-39ff84a85c41,id=019ddc89-ced3-78f0-9d47-39ff84a85c41; trace=019ddc89-ea63-74c2-95dc-735b6755a04d,id=019ddc89-ea63-74c2-95dc-735b6755a04d; trace=019ddc89-ea63-74c2-95dc-735b6755a04d,id=019ddc89-ea63-74c2-95dc-735b6755a04d; trace=019ddc89-eb31-7cd2-b4dd-bb92cd4cf4b0,id=019ddc89-eb31-7cd2-b4dd-bb92cd4cf4b0

      [23/50]   ok   9.61s  calls=2  in=10193 (cache    0%)  out= 255  acum=$0.2757

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-eb31-7cd2-b4dd-bb92cd4cf4b0,id=019ddc89-eb31-7cd2-b4dd-bb92cd4cf4b0; trace=019ddc89-f460-7573-8868-b4bc5bb7e3fb,id=019ddc89-f460-7573-8868-b4bc5bb7e3fb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc89-f460-7573-8868-b4bc5bb7e3fb,id=019ddc89-f460-7573-8868-b4bc5bb7e3fb; trace=019ddc8a-1bfd-7760-9e1c-9be972969ce2,id=019ddc8a-1bfd-7760-9e1c-9be972969ce2; trace=019ddc8a-1bfd-7760-9e1c-9be972969ce2,id=019ddc8a-1bfd-7760-9e1c-9be972969ce2; trace=019ddc8a-1cb7-78b3-af07-d3e991865475,id=019ddc8a-1cb7-78b3-af07-d3e991865475

      [24/50]   ok  13.78s  calls=2  in= 9824 (cache    0%)  out= 230  acum=$0.2867

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-1cb7-78b3-af07-d3e991865475,id=019ddc8a-1cb7-78b3-af07-d3e991865475; trace=019ddc8a-2a31-7173-85f3-953a50fd8299,id=019ddc8a-2a31-7173-85f3-953a50fd8299
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-2a31-7173-85f3-953a50fd8299,id=019ddc8a-2a31-7173-85f3-953a50fd8299; trace=019ddc8a-4997-7783-a7b2-1c5060257d10,id=019ddc8a-4997-7783-a7b2-1c5060257d10; trace=019ddc8a-4997-7783-a7b2-1c5060257d10,id=019ddc8a-4997-7783-a7b2-1c5060257d10; trace=019ddc8a-4a65-7f70-8f08-fcfd7f2e3438,id=019ddc8a-4a65-7f70-8f08-fcfd7f2e3438
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-4a65-7f70-8f08-fcfd7f2e3438,id=019ddc8a-4a65-7f70-8f08-fcfd7f2e3438; trace=019ddc8a-51f2-77f2-8682-5c5de089d751,id=019ddc8a-51f2-77f2-8682-5c5de089d751; trace=019ddc8a-51f2-77f2-8682-5c5de089d751,id=019ddc8a-51f2-77f2-8682-5c5de089d751; trace=019ddc8a-52bd-7403-a0bf-e942b7c58f80,id=019ddc8a-52bd-7403-a0bf-e942b7c58f80
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-52bd-7403-a0bf-e942b7c58f80,id=019ddc8a-52bd-7403-a0bf-e942b7c58f80; trace=019ddc8a-7d31-7271-9192-6e45469bc6fc,id=019ddc8a-7d31-7271-9192-6e45469bc6fc; trace=019ddc8a-7d31-7271-9192-6e45469bc6fc,id=019ddc8a-7d31-7271-9192-6e45469bc6fc; trace=019ddc8a-7d34-7a41-9c28-fd7614990eb4,id=019ddc8a-7d34-7a41-9c28-fd7614990eb4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-7d34-7a41-9c28-fd7614990eb4,id=019ddc8a-7d34-7a41-9c28-fd7614990eb4; trace=019ddc8a-add2-7c10-a6aa-92130e5b4560,id=019ddc8a-add2-7c10-a6aa-92130e5b4560; trace=019ddc8a-add2-7c10-a6aa-92130e5b4560,id=019ddc8a-add2-7c10-a6aa-92130e5b4560; trace=019ddc8a-add5-7912-8533-45de66b3acb8,id=019ddc8a-add5-7912-8533-45de66b3acb8
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-add5-7912-8533-45de66b3acb8,id=019ddc8a-add5-7912-8533-45de66b3acb8; trace=019ddc8a-e8ca-74a0-a741-1396dad8186d,id=019ddc8a-e8ca-74a0-a741-1396dad8186d; trace=019ddc8a-e8ca-74a0-a741-1396dad8186d,id=019ddc8a-e8ca-74a0-a741-1396dad8186d; trace=019ddc8a-e9a6-7423-b8be-dea500c030dc,id=019ddc8a-e9a6-7423-b8be-dea500c030dc

      [25/50]   ok  64.47s  calls=6  in=61882 (cache    0%)  out= 862  acum=$0.3529

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8a-e9a6-7423-b8be-dea500c030dc,id=019ddc8a-e9a6-7423-b8be-dea500c030dc; trace=019ddc8b-260a-72c0-9230-57d21c021cad,id=019ddc8b-260a-72c0-9230-57d21c021cad
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-260a-72c0-9230-57d21c021cad,id=019ddc8b-260a-72c0-9230-57d21c021cad; trace=019ddc8b-6bfe-7ab3-9224-782b08aac5a4,id=019ddc8b-6bfe-7ab3-9224-782b08aac5a4; trace=019ddc8b-6bfe-7ab3-9224-782b08aac5a4,id=019ddc8b-6bfe-7ab3-9224-782b08aac5a4; trace=019ddc8b-6c95-75f0-84b5-db50bc6524a9,id=019ddc8b-6c95-75f0-84b5-db50bc6524a9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-6c95-75f0-84b5-db50bc6524a9,id=019ddc8b-6c95-75f0-84b5-db50bc6524a9; trace=019ddc8b-74f2-71a1-a94c-d10a39fb4226,id=019ddc8b-74f2-71a1-a94c-d10a39fb4226; trace=019ddc8b-74f2-71a1-a94c-d10a39fb4226,id=019ddc8b-74f2-71a1-a94c-d10a39fb4226; trace=019ddc8b-7593-76c0-a8d4-46fedaa2e1d6,id=019ddc8b-7593-76c0-a8d4-46fedaa2e1d6

      [26/50]   ok  33.37s  calls=3  in=24591 (cache    0%)  out= 434  acum=$0.3796

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-7593-76c0-a8d4-46fedaa2e1d6,id=019ddc8b-7593-76c0-a8d4-46fedaa2e1d6; trace=019ddc8b-a866-70b2-b8fa-43d0d0a89ced,id=019ddc8b-a866-70b2-b8fa-43d0d0a89ced
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-a866-70b2-b8fa-43d0d0a89ced,id=019ddc8b-a866-70b2-b8fa-43d0d0a89ced; trace=019ddc8b-e2cb-7a01-bdfa-460d3dea7233,id=019ddc8b-e2cb-7a01-bdfa-460d3dea7233; trace=019ddc8b-e2cb-7a01-bdfa-460d3dea7233,id=019ddc8b-e2cb-7a01-bdfa-460d3dea7233; trace=019ddc8b-e337-7f12-ad52-a19ab9a425e7,id=019ddc8b-e337-7f12-ad52-a19ab9a425e7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-e337-7f12-ad52-a19ab9a425e7,id=019ddc8b-e337-7f12-ad52-a19ab9a425e7; trace=019ddc8b-eadc-7860-8bad-52e1dbb61bdc,id=019ddc8b-eadc-7860-8bad-52e1dbb61bdc; trace=019ddc8b-eadc-7860-8bad-52e1dbb61bdc,id=019ddc8b-eadc-7860-8bad-52e1dbb61bdc; trace=019ddc8b-eb4f-70b3-8ab8-cdc279159d6d,id=019ddc8b-eb4f-70b3-8ab8-cdc279159d6d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8b-eb4f-70b3-8ab8-cdc279159d6d,id=019ddc8b-eb4f-70b3-8ab8-cdc279159d6d; trace=019ddc8c-119a-76f2-a347-278c0914b695,id=019ddc8c-119a-76f2-a347-278c0914b695; trace=019ddc8c-119a-76f2-a347-278c0914b695,id=019ddc8c-119a-76f2-a347-278c0914b695; trace=019ddc8c-119d-7eb1-aa54-df2168d6cc6b,id=019ddc8c-119d-7eb1-aa54-df2168d6cc6b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8c-119d-7eb1-aa54-df2168d6cc6b,id=019ddc8c-119d-7eb1-aa54-df2168d6cc6b; trace=019ddc8c-4ee2-7301-9197-e4106e147f7e,id=019ddc8c-4ee2-7301-9197-e4106e147f7e; trace=019ddc8c-4ee2-7301-9197-e4106e147f7e,id=019ddc8c-4ee2-7301-9197-e4106e147f7e; trace=019ddc8c-4ee4-7b50-855d-8f29a2dfe300,id=019ddc8c-4ee4-7b50-855d-8f29a2dfe300

      [27/50]   ok  61.23s  calls=5  in=52370 (cache    0%)  out= 717  acum=$0.4356

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8c-4ee4-7b50-855d-8f29a2dfe300,id=019ddc8c-4ee4-7b50-855d-8f29a2dfe300; trace=019ddc8c-9793-7ff2-99a7-065072d85023,id=019ddc8c-9793-7ff2-99a7-065072d85023
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8c-9793-7ff2-99a7-065072d85023,id=019ddc8c-9793-7ff2-99a7-065072d85023; trace=019ddc8c-d264-7690-b45f-dbc1554e4ee8,id=019ddc8c-d264-7690-b45f-dbc1554e4ee8; trace=019ddc8c-d264-7690-b45f-dbc1554e4ee8,id=019ddc8c-d264-7690-b45f-dbc1554e4ee8; trace=019ddc8c-d322-7461-82ba-4c9beb5116dc,id=019ddc8c-d322-7461-82ba-4c9beb5116dc

      [28/50]   ok  20.39s  calls=2  in=10490 (cache    0%)  out= 510  acum=$0.4486

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8c-d322-7461-82ba-4c9beb5116dc,id=019ddc8c-d322-7461-82ba-4c9beb5116dc; trace=019ddc8c-e73f-73c0-b6dd-1ac997c89261,id=019ddc8c-e73f-73c0-b6dd-1ac997c89261
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8c-e73f-73c0-b6dd-1ac997c89261,id=019ddc8c-e73f-73c0-b6dd-1ac997c89261; trace=019ddc8d-0363-79d2-b166-0ae0f4b379da,id=019ddc8d-0363-79d2-b166-0ae0f4b379da; trace=019ddc8d-0363-79d2-b166-0ae0f4b379da,id=019ddc8d-0363-79d2-b166-0ae0f4b379da; trace=019ddc8d-0428-7532-a4d9-99e37a098db0,id=019ddc8d-0428-7532-a4d9-99e37a098db0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-0428-7532-a4d9-99e37a098db0,id=019ddc8d-0428-7532-a4d9-99e37a098db0; trace=019ddc8d-0b9d-7cd1-9b11-ebf8c87f0ca0,id=019ddc8d-0b9d-7cd1-9b11-ebf8c87f0ca0; trace=019ddc8d-0b9d-7cd1-9b11-ebf8c87f0ca0,id=019ddc8d-0b9d-7cd1-9b11-ebf8c87f0ca0; trace=019ddc8d-0c5e-7e91-8421-e33ff8d7b7ab,id=019ddc8d-0c5e-7e91-8421-e33ff8d7b7ab
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-0c5e-7e91-8421-e33ff8d7b7ab,id=019ddc8d-0c5e-7e91-8421-e33ff8d7b7ab; trace=019ddc8d-3b34-7c11-bf74-2adee25faa21,id=019ddc8d-3b34-7c11-bf74-2adee25faa21; trace=019ddc8d-3b34-7c11-bf74-2adee25faa21,id=019ddc8d-3b34-7c11-bf74-2adee25faa21; trace=019ddc8d-3b37-79d1-aa09-5d8f5d7387f9,id=019ddc8d-3b37-79d1-aa09-5d8f5d7387f9

      [29/50]   ok  38.19s  calls=4  in=38454 (cache    0%)  out= 587  acum=$0.4900

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-3b37-79d1-aa09-5d8f5d7387f9,id=019ddc8d-3b37-79d1-aa09-5d8f5d7387f9; trace=019ddc8d-7c6b-70d2-8c5f-89a448a94966,id=019ddc8d-7c6b-70d2-8c5f-89a448a94966
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-7c6b-70d2-8c5f-89a448a94966,id=019ddc8d-7c6b-70d2-8c5f-89a448a94966; trace=019ddc8d-b76a-7d42-8b3a-79de0c2685ce,id=019ddc8d-b76a-7d42-8b3a-79de0c2685ce; trace=019ddc8d-b76a-7d42-8b3a-79de0c2685ce,id=019ddc8d-b76a-7d42-8b3a-79de0c2685ce; trace=019ddc8d-b83f-70a0-9a5d-55e4b54e098b,id=019ddc8d-b83f-70a0-9a5d-55e4b54e098b

      [30/50]   ok  19.97s  calls=2  in=11686 (cache    0%)  out= 487  acum=$0.5041

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-b83f-70a0-9a5d-55e4b54e098b,id=019ddc8d-b83f-70a0-9a5d-55e4b54e098b; trace=019ddc8d-ca6a-77d1-b353-a6306da63b65,id=019ddc8d-ca6a-77d1-b353-a6306da63b65
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-ca6a-77d1-b353-a6306da63b65,id=019ddc8d-ca6a-77d1-b353-a6306da63b65; trace=019ddc8d-ed36-7ab1-bf4e-83a9cce5980a,id=019ddc8d-ed36-7ab1-bf4e-83a9cce5980a; trace=019ddc8d-ed36-7ab1-bf4e-83a9cce5980a,id=019ddc8d-ed36-7ab1-bf4e-83a9cce5980a; trace=019ddc8d-ee02-73b1-90ee-14291bb118ba,id=019ddc8d-ee02-73b1-90ee-14291bb118ba

      [31/50]   ok  13.11s  calls=2  in= 9863 (cache    0%)  out= 424  acum=$0.5161

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-ee02-73b1-90ee-14291bb118ba,id=019ddc8d-ee02-73b1-90ee-14291bb118ba; trace=019ddc8d-fd9e-7743-ab44-4cc91f872930,id=019ddc8d-fd9e-7743-ab44-4cc91f872930
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8d-fd9e-7743-ab44-4cc91f872930,id=019ddc8d-fd9e-7743-ab44-4cc91f872930; trace=019ddc8e-1ca0-7720-b2b9-6abd62c8a391,id=019ddc8e-1ca0-7720-b2b9-6abd62c8a391; trace=019ddc8e-1ca0-7720-b2b9-6abd62c8a391,id=019ddc8e-1ca0-7720-b2b9-6abd62c8a391; trace=019ddc8e-1d74-7952-886f-b8ad330cd555,id=019ddc8e-1d74-7952-886f-b8ad330cd555

      [32/50]   ok  11.88s  calls=2  in= 9387 (cache    0%)  out= 498  acum=$0.5280

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-1d74-7952-886f-b8ad330cd555,id=019ddc8e-1d74-7952-886f-b8ad330cd555; trace=019ddc8e-2c05-7bf1-b61e-2f41c9d1a884,id=019ddc8e-2c05-7bf1-b61e-2f41c9d1a884
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-2c05-7bf1-b61e-2f41c9d1a884,id=019ddc8e-2c05-7bf1-b61e-2f41c9d1a884; trace=019ddc8e-4e04-7b41-a51b-12123d93168b,id=019ddc8e-4e04-7b41-a51b-12123d93168b; trace=019ddc8e-4e04-7b41-a51b-12123d93168b,id=019ddc8e-4e04-7b41-a51b-12123d93168b; trace=019ddc8e-4ebd-72e0-8c70-03af2c7c9336,id=019ddc8e-4ebd-72e0-8c70-03af2c7c9336

      [33/50]   ok  12.12s  calls=2  in= 9977 (cache    0%)  out= 335  acum=$0.5396

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-4ebd-72e0-8c70-03af2c7c9336,id=019ddc8e-4ebd-72e0-8c70-03af2c7c9336; trace=019ddc8e-5b5a-7b03-a49f-94271bc479cb,id=019ddc8e-5b5a-7b03-a49f-94271bc479cb
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-5b5a-7b03-a49f-94271bc479cb,id=019ddc8e-5b5a-7b03-a49f-94271bc479cb; trace=019ddc8e-7739-7fc2-a51f-e34ee348ce8d,id=019ddc8e-7739-7fc2-a51f-e34ee348ce8d; trace=019ddc8e-7739-7fc2-a51f-e34ee348ce8d,id=019ddc8e-7739-7fc2-a51f-e34ee348ce8d; trace=019ddc8e-7816-7743-a879-b8fe924cdf70,id=019ddc8e-7816-7743-a879-b8fe924cdf70

      [34/50]   ok   9.02s  calls=2  in= 9762 (cache    0%)  out= 154  acum=$0.5502

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-7816-7743-a879-b8fe924cdf70,id=019ddc8e-7816-7743-a879-b8fe924cdf70; trace=019ddc8e-7e97-75f2-9710-41ead7475728,id=019ddc8e-7e97-75f2-9710-41ead7475728
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-7e97-75f2-9710-41ead7475728,id=019ddc8e-7e97-75f2-9710-41ead7475728; trace=019ddc8e-a52c-7022-9a43-46771e268db4,id=019ddc8e-a52c-7022-9a43-46771e268db4; trace=019ddc8e-a52c-7022-9a43-46771e268db4,id=019ddc8e-a52c-7022-9a43-46771e268db4; trace=019ddc8e-a5e1-7900-8dfa-6235f5406244,id=019ddc8e-a5e1-7900-8dfa-6235f5406244

      [35/50]   ok  13.09s  calls=2  in= 9876 (cache    0%)  out= 355  acum=$0.5618

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-a5e1-7900-8dfa-6235f5406244,id=019ddc8e-a5e1-7900-8dfa-6235f5406244; trace=019ddc8e-b1bb-7a91-9eff-d2d2201516cf,id=019ddc8e-b1bb-7a91-9eff-d2d2201516cf
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-b1bb-7a91-9eff-d2d2201516cf,id=019ddc8e-b1bb-7a91-9eff-d2d2201516cf; trace=019ddc8e-d603-75c3-b123-1efd0456cc30,id=019ddc8e-d603-75c3-b123-1efd0456cc30; trace=019ddc8e-d603-75c3-b123-1efd0456cc30,id=019ddc8e-d603-75c3-b123-1efd0456cc30; trace=019ddc8e-d6d6-7383-a26d-1c6b3a86a3ce,id=019ddc8e-d6d6-7383-a26d-1c6b3a86a3ce; trace=019ddc8e-d6d6-7383-a26d-1c6b3a86a3ce,id=019ddc8e-d6d6-7383-a26d-1c6b3a86a3ce; trace=019ddc8e-d6d8-7db3-abad-2e8226e92a84,id=019ddc8e-d6d8-7db3-abad-2e8226e92a84

      [36/50]   ok  13.42s  calls=2  in=11043 (cache    0%)  out= 535  acum=$0.5755

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-d6d8-7db3-abad-2e8226e92a84,id=019ddc8e-d6d8-7db3-abad-2e8226e92a84; trace=019ddc8e-e627-7690-a818-5abce53c2017,id=019ddc8e-e627-7690-a818-5abce53c2017
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8e-e627-7690-a818-5abce53c2017,id=019ddc8e-e627-7690-a818-5abce53c2017; trace=019ddc8f-0a05-7db0-a05c-9284df50cddc,id=019ddc8f-0a05-7db0-a05c-9284df50cddc; trace=019ddc8f-0a05-7db0-a05c-9284df50cddc,id=019ddc8f-0a05-7db0-a05c-9284df50cddc; trace=019ddc8f-0ac0-7f63-b3b9-43cc5b5a94ed,id=019ddc8f-0ac0-7f63-b3b9-43cc5b5a94ed

      [37/50]   ok  12.66s  calls=2  in=11681 (cache    0%)  out= 440  acum=$0.5894

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-0ac0-7f63-b3b9-43cc5b5a94ed,id=019ddc8f-0ac0-7f63-b3b9-43cc5b5a94ed; trace=019ddc8f-179c-7fd1-aa8d-be192c8119e7,id=019ddc8f-179c-7fd1-aa8d-be192c8119e7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-179c-7fd1-aa8d-be192c8119e7,id=019ddc8f-179c-7fd1-aa8d-be192c8119e7; trace=019ddc8f-3ed0-7980-bdcb-53f76a30f9d1,id=019ddc8f-3ed0-7980-bdcb-53f76a30f9d1; trace=019ddc8f-3ed0-7980-bdcb-53f76a30f9d1,id=019ddc8f-3ed0-7980-bdcb-53f76a30f9d1; trace=019ddc8f-3f88-7592-839f-aebda3205c34,id=019ddc8f-3f88-7592-839f-aebda3205c34
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-3f88-7592-839f-aebda3205c34,id=019ddc8f-3f88-7592-839f-aebda3205c34; trace=019ddc8f-46d0-7e90-9305-40e18fc87f1b,id=019ddc8f-46d0-7e90-9305-40e18fc87f1b; trace=019ddc8f-46d0-7e90-9305-40e18fc87f1b,id=019ddc8f-46d0-7e90-9305-40e18fc87f1b; trace=019ddc8f-479b-7870-aae2-3cab871aa5ff,id=019ddc8f-479b-7870-aae2-3cab871aa5ff

      [38/50]   ok  26.12s  calls=3  in=22859 (cache    0%)  out= 517  acum=$0.6149

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-479b-7870-aae2-3cab871aa5ff,id=019ddc8f-479b-7870-aae2-3cab871aa5ff; trace=019ddc8f-7da0-7e80-b25f-dafe74e3fae8,id=019ddc8f-7da0-7e80-b25f-dafe74e3fae8
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-7da0-7e80-b25f-dafe74e3fae8,id=019ddc8f-7da0-7e80-b25f-dafe74e3fae8; trace=019ddc8f-a805-7893-b438-8e6ae9ed9483,id=019ddc8f-a805-7893-b438-8e6ae9ed9483; trace=019ddc8f-a805-7893-b438-8e6ae9ed9483,id=019ddc8f-a805-7893-b438-8e6ae9ed9483; trace=019ddc8f-a862-7741-a06b-7fdd2fb433dc,id=019ddc8f-a862-7741-a06b-7fdd2fb433dc

      [39/50]   ok  14.65s  calls=2  in=10173 (cache    0%)  out= 354  acum=$0.6268

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-a862-7741-a06b-7fdd2fb433dc,id=019ddc8f-a862-7741-a06b-7fdd2fb433dc; trace=019ddc8f-b6d6-7813-abd4-46ac42f41f25,id=019ddc8f-b6d6-7813-abd4-46ac42f41f25
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-b6d6-7813-abd4-46ac42f41f25,id=019ddc8f-b6d6-7813-abd4-46ac42f41f25; trace=019ddc8f-da08-7790-ac0c-b29dbd74979f,id=019ddc8f-da08-7790-ac0c-b29dbd74979f; trace=019ddc8f-da08-7790-ac0c-b29dbd74979f,id=019ddc8f-da08-7790-ac0c-b29dbd74979f; trace=019ddc8f-dad4-7062-8f17-66812874e95f,id=019ddc8f-dad4-7062-8f17-66812874e95f

      [40/50]   ok  15.57s  calls=2  in=11279 (cache    0%)  out= 619  acum=$0.6412

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-dad4-7062-8f17-66812874e95f,id=019ddc8f-dad4-7062-8f17-66812874e95f; trace=019ddc8f-f3a6-72c1-873d-2a72dadab1fc,id=019ddc8f-f3a6-72c1-873d-2a72dadab1fc
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc8f-f3a6-72c1-873d-2a72dadab1fc,id=019ddc8f-f3a6-72c1-873d-2a72dadab1fc; trace=019ddc90-0f0c-7fb0-a6ad-16b08d3865a9,id=019ddc90-0f0c-7fb0-a6ad-16b08d3865a9; trace=019ddc90-0f0c-7fb0-a6ad-16b08d3865a9,id=019ddc90-0f0c-7fb0-a6ad-16b08d3865a9; trace=019ddc90-0f79-7713-969d-5fa061f102e3,id=019ddc90-0f79-7713-969d-5fa061f102e3

      [41/50]   ok  11.56s  calls=2  in=11767 (cache    0%)  out= 554  acum=$0.6557

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-0f79-7713-969d-5fa061f102e3,id=019ddc90-0f79-7713-969d-5fa061f102e3; trace=019ddc90-20d3-7283-b3da-19c862bfdaad,id=019ddc90-20d3-7283-b3da-19c862bfdaad
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-20d3-7283-b3da-19c862bfdaad,id=019ddc90-20d3-7283-b3da-19c862bfdaad; trace=019ddc90-439f-7823-8cfe-734076c28485,id=019ddc90-439f-7823-8cfe-734076c28485; trace=019ddc90-439f-7823-8cfe-734076c28485,id=019ddc90-439f-7823-8cfe-734076c28485; trace=019ddc90-43ff-7dd2-86bd-2336216f0cec,id=019ddc90-43ff-7dd2-86bd-2336216f0cec

      [42/50]   ok   12.7s  calls=2  in= 9947 (cache    0%)  out= 346  acum=$0.6674

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-43ff-7dd2-86bd-2336216f0cec,id=019ddc90-43ff-7dd2-86bd-2336216f0cec; trace=019ddc90-526e-7650-a4ad-841bc21ea9c1,id=019ddc90-526e-7650-a4ad-841bc21ea9c1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-526e-7650-a4ad-841bc21ea9c1,id=019ddc90-526e-7650-a4ad-841bc21ea9c1; trace=019ddc90-7606-70c3-ae5e-439d67b05dc9,id=019ddc90-7606-70c3-ae5e-439d67b05dc9; trace=019ddc90-7606-70c3-ae5e-439d67b05dc9,id=019ddc90-7606-70c3-ae5e-439d67b05dc9; trace=019ddc90-76e0-7841-8f64-cf532f794dc9,id=019ddc90-76e0-7841-8f64-cf532f794dc9

      [43/50]   ok  11.57s  calls=2  in=10056 (cache    0%)  out= 248  acum=$0.6787

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-76e0-7841-8f64-cf532f794dc9,id=019ddc90-76e0-7841-8f64-cf532f794dc9; trace=019ddc90-7fa0-7fe2-b679-8c98949a3e6a,id=019ddc90-7fa0-7fe2-b679-8c98949a3e6a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-7fa0-7fe2-b679-8c98949a3e6a,id=019ddc90-7fa0-7fe2-b679-8c98949a3e6a; trace=019ddc90-a1cd-7761-b32b-ed249667388d,id=019ddc90-a1cd-7761-b32b-ed249667388d; trace=019ddc90-a1cd-7761-b32b-ed249667388d,id=019ddc90-a1cd-7761-b32b-ed249667388d; trace=019ddc90-a23f-7872-942f-b80c77a01a4f,id=019ddc90-a23f-7872-942f-b80c77a01a4f

      [44/50]   ok  12.47s  calls=2  in=10488 (cache    0%)  out= 345  acum=$0.6909

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-a23f-7872-942f-b80c77a01a4f,id=019ddc90-a23f-7872-942f-b80c77a01a4f; trace=019ddc90-b054-7df3-9e7c-da47b736dc77,id=019ddc90-b054-7df3-9e7c-da47b736dc77
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-b054-7df3-9e7c-da47b736dc77,id=019ddc90-b054-7df3-9e7c-da47b736dc77; trace=019ddc90-d342-7521-9393-4360ce85ac6b,id=019ddc90-d342-7521-9393-4360ce85ac6b; trace=019ddc90-d342-7521-9393-4360ce85ac6b,id=019ddc90-d342-7521-9393-4360ce85ac6b; trace=019ddc90-d3a3-7260-b063-5c70425af8cd,id=019ddc90-d3a3-7260-b063-5c70425af8cd

      [45/50]   ok  14.26s  calls=2  in=10297 (cache    0%)  out= 556  acum=$0.7040

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-d3a3-7260-b063-5c70425af8cd,id=019ddc90-d3a3-7260-b063-5c70425af8cd; trace=019ddc90-e804-7f92-b53a-0c3a1962dc69,id=019ddc90-e804-7f92-b53a-0c3a1962dc69
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc90-e804-7f92-b53a-0c3a1962dc69,id=019ddc90-e804-7f92-b53a-0c3a1962dc69; trace=019ddc91-0275-7722-bf6a-925f5a6d3c3f,id=019ddc91-0275-7722-bf6a-925f5a6d3c3f; trace=019ddc91-0275-7722-bf6a-925f5a6d3c3f,id=019ddc91-0275-7722-bf6a-925f5a6d3c3f; trace=019ddc91-033e-75d0-9500-bbb60ebebbca,id=019ddc91-033e-75d0-9500-bbb60ebebbca

      [46/50]   ok  10.24s  calls=2  in= 9073 (cache    0%)  out= 356  acum=$0.7148

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-033e-75d0-9500-bbb60ebebbca,id=019ddc91-033e-75d0-9500-bbb60ebebbca; trace=019ddc91-1004-78f2-9e85-7cd2f5546ec7,id=019ddc91-1004-78f2-9e85-7cd2f5546ec7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-1004-78f2-9e85-7cd2f5546ec7,id=019ddc91-1004-78f2-9e85-7cd2f5546ec7; trace=019ddc91-2f33-7410-b726-075931597989,id=019ddc91-2f33-7410-b726-075931597989; trace=019ddc91-2f33-7410-b726-075931597989,id=019ddc91-2f33-7410-b726-075931597989; trace=019ddc91-2f95-7472-9f5f-ebc759b71511,id=019ddc91-2f95-7472-9f5f-ebc759b71511

      [47/50]   ok  11.98s  calls=2  in= 9131 (cache    0%)  out= 455  acum=$0.7262

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-2f95-7472-9f5f-ebc759b71511,id=019ddc91-2f95-7472-9f5f-ebc759b71511; trace=019ddc91-3ece-70a0-937f-fb60adc73082,id=019ddc91-3ece-70a0-937f-fb60adc73082
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-3ece-70a0-937f-fb60adc73082,id=019ddc91-3ece-70a0-937f-fb60adc73082; trace=019ddc91-5a00-7bd3-bf72-ae77c8572a93,id=019ddc91-5a00-7bd3-bf72-ae77c8572a93; trace=019ddc91-5a00-7bd3-bf72-ae77c8572a93,id=019ddc91-5a00-7bd3-bf72-ae77c8572a93; trace=019ddc91-5acb-7f42-b697-7178d9ed2a3d,id=019ddc91-5acb-7f42-b697-7178d9ed2a3d

      [48/50]   ok  10.44s  calls=2  in= 9727 (cache    0%)  out= 332  acum=$0.7376

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-5acb-7f42-b697-7178d9ed2a3d,id=019ddc91-5acb-7f42-b697-7178d9ed2a3d; trace=019ddc91-679a-7952-88aa-b82396b8c810,id=019ddc91-679a-7952-88aa-b82396b8c810
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-679a-7952-88aa-b82396b8c810,id=019ddc91-679a-7952-88aa-b82396b8c810; trace=019ddc91-870c-7793-9834-72768e1ab1a9,id=019ddc91-870c-7793-9834-72768e1ab1a9; trace=019ddc91-870c-7793-9834-72768e1ab1a9,id=019ddc91-870c-7793-9834-72768e1ab1a9; trace=019ddc91-87d5-7293-a6c4-1bae20522c87,id=019ddc91-87d5-7293-a6c4-1bae20522c87

      [49/50]   ok   17.2s  calls=2  in=10188 (cache    0%)  out= 868  acum=$0.7522

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-87d5-7293-a6c4-1bae20522c87,id=019ddc91-87d5-7293-a6c4-1bae20522c87; trace=019ddc91-aace-7d62-bac5-007d81c678b5,id=019ddc91-aace-7d62-bac5-007d81c678b5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-aace-7d62-bac5-007d81c678b5,id=019ddc91-aace-7d62-bac5-007d81c678b5; trace=019ddc91-b05f-7ab3-9e36-6b12a022c4ad,id=019ddc91-b05f-7ab3-9e36-6b12a022c4ad; trace=019ddc91-b05f-7ab3-9e36-6b12a022c4ad,id=019ddc91-b05f-7ab3-9e36-6b12a022c4ad; trace=019ddc91-b12e-79a0-916a-a2055d3d6295,id=019ddc91-b12e-79a0-916a-a2055d3d6295

      [50/50]   ok  10.18s  calls=2  in= 9202 (cache    0%)  out= 554  acum=$0.7641
       ✓ ok — salvo em cvm__anthropic__claude-haiku-4-5__20260430_010717.xlsx

[run]  anthropic/claude-haiku-4-5 × petrobras (id=3)

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-b12e-79a0-916a-a2055d3d6295,id=019ddc91-b12e-79a0-916a-a2055d3d6295; trace=019ddc91-d2bb-7771-b299-aa91b613430d,id=019ddc91-d2bb-7771-b299-aa91b613430d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-d2bb-7771-b299-aa91b613430d,id=019ddc91-d2bb-7771-b299-aa91b613430d; trace=019ddc91-e2ca-7b32-b409-667c402b5af4,id=019ddc91-e2ca-7b32-b409-667c402b5af4; trace=019ddc91-e2ca-7b32-b409-667c402b5af4,id=019ddc91-e2ca-7b32-b409-667c402b5af4; trace=019ddc91-e330-7420-ba2a-b4eda648957b,id=019ddc91-e330-7420-ba2a-b4eda648957b; trace=019ddc91-e330-7420-ba2a-b4eda648957b,id=019ddc91-e330-7420-ba2a-b4eda648957b; trace=019ddc91-e331-7ad3-8923-f5788c17d7c6,id=019ddc91-e331-7ad3-8923-f5788c17d7c6

      [ 1/50]   ok   7.18s  calls=2  in=11608 (cache    0%)  out= 307  acum=$0.0131

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-e331-7ad3-8923-f5788c17d7c6,id=019ddc91-e331-7ad3-8923-f5788c17d7c6; trace=019ddc91-eec5-77c0-9420-d5ddea10d6ff,id=019ddc91-eec5-77c0-9420-d5ddea10d6ff
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc91-eec5-77c0-9420-d5ddea10d6ff,id=019ddc91-eec5-77c0-9420-d5ddea10d6ff; trace=019ddc92-1730-79c0-8cc6-2da1a8f41cb0,id=019ddc92-1730-79c0-8cc6-2da1a8f41cb0; trace=019ddc92-1730-79c0-8cc6-2da1a8f41cb0,id=019ddc92-1730-79c0-8cc6-2da1a8f41cb0; trace=019ddc92-17f9-7c93-905a-f5802c765785,id=019ddc92-17f9-7c93-905a-f5802c765785

      [ 2/50]   ok  13.95s  calls=2  in= 9793 (cache    0%)  out= 348  acum=$0.0247

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-17f9-7c93-905a-f5802c765785,id=019ddc92-17f9-7c93-905a-f5802c765785; trace=019ddc92-2543-7573-8513-d9112e5a6bee,id=019ddc92-2543-7573-8513-d9112e5a6bee
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-2543-7573-8513-d9112e5a6bee,id=019ddc92-2543-7573-8513-d9112e5a6bee; trace=019ddc92-4730-73d2-9e01-e40141588174,id=019ddc92-4730-73d2-9e01-e40141588174; trace=019ddc92-4730-73d2-9e01-e40141588174,id=019ddc92-4730-73d2-9e01-e40141588174; trace=019ddc92-478d-7201-969b-c82159b10ca3,id=019ddc92-478d-7201-969b-c82159b10ca3

      [ 3/50]   ok  11.84s  calls=2  in=10223 (cache    0%)  out= 353  acum=$0.0367

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-478d-7201-969b-c82159b10ca3,id=019ddc92-478d-7201-969b-c82159b10ca3; trace=019ddc92-537f-72e3-bd58-bc4baedf7f55,id=019ddc92-537f-72e3-bd58-bc4baedf7f55
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-537f-72e3-bd58-bc4baedf7f55,id=019ddc92-537f-72e3-bd58-bc4baedf7f55; trace=019ddc92-76c6-7ab3-9a9c-8b76ebe9327f,id=019ddc92-76c6-7ab3-9a9c-8b76ebe9327f; trace=019ddc92-76c6-7ab3-9a9c-8b76ebe9327f,id=019ddc92-76c6-7ab3-9a9c-8b76ebe9327f; trace=019ddc92-7720-74e1-98d6-d16fe09468b4,id=019ddc92-7720-74e1-98d6-d16fe09468b4

      [ 4/50]   ok  15.84s  calls=2  in=10059 (cache    0%)  out= 433  acum=$0.0489

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-7720-74e1-98d6-d16fe09468b4,id=019ddc92-7720-74e1-98d6-d16fe09468b4; trace=019ddc92-9162-7eb0-ab10-2949116e1a6e,id=019ddc92-9162-7eb0-ab10-2949116e1a6e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-9162-7eb0-ab10-2949116e1a6e,id=019ddc92-9162-7eb0-ab10-2949116e1a6e; trace=019ddc92-a3cf-7c11-bf7f-b26eb13e1433,id=019ddc92-a3cf-7c11-bf7f-b26eb13e1433; trace=019ddc92-a3cf-7c11-bf7f-b26eb13e1433,id=019ddc92-a3cf-7c11-bf7f-b26eb13e1433; trace=019ddc92-a4a4-71f3-995e-8514e916a1a0,id=019ddc92-a4a4-71f3-995e-8514e916a1a0; trace=019ddc92-a4a4-71f3-995e-8514e916a1a0,id=019ddc92-a4a4-71f3-995e-8514e916a1a0; trace=019ddc92-a4a8-71d3-847b-7f3093e8cab2,id=019ddc92-a4a8-71d3-847b-7f3093e8cab2

      [ 5/50]   ok   8.04s  calls=2  in=11315 (cache    0%)  out= 317  acum=$0.0618

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-a4a8-71d3-847b-7f3093e8cab2,id=019ddc92-a4a8-71d3-847b-7f3093e8cab2; trace=019ddc92-b0c8-7541-b659-d01582b08804,id=019ddc92-b0c8-7541-b659-d01582b08804
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-b0c8-7541-b659-d01582b08804,id=019ddc92-b0c8-7541-b659-d01582b08804; trace=019ddc92-dbd4-7842-a6c8-7e7306eb8715,id=019ddc92-dbd4-7842-a6c8-7e7306eb8715; trace=019ddc92-dbd4-7842-a6c8-7e7306eb8715,id=019ddc92-dbd4-7842-a6c8-7e7306eb8715; trace=019ddc92-dc36-7470-8441-c9f3a5b4af82,id=019ddc92-dc36-7470-8441-c9f3a5b4af82

      [ 6/50]   ok  16.38s  calls=2  in=11167 (cache    0%)  out= 545  acum=$0.0757

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-dc36-7470-8441-c9f3a5b4af82,id=019ddc92-dc36-7470-8441-c9f3a5b4af82; trace=019ddc92-f0c7-7463-b35a-d63cd30cfae6,id=019ddc92-f0c7-7463-b35a-d63cd30cfae6
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc92-f0c7-7463-b35a-d63cd30cfae6,id=019ddc92-f0c7-7463-b35a-d63cd30cfae6; trace=019ddc93-0ff8-7151-be6e-0e241eaa9e34,id=019ddc93-0ff8-7151-be6e-0e241eaa9e34; trace=019ddc93-0ff8-7151-be6e-0e241eaa9e34,id=019ddc93-0ff8-7151-be6e-0e241eaa9e34; trace=019ddc93-10af-7873-9b5e-db46f62974c0,id=019ddc93-10af-7873-9b5e-db46f62974c0

      [ 7/50]   ok  13.41s  calls=2  in=11319 (cache    0%)  out= 481  acum=$0.0894

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-10af-7873-9b5e-db46f62974c0,id=019ddc93-10af-7873-9b5e-db46f62974c0; trace=019ddc93-252b-7f02-80f6-700ec4605542,id=019ddc93-252b-7f02-80f6-700ec4605542
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-252b-7f02-80f6-700ec4605542,id=019ddc93-252b-7f02-80f6-700ec4605542; trace=019ddc93-44c2-70c2-9837-d1e02b3f0267,id=019ddc93-44c2-70c2-9837-d1e02b3f0267; trace=019ddc93-44c2-70c2-9837-d1e02b3f0267,id=019ddc93-44c2-70c2-9837-d1e02b3f0267; trace=019ddc93-458f-75b1-af4b-3a89ab7ca548,id=019ddc93-458f-75b1-af4b-3a89ab7ca548

      [ 8/50]   ok  12.29s  calls=2  in= 9928 (cache    0%)  out= 391  acum=$0.1013

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-458f-75b1-af4b-3a89ab7ca548,id=019ddc93-458f-75b1-af4b-3a89ab7ca548; trace=019ddc93-552a-7e81-858b-f4ad94c443c3,id=019ddc93-552a-7e81-858b-f4ad94c443c3
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-552a-7e81-858b-f4ad94c443c3,id=019ddc93-552a-7e81-858b-f4ad94c443c3; trace=019ddc93-73cd-7310-b031-95fb78313666,id=019ddc93-73cd-7310-b031-95fb78313666; trace=019ddc93-73cd-7310-b031-95fb78313666,id=019ddc93-73cd-7310-b031-95fb78313666; trace=019ddc93-7424-7e73-9d9a-b487d9ca83d1,id=019ddc93-7424-7e73-9d9a-b487d9ca83d1

      [ 9/50]   ok   12.9s  calls=2  in= 9817 (cache    0%)  out= 471  acum=$0.1135

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-7424-7e73-9d9a-b487d9ca83d1,id=019ddc93-7424-7e73-9d9a-b487d9ca83d1; trace=019ddc93-8790-7190-8e4b-687c41a55641,id=019ddc93-8790-7190-8e4b-687c41a55641
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-8790-7190-8e4b-687c41a55641,id=019ddc93-8790-7190-8e4b-687c41a55641; trace=019ddc93-a327-7e20-a990-e14500e96e64,id=019ddc93-a327-7e20-a990-e14500e96e64; trace=019ddc93-a327-7e20-a990-e14500e96e64,id=019ddc93-a327-7e20-a990-e14500e96e64; trace=019ddc93-a3e9-7722-ab5d-2509db9be55c,id=019ddc93-a3e9-7722-ab5d-2509db9be55c

      [10/50]   ok  11.03s  calls=2  in= 9894 (cache    0%)  out= 435  acum=$0.1255

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-a3e9-7722-ab5d-2509db9be55c,id=019ddc93-a3e9-7722-ab5d-2509db9be55c; trace=019ddc93-b2ab-7fb1-b27e-0a77c5d51ff7,id=019ddc93-b2ab-7fb1-b27e-0a77c5d51ff7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-b2ab-7fb1-b27e-0a77c5d51ff7,id=019ddc93-b2ab-7fb1-b27e-0a77c5d51ff7; trace=019ddc93-ce57-7630-8f4e-1b144001f7bc,id=019ddc93-ce57-7630-8f4e-1b144001f7bc; trace=019ddc93-ce57-7630-8f4e-1b144001f7bc,id=019ddc93-ce57-7630-8f4e-1b144001f7bc; trace=019ddc93-cf23-74d0-98fb-51bef60ad3f1,id=019ddc93-cf23-74d0-98fb-51bef60ad3f1

      [11/50]   ok  10.73s  calls=2  in= 9932 (cache    0%)  out= 339  acum=$0.1372

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-cf23-74d0-98fb-51bef60ad3f1,id=019ddc93-cf23-74d0-98fb-51bef60ad3f1; trace=019ddc93-dc99-7403-a956-488aa56ec57f,id=019ddc93-dc99-7403-a956-488aa56ec57f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-dc99-7403-a956-488aa56ec57f,id=019ddc93-dc99-7403-a956-488aa56ec57f; trace=019ddc93-ff25-7c71-b1ea-c85e47990fbf,id=019ddc93-ff25-7c71-b1ea-c85e47990fbf; trace=019ddc93-ff25-7c71-b1ea-c85e47990fbf,id=019ddc93-ff25-7c71-b1ea-c85e47990fbf; trace=019ddc93-ffe6-7051-b536-d6b592bf131a,id=019ddc93-ffe6-7051-b536-d6b592bf131a

      [12/50]   ok  13.59s  calls=2  in=11263 (cache    0%)  out= 462  acum=$0.1507

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc93-ffe6-7051-b536-d6b592bf131a,id=019ddc93-ffe6-7051-b536-d6b592bf131a; trace=019ddc94-11b6-7700-be6d-3bbdd121427e,id=019ddc94-11b6-7700-be6d-3bbdd121427e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-11b6-7700-be6d-3bbdd121427e,id=019ddc94-11b6-7700-be6d-3bbdd121427e; trace=019ddc94-342d-72e1-b222-676b33746132,id=019ddc94-342d-72e1-b222-676b33746132; trace=019ddc94-342d-72e1-b222-676b33746132,id=019ddc94-342d-72e1-b222-676b33746132; trace=019ddc94-3516-7b51-94e0-3a1522f0b667,id=019ddc94-3516-7b51-94e0-3a1522f0b667

      [13/50]   ok  11.81s  calls=2  in=11943 (cache    0%)  out= 269  acum=$0.1640

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-3516-7b51-94e0-3a1522f0b667,id=019ddc94-3516-7b51-94e0-3a1522f0b667; trace=019ddc94-3fd4-7461-a0e3-537be4f4e013,id=019ddc94-3fd4-7461-a0e3-537be4f4e013
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-3fd4-7461-a0e3-537be4f4e013,id=019ddc94-3fd4-7461-a0e3-537be4f4e013; trace=019ddc94-6abc-70d1-ac6d-d87d960ff211,id=019ddc94-6abc-70d1-ac6d-d87d960ff211; trace=019ddc94-6abc-70d1-ac6d-d87d960ff211,id=019ddc94-6abc-70d1-ac6d-d87d960ff211; trace=019ddc94-6b94-7a83-a9b4-35d509452b18,id=019ddc94-6b94-7a83-a9b4-35d509452b18

      [14/50]   ok  15.17s  calls=2  in=11544 (cache    0%)  out= 437  acum=$0.1777

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-6b94-7a83-a9b4-35d509452b18,id=019ddc94-6b94-7a83-a9b4-35d509452b18; trace=019ddc94-7b1b-7a20-a7fb-b0bcdc9430b7,id=019ddc94-7b1b-7a20-a7fb-b0bcdc9430b7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-7b1b-7a20-a7fb-b0bcdc9430b7,id=019ddc94-7b1b-7a20-a7fb-b0bcdc9430b7; trace=019ddc94-a187-7c53-a5b6-c215b7605b73,id=019ddc94-a187-7c53-a5b6-c215b7605b73; trace=019ddc94-a187-7c53-a5b6-c215b7605b73,id=019ddc94-a187-7c53-a5b6-c215b7605b73; trace=019ddc94-a26a-7b90-bb2c-15c012e72e69,id=019ddc94-a26a-7b90-bb2c-15c012e72e69

      [15/50]   ok  14.24s  calls=2  in=11396 (cache    0%)  out= 427  acum=$0.1913

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-a26a-7b90-bb2c-15c012e72e69,id=019ddc94-a26a-7b90-bb2c-15c012e72e69; trace=019ddc94-b2bd-7753-aada-0142600a0d77,id=019ddc94-b2bd-7753-aada-0142600a0d77
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-b2bd-7753-aada-0142600a0d77,id=019ddc94-b2bd-7753-aada-0142600a0d77; trace=019ddc94-d609-7d20-b15a-838b8e47918f,id=019ddc94-d609-7d20-b15a-838b8e47918f; trace=019ddc94-d609-7d20-b15a-838b8e47918f,id=019ddc94-d609-7d20-b15a-838b8e47918f; trace=019ddc94-d671-7f31-9c81-f3af12702ac7,id=019ddc94-d671-7f31-9c81-f3af12702ac7

      [16/50]   ok  14.08s  calls=2  in=11673 (cache    0%)  out= 447  acum=$0.2052

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-d671-7f31-9c81-f3af12702ac7,id=019ddc94-d671-7f31-9c81-f3af12702ac7; trace=019ddc94-e9be-7eb0-8b6d-3f04db09825e,id=019ddc94-e9be-7eb0-8b6d-3f04db09825e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc94-e9be-7eb0-8b6d-3f04db09825e,id=019ddc94-e9be-7eb0-8b6d-3f04db09825e; trace=019ddc95-0d86-7f02-8306-730d79a9d6da,id=019ddc95-0d86-7f02-8306-730d79a9d6da; trace=019ddc95-0d86-7f02-8306-730d79a9d6da,id=019ddc95-0d86-7f02-8306-730d79a9d6da; trace=019ddc95-0e5a-7b10-ab54-8ca4ff5f3c17,id=019ddc95-0e5a-7b10-ab54-8ca4ff5f3c17

      [17/50]   ok  14.79s  calls=2  in=10166 (cache    0%)  out= 590  acum=$0.2183

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-0e5a-7b10-ab54-8ca4ff5f3c17,id=019ddc95-0e5a-7b10-ab54-8ca4ff5f3c17; trace=019ddc95-2387-7f42-864a-dfd6b51f6553,id=019ddc95-2387-7f42-864a-dfd6b51f6553
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-2387-7f42-864a-dfd6b51f6553,id=019ddc95-2387-7f42-864a-dfd6b51f6553; trace=019ddc95-3e48-7c40-8de8-202a098913c7,id=019ddc95-3e48-7c40-8de8-202a098913c7; trace=019ddc95-3e48-7c40-8de8-202a098913c7,id=019ddc95-3e48-7c40-8de8-202a098913c7; trace=019ddc95-3eaa-76f0-bf93-d693bfc6d6bc,id=019ddc95-3eaa-76f0-bf93-d693bfc6d6bc

      [18/50]   ok  12.08s  calls=2  in=10789 (cache    0%)  out= 520  acum=$0.2317

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-3eaa-76f0-bf93-d693bfc6d6bc,id=019ddc95-3eaa-76f0-bf93-d693bfc6d6bc; trace=019ddc95-52bc-7590-850d-3c03e0342a3a,id=019ddc95-52bc-7590-850d-3c03e0342a3a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-52bc-7590-850d-3c03e0342a3a,id=019ddc95-52bc-7590-850d-3c03e0342a3a; trace=019ddc95-6eba-7462-a8da-db5e3b1b733b,id=019ddc95-6eba-7462-a8da-db5e3b1b733b; trace=019ddc95-6eba-7462-a8da-db5e3b1b733b,id=019ddc95-6eba-7462-a8da-db5e3b1b733b; trace=019ddc95-6f17-7dc2-a089-9f082ee714bd,id=019ddc95-6f17-7dc2-a089-9f082ee714bd

      [19/50]   ok  10.13s  calls=2  in=10713 (cache    0%)  out= 339  acum=$0.2441

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-6f17-7dc2-a089-9f082ee714bd,id=019ddc95-6f17-7dc2-a089-9f082ee714bd; trace=019ddc95-7a53-76f3-994f-199ffce9b8f9,id=019ddc95-7a53-76f3-994f-199ffce9b8f9
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-7a53-76f3-994f-199ffce9b8f9,id=019ddc95-7a53-76f3-994f-199ffce9b8f9; trace=019ddc95-a0b6-77f0-8abf-5c9d9ba2b796,id=019ddc95-a0b6-77f0-8abf-5c9d9ba2b796; trace=019ddc95-a0b6-77f0-8abf-5c9d9ba2b796,id=019ddc95-a0b6-77f0-8abf-5c9d9ba2b796; trace=019ddc95-a112-7362-92b9-81cb7ea6e557,id=019ddc95-a112-7362-92b9-81cb7ea6e557

      [20/50]   ok   12.7s  calls=2  in=11246 (cache    0%)  out= 283  acum=$0.2568

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-a112-7362-92b9-81cb7ea6e557,id=019ddc95-a112-7362-92b9-81cb7ea6e557; trace=019ddc95-abec-78e0-9579-418a91991fee,id=019ddc95-abec-78e0-9579-418a91991fee
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-abec-78e0-9579-418a91991fee,id=019ddc95-abec-78e0-9579-418a91991fee; trace=019ddc95-d6b2-7e22-b30c-9d4544c8ac99,id=019ddc95-d6b2-7e22-b30c-9d4544c8ac99; trace=019ddc95-d6b2-7e22-b30c-9d4544c8ac99,id=019ddc95-d6b2-7e22-b30c-9d4544c8ac99; trace=019ddc95-d750-7790-ac32-483ae8eb60ad,id=019ddc95-d750-7790-ac32-483ae8eb60ad

      [21/50]   ok  15.67s  calls=2  in= 9653 (cache    0%)  out= 472  acum=$0.2688

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-d750-7790-ac32-483ae8eb60ad,id=019ddc95-d750-7790-ac32-483ae8eb60ad; trace=019ddc95-e91f-7c63-984e-4aa88420e3de,id=019ddc95-e91f-7c63-984e-4aa88420e3de
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc95-e91f-7c63-984e-4aa88420e3de,id=019ddc95-e91f-7c63-984e-4aa88420e3de; trace=019ddc96-0381-7e52-90cc-735b56390e5f,id=019ddc96-0381-7e52-90cc-735b56390e5f; trace=019ddc96-0381-7e52-90cc-735b56390e5f,id=019ddc96-0381-7e52-90cc-735b56390e5f; trace=019ddc96-03ed-7860-b815-ec4476f41873,id=019ddc96-03ed-7860-b815-ec4476f41873

      [22/50]   ok  11.98s  calls=2  in= 9658 (cache    0%)  out= 634  acum=$0.2816

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-03ed-7860-b815-ec4476f41873,id=019ddc96-03ed-7860-b815-ec4476f41873; trace=019ddc96-17ea-7e63-a12d-b8ab5e251e47,id=019ddc96-17ea-7e63-a12d-b8ab5e251e47
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-17ea-7e63-a12d-b8ab5e251e47,id=019ddc96-17ea-7e63-a12d-b8ab5e251e47; trace=019ddc96-2e45-7fd1-afd9-e968440eae87,id=019ddc96-2e45-7fd1-afd9-e968440eae87; trace=019ddc96-2e45-7fd1-afd9-e968440eae87,id=019ddc96-2e45-7fd1-afd9-e968440eae87; trace=019ddc96-2f13-71a0-bc26-6cbc70e54e3d,id=019ddc96-2f13-71a0-bc26-6cbc70e54e3d

      [23/50]   ok    8.4s  calls=2  in=10378 (cache    0%)  out= 273  acum=$0.2933

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-2f13-71a0-bc26-6cbc70e54e3d,id=019ddc96-2f13-71a0-bc26-6cbc70e54e3d; trace=019ddc96-38b6-77e3-85d2-55c7d9271871,id=019ddc96-38b6-77e3-85d2-55c7d9271871
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-38b6-77e3-85d2-55c7d9271871,id=019ddc96-38b6-77e3-85d2-55c7d9271871; trace=019ddc96-5d3c-7681-a3ed-8d1dfd2a8a35,id=019ddc96-5d3c-7681-a3ed-8d1dfd2a8a35; trace=019ddc96-5d3c-7681-a3ed-8d1dfd2a8a35,id=019ddc96-5d3c-7681-a3ed-8d1dfd2a8a35; trace=019ddc96-5e0a-7240-9c5b-5908b0abb835,id=019ddc96-5e0a-7240-9c5b-5908b0abb835

      [24/50]   ok  15.87s  calls=2  in=10560 (cache    0%)  out= 425  acum=$0.3060

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-5e0a-7240-9c5b-5908b0abb835,id=019ddc96-5e0a-7240-9c5b-5908b0abb835; trace=019ddc96-76b6-72c0-8458-4d74f4f3ca41,id=019ddc96-76b6-72c0-8458-4d74f4f3ca41
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-76b6-72c0-8458-4d74f4f3ca41,id=019ddc96-76b6-72c0-8458-4d74f4f3ca41; trace=019ddc96-8f81-7312-a710-d5fa2f411ef6,id=019ddc96-8f81-7312-a710-d5fa2f411ef6; trace=019ddc96-8f81-7312-a710-d5fa2f411ef6,id=019ddc96-8f81-7312-a710-d5fa2f411ef6; trace=019ddc96-9059-7562-81ad-19a31bb74f1f,id=019ddc96-9059-7562-81ad-19a31bb74f1f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-9059-7562-81ad-19a31bb74f1f,id=019ddc96-9059-7562-81ad-19a31bb74f1f; trace=019ddc96-a0b4-74c3-af2b-a52e03428f29,id=019ddc96-a0b4-74c3-af2b-a52e03428f29; trace=019ddc96-a0b4-74c3-af2b-a52e03428f29,id=019ddc96-a0b4-74c3-af2b-a52e03428f29; trace=019ddc96-a18d-7b23-8c96-fc12c23a2c85,id=019ddc96-a18d-7b23-8c96-fc12c23a2c85
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-a18d-7b23-8c96-fc12c23a2c85,id=019ddc96-a18d-7b23-8c96-fc12c23a2c85; trace=019ddc96-cd1a-7373-9a9a-bfccf8d264a8,id=019ddc96-cd1a-7373-9a9a-bfccf8d264a8; trace=019ddc96-cd1a-7373-9a9a-bfccf8d264a8,id=019ddc96-cd1a-7373-9a9a-bfccf8d264a8; trace=019ddc96-cd1d-7aa0-bbdb-184b2a699324,id=019ddc96-cd1d-7aa0-bbdb-184b2a699324

      [25/50]   ok  38.19s  calls=4  in=37520 (cache    0%)  out= 605  acum=$0.3466

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc96-cd1d-7aa0-bbdb-184b2a699324,id=019ddc96-cd1d-7aa0-bbdb-184b2a699324; trace=019ddc97-0be8-7350-b7b8-24ada50e28f4,id=019ddc97-0be8-7350-b7b8-24ada50e28f4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc97-0be8-7350-b7b8-24ada50e28f4,id=019ddc97-0be8-7350-b7b8-24ada50e28f4; trace=019ddc97-4719-7cd3-9d06-1b191240cb8a,id=019ddc97-4719-7cd3-9d06-1b191240cb8a; trace=019ddc97-4719-7cd3-9d06-1b191240cb8a,id=019ddc97-4719-7cd3-9d06-1b191240cb8a; trace=019ddc97-47e5-72a1-8365-1f58d493f263,id=019ddc97-47e5-72a1-8365-1f58d493f263
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc97-47e5-72a1-8365-1f58d493f263,id=019ddc97-47e5-72a1-8365-1f58d493f263; trace=019ddc97-50b0-7723-bb73-4e9d41803128,id=019ddc97-50b0-7723-bb73-4e9d41803128; trace=019ddc97-50b0-7723-bb73-4e9d41803128,id=019ddc97-50b0-7723-bb73-4e9d41803128; trace=019ddc97-510f-7833-8853-c0352adbefc2,id=019ddc97-510f-7833-8853-c0352adbefc2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc97-510f-7833-8853-c0352adbefc2,id=019ddc97-510f-7833-8853-c0352adbefc2; trace=019ddc97-80e4-7c31-b728-b83f57d0ee78,id=019ddc97-80e4-7c31-b728-b83f57d0ee78; trace=019ddc97-80e4-7c31-b728-b83f57d0ee78,id=019ddc97-80e4-7c31-b728-b83f57d0ee78; trace=019ddc97-80e8-7f81-8c33-fd576d9ce39c,id=019ddc97-80e8-7f81-8c33-fd576d9ce39c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc97-80e8-7f81-8c33-fd576d9ce39c,id=019ddc97-80e8-7f81-8c33-fd576d9ce39c; trace=019ddc97-c5e3-7b90-a046-218caec9b9ea,id=019ddc97-c5e3-7b90-a046-218caec9b9ea; trace=019ddc97-c5e3-7b90-a046-218caec9b9ea,id=019ddc97-c5e3-7b90-a046-218caec9b9ea; trace=019ddc97-c5e6-7b92-9b43-ba871d867fac,id=019ddc97-c5e6-7b92-9b43-ba871d867fac

      [26/50]   ok  68.91s  calls=5  in=59570 (cache    0%)  out= 709  acum=$0.4097

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc97-c5e6-7b92-9b43-ba871d867fac,id=019ddc97-c5e6-7b92-9b43-ba871d867fac; trace=019ddc98-1918-7550-bf5f-d4a55f1a456f,id=019ddc98-1918-7550-bf5f-d4a55f1a456f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-1918-7550-bf5f-d4a55f1a456f,id=019ddc98-1918-7550-bf5f-d4a55f1a456f; trace=019ddc98-5fb3-7e12-8a25-ea6518637df1,id=019ddc98-5fb3-7e12-8a25-ea6518637df1; trace=019ddc98-5fb3-7e12-8a25-ea6518637df1,id=019ddc98-5fb3-7e12-8a25-ea6518637df1; trace=019ddc98-6019-7210-8c2d-1d7b1f4bc483,id=019ddc98-6019-7210-8c2d-1d7b1f4bc483
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-6019-7210-8c2d-1d7b1f4bc483,id=019ddc98-6019-7210-8c2d-1d7b1f4bc483; trace=019ddc98-696f-7ac0-9458-461f23a87f02,id=019ddc98-696f-7ac0-9458-461f23a87f02; trace=019ddc98-696f-7ac0-9458-461f23a87f02,id=019ddc98-696f-7ac0-9458-461f23a87f02; trace=019ddc98-69cf-7053-962d-364dcd316836,id=019ddc98-69cf-7053-962d-364dcd316836

      [27/50]   ok  31.13s  calls=3  in=22915 (cache    0%)  out= 498  acum=$0.4351

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-69cf-7053-962d-364dcd316836,id=019ddc98-69cf-7053-962d-364dcd316836; trace=019ddc98-92b3-7e10-b4dd-d99e55f223a7,id=019ddc98-92b3-7e10-b4dd-d99e55f223a7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-92b3-7e10-b4dd-d99e55f223a7,id=019ddc98-92b3-7e10-b4dd-d99e55f223a7; trace=019ddc98-c847-79e2-95fd-db37795f342d,id=019ddc98-c847-79e2-95fd-db37795f342d; trace=019ddc98-c847-79e2-95fd-db37795f342d,id=019ddc98-c847-79e2-95fd-db37795f342d; trace=019ddc98-c8ae-7ce1-80e0-071c00609ae7,id=019ddc98-c8ae-7ce1-80e0-071c00609ae7

      [28/50]   ok  19.14s  calls=2  in=10436 (cache    0%)  out= 539  acum=$0.4482

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-c8ae-7ce1-80e0-071c00609ae7,id=019ddc98-c8ae-7ce1-80e0-071c00609ae7; trace=019ddc98-dd7c-7c83-846c-2607d4e77178,id=019ddc98-dd7c-7c83-846c-2607d4e77178
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-dd7c-7c83-846c-2607d4e77178,id=019ddc98-dd7c-7c83-846c-2607d4e77178; trace=019ddc98-f4ae-7820-b1cb-1825192a98ba,id=019ddc98-f4ae-7820-b1cb-1825192a98ba; trace=019ddc98-f4ae-7820-b1cb-1825192a98ba,id=019ddc98-f4ae-7820-b1cb-1825192a98ba; trace=019ddc98-f510-70a1-9457-f3588400ab25,id=019ddc98-f510-70a1-9457-f3588400ab25
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-f510-70a1-9457-f3588400ab25,id=019ddc98-f510-70a1-9457-f3588400ab25; trace=019ddc98-fd29-7853-a919-e07829006dc1,id=019ddc98-fd29-7853-a919-e07829006dc1; trace=019ddc98-fd29-7853-a919-e07829006dc1,id=019ddc98-fd29-7853-a919-e07829006dc1; trace=019ddc98-fd98-7fb2-86f0-2f9a9d85b826,id=019ddc98-fd98-7fb2-86f0-2f9a9d85b826
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc98-fd98-7fb2-86f0-2f9a9d85b826,id=019ddc98-fd98-7fb2-86f0-2f9a9d85b826; trace=019ddc99-2d78-7091-8b51-98f27f1f20b6,id=019ddc99-2d78-7091-8b51-98f27f1f20b6; trace=019ddc99-2d78-7091-8b51-98f27f1f20b6,id=019ddc99-2d78-7091-8b51-98f27f1f20b6; trace=019ddc99-2d7b-77d0-8c51-df0c87374d37,id=019ddc99-2d7b-77d0-8c51-df0c87374d37
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc99-2d7b-77d0-8c51-df0c87374d37,id=019ddc99-2d7b-77d0-8c51-df0c87374d37; trace=019ddc99-6246-7b20-b24f-7919f54141a0,id=019ddc99-6246-7b20-b24f-7919f54141a0; trace=019ddc99-6246-7b20-b24f-7919f54141a0,id=019ddc99-6246-7b20-b24f-7919f54141a0; trace=019ddc99-6249-72a2-9025-2eb837bf8e08,id=019ddc99-6249-72a2-9025-2eb837bf8e08

      [29/50]   ok  50.27s  calls=5  in=47716 (cache    0%)  out= 727  acum=$0.4996

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc99-6249-72a2-9025-2eb837bf8e08,id=019ddc99-6249-72a2-9025-2eb837bf8e08; trace=019ddc99-a1df-73e1-a341-43b9583a6e97,id=019ddc99-a1df-73e1-a341-43b9583a6e97
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc99-a1df-73e1-a341-43b9583a6e97,id=019ddc99-a1df-73e1-a341-43b9583a6e97; trace=019ddc99-d512-7200-840b-293b519cbe91,id=019ddc99-d512-7200-840b-293b519cbe91; trace=019ddc99-d512-7200-840b-293b519cbe91,id=019ddc99-d512-7200-840b-293b519cbe91; trace=019ddc99-d57d-71b3-9f11-7a371e58ef8e,id=019ddc99-d57d-71b3-9f11-7a371e58ef8e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc99-d57d-71b3-9f11-7a371e58ef8e,id=019ddc99-d57d-71b3-9f11-7a371e58ef8e; trace=019ddc99-dc46-73b1-adb6-6a6634bb906f,id=019ddc99-dc46-73b1-adb6-6a6634bb906f; trace=019ddc99-dc46-73b1-adb6-6a6634bb906f,id=019ddc99-dc46-73b1-adb6-6a6634bb906f; trace=019ddc99-dc4d-77c0-b73a-a583b6cb980f,id=019ddc99-dc4d-77c0-b73a-a583b6cb980f

      [30/50]   ok  27.04s  calls=3  in=18244 (cache    0%)  out= 523  acum=$0.5204

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc99-dc4d-77c0-b73a-a583b6cb980f,id=019ddc99-dc4d-77c0-b73a-a583b6cb980f; trace=019ddc9a-0b7c-7e20-8919-4a04bc8e3c7a,id=019ddc9a-0b7c-7e20-8919-4a04bc8e3c7a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-0b7c-7e20-8919-4a04bc8e3c7a,id=019ddc9a-0b7c-7e20-8919-4a04bc8e3c7a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-2b85-7ae3-b099-1def209628fc,id=019ddc9a-2b85-7ae3-b099-1def209628fc; trace=019ddc9a-2b85-7ae3-b099-1def209628fc,id=019ddc9a-2b85-7ae3-b099-1def209628fc; trace=019ddc9a-2c23-7870-a4fd-eab6d80b84b2,id=019ddc9a-2c23-7870-a4fd-eab6d80b84b2

      [31/50]   ok  12.59s  calls=2  in= 9901 (cache    0%)  out= 436  acum=$0.5325

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-2c23-7870-a4fd-eab6d80b84b2,id=019ddc9a-2c23-7870-a4fd-eab6d80b84b2; trace=019ddc9a-3cad-7a10-8629-06315eebf8ef,id=019ddc9a-3cad-7a10-8629-06315eebf8ef
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-3cad-7a10-8629-06315eebf8ef,id=019ddc9a-3cad-7a10-8629-06315eebf8ef; trace=019ddc9a-5775-79e2-986d-ec0b9bab9677,id=019ddc9a-5775-79e2-986d-ec0b9bab9677; trace=019ddc9a-5775-79e2-986d-ec0b9bab9677,id=019ddc9a-5775-79e2-986d-ec0b9bab9677; trace=019ddc9a-584f-76d0-80a7-caf6d48c1092,id=019ddc9a-584f-76d0-80a7-caf6d48c1092

      [32/50]   ok  10.46s  calls=2  in=11330 (cache    0%)  out= 321  acum=$0.5454

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-584f-76d0-80a7-caf6d48c1092,id=019ddc9a-584f-76d0-80a7-caf6d48c1092; trace=019ddc9a-6588-7fa3-9477-f64e67a646b4,id=019ddc9a-6588-7fa3-9477-f64e67a646b4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-6588-7fa3-9477-f64e67a646b4,id=019ddc9a-6588-7fa3-9477-f64e67a646b4; trace=019ddc9a-90a8-7eb3-9868-1d8d4e917a05,id=019ddc9a-90a8-7eb3-9868-1d8d4e917a05; trace=019ddc9a-90a8-7eb3-9868-1d8d4e917a05,id=019ddc9a-90a8-7eb3-9868-1d8d4e917a05; trace=019ddc9a-9106-7903-b500-17fccf2f3ed0,id=019ddc9a-9106-7903-b500-17fccf2f3ed0

      [33/50]   ok   13.7s  calls=2  in=10070 (cache    0%)  out= 267  acum=$0.5569

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-9106-7903-b500-17fccf2f3ed0,id=019ddc9a-9106-7903-b500-17fccf2f3ed0; trace=019ddc9a-9b11-7c90-a9b1-6ca2ae683a7b,id=019ddc9a-9b11-7c90-a9b1-6ca2ae683a7b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-9b11-7c90-a9b1-6ca2ae683a7b,id=019ddc9a-9b11-7c90-a9b1-6ca2ae683a7b; trace=019ddc9a-bd75-72e1-aca1-697d5127b326,id=019ddc9a-bd75-72e1-aca1-697d5127b326; trace=019ddc9a-bd75-72e1-aca1-697d5127b326,id=019ddc9a-bd75-72e1-aca1-697d5127b326; trace=019ddc9a-be3f-7c70-8920-0bfa64e7a82b,id=019ddc9a-be3f-7c70-8920-0bfa64e7a82b

      [34/50]   ok  12.14s  calls=2  in=10091 (cache    0%)  out= 296  acum=$0.5684

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-be3f-7c70-8920-0bfa64e7a82b,id=019ddc9a-be3f-7c70-8920-0bfa64e7a82b; trace=019ddc9a-ca7b-7e02-95af-7960a010d8e1,id=019ddc9a-ca7b-7e02-95af-7960a010d8e1
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-ca7b-7e02-95af-7960a010d8e1,id=019ddc9a-ca7b-7e02-95af-7960a010d8e1; trace=019ddc9a-f042-7e01-a066-80e58dc36557,id=019ddc9a-f042-7e01-a066-80e58dc36557; trace=019ddc9a-f042-7e01-a066-80e58dc36557,id=019ddc9a-f042-7e01-a066-80e58dc36557; trace=019ddc9a-f10e-7b92-9962-16a4c4207845,id=019ddc9a-f10e-7b92-9962-16a4c4207845; trace=019ddc9a-f10e-7b92-9962-16a4c4207845,id=019ddc9a-f10e-7b92-9962-16a4c4207845; trace=019ddc9a-f110-7830-a88a-eedf712be0d7,id=019ddc9a-f110-7830-a88a-eedf712be0d7

      [35/50]   ok  14.49s  calls=2  in=12376 (cache    0%)  out= 530  acum=$0.5835

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9a-f110-7830-a88a-eedf712be0d7,id=019ddc9a-f110-7830-a88a-eedf712be0d7; trace=019ddc9b-0312-7f80-8faa-3da1bbb76e59,id=019ddc9b-0312-7f80-8faa-3da1bbb76e59
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-0312-7f80-8faa-3da1bbb76e59,id=019ddc9b-0312-7f80-8faa-3da1bbb76e59; trace=019ddc9b-2763-7420-bab5-3042c3fe6a12,id=019ddc9b-2763-7420-bab5-3042c3fe6a12; trace=019ddc9b-2763-7420-bab5-3042c3fe6a12,id=019ddc9b-2763-7420-bab5-3042c3fe6a12; trace=019ddc9b-2841-7213-bb05-56610125489c,id=019ddc9b-2841-7213-bb05-56610125489c; trace=019ddc9b-2841-7213-bb05-56610125489c,id=019ddc9b-2841-7213-bb05-56610125489c; trace=019ddc9b-2843-76c2-ba7c-2435b7fb15c6,id=019ddc9b-2843-76c2-ba7c-2435b7fb15c6

      [36/50]   ok  14.28s  calls=2  in=14148 (cache    0%)  out= 612  acum=$0.6007

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-2843-76c2-ba7c-2435b7fb15c6,id=019ddc9b-2843-76c2-ba7c-2435b7fb15c6; trace=019ddc9b-3ad6-7433-940b-d1dd0d61fa49,id=019ddc9b-3ad6-7433-940b-d1dd0d61fa49
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-3ad6-7433-940b-d1dd0d61fa49,id=019ddc9b-3ad6-7433-940b-d1dd0d61fa49; trace=019ddc9b-69b6-7210-b97a-1a7e7c8e8d57,id=019ddc9b-69b6-7210-b97a-1a7e7c8e8d57; trace=019ddc9b-69b6-7210-b97a-1a7e7c8e8d57,id=019ddc9b-69b6-7210-b97a-1a7e7c8e8d57; trace=019ddc9b-6a93-7103-bc85-3d86acb66de0,id=019ddc9b-6a93-7103-bc85-3d86acb66de0

      [37/50]   ok  16.96s  calls=2  in=12160 (cache    0%)  out= 524  acum=$0.6154

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-6a93-7103-bc85-3d86acb66de0,id=019ddc9b-6a93-7103-bc85-3d86acb66de0; trace=019ddc9b-7d11-7d43-913c-27fbeb05619a,id=019ddc9b-7d11-7d43-913c-27fbeb05619a
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-7d11-7d43-913c-27fbeb05619a,id=019ddc9b-7d11-7d43-913c-27fbeb05619a; trace=019ddc9b-a4a7-7321-a84c-aec65337e4b0,id=019ddc9b-a4a7-7321-a84c-aec65337e4b0; trace=019ddc9b-a4a7-7321-a84c-aec65337e4b0,id=019ddc9b-a4a7-7321-a84c-aec65337e4b0; trace=019ddc9b-a56b-73a2-bd67-9538db5dd751,id=019ddc9b-a56b-73a2-bd67-9538db5dd751

      [38/50]   ok  14.54s  calls=2  in= 9908 (cache    0%)  out= 448  acum=$0.6276

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-a56b-73a2-bd67-9538db5dd751,id=019ddc9b-a56b-73a2-bd67-9538db5dd751; trace=019ddc9b-b5db-7400-a27f-e4af355d95f7,id=019ddc9b-b5db-7400-a27f-e4af355d95f7
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-b5db-7400-a27f-e4af355d95f7,id=019ddc9b-b5db-7400-a27f-e4af355d95f7; trace=019ddc9b-d041-76c0-8d74-147950ee5553,id=019ddc9b-d041-76c0-8d74-147950ee5553; trace=019ddc9b-d041-76c0-8d74-147950ee5553,id=019ddc9b-d041-76c0-8d74-147950ee5553; trace=019ddc9b-d108-7893-8da0-60daecfe7a6f,id=019ddc9b-d108-7893-8da0-60daecfe7a6f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-d108-7893-8da0-60daecfe7a6f,id=019ddc9b-d108-7893-8da0-60daecfe7a6f

      [39/50]   ok  10.65s  calls=2  in=10653 (cache    0%)  out= 447  acum=$0.6405

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-df77-7573-97f6-bdc867071b6b,id=019ddc9b-df77-7573-97f6-bdc867071b6b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9b-df77-7573-97f6-bdc867071b6b,id=019ddc9b-df77-7573-97f6-bdc867071b6b; trace=019ddc9c-0068-7443-b694-283b61cc49b7,id=019ddc9c-0068-7443-b694-283b61cc49b7; trace=019ddc9c-0068-7443-b694-283b61cc49b7,id=019ddc9c-0068-7443-b694-283b61cc49b7; trace=019ddc9c-0138-79d3-ae0f-04e7b4ee41ce,id=019ddc9c-0138-79d3-ae0f-04e7b4ee41ce

      [40/50]   ok  11.88s  calls=2  in=12017 (cache    0%)  out= 379  acum=$0.6544

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-0138-79d3-ae0f-04e7b4ee41ce,id=019ddc9c-0138-79d3-ae0f-04e7b4ee41ce; trace=019ddc9c-0dda-7ed1-af7e-6d0694e41657,id=019ddc9c-0dda-7ed1-af7e-6d0694e41657
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-0dda-7ed1-af7e-6d0694e41657,id=019ddc9c-0dda-7ed1-af7e-6d0694e41657; trace=019ddc9c-3b0c-7b33-963c-010a289a0037,id=019ddc9c-3b0c-7b33-963c-010a289a0037; trace=019ddc9c-3b0c-7b33-963c-010a289a0037,id=019ddc9c-3b0c-7b33-963c-010a289a0037; trace=019ddc9c-3bff-78c1-9eb5-8d4bf97c061d,id=019ddc9c-3bff-78c1-9eb5-8d4bf97c061d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-3bff-78c1-9eb5-8d4bf97c061d,id=019ddc9c-3bff-78c1-9eb5-8d4bf97c061d; trace=019ddc9c-450c-73e0-9c74-71475f37b831,id=019ddc9c-450c-73e0-9c74-71475f37b831; trace=019ddc9c-450c-73e0-9c74-71475f37b831,id=019ddc9c-450c-73e0-9c74-71475f37b831; trace=019ddc9c-45d9-7971-bb25-10b9e379c737,id=019ddc9c-45d9-7971-bb25-10b9e379c737
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-45d9-7971-bb25-10b9e379c737,id=019ddc9c-45d9-7971-bb25-10b9e379c737; trace=019ddc9c-75d9-78c2-aeda-d5da391c7f32,id=019ddc9c-75d9-78c2-aeda-d5da391c7f32; trace=019ddc9c-75d9-78c2-aeda-d5da391c7f32,id=019ddc9c-75d9-78c2-aeda-d5da391c7f32; trace=019ddc9c-75dd-7cf0-b620-a034508a666b,id=019ddc9c-75dd-7cf0-b620-a034508a666b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-75dd-7cf0-b620-a034508a666b,id=019ddc9c-75dd-7cf0-b620-a034508a666b; trace=019ddc9c-b772-7a52-b5c7-51a5e71e501f,id=019ddc9c-b772-7a52-b5c7-51a5e71e501f; trace=019ddc9c-b772-7a52-b5c7-51a5e71e501f,id=019ddc9c-b772-7a52-b5c7-51a5e71e501f; trace=019ddc9c-b775-7043-a4b3-23825672f3ea,id=019ddc9c-b775-7043-a4b3-23825672f3ea
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9c-b775-7043-a4b3-23825672f3ea,id=019ddc9c-b775-7043-a4b3-23825672f3ea; trace=019ddc9d-0122-72c3-b8ab-3a1c3ca401b2,id=019ddc9d-0122-72c3-b8ab-3a1c3ca401b2; trace=019ddc9d-0122-72c3-b8ab-3a1c3ca401b2,id=019ddc9d-0122-72c3-b8ab-3a1c3ca401b2; trace=019ddc9d-0124-7f50-beb6-608564a5f421,id=019ddc9d-0124-7f50-beb6-608564a5f421

      [41/50]   ok  84.79s  calls=6  in=75316 (cache    0%)  out=1010  acum=$0.7348

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9d-0124-7f50-beb6-608564a5f421,id=019ddc9d-0124-7f50-beb6-608564a5f421; trace=019ddc9d-590e-7693-82d4-7a5e2a69653f,id=019ddc9d-590e-7693-82d4-7a5e2a69653f
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9d-590e-7693-82d4-7a5e2a69653f,id=019ddc9d-590e-7693-82d4-7a5e2a69653f; trace=019ddc9d-9c3d-75b3-8c2e-6f9ea98915f3,id=019ddc9d-9c3d-75b3-8c2e-6f9ea98915f3; trace=019ddc9d-9c3d-75b3-8c2e-6f9ea98915f3,id=019ddc9d-9c3d-75b3-8c2e-6f9ea98915f3; trace=019ddc9d-9c8f-71a1-95c0-e7afd1432481,id=019ddc9d-9c8f-71a1-95c0-e7afd1432481
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9d-9c8f-71a1-95c0-e7afd1432481,id=019ddc9d-9c8f-71a1-95c0-e7afd1432481; trace=019ddc9d-a509-76b2-a7ed-16f172628fe9,id=019ddc9d-a509-76b2-a7ed-16f172628fe9; trace=019ddc9d-a509-76b2-a7ed-16f172628fe9,id=019ddc9d-a509-76b2-a7ed-16f172628fe9; trace=019ddc9d-a5d2-7580-bf20-ed15f4ba2c4d,id=019ddc9d-a5d2-7580-bf20-ed15f4ba2c4d
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9d-a5d2-7580-bf20-ed15f4ba2c4d,id=019ddc9d-a5d2-7580-bf20-ed15f4ba2c4d; trace=019ddc9d-d44a-7f51-8a4a-0fe1f681a396,id=019ddc9d-d44a-7f51-8a4a-0fe1f681a396; trace=019ddc9d-d44a-7f51-8a4a-0fe1f681a396,id=019ddc9d-d44a-7f51-8a4a-0fe1f681a396; trace=019ddc9d-d44d-7782-9e71-55a4830b7af0,id=019ddc9d-d44d-7782-9e71-55a4830b7af0
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9d-d44d-7782-9e71-55a4830b7af0,id=019ddc9d-d44d-7782-9e71-55a4830b7af0; trace=019ddc9e-103a-70c0-b685-ac3b07dea291,id=019ddc9e-103a-70c0-b685-ac3b07dea291; trace=019ddc9e-103a-70c0-b685-ac3b07dea291,id=019ddc9e-103a-70c0-b685-ac3b07dea291; trace=019ddc9e-103c-7c82-872a-8bc7eeba4376,id=019ddc9e-103c-7c82-872a-8bc7eeba4376

      [42/50]   ok  64.71s  calls=5  in=51431 (cache    0%)  out= 692  acum=$0.7896

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9e-103c-7c82-872a-8bc7eeba4376,id=019ddc9e-103c-7c82-872a-8bc7eeba4376; trace=019ddc9e-55d9-7763-804d-f3cb4e5e008e,id=019ddc9e-55d9-7763-804d-f3cb4e5e008e
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9e-55d9-7763-804d-f3cb4e5e008e,id=019ddc9e-55d9-7763-804d-f3cb4e5e008e; trace=019ddc9e-8d29-7b21-8f00-9b35c8c10ac5,id=019ddc9e-8d29-7b21-8f00-9b35c8c10ac5; trace=019ddc9e-8d29-7b21-8f00-9b35c8c10ac5,id=019ddc9e-8d29-7b21-8f00-9b35c8c10ac5; trace=019ddc9e-8de0-7273-bf34-ab6e14abef64,id=019ddc9e-8de0-7273-bf34-ab6e14abef64
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9e-8de0-7273-bf34-ab6e14abef64,id=019ddc9e-8de0-7273-bf34-ab6e14abef64; trace=019ddc9e-95f7-7ac1-b490-940f285725c5,id=019ddc9e-95f7-7ac1-b490-940f285725c5; trace=019ddc9e-95f7-7ac1-b490-940f285725c5,id=019ddc9e-95f7-7ac1-b490-940f285725c5; trace=019ddc9e-96c7-7963-a276-127a7ffd6f92,id=019ddc9e-96c7-7963-a276-127a7ffd6f92
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9e-96c7-7963-a276-127a7ffd6f92,id=019ddc9e-96c7-7963-a276-127a7ffd6f92; trace=019ddc9e-c8fd-75c3-ae59-13c3913f7028,id=019ddc9e-c8fd-75c3-ae59-13c3913f7028; trace=019ddc9e-c8fd-75c3-ae59-13c3913f7028,id=019ddc9e-c8fd-75c3-ae59-13c3913f7028; trace=019ddc9e-c901-7da2-a4e8-a6427e7a0ad5,id=019ddc9e-c901-7da2-a4e8-a6427e7a0ad5
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9e-c901-7da2-a4e8-a6427e7a0ad5,id=019ddc9e-c901-7da2-a4e8-a6427e7a0ad5; trace=019ddc9f-096e-79c0-b1d2-ab0b899e6338,id=019ddc9f-096e-79c0-b1d2-ab0b899e6338; trace=019ddc9f-096e-79c0-b1d2-ab0b899e6338,id=019ddc9f-096e-79c0-b1d2-ab0b899e6338; trace=019ddc9f-0971-7991-ba3f-f080d0fd67ca,id=019ddc9f-0971-7991-ba3f-f080d0fd67ca
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9f-0971-7991-ba3f-f080d0fd67ca,id=019ddc9f-0971-7991-ba3f-f080d0fd67ca; trace=019ddc9f-56a4-7133-9d9c-bbe0bedfad0b,id=019ddc9f-56a4-7133-9d9c-bbe0bedfad0b; trace=019ddc9f-56a4-7133-9d9c-bbe0bedfad0b,id=019ddc9f-56a4-7133-9d9c-bbe0bedfad0b; trace=019ddc9f-56b0-7a33-8def-aa8c114ac453,id=019ddc9f-56b0-7a33-8def-aa8c114ac453

      [43/50]   ok  85.88s  calls=6  in=74284 (cache    0%)  out= 978  acum=$0.8688

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9f-56b0-7a33-8def-aa8c114ac453,id=019ddc9f-56b0-7a33-8def-aa8c114ac453; trace=019ddc9f-a553-7ad0-b2b0-71234c89e5ef,id=019ddc9f-a553-7ad0-b2b0-71234c89e5ef
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9f-a553-7ad0-b2b0-71234c89e5ef,id=019ddc9f-a553-7ad0-b2b0-71234c89e5ef; trace=019ddc9f-efd4-7c30-9a25-81e8bc282a79,id=019ddc9f-efd4-7c30-9a25-81e8bc282a79; trace=019ddc9f-efd4-7c30-9a25-81e8bc282a79,id=019ddc9f-efd4-7c30-9a25-81e8bc282a79; trace=019ddc9f-f09b-7130-bd04-894f878fe01b,id=019ddc9f-f09b-7130-bd04-894f878fe01b
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9f-f09b-7130-bd04-894f878fe01b,id=019ddc9f-f09b-7130-bd04-894f878fe01b; trace=019ddc9f-f906-7531-b8f0-345a4d8ec118,id=019ddc9f-f906-7531-b8f0-345a4d8ec118; trace=019ddc9f-f906-7531-b8f0-345a4d8ec118,id=019ddc9f-f906-7531-b8f0-345a4d8ec118; trace=019ddc9f-f9d6-7020-b8aa-8b6c135ff11c,id=019ddc9f-f9d6-7020-b8aa-8b6c135ff11c
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddc9f-f9d6-7020-b8aa-8b6c135ff11c,id=019ddc9f-f9d6-7020-b8aa-8b6c135ff11c; trace=019ddca0-203a-7120-b636-4e6707f14c76,id=019ddca0-203a-7120-b636-4e6707f14c76; trace=019ddca0-203a-7120-b636-4e6707f14c76,id=019ddca0-203a-7120-b636-4e6707f14c76; trace=019ddca0-203d-7112-9ef3-b54b83a71e85,id=019ddca0-203d-7112-9ef3-b54b83a71e85
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca0-203d-7112-9ef3-b54b83a71e85,id=019ddca0-203d-7112-9ef3-b54b83a71e85; trace=019ddca0-51fd-7640-a495-dff0edb5e09b,id=019ddca0-51fd-7640-a495-dff0edb5e09b; trace=019ddca0-51fd-7640-a495-dff0edb5e09b,id=019ddca0-51fd-7640-a495-dff0edb5e09b; trace=019ddca0-5200-7762-8713-cfa0350d3786,id=019ddca0-5200-7762-8713-cfa0350d3786

      [44/50]   ok  62.49s  calls=5  in=48794 (cache    0%)  out= 691  acum=$0.9211

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca0-5200-7762-8713-cfa0350d3786,id=019ddca0-5200-7762-8713-cfa0350d3786; trace=019ddca0-996f-7501-8f07-fb06e07e3218,id=019ddca0-996f-7501-8f07-fb06e07e3218
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca0-996f-7501-8f07-fb06e07e3218,id=019ddca0-996f-7501-8f07-fb06e07e3218; trace=019ddca0-d049-70d0-a224-0cfdbdebd127,id=019ddca0-d049-70d0-a224-0cfdbdebd127; trace=019ddca0-d049-70d0-a224-0cfdbdebd127,id=019ddca0-d049-70d0-a224-0cfdbdebd127; trace=019ddca0-d0ea-7040-b2bc-a6e21e3e52f9,id=019ddca0-d0ea-7040-b2bc-a6e21e3e52f9

      [45/50]   ok  19.25s  calls=2  in=11962 (cache    0%)  out= 592  acum=$0.9360

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca0-d0ea-7040-b2bc-a6e21e3e52f9,id=019ddca0-d0ea-7040-b2bc-a6e21e3e52f9; trace=019ddca0-e4a1-7621-b670-47f2bf569ef2,id=019ddca0-e4a1-7621-b670-47f2bf569ef2
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca0-e4a1-7621-b670-47f2bf569ef2,id=019ddca0-e4a1-7621-b670-47f2bf569ef2; trace=019ddca1-06a0-7f71-bf6e-cf3bff966151,id=019ddca1-06a0-7f71-bf6e-cf3bff966151; trace=019ddca1-06a0-7f71-bf6e-cf3bff966151,id=019ddca1-06a0-7f71-bf6e-cf3bff966151; trace=019ddca1-0776-74f1-9147-e1a5ce5cf19b,id=019ddca1-0776-74f1-9147-e1a5ce5cf19b

      [46/50]   ok  11.98s  calls=2  in=11948 (cache    0%)  out= 269  acum=$0.9493

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-0776-74f1-9147-e1a5ce5cf19b,id=019ddca1-0776-74f1-9147-e1a5ce5cf19b; trace=019ddca1-1372-7342-9453-078f2480d9df,id=019ddca1-1372-7342-9453-078f2480d9df
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-1372-7342-9453-078f2480d9df,id=019ddca1-1372-7342-9453-078f2480d9df; trace=019ddca1-3d90-7763-a8e5-cea22ecaccb9,id=019ddca1-3d90-7763-a8e5-cea22ecaccb9; trace=019ddca1-3d90-7763-a8e5-cea22ecaccb9,id=019ddca1-3d90-7763-a8e5-cea22ecaccb9; trace=019ddca1-3e66-78e2-8db6-a25ffb35a781,id=019ddca1-3e66-78e2-8db6-a25ffb35a781

      [47/50]   ok  16.28s  calls=2  in=11254 (cache    0%)  out= 550  acum=$0.9633

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-3e66-78e2-8db6-a25ffb35a781,id=019ddca1-3e66-78e2-8db6-a25ffb35a781; trace=019ddca1-5308-7471-b065-ad9314bba126,id=019ddca1-5308-7471-b065-ad9314bba126
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-5308-7471-b065-ad9314bba126,id=019ddca1-5308-7471-b065-ad9314bba126; trace=019ddca1-729f-7b00-bd7a-429f89600849,id=019ddca1-729f-7b00-bd7a-429f89600849; trace=019ddca1-729f-7b00-bd7a-429f89600849,id=019ddca1-729f-7b00-bd7a-429f89600849; trace=019ddca1-7304-7121-ad51-f13ccd5c2ebb,id=019ddca1-7304-7121-ad51-f13ccd5c2ebb

      [48/50]   ok  11.12s  calls=2  in=11876 (cache    0%)  out= 263  acum=$0.9765

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-7304-7121-ad51-f13ccd5c2ebb,id=019ddca1-7304-7121-ad51-f13ccd5c2ebb; trace=019ddca1-7e7a-7c71-b25d-ee5f4b4e0fe4,id=019ddca1-7e7a-7c71-b25d-ee5f4b4e0fe4
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-7e7a-7c71-b25d-ee5f4b4e0fe4,id=019ddca1-7e7a-7c71-b25d-ee5f4b4e0fe4; trace=019ddca1-aa9d-7a72-bfe2-c214cccfb1d0,id=019ddca1-aa9d-7a72-bfe2-c214cccfb1d0; trace=019ddca1-aa9d-7a72-bfe2-c214cccfb1d0,id=019ddca1-aa9d-7a72-bfe2-c214cccfb1d0; trace=019ddca1-ab07-75f1-abfc-0a6b2f815c3d,id=019ddca1-ab07-75f1-abfc-0a6b2f815c3d

      [49/50]   ok  18.09s  calls=2  in= 9944 (cache    0%)  out= 627  acum=$0.9896

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-ab07-75f1-abfc-0a6b2f815c3d,id=019ddca1-ab07-75f1-abfc-0a6b2f815c3d; trace=019ddca1-c521-71e2-b4d3-2a99d4587839,id=019ddca1-c521-71e2-b4d3-2a99d4587839
Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-c521-71e2-b4d3-2a99d4587839,id=019ddca1-c521-71e2-b4d3-2a99d4587839; trace=019ddca1-d9d0-7091-8f10-96d021b3c159,id=019ddca1-d9d0-7091-8f10-96d021b3c159; trace=019ddca1-d9d0-7091-8f10-96d021b3c159,id=019ddca1-d9d0-7091-8f10-96d021b3c159; trace=019ddca1-da9f-7b32-8c69-8d1eaf6345c8,id=019ddca1-da9f-7b32-8c69-8d1eaf6345c8

      [50/50]   ok  11.87s  calls=2  in=10484 (cache    0%)  out= 641  acum=$1.0032
       ✓ ok — salvo em petrobras__anthropic__claude-haiku-4-5__20260430_012454.xlsx

============================================================
=== SUMÁRIO ===
============================================================

✓ Sucessos: 15
    openai/gpt-4o-mini × bndes  →  bndes__openai__gpt-4o-mini__20260429_231806.xlsx
    openai/gpt-4o-mini × cvm  →  cvm__openai__gpt-4o-mini__20260429_232228.xlsx
    openai/gpt-4o-mini × petrobras  →  petrobras__openai__gpt-4o-mini__20260429_232739.xlsx
    deepseek/deepseek-v4-flash × bndes  →  bndes__deepseek__deepseek-v4-flash__20260429_233504.xlsx
    deepseek/deepseek-v4-flash × cvm  →  cvm__deepseek__deepseek-v4-flash__20260429_234135.xlsx
    deepseek/deepseek-v4-flash × petrobras  →  petrobras__deepseek__deepseek-v4-flash__20260429_234903.xlsx
    openai/gpt-5.4-mini × bndes  →  bndes__openai__gpt-5.4-mini__20260429_235130.xlsx
    openai/gpt-5.4-mini × cvm  →  cvm__openai__gpt-5.4-mini__20260429_235347.xlsx
    openai/gpt-5.4-mini × petrobras  →  petrobras__openai__gpt-5.4-mini__20260429_235625.xlsx
    deepseek/deepseek-v4-pro × bndes  →  bndes__deepseek__deepseek-v4-pro__20260430_001110.xlsx
    deepseek/deepseek-v4-pro × cvm  →  cvm__deepseek__deepseek-v4-pro__20260430_002507.xlsx
    deepseek/deepseek-v4-pro × petrobras  →  petrobras__deepseek__deepseek-v4-pro__20260430_004108.xlsx
    anthropic/claude-haiku-4-5 × bndes  →  bndes__anthropic__claude-haiku-4-5__20260430_005407.xlsx
    anthropic/claude-haiku-4-5 × cvm  →  cvm__anthropic__claude-haiku-4-5__20260430_010717.xlsx
    anthropic/claude-haiku-4-5 × petrobras  →  petrobras__anthropic__claude-haiku-4-5__20260430_012454.xlsx

⚠ Parciais (estouro de orçamento): 0

✗ Falhas: 0

Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ddca1-da9f-7b32-8c69-8d1eaf6345c8,id=019ddca1-da9f-7b32-8c69-8d1eaf6345c8

## Sumário consolidado

In [19]:
import re

padrao_nome = re.compile(
    r"^(?P<edital>[^_]+)__(?P<provider>[^_]+)__(?P<modelo>.+?)__\d{8}_\d{6}(?:__PARCIAL)?\.xlsx$"
)

linhas = []
for arq in sorted(RESULTADOS_DIR.glob("*.xlsx")):
    m = padrao_nome.match(arq.name)
    if not m:
        continue
    df = pd.read_excel(arq)
    if "cache_read_tokens" not in df.columns:
        df["cache_read_tokens"] = 0
    if "custo_real_usd" not in df.columns:
        df["custo_real_usd"] = df["custo_usd"]

    linhas.append({
        "edital":           m["edital"],
        "provider":         m["provider"],
        "modelo":           m["modelo"],
        "n_perguntas":      len(df),
        "n_erros":          int(df["erro"].notna().sum()),
        "input_tokens":     int(df["input_tokens"].sum()),
        "output_tokens":    int(df["output_tokens"].sum()),
        "cache_read":       int(df["cache_read_tokens"].sum()),
        "cache_pct":        float(df["cache_read_tokens"].sum() / max(df["input_tokens"].sum(), 1)),
        "custo_estim_usd":  round(float(df["custo_usd"].sum()), 4),
        "custo_real_usd":   round(float(df["custo_real_usd"].sum()), 4),
        "latencia_med_s":   round(float(df["latencia_s"].mean()), 2),
        "latencia_p95_s":   round(float(df["latencia_s"].quantile(0.95)), 2),
        "arquivo":          arq.name,
    })

df_sumario = pd.DataFrame(linhas).sort_values(["edital", "custo_real_usd"]).reset_index(drop=True)
df_sumario["cache_pct"] = df_sumario["cache_pct"].map("{:.1%}".format)
df_sumario

,edital,provider,modelo,n_perguntas,n_erros,input_tokens,output_tokens,cache_read,cache_pct,custo_estim_usd,custo_real_usd,latencia_med_s,latencia_p95_s,arquivo
0,bndes,deepseek,deepseek-v4-flash,50,0,651794,21562,1223680,187.7%,0.0973,0.0405,8.89,17.08,bndes__deepseek__deepseek-v4-flash__20260429_2...
1,bndes,openai,gpt-4o-mini,50,0,423484,9378,60416,14.3%,0.0691,0.0646,5.45,10.38,bndes__openai__gpt-4o-mini__20260429_231806.xlsx
2,bndes,openai,gpt-5.4-mini,50,0,332401,8532,84864,25.5%,0.1002,0.0896,2.94,4.73,bndes__openai__gpt-5.4-mini__20260429_235130.xlsx
3,bndes,deepseek,deepseek-v4-pro,50,0,681518,23169,772096,113.3%,1.2665,0.2201,17.69,33.55,bndes__deepseek__deepseek-v4-pro__20260430_001...
4,bndes,anthropic,claude-haiku-4-5,50,0,700866,23247,0,0.0%,0.8171,0.8171,15.57,35.46,bndes__anthropic__claude-haiku-4-5__20260430_0...
5,cvm,deepseek,deepseek-v4-flash,50,0,558979,19510,715264,128.0%,0.0837,0.0262,7.82,13.25,cvm__deepseek__deepseek-v4-flash__20260429_234...
6,cvm,openai,gpt-4o-mini,50,0,433446,8765,145408,33.5%,0.0703,0.0594,5.23,8.58,cvm__openai__gpt-4o-mini__20260429_232228.xlsx
7,cvm,openai,gpt-5.4-mini,50,0,323919,8298,82816,25.6%,0.0976,0.0872,2.72,4.32,cvm__openai__gpt-5.4-mini__20260429_235347.xlsx
8,cvm,deepseek,deepseek-v4-pro,50,0,601746,22188,707584,117.6%,1.1242,0.1899,16.75,30.45,cvm__deepseek__deepseek-v4-pro__20260430_00250...
9,cvm,anthropic,claude-haiku-4-5,50,0,655949,21637,0,0.0%,0.7641,0.7641,15.80,36.02,cvm__anthropic__claude-haiku-4-5__20260430_010...
10,petrobras,deepseek,deepseek-v4-flash,50,0,782633,23279,985856,126.0%,0.1161,0.0359,8.97,18.94,petrobras__deepseek__deepseek-v4-flash__202604...
11,petrobras,openai,gpt-4o-mini,50,0,481300,9269,156288,32.5%,0.0778,0.0660,6.22,9.98,petrobras__openai__gpt-4o-mini__20260429_23273...
12,petrobras,openai,gpt-5.4-mini,50,0,393450,9109,110336,28.0%,0.1166,0.1028,3.17,5.41,petrobras__openai__gpt-5.4-mini__20260429_2356...
13,petrobras,deepseek,deepseek-v4-pro,50,0,730046,26005,876288,120.0%,1.3608,0.2362,19.22,38.01,petrobras__deepseek__deepseek-v4-pro__20260430...
14,petrobras,anthropic,claude-haiku-4-5,50,0,882385,24172,0,0.0%,1.0032,1.0032,21.14,67.02,petrobras__anthropic__claude-haiku-4-5__202604...

## Tabela cruzada — custo real por modelo × edital

In [20]:
df_pivot = (
    df_sumario.assign(modelo_full=lambda d: d["provider"] + "/" + d["modelo"])
              .pivot_table(index="modelo_full", columns="edital",
                          values="custo_real_usd", aggfunc="last")
)
df_pivot["total"] = df_pivot.sum(axis=1)
df_pivot.sort_values("total")

edital                       bndes     cvm  petrobras   total
modelo_full
deepseek/deepseek-v4-flash  0.0405  0.0262     0.0359  0.1026
openai/gpt-4o-mini          0.0646  0.0594     0.0660  0.1900
openai/gpt-5.4-mini         0.0896  0.0872     0.1028  0.2796
deepseek/deepseek-v4-pro    0.2201  0.1899     0.2362  0.6462
anthropic/claude-haiku-4-5  0.8171  0.7641     1.0032  2.5844